### ISSUE TITLE
Offline version (Electron)

### ISSUE THREAD

**Issue by mat1jaczyyy** [tetrio/issues#10]
An offline executable version in Electron would be another nice addition, for example to play solo modes while offline. It could support some extra features like Discord Rich Presence. Unsure of the demand for this though

**Comment by professor-l** [comment]
If I'm not mistaken, WebGL + Electron = sloooooowwwww.  It's a nice idea, but probably for the more distant future.

**Comment by mat1jaczyyy** [comment]
I'm not a webdev so I wouldn't know /shrug

**Comment by jp06** [comment]
Or make it a [progressive web app (PWA)](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps) instead, which could also be [configured to run offline](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers).

**Comment by LayneTheEpic** [comment]
But isn't Electron literally Chromium though? Why would WebGL be slower on Electron than on any other Chromium browser?

**Comment by UniQMG522** [comment]
Tetrio actually already works fine when loaded offline, I was experimenting with adding a service worker and got it working. Single player modes were completely playable (with network errors when it tried to submit replays), but connecting to live servers wasn't handled gracefully and softlocked.

Electron shouldn't run measurably slower than any other chromium based browser, though its always a few major versions out of date.

**Comment by LayneTheEpic** [comment]
@o5k Could you use the [Nativefier](https://github.com/jiahaog/nativefier) NPM module to make it offline?

You can check [here](https://youtu.be/fgMx1cfqzDw) where I successfully ported it. Professor-L is right though, it is noticeably slower than my browser and I have a fairly good build.

**Comment by o5k** [comment]
@LayneTheEpic The point of an Electron port would be to be able to tweak the Chromium instance to run as smoothly as possible (not normally possible for users, or rather hard (like the `--disable-frame-rate-limit` flag)). These apps would be too simplistic. Also, I'd like it to be able to play offline (as potentially stash failed replay uploads so you can submit them once you're online)

For any of that to work though, we need at performance that at least matches that in browser...

**Comment by LayneTheEpic** [comment]
I see what you mean, it'd be unfortunate but it seems like the best option is to build Tetr.io desktop from the ground up

**Comment by professor-l** [comment]
I have no idea what WebGL code looks like or how osk structured his codebase, but if it's React-based, there's [expo-gl](https://github.com/expo/expo/tree/master/packages/expo-gl), which appears to be decently quick and can work with React Native.  Even then, though, porting this to a native application is a significant ordeal.

**Comment by Niquolas** [comment]
For what it's worth, I get almost identical performance (in terms of FPS as counted by the F8 menu) in Chrome 80 as I do in a very basic Electron (8.2.1) wrapper that just adds the two performance flags and opens https://tetr.io in a `BrowserWindow`.

It's not any more useful than a regular browser at this point since there is no offline functionality, but it's something to think about.

```
const {app, BrowserWindow} = require("electron");

let win;

app.commandLine.appendSwitch("--disable-frame-rate-limit");
app.commandLine.appendSwitch("--disable-gpu-vsync");

app.on("ready", () => {
    win = new BrowserWindow({
        width: 1280,
        height: 720
    });

    win.setMenuBarVisibility(false);

    win.loadURL("https://tetr.io");
});
```

**Comment by Jabster28** [comment]
A sub-par version of this can be done with [nativefier](https://github.com/jiahaog/nativefier)
 
Upon doing this, I get the same performance (maybe better because no extensions?) as I would using Firefox.

**Comment by Ads20000** [comment]
With 3.0.0 can this be closed or maybe a checklist provided on what needs to be done to get it out of 'experimental'? :)

Also I don't know if you're using Electron, I assume you are (though I'm aware there's other toolkits available)?

**Comment by o5k** [comment]
wait why was this still open
