### ISSUE TITLE
Reducing lock delay in custom multiplayer rooms

### ISSUE THREAD

**Issue by deedeeen** [tetrio/issues#1000]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

This is not a problem, just a way to play under maximum gravity. This can work as an enhancement to existing custom multiplayer rooms that try to blend classic and modern mechanics.

### Describe the solution you'd like

A way to set a starting lock delay, margin time and rate of decrement, just like gravity and garbage multiplier. Additionally, there can be a minimum lock delay.

### Describe alternatives you've considered

This is an implement-or-not scenario. Alternatives are not applicable.

### Additional context

_wait, this is already issue no. 1000?_

**Comment by ZaptorZap** [comment]
How come the already implemented lock delay configuration isn't an applicable alternative? 
![image](https://user-images.githubusercontent.com/64891705/185030786-8f295a84-35c6-4b79-b963-dd1acbbc9b25.png)
Creating **whole margin times** for something as underused as lock delay modifications just overbloats an already hard to understand and underused room settings panel.

**Comment by deedeeen** [comment]
For example, I want to play at maximum gravity for every game. Do you think 30 frames for _the entirety of a game_ is enough? 25? 20?

On top of it, tell me just **1** game that will offer roughly the same sets of options as gravity or garbage multipliers. If you can't find one, the entire room panel itself is limited to TETR.IO, and its "underused" status is not valid since only one game has implemented it.

**Comment by ZaptorZap** [comment]
Well, _yes_, I do believe that's enough. There's a **2nd** set of margin time functions for just that reason, actually. If gravity doesn't kill them, then surely multiplying garbage itself to untenable metrics will!

To answer your question, I scowered [Jstris](http://jstris.jezevec10.com/), [Stackmate](https://stack-mate.herokuapp.com/), [Spirit Drop](https://rayblastgames.com/spiritdrop/rulesets.php), [NullpoMino](https://github.com/nullpomino/nullpomino), [Puyo Puyo Tetris](https://puyo.sega.com/tetris/), and [Tetris Effect: Connected](https://www.tetriseffect.game/). Here's some examples:
* Jstris has a pretty feature complete room configuration, although their chosen method of ending games is introducing unclearable garbage. It looks like this:
![image](https://user-images.githubusercontent.com/64891705/185285721-fb9ab9f3-2eba-445b-984a-97490dbf2270.png)
* I was surprised to learn Stackmate didn't have much configuration regarding gravity, but it does have scripting of some sort. Here's an example of their built-in gravity settings:
![image](https://user-images.githubusercontent.com/64891705/185286168-513657d5-2d80-4614-a640-a6b30e569ab7.png)
* Spirit Drop's currently accessible configuration is nearly non-existent, but the next update down the line promises to add [powerful JSON based rulesets that can modify practically any sort of engine-driven variable](https://rayblastgames.com/spiritdrop/rulesets.php). It should be **trivial** to create one that lowers lock delay after an arbitrary amount of time—and perhaps even more straightforward for the end-user, as lock delay is both controlled by much more granular miliseconds and illustrated within Spirit Drop's core UI.
    * We're specifically looking at logic pertaining to variables `gameTime`, `lockDelay` and `gravityInterval`. 
* NullpoMino's room configuration is an unlabeled nightmare, but it does have hurryup in the form of unclearable garbage and a promise of a gravity curve here:
![image](https://user-images.githubusercontent.com/64891705/185286439-45e2990b-e2e0-4ba7-a955-d1bf7ee5c46d.png)
* Puyo Puyo Tetris introduces its gravity configurations through the somewhat obscure handicap modes (the spicier, the more gravity and garbage messiness you have to contend with)
![image](https://user-images.githubusercontent.com/64891705/185288035-00415e06-eae4-4be9-9f82-10baa6f95160.png)
* Tetris Effect: Connected is surprisingly comprehensive when it comes to gravity/garbage multiplication.
    * Per-user, you can adjust garbage multiplication before a match begins.
    * For the whole lobby, you can adjust gravity, as well how quickly each "phase" progresses.
    * Tetris Effect: Connected's "Score Attack" features several different methods of gravity/lock delay progression in a given game. Implementing these are just **implied** with the addition of score attack modes, as suggested in #456—you don't need **entirely different issues** to suggest conventional line-based leveling within games.
        * In modern score attack, levels above level 20 begin lowering the lock delay. It's been said before that level 30 is TE:C's intended "killscreen".
        * In classic score attack, a single **persistent**, very harsh lock delay is used in combination with increasing gravity. This is very efficient at ending games quickly for unprepared users.
            * In both, once one player tops out, the other only has two minutes to stack before the game immediately ends

And that's the point I want to make here: leveling makes it **easy**, understandable, and fair to explain when and why exactly your lock delay is going to be decreased by the frame. Arbitrarily lowering it without any clear UI, as with the margin time we have currently, sounds like a painful nightmare for most players, solved only by increasing ARE to a point where all movement is initial, and misdrops created by lock delay mishaps are fatal. (unless we should have ARE margin time too?)

**Comment by deedeeen** [comment]
> There's a 2nd set of margin time functions for just that reason, actually. If gravity doesn't kill them, then surely multiplying garbage itself to untenable metrics will!

~~Pending a game that does not implement garbage.~~
Anyway, adding more depth and difficulty should not hurt, and will surely make the game stand out, eh?
Seriously though, playing at a set lock delay is still bland, and garbage can be indefinitely sent back and forth. Whereas, reducing lock delays is a permanent and persistent change of environment, forcing one to strategize if their moves work to avoid losing.

> To answer your question, I scowered [Jstris](http://jstris.jezevec10.com/), [Stackmate](https://stack-mate.herokuapp.com/), [Spirit Drop](https://rayblastgames.com/spiritdrop/rulesets.php), [NullpoMino](https://github.com/nullpomino/nullpomino), [Puyo Puyo Tetris](https://puyo.sega.com/tetris/), and [Tetris Effect: Connected](https://www.tetriseffect.game/).
 
I can only accept _Spirit Drop_ as a reasonable example. The rest do not have time-based increasing garbage or gravity settings.
And, as you have demonstrated, _SD_ does allow you to change anything, no matter gravity, garbage or lock delay.

> leveling makes it **easy**, understandable, and fair to explain when and why exactly your lock delay is going to be decreased by the frame.

Are gravity and garbage settings level-based in multiplayer games, even?
I would advocate for clear indications of in-game statistics, just like [_Spirit Drop_](https://rayblastgames.com/spiritdrop.php) or [_Tetra Legends_](https://tetralegends.app/), but that's not what this issue is about.

> misdrops created by lock delay mishaps are fatal

Intended by my suggestion. I don't see anything wrong with _that_.

> (unless we should have ARE margin time too?)

~~that's a surprisingly good idea lol~~

**Comment by ZaptorZap** [comment]
> Seriously though, playing at a set lock delay is still bland, and garbage can be indefinitely sent back and forth.

.......is it? Do people genuinely believe this? I don't think that. Nobody else running tournaments think that.

> which defends my point.

How so? Alright, let's back up a bit:
> > the entire room panel itself is limited to TETR.IO, and its "underused" status is not valid since only one game has implemented it.

My counterexample: here I've implemented a "instantly `os.exit()` the game" function to Cambridge under the open source Zaptor-made [killable-cambridge](https://github.com/ZaptorZap/killable-cambridge) repository. You can press the `k` button and it immediately kills Cambridge, no matter where you are! Name another game that does this. If you can't, then this feature's "underused" status is **invalid** and I expect osk to implement it into TETR.IO by tomorrow so that it *can* be underused.

Or maybe it's _overused_ since I just implemented it to every game:
![image](https://user-images.githubusercontent.com/64891705/185299072-51df8b5c-490f-4ef9-bead-aa2312de0cd1.png)

> Are gravity and garbage settings level-based in multiplayer games, even?

Sure it is, I labeled a few examples up there. TE:C Score attack **is** a multiplayer game, believe it or not.

> I don't see anything wrong with _that_.

The issue here is in how brutal this topout comes. It may very well feel and **be unpreventable,** unlike topping out by gravity or an enemy's attack. Death by gravity/an enemy's garbage may feel the opposite, given that you can fairly counter with equal footing and adapt to infinite gravity under generous lock delay. You **can not** adapt to lock delay at 0 frames. (Yes, I *know* you want to implement a 3rd new slider for "minimum lock delay", but MAN that's unconventional.)

**Comment by deedeeen** [comment]
> Was lock delay ever considered an obstacle to these players?

Well, why shouldn't it be in potential games?

> My counterexample: here I've implemented a "instantly `os.exit()` the game" function to Cambridge under the open source Zaptor-made [killable-cambridge](https://github.com/ZaptorZap/killable-cambridge) repository. You can press the `k` button and it immediately kills Cambridge, no matter where you are!

~~Not going to lie, that's actually a good idea. Quick way to disconnect if implemented in TETR.IO and does not need confirmations.~~

> Or maybe it's _overused_ since I just implemented it to every game

Now you're targeting me and me only. I believe that isn't the way to resolve this issue.

> Sure it is, I labeled a few examples up there. TE:C Score Attack is a multiplayer game, believe it or not.

I shall apologize for not specifying that **TETR.IO** does not yet support level-based gravity/garbage in multiplayer, publicly.

> The issue here is in how brutal this topout comes. It may very well feel and **be unpreventable**

Complain to _TE:C_'s Score Attack modes. You can't escape your fate there.

**Comment by Purplegaze** [comment]
personally I think this would be a great feature. obviously adding margin time and multiplier settings to every single setting would be super unnecessary, but lock delay is a fairly standard way to increase difficulty in games such as tetris.com once gravity reaches 20G, and to me it sounds like a fairer way to increase the volatility of a long round than the garbage multiplier.
