### ISSUE TITLE
When the host leaves a custom room and the game assigns a new host, favor players over spectators

### ISSUE THREAD

**Issue by godotgamedeveloper** [tetrio/issues#1006]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Custom rooms in multiplayer often become a frustrating experience for players when the host suddenly leaves and the game responds by making someone else a host who is a spectator and actually either not paying attention or even AFK.

Typically when this happens, the players in the room try to get the new host to start the game, often to no avail, before all bailing out of the room altogether.

I experienced this continually in various custom rooms both yesterday and today, which prompted me to make this request.

### Describe the solution you'd like

If there are people playing and other people spectating, the new host should be selected from the players and not from the spectators.  Only if no players remain, should one of the spectators be chosen as the new host.

### Describe alternatives you've considered

One alternative is to show the selected person a prompt that says, "You have been randomly selected to be the new host.  Click confirm to accept."  If they don't accept within ten seconds, or if they choose No, then the game selects a different person, and the process repeats.

Note that this alternative can actually be implemented in conjunction with the solution described above for a more complete solution to the problem.

### Additional context

A request for a different feature that at best offers only a partial solution to this problem, and a flawed one at that: https://github.com/tetrio/issues/issues/444.

**Comment by Dimentio** [comment]
Will look into this!

**Comment by Dimentio** [comment]
Added for next update
