### ISSUE TITLE
Inconsistent behavior of "Playing/Spectating" button in multiplayer rooms

### ISSUE THREAD

**Issue by cIymax** [tetrio/issues#1007]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop client

### Describe the bug/issue

I've noticed an inconsistent behavior in the UI that can lead to confusing experiences for players in multiplayer rooms.

Specifically, I am referring to the button for toggling Playing/Spectating status, that is in the bottom-left corner of the screen when inside multiplayer rooms:

![image](https://user-images.githubusercontent.com/94894395/186775078-0adb5e8f-a548-4b3c-b97c-e69e0446f9fb.png)

![image](https://user-images.githubusercontent.com/94894395/186774956-9ccb9317-3f3c-422c-ae66-fa69966c28e0.png)

Please bear with me if I don't have the details 100% correct, but what I describe should be enough to isolate the issue.  Clarifications on actual behavior are welcome.

From what I can tell, when joining certain rooms where you are eligible to hop into the next game once the current game finishes (a room that is isn't "full," perhaps), such as a room supporting up to 10 concurrent players but with only 5 in the room other than you, the game gives you the "Playing" status when you enter the room.  You can click the button to make it "Spectating."

But when joining certain other rooms in which you are not currently expected to be eligible to hop into the next game once the current game finishes (a "full room," perhaps), such as a 1v1 room with what is effectively a queue of players in the room each waiting their successive turn to 1v1, the game basically says it can't add you as a player because the player slots are full, so the game adds you as a spectator instead:

![image](https://user-images.githubusercontent.com/94894395/186775576-0aebdf7b-0962-48e1-bed8-3980b4aec72a.png)

![image](https://user-images.githubusercontent.com/94894395/186774956-9ccb9317-3f3c-422c-ae66-fa69966c28e0.png)

At first glance, this spectator button looks identical to the earlier one.  Surprisingly though, this second spectator status is not actually the same as the earlier one.  First, this second spectator status is actually queued to play (when it eventually becomes your turn sooner or later).  Second, and what is probably more problematic, you can't click the button to get off of the queue to become a "true" spectator.  If you try to click the button, the game will say that it can't add you as a player because the player slots are full:

![image](https://user-images.githubusercontent.com/94894395/186775269-15c13631-b4c3-45ea-a94d-17c825322f25.png)

This means you are basically stuck in this weird, pseudo-player, pseudo-spectator status.  (The way I've found to become a true spectator is by typing the appropriate command in the chat window.)

The resulting confusion can cause some players to think that they are truly spectating in a room when they are actually queued to play.  The confusion can also cause other players to leave rooms because the second spectating status causes them to think that they were not actually queued to play, when they were in fact queued to play.  The behavior of the button for the second spectator status being unable to toggle anything for the player only compounds the confusion.  One result could be that your typical player (who doesn't know the console command) cannot truly spectate such 1v1 rooms and other similar rooms deemed full.

### Expected behavior

When joining rooms in which the player slots are full, such as a 1v1 room with a queue of players all inside the room just waiting their turn to 1v1, the game could give the player an initial status of "Waiting to play," "Queued to play," or even just "Playing."

Then, the button could allow the player to toggle between that status and a "Spectator" status in which they are not waiting their turn to play.

This would make the UI consistent across multiplayer rooms, regardless of whether the player slots are full, thereby improving the player experience.

### Additional context

The feature addition that may have led to the current behavior: https://github.com/tetrio/issues/issues/9.

**Comment by godotgamedeveloper** [comment]
Commenting to avoid closure.

**Comment by godotgamedeveloper** [comment]
Replying to remove stale label.

**Comment by Dimentio** [comment]
I believe this got fixed lately, feel free to re-open if still occurring!
