### ISSUE TITLE
Room Setting don't update the new information in new room when Unsave previous room Setting and move to new room

### ISSUE THREAD

**Issue by thanhgaming5550** [tetrio/issues#1008]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 18362.30

### Browser and version

Chrome 103.0.5060.53

### Describe the bug/issue

When you have not saved the information in the old room but have moved to a new room, your settings in the old room will be overwritten with the settings in the new room (Only visible in your Client)

### Reproducing

1. Go (or create new) Multiplayer room **(You are owner)**
2. Make change in Room Setting and **DON'T SAVE** this
3. Tell your friend invite you to another room and accept it in-game

### Expected behavior

The new room's information will update the old information

### Screenshots

https://streamable.com/3ci456

**Comment by Dimentio** [comment]
Fixed in next update!
