### ISSUE TITLE
Active particles persist when switching to Zen

### ISSUE THREAD

**Issue by lucs100** [tetrio/issues#1009]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop

### Describe the bug/issue

When switching to Zen mode after being KO'ed in a multiplayer game, the active particles / attack travel animations on the board do not clear. This is usually only an issue when using painfully slow Garbage Travel Speed. I'm not sure if this would still occur when (for example) backing out of the room to a menu, I wasn't able to test this again.

### Reproducing

1. Start a multiplayer lobby.
2. Set Garbage Travel Speed to 10000.
3. Have garbage queued for your board. (Garbage travel indicators should be obnoxiously large and obstructive.)
4. Block/lock out.
5. Immediately switch to Zen.
6. Zen board will be obstructed by garbage particles.

### Expected behavior

All particles should be cleared upon a board becoming inactive (by KO or otherwise), or when switching "scenes" (eg. from a multiplayer game to Zen).

### Screenshots

![image](https://user-images.githubusercontent.com/59773132/187007617-16a064ea-a80e-453c-a944-ea724f74a061.png)

### Console logs

Not relevant

### Additional context

It's probably not that big of a deal because 99% of rooms don't use janky settings like this, but it's still annoying.

**Comment by Dimentio** [comment]
fixed in next update!
