### ISSUE TITLE
When Kicking/Banning a player, everything related to that player will be deleted in Multiplayer chat

### ISSUE THREAD

**Issue by thanhgaming5550** [tetrio/issues#1013]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 18362.30

### Browser and version

Chrome 103.0.5060.53

### Describe the bug/issue

**Read The Title**

Like that person said something important to you, and someone kicked/banned that person... Boom... You lost that important thing.
Moreover, everyone knows that the Room Owner has Kicked/Banned that person thanks to the chat sign that doesn't say that the person has left the Room and that person's old Chat disappears. It's **COMPLETELY DIFFERENT** from the person leaving on the initiative. (See in the Video)

### Reproducing

1. Kick/Ban someone in Multiplayer Room
2. See the difference in the chat

### Expected behavior

Behaving like the person actively left

### Screenshots

https://streamable.com/75rlql

### Additional context

I knew this is feature, but this is not **BLOCK**. This is **KICK/BAN**.

**Comment by ZaptorZap** [comment]
Sorry, but this is very clearly intended by osk as a feature of the chat system. You may review the patchnotes [here](https://tetr.io/about/patchnotes/#chlog_6_2_1)
> ➔ Chat messages by a user are now removed when they are kicked or silenced

As for rationale behind the decision: typically, users may be kicked for overtly negative behavior, and once they're under active moderation by a room host, we believe it is safe to remove these messages incase they include undue language. This is definitely more than a positive than a negative, as we can attest to reports after reports over the years with racist, derogatory language in public rooms. For the record, when you report a user who has been kicked, their "deleted", or rather, hidden messages will be preserved in your report.

Irregardless, a kick/ban indicates a clear intention that the user was not appreciated in the room, and removing their chat simply extends this meaning behind the action. If you're kicking a trusted friend, say, as part of a joke, then please understand that the system wasn't designed for inside jokes. It's designed to allow room hosts to **moderate their rooms.**
