### ISSUE TITLE
Lobby timing bug

### ISSUE THREAD

**Issue by waffledeluxe** [tetrio/issues#1015]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Macbook Pro

### Browser and version

Opera GX

### Describe the bug/issue

If you exit the lobby when the lobby starts, the counter will appear. you will not be playing the game however.

***(Please read the additional context!)***

### Reproducing

Join lobby
leave when the host clicks the "start" button
timer should appear without the game starting. 
(the chat should still be there too.)

### Expected behavior

I expected the chat/timer to not be on the home screen.

### Screenshots

![Screen Shot 2022-09-05 at 5 58 07 PM](https://user-images.githubusercontent.com/112222117/188519045-4787c243-a1cb-494b-8bd9-4bfe336dbfa5.png)

The chat is back there.

### Console logs

I cant do that lol

### Additional context

I AM using tetr.io plus, but nothing is being modified (I'm pretty sure). Tetr.io plus only modifies extra stuff about the game, ex. skins, music, and the map editor. It doesn't change anything about multiplayer rooms.

If this was caused from tetr.io plus, this is my fault, although that shouldn't be why.

There was also a similar timing bug like this that I've posted before this one, so idk if there's more of them.

**Comment by ZaptorZap** [comment]
Sorry, but this is about the principle—point is, TETR.IO PLUS **has the capacity** to cause this, and osk will not fix TETR.IO PLUS if that's the case. At the end of the day, you were literally lying to us when you checked this box:
![image](https://user-images.githubusercontent.com/64891705/188526389-83453dff-dc88-417f-a98c-21fd850c709f.png)

The rules exist for a reason, and there's no jury nullification on GitHub. That said, I'd still group this in as a duplicate issue of #989.
