### ISSUE TITLE
Track TR gain/loss in match history

### ISSUE THREAD

**Issue by Droxescee** [tetrio/issues#1016]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I'd like to see how many TR i gained or lost even after i exit the after-game-lobby.

### Describe the solution you'd like

Show TR gain/loss in Tetra League Records per Game.

### Describe alternatives you've considered

It would be nice to have the Tetra League Page on the Client too, basically a proper Match-History that (maybe, don't know what the ressources are) could display more than only the 10 most recent matches.

This could be extended into statistics graphs and such to see how you improved over the past x amount of time, even in-game stats could be extracted into the statistics. Tho this is not the request, it could be a cool feature.

There could also be something like a 'trend', like how much you've gained lost on average over the recent x amount of matches.

### Additional context

I don't know if TR-Points is the right term, but i'm talking about the number you gain or loose after a match, which is the Number describing your skill in the Game and therefore is ranking you in Leagues relative to the Number, a higher number is representing a better player and a lower number is representing a worse player.

I would like to see this number somewhere else, preferably in a per-game basis, even after exiting the after-game-lobby.

**Comment by ZaptorZap** [comment]
The alternative you suggested is covered in-depth around #902 and #830—particularly including services that already provide these sorts of trendy statistics. I've also seen a couple people hand-craft Google Sheets that track TR gain and loss per match for you, but, of course, those are no substitute for an official feature and require far more active upkeep. Just adding some context!
