### ISSUE TITLE
Support on Nintendo Switch BrowseDNS (browser check fix)

### ISSUE THREAD

**Issue by UnderNoControl** [tetrio/issues#1017]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Tetr.io will hang on the browser check screen when trying to open on a Switch using BrowseDNS. (https://switchbru.com/dns/)

### Describe the solution you'd like

idk make it work or something.

### Describe alternatives you've considered

Release Tetr.io on Switch, though I highly doubt that would ever happen as its an unofficial game.

**Comment by o5k** [comment]
The Switch browser does not support WebGL, so even if you manage to get past Cloudflare you'll still have trouble, sadly
Get a Steam Deck :^)
