### ISSUE TITLE
nvm, i figured it out, pls igore

### ISSUE THREAD

**Issue by lilchild** [tetrio/issues#1020]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

i accidently get logged out and i have to make a new accont where i ahve to grind back up. 

### Describe the solution you'd like

make a login button sao people dont have to really struggle

### Describe alternatives you've considered

there actully really arent much. but there could be a link thats sent to the email you've registered with and that could sign you in.

**Comment by ZaptorZap** [comment]
Oh dear...what you've explained here is very against [the rules](https://tetr.io/about/rules/#altpolicy). You also failed to document any sort of instructions for others experiencing the same issue, so [here's some in this FAQ](https://github.com/ZaptorZap/tetriofaq/wiki/Personalization#logging-into-your-account).
