### ISSUE TITLE
Zen mode header shows when joining a room via invite

### ISSUE THREAD

**Issue by 25Pi25** [tetrio/issues#1021]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome 105

### Describe the bug/issue

When I was in quick play zen mode, I was sent a lobby invite and I accepted. When I got there, the zen mode header that says "ZEN WHILE WAITING" still displays in the main lobby. Clicking on it removes the header without anything else occuring.
![image](https://user-images.githubusercontent.com/67805443/191588716-c549bd51-c6ea-4be6-b2dc-8989e0dd2aba.png)

### Reproducing

1. Go to a lobby in progress
2. Open Zen Mode
3. Receive an invite from someone to another lobby
4. Accept and the zen header will still be there

### Expected behavior

I expected the zen header to be removed from the screen.

### Screenshots

https://user-images.githubusercontent.com/67805443/191588716-c549bd51-c6ea-4be6-b2dc-8989e0dd2aba.png

### Console logs

![image](https://user-images.githubusercontent.com/67805443/191590303-f275f1b3-2935-4ba9-8e85-ab12dedc3dd5.png)
![image](https://user-images.githubusercontent.com/67805443/191590351-b5ff776f-9eb7-422e-addd-b75c05a57f3f.png)
![image](https://user-images.githubusercontent.com/67805443/191590378-4448b010-c788-47bb-8367-27499c117cf6.png)
![image](https://user-images.githubusercontent.com/67805443/191590410-d3ad27ba-1eab-43a0-bf01-3a2400c5ae28.png)
![image](https://user-images.githubusercontent.com/67805443/191590431-0e91e6f9-ab55-4372-a736-361187992cc3.png)

### Additional context

nothing really breaks the game it's just a small thing

**Comment by Dimentio** [comment]
Fixed in upcoming update!
