### ISSUE TITLE
Connected to wrong spool server making ping way worse

### ISSUE THREAD

**Issue by Artixuwu** [tetrio/issues#1023]
I'm a player from South Africa and the game keeps connecting me to the Brazil server and then from Brazil to France, giving me 330+ms ping. If the game sometimes connects me to London or straight to France I get 160ms ping at most. Is there a way to maybe disable the spool server option for me to get better ping? I'm struggling a lot with stuff like passthrough and overall lag when I'm connected to Brazil with 330ms latency.

**Comment by WallOfMessages** [comment]
"user couldn't be bothered with the issue template" BRO :skull:

**Comment by Imagine-Gamer** [comment]
yall really had a tag for "user couldn't be bothered with the issue template" lmao.
