### ISSUE TITLE
board not showing

### ISSUE THREAD

**Issue by dNexdeez** [tetrio/issues#1024]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

macOS Monterey version 12.6

### Browser and version

Chrome Version 105.0.5195.125

### Describe the bug/issue

board and queue does not load or show on any game modes
pieces can move and drop
sfx can be heard

![Screenshot 2022-09-23 at 9 45 32 PM](https://user-images.githubusercontent.com/114239296/191974822-2015f515-d68a-46d7-859e-ddd83988e637.png)
example of 40 lines

### Expected behavior

board was supposed to show but isn't

### Console logs

VM10:4253 TETR.IO
VM10:4253 Please be careful when pasting anything in the console. Attackers may be out to steal your login information.
VM10:4253 Up to date. Local version 6.3.0-production | Commit a047f021 (13/09/2022, 23:48:26) | Server cycle NAr73J0Df | Build d5ARXmEtv (20/09/2022, 19:55:28)
VM10:4253 tetr-io_728x90_9 mounted, now 1 mounts
tag.min.js:1154 
     ✰ TTI - tetr.io ✰ aiplib v11.0 - prebid v6.24.1 - MCM 22431394745 ✰      ads by https://www.adinplay.com/    
VM10:4253 Ceriad provider has been loaded successfully.
VM10:4253 tetr-io_728x90_9 unmounted, now 0 mounts
VM10:4253 tetr-io_970X250_1 mounted, now 1 mounts
VM10:4253 PixiJS 6.1.3 - WebGL 2
VM10:4253 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 -
CPU: 12-core
Memory: ~8 GB
Connection: 10 Mbps, 50ms RTT [4g]
VM10:4253 Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 5300M OpenGL Engine, OpenGL 4.1)
VM10:4253 InitialConnect > Obtaining Ribbon endpoint...
VM10:4253 InitialConnect > Obtained Ribbon endpoint /ribbon/lucia and 20 spools.
VM10:4253 InitialConnect > Getting a spool...
VM10:4253 InitialConnect > Spool > Spooling started
VM10:4253 InitialConnect > Spool >    22ms ap-south-komori [SG] v2 // 0.15625, 0.15625, 0.15625
VM10:4253 InitialConnect > Spool >    16ms ap-south-fuuka [SG] v2 // 0.21875, 0.15625, 0.109375
VM10:4253 InitialConnect > Spool >    20ms ap-south-nozomu [SG] v2 // 0.1875, 0.1875, 0.125
VM10:4253 InitialConnect > Spool > Spooled ap-south-fuuka!
VM10:4253 InitialConnect > Obtained spool ap-south-fuuka (ap-south-fuuka.spool.tetr.io) [SG].
VM10:356 Ribbon 30e8d7300f1a373c opened
VM10:4253 tetr-io_970X250_1 unmounted, now 0 mounts
VM10:4253 tetr-io_728x90_2 mounted, now 1 mounts
VM10:4253 tetr-io_728x90_2 unmounted, now 0 mounts
VM10:4253 tetr-io_728x90_10 mounted, now 1 mounts
74
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
VM10:4253 tetr-io_970X250_1 mounted, now 2 mounts
VM10:4253 tetr-io_728x90_10 unmounted, now 1 mounts
impl_v91.js:100 Unrecognized feature: 'attribution-reporting'.
impl_v91.js:112 Origin trial controlled feature not enabled: 'attribution-reporting'.
VM10:4253 tetr-io_970X250_1 unmounted, now 0 mounts
VM10:4253 tetr-io_970X250_1 mounted, now 1 mounts
VM10:4253 AmbientRespool > Starting ambient respool.
VM10:4253 AmbientRespool > Obtaining Ribbon endpoint...
VM10:4253 AmbientRespool > Obtained Ribbon endpoint /ribbon/chihaya and 20 spools.
VM10:4253 AmbientRespool > Getting a spool...
VM10:4253 AmbientRespool > Spool > Spooling started
VM10:4253 AmbientRespool > Spool >    10ms ap-south-komori [SG] v2 // 0.015625, 0.109375, 0.125
VM10:4253 AmbientRespool > Spool >    13ms ap-south-nozomu [SG] v2 // 0.140625, 0.15625, 0.109375
VM10:4253 AmbientRespool > Spool >    13ms ap-south-fuuka [SG] v2 // 0, 0.078125, 0.078125
VM10:4253 AmbientRespool > Spool > Spooled ap-south-nozomu!
VM10:4253 AmbientRespool > Obtained spool ap-south-nozomu (ap-south-nozomu.spool.tetr.io) [SG].
VM10:4253 AmbientRespool > Obtained new token, no significant ping advantage 12ms → 13ms.
VM10:4253 tetr-io_970X250_1 unmounted, now 0 mounts
VM10:4253 tetr-io_728x90_2 mounted, now 1 mounts
VM10:4253 tetr-io_728x90_2 unmounted, now 0 mounts
impl_v91.js:100 Unrecognized feature: 'attribution-reporting'.
VM10:4253 AmbientRespool > Starting ambient respool.
VM10:4253 AmbientRespool > Obtaining Ribbon endpoint...
sca.17.6.2.js:32 a: 0.01416015625 ms
VM10:4253 AmbientRespool > Obtained Ribbon endpoint /ribbon/lucia and 20 spools.
VM10:4253 AmbientRespool > Getting a spool...
VM10:4253 AmbientRespool > Spool > Spooling started
VM10:4253 AmbientRespool > Spool >    11ms ap-south-komori [SG] v2 // 0.203125, 0.15625, 0.140625
VM10:4253 AmbientRespool > Spool >    13ms ap-south-chiri [SG] v2 // 0.015625, 0.109375, 0.109375
VM10:4253 AmbientRespool > Spool >    12ms ap-south-nozomu [SG] v2 // 0.234375, 0.234375, 0.15625
VM10:4253 AmbientRespool > Spool > Spooled ap-south-komori!
VM10:4253 AmbientRespool > Obtained spool ap-south-komori (ap-south-komori.spool.tetr.io) [SG].
VM10:4253 AmbientRespool > Obtained new token, no significant ping advantage 11ms → 11ms.
VM10:4253 tetr-io_728x90_10 mounted, now 1 mounts
DevTools failed to load source map: Could not parse content for https://tetr.io/tf.min.js.map: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
amp-inabox.js:129 Powered by AMP ⚡ HTML – Version 2209072154000 https://tetr.io/
amp-ad-exit.js:439 Unrecognized feature: 'attribution-reporting'.
amp-inabox.js:129 Powered by AMP ⚡ HTML – Version 2209072154000 https://tetr.io/
amp-ad-exit.js:439 Unrecognized feature: 'attribution-reporting'.
﻿

Uploading Screen Recording 2022-09-23 at 9.49.26 PM.mov…

**Comment by Que-tin** [comment]
Duplicate from - #895

**Comment by ZaptorZap** [comment]
Felt pretty low quality.
