### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Wifz** [tetrio/issues#1029]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 10

### Browser and version

chrome 106

### Describe the bug/issue

i could play the game started but i was still in the menu and i crashed

### Reproducing

what ?

### Expected behavior

let me menu load for a little time and after the game start

### Screenshots

i cant

**Comment by ZaptorZap** [comment]
This is extremely vague, we can't help you with this issue's current state. If you have actual details please supply them in a reply to this comment.
