### ISSUE TITLE
hold CONTROL and press Z/Y will not response

### ISSUE THREAD

**Issue by Richard969** [tetrio/issues#1030]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Arch Linux x86_64, Linux-zen 6.0.2

### Browser and version

Desktop Client

### Describe the bug/issue

Pressing Control + Z at the same time will not do what it should to do (e.g. 180-rot, hold)

### Reproducing

1. Start a game
2. Hold CONTROL and press Z/Y
3. See weird behavior

### Expected behavior

Game response input normally.

### Additional context

Looks like appears on all mode(either have undo or don't have undo)
For my case:
RCONTROL for SD, Z for 180

**Comment by ZaptorZap** [comment]
nah
