### ISSUE TITLE
soft drop continues even after button is released

### ISSUE THREAD

**Issue by CompactLethargy13** [tetrio/issues#1039]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

MacOS 13.0 Beta (22A5365d)

### Browser and version

Desktop client

### Describe the bug/issue

i use instant soft drop
sometimes even after i release the button for soft drop, the game behaves as if soft drop is being held down, causing mino to instant soft drop repeatedly

### Reproducing

set sdf to infinity
build a tall stack on the left with nothing on the right
soft drop onto the stack and immediately move the mino over the right
the mino should instant soft drop to the bottom of the well even when soft drop isn't held down

### Expected behavior

the mino should not soft drop all the way down

### Screenshots

https://user-images.githubusercontent.com/107340414/199037398-d041033a-18d0-4319-8830-ee08e3b65cc9.mov

### Console logs

<img width="555" alt="image" src="https://user-images.githubusercontent.com/107340414/199037566-4c0f25a8-bcbf-4b03-88ca-02e35a5a8843.png">

### Additional context

im using default wasd keybinds
this only happens if softdrop and move are pressed in quick succession

i really hope that you can fix this because it is affecting me when I'm playing in tetra league :(

**Comment by godotgamedeveloper** [comment]
I think this can be fixed via a fix for https://github.com/tetrio/issues/issues/901.  Note my video clip in reply to that issue.

**Comment by CompactLethargy13** [comment]
[replay1.zip](https://github.com/tetrio/issues/files/10201684/replay1.zip)
Heres a replay (sorry for late reply)
