### ISSUE TITLE
Zen mode loading mechanism causes illegal piece generation

### ISSUE THREAD

**Issue by MkTr** [tetrio/issues#1041]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 7

### Browser and version

chrome 107

### Describe the bug/issue

While I was playing Zen Mode (I'm playing on browser), three T pieces appeared in the queue in a row (screenshot below). Uh, if I understand how the 7-bag system works, this should be impossible, right? 
Unfortunately I don't have any screenshots of the pieces afterwards, at the time I just assumed I was going insane and reset. The only thing I think could have caused this is the undo/redo system, which I've been using a lot to practice 4-wide, possibly in combination with constantly leaving and entering zen mode to play multiplayer. Another thing to note is that I feel like I'm getting bizarrely unlucky, getting a ton of the same one or two pieces in a row - not breaking the 7-bag rules, just bizarre coincidences, most often SZSZ and LJLJ. Is it possible that undoing and redoing could be causing that too?

### Reproducing

Assuming the Zen mode uses a seed to generate its pieces, I guess the best way to test this is by playing two Zen games with the exact same seed, and using undo/redo every now and again in one of them, maybe leaving and entering it every now and again, and seeing if the pieces desync. Really sorry if this is a wild goose chase, but if there's a problem, I hope this is easy for you to set up.

### Screenshots

https://cdn.discordapp.com/attachments/911134969781420082/1041896415766528090/HOW.png

**Comment by ZaptorZap** [comment]
This seems altered by a known phenomena caused by ZEN mode's loading mechanic:
> y'see, the way tetrio saves your next queue when you forfeit a game of zen mode is really simple. it takes your currently active piece and the next five pieces, then stores it in a local string known as "zenProgression". then when you load back up zen mode, it'll read "zenProgression", see the next six pieces, then revert to normal 7bag randomization after the defined next queue from "zenProgression" is used up
with this, it's totally possible to get an entirely filled I piece queue legitimately if you grind for it long enough

I've done just that on purpose before: it's just a limitation with maps not saving queue states. Now nobody has considered the implications of undo/redo effecting this issue, though.

**Comment by MkTr** [comment]
Oh, that might be it then. I _vaguely_ remember that the triple-T happened shortly after I entered zen mode, but I'm not sure. Sorry if it turns out that there's no bugs with undoing/redoing.

**Comment by MkTr** [comment]
Oh uh, since the issue was reopened I've got a suggestion
Instead of saving the next five pieces, you can save the seed that the zen mode started with, a second seed, and the number of pieces which have been placed. When zen mode is loaded, you run the seed through the random number generator a number of times equal to the amount of pieces placed, then the player's back where they left off. And every 700 pieces, at the end of the last bag, you start the next bag with the new second seed, reset the pieces placed count to 0 when the new bag is reached, and generate a new seed for the next 700 pieces. (The point of saving two seeds at the same time is in case the player quits on pieces 695-700, when the newly generated bag is visible). 
The point of resetting the seed every 700 pieces is just in case someone decides to play zen mode without ever resetting - if they placed tens of thousands of pieces, the seed would be put through the RNG tens of thousands of times. But if lag isn't ever going to be an issue you can just save one seed and pieces placed without a limit.

**Comment by ZaptorZap** [comment]
I mean all you really need to do is complete the current bag and resume normal operation afterwards. Remember that the map field is a string of letters? Perhaps the "current" bag of the 5th next piece would be saved like `?so[lijt]`, which signifies that the current bag has already used `L I J T` and should shuffle around what's left(`S Z O`) before generating the next bag over, making, for instance, a queue of `S O L I J T O Z S`.
