### ISSUE TITLE
add offline play

### ISSUE THREAD

**Issue by peejxyy** [tetrio/issues#1042]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Black screen when loading Tetr.io client offline.

### Describe the solution you'd like

I would like for you guys to add the offline feature, so users can play tetris anytime, anywhere, that does not have internet connection.

### Describe alternatives you've considered

i cant find no alternative to this because the web version definitely uses internet connection.

**Comment by ZaptorZap** [comment]
This's a duplicate of #521
