### ISSUE TITLE
Game mode displays as "undefined" when loading a solo custom game replay

### ISSUE THREAD

**Issue by JadiPlayz** [tetrio/issues#1043]
### Checklist

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 21H2

### Browser and version

Chrome 107

### Describe the bug/issue

When you play 4-wide board width with a custom game, when you load the replay: it says undefined

### Reproducing

1:Go to Tetrio
2:Go to solo, custom game,set board width to 4, make the lines onto whatever you want
3:After the game, save the replay
4:Load the replay

### Expected behavior

nothing

### Screenshots

![image](https://user-images.githubusercontent.com/4703499/202459120-a1560281-6738-464c-8bcd-f56ceda1d8d3.png)
![image](https://user-images.githubusercontent.com/4703499/202459150-f7ac2069-6565-40da-b207-65d54a3e26bd.png)

### Console logs

nothing

### Additional context

nothing

**Comment by ZaptorZap** [comment]
Can you please upload the replay file? This is most likely caused by the unprepared behavior for when `/savereplay` is invoked on 3+ player matches.

**Comment by JadiPlayz** [comment]
oh and also,its custom game

**Comment by ZudoB** [comment]
@JadiPlayz please relax, there's no need to open more than one issue - and you're free to edit your original post, rather than repeatedly commenting

**Comment by JadiPlayz** [comment]
> > @JadiPlayz please relax, there's no need to open more than one issue - and you're free to edit your original post, rather than repeatedly commenting
> 
> oh nice

also I cannot paste screenshots so I opened a new issue

**Comment by JadiPlayz** [comment]
also,i played width:4-Wide
