### ISSUE TITLE
Music non-plays sometime

### ISSUE THREAD

**Issue by JadiPlayz** [tetrio/issues#1046]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 21H2

### Browser and version

Chrome 107

### Describe the bug/issue

Sometimes,music stops playing.

### Expected behavior

not me

**Comment by Muwqas** [comment]
might be because you have "disable sound entirely" option enabled

**Comment by JadiPlayz** [comment]
I am sorry.
This issue got stale at a time.
This issue will close so the bug tracker will keep clean.

**Comment by JadiPlayz** [comment]
This issue will open after an undated time.

**Comment by JadiPlayz** [comment]
Good news!
This issue will open today!

**Comment by JadiPlayz** [comment]
ok i need this issue to open so im commenting and i will close when possible
