### ISSUE TITLE
Inputs not responding well

### ISSUE THREAD

**Issue by Snipe061** [tetrio/issues#1050]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome version 107.0.5304.107 

### Describe the bug/issue

When i am playing, sometimes when i press keys on the keyboard, the inputs are not registering in the game and sometimes i have double drops. You can check an example with this replay: https://tetr.io/#R:rhezs6iSp
I don't think it comes from my keyboard because it is quite new so i think it's from the game or the connexion.

### Reproducing

1. Go to Tetra League
2. Try to place your pieces by pressing the keys
3. The errors will happen : either inputs are not responding or double drops

### Expected behavior

All my inputs should be registered well as expected when I press the keys

### Screenshots

https://tetr.io/#R:rhezs6iSp

### Additional context

I also tried to enable "prevent accidental hardrops" but it doesn't help

**Comment by ARDEACT** [comment]
I've had tons of latency with windowed mode, playing in fullscreen seems to unlock the framerate and the game will feel very responsively. Although the FPS limiter for me isn't working, that's another issue post I have to create.
