### ISSUE TITLE
The happen I spectate, the lag happens

### ISSUE THREAD

**Issue by JoseChuaJuanChen2022** [tetrio/issues#1051]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Firefox 107.0

### Describe the bug/issue

When I spectate any room, sometimes cause lag, it could be a bug when I see this... and some(or 1) board may become invisible. But when I reload, it's working again.

### Expected behavior

It may be something that is caused to happen, or others. I have no idea why it lags the game when you spectate sometimes

**Comment by ZaptorZap** [comment]
Network issues are outside the scope of this repo.
