### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by dinosaurnugget** [tetrio/issues#1054]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 11

### Browser and version

chrome Versie 107.0.5304.122

### Describe the bug/issue

it says network error when i am playing a tetra league game, it kicks me out and my tr goes way down. I was S- and i dropped down to A+ by a lot. it is annoying, i tried the website, cuz i usually use the desktop thingy. So please help

### Expected behavior

i expect to be able to finish a tetra league game

**Comment by ZudoB** [comment]
we're undergoing a large scale DDoS attack, be patient
