### ISSUE TITLE
Tetrio desktop client trapped inside of room that doesn't exist

### ISSUE THREAD

**Issue by Blocksnmore** [tetrio/issues#1059]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Arch Linux x86_64 6.0.12-arch1-1 (Wayland)

### Browser and version

Desktop 6.3.1-PRODUCTION

### Describe the bug/issue

I left a room right as it was being started and my screen had the "You KO'd yourself" message at the top as well as my kill in the deathlog on the menu. Then it showed the game over page and once I clicked continue it took me to the room page but the room didn't exist anymore as my friend also left. Resulting with me being stuck inside of the room as shown in the video: 

https://user-images.githubusercontent.com/51055767/208211322-1c632fee-35b5-4ef0-ae97-0074e6f7246a.mp4

You can't exit the room with the exit button nor escape so your only way to exit the bug is close the game and reopen. 

### Expected behavior

Keep me in the main menu or at least let me leave the room.

**Comment by ZaptorZap** [comment]
This likely doesn't have anything to do with the Desktop Client; the same happens on browser all the time. That said, you can just reload the game on the desktop client with F5—that'd likely fix the issue all the same.
