### ISSUE TITLE
Option to remove holiday filter on tetrio vs mode

### ISSUE THREAD

**Issue by yourlocaljedi** [tetrio/issues#1062]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Hello, I tried looking through the setting and I dont see an option to remove the holiday filter and revert it to the original layout. Like I love the lights, but the way that the grid is filter makes it very difficult to see open spots while playing, making me think that the spot is filled but its not. 
Thank you. 

### Describe the solution you'd like

Maybe keep the lights and remove the grid holiday filter would be better. Or to have the option to have the xmas lights filter only. 

### Describe alternatives you've considered

Maybe keep the lights and remove the grid holiday filter would be better. Or to have the option to have the xmas lights filter only.

**Comment by ZudoB** [comment]
it is quite literally at the top of the settings menu

![](https://zudo.pics/dt6lr70j.png)
