### ISSUE TITLE
Custom Background showed in black

### ISSUE THREAD

**Issue by VolNUTt64** [tetrio/issues#1063]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop Client

### Describe the bug/issue

The background is pitch black when i customize.

### Expected behavior

It is supposedly to show to image I assigned.

### Screenshots

![Screenshot 2022-12-22 144021](https://user-images.githubusercontent.com/121201996/209222163-7a7df2ad-9dbb-4c26-a77f-993eb5b6127a.png)

### Additional context

I already use the link with and without the https://

**Comment by ZaptorZap** [comment]
According to [this interactive checker](https://you.have.fail/ed/at/tetrio/backgrounds/), that URL doesn't send CORS headers. This isn't our issue.
![image](https://user-images.githubusercontent.com/64891705/209235002-d12b4cf4-fbcd-4f55-83ff-558c33510889.png)
