### ISSUE TITLE
Unable to log in due to an connection error

### ISSUE THREAD

**Issue by MESIR1** [tetrio/issues#1067]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Chromebook 107.0.5304.110

### Browser and version

Chrome 

### Describe the bug/issue

Whenever I try to log in to play the game, I get a notification that a connection error has occurred. I am sure that this is not on my side, because I am able to use the wifi at fast speeds. It could potentially be an IP ban as the IP has been banned before due a person repeatedly breaking the multicounting rule

### Reproducing

go to TETR.io and try to log in, it should work. 

### Expected behavior

I expected to be able to log into Tetr.io

### Screenshots

https://user-images.githubusercontent.com/103009976/209409417-f648277b-5d56-42f9-8889-3caa2ce229f8.png

### Additional context

fun game

**Comment by ZudoB** [comment]
known issue, the outage is being worked on

https://twitter.com/tetriogame for updates

**Comment by ZaptorZap** [comment]
Yes, there's current unplanned infrasturcture downtime. Yes, we're all aware. Unfortunately, this issue is out of scope of this repository. See [osk status](https://status.osk.sh/) and [the @tetriogame Twitter](https://twitter.com/tetriogame) for the latest details.

**Comment by MESIR1** [comment]
thanks

**Comment by Dimentio** [comment]
![BkGXO2_AKVdD849CCjaAT](https://user-images.githubusercontent.com/3157366/209410612-c4d1ee42-7fde-4771-9e23-0d31872e5b2b.jpg)
