### ISSUE TITLE
Update desktop electron version

### ISSUE THREAD

**Issue by huantianad** [tetrio/issues#1068]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

TETR.IO Deskop is currently running Electron 9, which reached end-of-life 2 years and 8 months ago already. This is a pretty big security concern, as well prevents it from new features and fixes included in newer electron versions.

### Describe the solution you'd like

Update TETR.IO Desktop to the latest Electron version.

### Describe alternatives you've considered

I can't think of any.

**Comment by Monredo** [comment]
I don't know if it's gonna run on Electron 9 or not...

**Comment by huantianad** [comment]
@Monredo sorry, I don't understand.

**Comment by Dimentio** [comment]
It's planned to be updated!

**Comment by huantianad** [comment]
Awesome! Looking forward to it :)

**Comment by huantianad** [comment]
Don't want to badger, but any updates on this? Still a pretty important issue imo.

**Comment by huantianad** [comment]
Hello, any further action on this? Electron 9 is very outdated by now, it reached EOL March 2021 and is using an ancient version of chromium. I feel this is a severe security issue and should not be so easily ignored.

**Comment by o5k** [comment]
Slated for next tetrio-desktop build, note we will test for a bit internally as our apprehension to jumping versions comes from many arcane issues with graphics (especially AMD as per the usual)

We plan to jump to Electron 22 to retain Windows 7 support for the time being, if need be we will have separate builds for W7 and W10+, even if the web world moves fast we hope to be able to sit on the featureset of chromium108 for a while

**Comment by huantianad** [comment]
Awesome to hear! I feel you with the graphics issues, though I'd personally argue that windows 7 support is not necessary anymore, and it's more important to keep up with the current electron version for security concerns rather than feature. That aside though, I'm looking forward to this update!

(Hopefully this also comes with fixing some of the major electron configuration issues in the current app that are very much bad security practice lmao)

Thanks for the communication 🙏

**Comment by huantianad** [comment]
Should this be closed with the release of desktop v9?

**Comment by Dimentio** [comment]
Yeah sure!

**Comment by huantianad** [comment]
Thanks again for the update, makes the package over in https://github.com/NixOS/nixpkgs/pull/300166 much nicer :)
