### ISSUE TITLE
Join date in a certain way

### ISSUE THREAD

**Issue by Monredo** [tetrio/issues#1070]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I need to see a date which would be included where the user is joined on its text below the level and the XP overall.

### Describe the solution you'd like

Instead of the date age, This userpage shows the date where the user has been joined from the last year(s), month(s), or day(s).

### Additional context

![ch tetr io_u_evapotetra (1)](https://user-images.githubusercontent.com/107286254/211454520-2b527470-9df8-457a-850a-2f9fb56eb631.png)

**Comment by ZaptorZap** [comment]
You can also hover over the relative date stamp to get your join date to the **precision of seconds**. #459 requested this already.

**Comment by Monredo** [comment]
> You can also hover over the relative date stamp to get your join date to the **precision of seconds**. #459 requested this already.

Oh ok
