### ISSUE TITLE
game in a lobby

### ISSUE THREAD

**Issue by zoil40** [tetrio/issues#1073]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

chromeos

### Browser and version

idk

### Describe the bug/issue

the game started right after it ended, and the only way to play was trogh spectate. the play area was in the background. this happened to everyone in the lobby.

### Reproducing

unknown

### Expected behavior

i expected the normal lobby and to wait for the host to start.

### Screenshots

i dont have any

### Console logs

i had closed the tab.

### Additional context

none

**Comment by o5k** [comment]
theres very little i can do with this issue report considering theres no info
ive heard of this before tho ill look into it
