### ISSUE TITLE
Server connection

### ISSUE THREAD

**Issue by StoreFrontSanta** [tetrio/issues#1074]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I've noticed that when I'm doing a private room with my friends, we experience major lag spikes. this has been a repeated issue. Instead of connecting me and my friends to an American server, it transfers us to french servers. We believe this is causing our lag spikes, along with the process of loading ads in the middle of a match. 

### Describe the solution you'd like

Add a feature that allows us to choose our servers. Also only load one ad per match in order to prevent lag spikes in the middle of a match.

### Describe alternatives you've considered

One alternative is to allow the servers to connect us to a server related to our marked country. Also, limit the number of ads shown in a match or extend the time they are featured, preventing those with slower computers from staring at one frame for upwards of 30 seconds.

**Comment by o5k** [comment]
![](https://kagari.online/kishikawa_yoshiko.png)

**Comment by o5k** [comment]
connection problems outside of scope of repo
