### ISSUE TITLE
Please!

### ISSUE THREAD

**Issue by adisom9875642** [tetrio/issues#1077]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Hello , My game name is MARIO48139881 , I have some question . How can i play with bot(zzztoj)? Thank you for answer.

### Describe the solution you'd like

Let me play with bot,please!

### Describe alternatives you've considered

Let me play with bot,please!

**Comment by ZaptorZap** [comment]
Please Direct Message the bot ingame by first friending it, then sending it `!invite` in the social system. If it doesn't respond, then it may be completely inaccessible—as an end user, there is nothing you can do to remedy this. ZZZTOJ **is not** an official TETR.IO feature.

**A quick note!** This repository is for ingame requests only! Consider asking questions such as these in [the TETR.IO Discord server](https://l.tetr.io/discord) instead in the future.
