### ISSUE TITLE
When closing the desktop client: Bunch of javascript errors when the storage is full

### ISSUE THREAD

**Issue by Camillewz24340** [tetrio/issues#1081]
### Checklist

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Lubuntu (LxQt) 22.04

### Browser and version

Tetr.io desktop client, Chrome 108

### Describe the bug/issue

While closing the client, i get alot of javascript errors because my storage is full, it may be because it haves to write something in the disk but it's full.

### Reproducing

1. Start TETR.IO desktop client
2. Make the storage full (yes this is completely stupid)
3. Try to close TETR.IO desktop client

### Expected behavior

TETR.IO client must close properly without errors

**Comment by ZudoB** [comment]
of course you're going to run into errors..? if you have no disk space remaining you have bigger problems to worry about
