### ISSUE TITLE
Aborting when autostart starts the game makes the timer go negative

### ISSUE THREAD

**Issue by Lishouuu** [tetrio/issues#1085]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Tetris desktop

### Describe the bug/issue

Aborting when the game is starting (with autostart enabled) makes the timer go to -infinity

### Reproducing

1. Enable autostart
2. Set timer to 15
3. Wait until timer start the game
4. Type /abort while the game is starting ( At the 3, 2, 1 countdown )
5. Enjoy

### Expected behavior

Timer should restart to it's initial number

### Screenshots

![image](https://user-images.githubusercontent.com/61601267/220172101-f5b0e255-2e45-4232-a174-68a9ef0ebfc8.png)

**Comment by ZaptorZap** [comment]
Reproduced and made a video out of it.

https://user-images.githubusercontent.com/64891705/220679357-c667c2a6-e7c5-464a-8a9a-aec3b3963e89.mp4

**Comment by Dimentio** [comment]
Was fixed in one of the maintenance!
