### ISSUE TITLE
Delete old account

### ISSUE THREAD

**Issue by ofYulia** [tetrio/issues#1087]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

If the nickname I want to use already exists

### Describe the solution you'd like

Delete accounts below level 100 with no login history for over 24 months

### Describe alternatives you've considered

It would be nice if you could use a nickname for an account below level 100 that has not logged in for more than 2 years through 24 months of sponsorship.

### Additional context

If it is possible to change the name through sponsorship, please tell me about Discord 수면바지#9074. or ilg88889@gmail.com

THANK YOU!

**Comment by ZudoB** [comment]
Account-related questions should go to support@tetr.io
