### ISSUE TITLE
GDPR cookie consent window does not display properly on 2K monitors

### ISSUE THREAD

**Issue by monroethelizard** [tetrio/issues#1088]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Desktop client (latest version, first-time installation)

### Describe the bug/issue

When I select to modify my cookie consent options, a pop-up window appears asking me to select which cookies I would like to accept. However, the window is mostly empty, with hyperlinks for "legitimate interests" and "partners" overlapping. Clicking these links seems to do nothing.

This bug occurs only on my 2560x1440 monitor, whereas the text appears fine on my 1920x1080 monitor.

### Reproducing

1. Launch TETR.IO desktop client after a fresh installation
2. Have the window maximised on a 2K-resolution monitor (i.e., 2560x1440 resolution).
3. Click "More Options" at the bottom.
4. The bugged window appears.

### Expected behavior

The window should have displayed text allowing me to consent or object to personal data processing.

### Screenshots

![Tetrio_cookies](https://user-images.githubusercontent.com/87441504/221381151-a3853816-c535-4496-9b6d-45f08e50e9a5.png)
![Tetrio_bug](https://user-images.githubusercontent.com/87441504/221381153-96f79fb0-7752-4bda-92a5-051cf63e42b9.png)

**Comment by o5k** [comment]
Good catch; seems to have been an issue with Quantcast jank and my trying my best to make it not look _as_ bad as it usually does. It should be fixed now!
