### ISSUE TITLE
Pieces rapidly missdrop

### ISSUE THREAD

**Issue by kinh123** [tetrio/issues#1092]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome 110.0.5481.177

### Describe the bug/issue

Right after i drop a piece, another one drop right away without me pressing space

### Reproducing

1. Start a game of tetris
2. Just drop a piece or do it several times
3.   See error

### Expected behavior

When you drop a piece, you may see the next piece also fall right away

### Console logs

![image](https://user-images.githubusercontent.com/75014283/223932505-08928b62-66ce-4131-ac88-bf3f5f21591b.png)

**Comment by ZaptorZap** [comment]
Could you send an example replay file of this occurring? Quite frankly this just seems like a hardware issue we cannot amend without disrupting higher ranked players who do hard drop that quickly.

**Comment by kinh123** [comment]
2023-03-12 18-39-42.mp4
<https://drive.google.com/file/d/1FeEdhhPiio7FFcwNsC5UjIifq963IPYo/view?usp=drive_web>
As  you can tell at around 0:52, when i drop the L piece, the I piece also
drop

Vào Th 5, 9 thg 3, 2023 vào lúc 22:24 Zaptor ***@***.***>
đã viết:
