### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by Labeeb2339** [tetrio/issues#1094]
WHEN I PLAY 40 LINES TETR IO DOESNT GIVE ME XP AND WHEN I CHECK TETRA CHANNEL IT SAYS I NEVER PLAYED 40 LINES
IT DIDNT SAVE

**Comment by ZaptorZap** [comment]
Looks like you're offline, then. Please connect to the internet while playing TETR.IO to submit 40 Lines scores and, in turn, receive experience points. Otherwise, this repository does not concern clientside networking issues, and as such, this issue is invalid.
