### ISSUE TITLE
Desktop client Renderer crash

### ISSUE THREAD

**Issue by itscoldhere** [tetrio/issues#1095]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop Client 8.0.0.0

### Describe the bug/issue

Recently I've been playing a bit in the game and made some private rooms with my friends, I was messing with some setting and the renderer crashed.
I launched the game again and tried to reproduce the crash and after a while figured it out.

### Reproducing

1. Open the game
2. Make a custom room(custom public, custom private or custom in solo)
3. Randomly click on the right and left click at the same time on the right side of a setting(like the auto start lives or more) a lot of times
4. You should get the crash at some point

### Expected behavior

I expected it to trigger 2 clicks one from the left click and one from the right click

### Screenshots
The mouse is on the right side clicking the down arrow and up arrow in the stock counter

![image](https://user-images.githubusercontent.com/118459764/227020136-34810378-4a35-47b4-bed2-7dac8f2059c7.png)

### Console logs

The console logs don't show after the renderer crashes so I do not have any(You should make a save logs system)

**Comment by Monredo** [comment]
Explain to me why did the desktop client renderer crash for the first time?

**Comment by itscoldhere** [comment]
> Explain to me why did the desktop client renderer crash for the first time?

I don't understand what you mean please explain it more

**Comment by ZaptorZap** [comment]
Yeah interestingly I'm able to reproduce it as well, but the technical output of electron crashes such as these aren't very in-depth. osk once posted on the legacy issue report channel on our Discord:
> that popup means i got a crash event from the renderer, and it turns out those have 0 error information or anything so theyre useless
> but they let me kinda gauge how often they happen at least

Honestly there's not much unique TETR.IO-specific coding going on with that field. Those up and down arrows are implemented by the _web rendering library itself_, so maybe this'll be incidentally fixed when TETR.IO upgrades in electron later down the line.
