### ISSUE TITLE
New custom game preset: 4 Wide

### ISSUE THREAD

**Issue by rajun274** [tetrio/issues#1096]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

4 WIDE public rooms are pretty popular these days, and I'd like to play privately with friends. However, there are several game room settings you need to change to get the room right, and I don't know what they all are. I could go to an existing 4 WIDE room, screenshot all the settings, and mimic them locally, but that's a good amount of effort.

### Describe the solution you'd like

Custom games already support the feature Game Presets: Default | Tetra League | etc. Add a new one, 4 Wide.

### Describe alternatives you've considered

N/A, this is likely the best solution.

**Comment by JadiPlayz** [comment]
Cool

**Comment by Dimentio** [comment]
Added in next update!

**Comment by rajun274** [comment]
Wow, amazing, thank you!!!
