### ISSUE TITLE
Lockout still spawns the next piece in addition to the game over animation — Zen mode consequences

### ISSUE THREAD

**Issue by Tomergngn** [tetrio/issues#1097]
### Checklist

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop Client, but if it's relevant, Opera GX  96.0.4693.117

### Describe the bug/issue

This issue only exists in Zen, as it has to do with the "Undo" option.

If you drop a piece in such a way that will kill you, the "clutch" mechanic works as intended and lets you drop another piece in time.

BUT if you also drop that piece out of bounds, wait for it to kill you and press "Undo", you will see those two pieces placed outside the border, and you'll get another chance to put a piece.

I stacked 4 lines above the board without dying.

### Reproducing

1. Go to Zen.
2. Fill the board in such a way that it's possible to die in the next piece.
3. Kill yourself in a way that allows a clutch.
4. Don't do the clutch, place the clutch outside the board as well.
5. Press "Undo"
6. You'll now be able to place another piece when you should've died.

### Expected behavior

I excepted for it to not remember the clutch when I clicked "Undo". That way I won't be able to keep triggering the clutch mechanic.

### Screenshots

(Tried to get the secret badge when I found it)

![image_2023-03-26_004055334](https://user-images.githubusercontent.com/76809888/227743550-9b708d1e-8d69-4e79-9c2a-b90b0d55010c.png)

### Console logs

> **Note**
> i appreciate you following the questions but this time they're irrelevant since it's an oversight. - @ZaptorZap

**Comment by ZaptorZap** [comment]
This bug is unrelated to the clutch clear mechanic. Recently, as of the last patch, lockout under any circumstance will still spawn the next piece during the game over animation. It appears as though undoing that will artificially prolong the game using this bug.

As an aside, I hope you know by now that Zen mode doesn't allow for Secret Grade completion.<sup>[[1]](url)</sup> Furthermore, it's possible in online custom rooms using practice mode as well.

**Comment by o5k** [comment]
Fixed in next patch.
