### ISSUE TITLE
Clockwise key stops working sometimes when near top of board

### ISSUE THREAD

**Issue by rajun274** [tetrio/issues#1098]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

HP Elite Dragonfly 13.5 2022 (16GB) Chromebook

### Browser and version

Chrome Version 111.0.5563.71 (Official Build) (64-bit)

### Describe the bug/issue

Sometimes, when I'm close to the top of the screen, pressing the clockwise key stops working.

It's an intermittent bug, and it has been happening for at least 1 year, maybe even the entire time I've been playing Tetrio. Almost always, when the bug occurs, I top out because the default position where the piece lands makes me lose. This has made me think that my keystrokes are delayed, and I'm pressing the clockwise key after the piece settles. However, over time, I've become increasingly confident that I'm pressing the clockwise key BEFORE the key settles, and it's a bug in the game.

I also don't think it's due to lag, as it happens when the rest of the match plays smoothly.

IDK if the bug also occurs with the counterclockwise key. I don't practice finesse, so I'm rarely pressing CCW.

### Reproducing

I don't know how to reproduce it, but I do have a REPLAY where the bug occurs. PTAL at https://tetr.io/#R:qXtj791RX@3 . My last piece is the Z. In the half second between the piece appearing and settling, I am confident I am pressing the clockwise rotation key.

### Expected behavior

Clockwise key works in all situations.

### Console logs

Bootstrapping for hardver 0de379f9.3FbweTC6q.TEuAEqLLM7
VM219:4261 webgl backend was already registered. Reusing existing backend factory.
t.registerBackend @ VM219:4261
VM219:4261 cpu backend was already registered. Reusing existing backend factory.
t.registerBackend @ VM219:4261
VM219:4261 Platform browser has already been set. Overwriting the platform with [object Object].
t.setPlatform @ VM219:4261
VM219:4267 TETR.IO
VM219:4267 Please be careful when pasting anything in the console. Attackers may be out to steal your login information.
VM219:4267 Up to date. Local version 6.3.2-production | Commit 0de379f9@master (3/13/2023, 10:44:16 PM) | Server cycle 3FbweTC6q | Build TEuAEqLLM7 (3/28/2023, 10:13:06 PM)
VM219:4267 auth-return-lb mounted, now 1 mounts
VM219:4267 Ceriad provider has been loaded successfully.
VM18:1 fun-hooks: referenced 'adpod' but it was never created
(anonymous) @ VM18:1
VM219:4267 Ceriad provider launched after 1 ticks.
Object
VM219:4267 home-lb mounted, now 2 mounts
VM219:4267 PixiJS 6.1.3 - WebGL 2
VM219:4267 - Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 -CPU: 12-coreMemory: ~8 GBConnection: 10 Mbps, 50ms RTT [4g]
VM219:4267 Renderer: Mesa Intel(R) Graphics (ADL GT2)
VM219:4267 InitialConnect > Obtaining Ribbon endpoint...
VM219:4267 auth-return-lb unmounted, now 1 mounts
VM219:4267 InitialConnect > Obtained Ribbon endpoint /ribbon/akane and 20 spools, fallback available.
VM219:4267 InitialConnect > Getting a spool...
VM219:4267 InitialConnect > Spool > Spooling started
VM219:4267 InitialConnect > Spool >    17ms au-hakase [AU] v2 // 0.03125, 0.03125, 0
VM219:4267 InitialConnect > Spool >    29ms au-nano [AU] v2 // 0.015625, 0.03125, 0
VM219:4267 InitialConnect > Spool >   257ms ap-south-chiri [SG] v2 // 0, 0.015625, 0
VM219:4267 InitialConnect > Spool > Spooled au-hakase!
VM219:4267 InitialConnect > Obtained spool au-hakase (au-hakase.spool.tetr.io) [AU].
VM219:4267 home-lb unmounted, now 0 mounts
VM219:370 Ribbon 45012c57b11b4389 opened
global.ib-ibi.com/image.sbxx?go=242840&pid=260&xid=6065453456419953728&id1=:1          Failed to load resource: net::ERR_CERT_DATE_INVALID
global.ib-ibi.com/image.sbxx?go=242840&pid=260&xid=6065453456419953728&id1=:1          Failed to load resource: net::ERR_CERT_DATE_INVALID
global.ib-ibi.com/image.sbxx?go=242840&pid=260&xid=6065453456419953728&id1=:1          Failed to load resource: net::ERR_CERT_DATE_INVALID
global.ib-ibi.com/image.sbxx?go=242840&pid=260&xid=6065453456419953728&id1=:1          Failed to load resource: net::ERR_CERT_DATE_INVALID
tetr.io/:1 The resource https://cdn.xsolla.net/img/favicon.ico was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
tetr.io/:1 The resource https://secure.xsolla.com/favicon.ico was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
DevTools failed to load source map: Could not load content for https://tetr.io/tf.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Additional context

If the replay link isn't enough to diagnose the issue, please instruct me on how I can gather more information for you to prove the bug exists. I'm very sure this is a bug.

**Comment by Richard969** [comment]
[Super Rotation System(SRS)](https://harddrop.com/wiki/SRS) caused this behavior, this is an excepted behavior.

could be reproduce like this
![2023-04-03_09-30](https://user-images.githubusercontent.com/62456622/229392062-f942ba21-7671-45dd-bd40-951fe3276c80.png)

**Comment by ZaptorZap** [comment]
Yeah sorry, this is a shortcoming of the Super Rotation System, which is an industry standard we're not looking to change. You can read more about the Z kicks [**here**](https://four.lol/srs/z-kicks).

**Comment by rajun274** [comment]
Thank you both for the reply! To make sure I understand the issue, is this simiar to, say, when you have an I piece going down a well, and CW and CCW seemingly does nothing?

If yes, then I reckon there's still room for improvement. For example, in #575, o5k states that even though pressing HOLD in certain scenarios legitimately makes you lose, the game can still benefit from a warning indicator that pressing HOLD will end the game. In my situation, the game can benefit from an indicator / notification that pressing a spin key legitimately does nothing, instead of the user wondering why keystrokes aren't working. As such, let's leave this ticket closed, and I'll instead create a Feature Request ticket.

**Comment by rajun274** [comment]
Hello @ZaptorZap ! I'm actually still very confused about how this is caused by SRS. How does @Richard969 's screenshot show that it can be reproduced by that? Thanks!

(I ask because I'm still encountering this issue, and I would love to understand what I'm doing wrong.)

**Comment by ZaptorZap** [comment]
Sure @rajun274, here's a video that hopes to illustrate a bit clearer why this rotation fails:

https://github.com/tetrio/issues/assets/64891705/f337ec44-1679-4e58-99b7-6c73702647cf

You're just more likely to come into contact with this situation at the top of the board.

**Comment by rajun274** [comment]
Wow that blows my mind haha. Thank you so much for the visual explanation!!
