### ISSUE TITLE
Gameplay Presets based on other games

### ISSUE THREAD

**Issue by GlitchyPSIX** [tetrio/issues#11]
Essentially: a way to have preconfigured sets of Gameplay Settings (DAS, ARR, SDF) that are similar or equal to the other games they're based off.

Can be useful for beginners to use a setting set from a game they come from, and optionally also a "custom" tab for them to modify their settings once they're starting to scale up in speed, for example.
(May also be useful for a "first-run" setup for people that recently registered)

**Comment by trudnorx** [comment]
Should include at least NES Tetris, TGM3.

**Comment by Lukahna** [comment]
Any plans with this nearly two year old issue? At the very least, I would appreciate the Custom game settings to be saved between logins/application restarts, with a "Restore defaults" button. Having to tweak 8-10 different settings every time I want to practice T-spins is a chore, and I often get a setting wrong. I would submit that sticky settings idea as a separate suggestion, but I do think the issue that @GlitchyPSIX described is better.

Having a full menu of presets (maybe just presets I create, if there are infringement issues emulating other games) would definitely be appreciated.
