### ISSUE TITLE
Bug With Starting Private or Public Match

### ISSUE THREAD

**Issue by Dr-QwSmI** [tetrio/issues#1104]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11 

### Browser and version

Brave 1.50.114

### Describe the bug/issue

Lets say that the host of an online match died. The game goes on until the end. If the host hits start right as the match ends the Tetrio match will be in the background of the lobby area.

### Expected behavior

Tetrio game will be in the background of lobby waiting area.

**Comment by Dimentio** [comment]
Fixed in the one of the recent maintenance!
