### ISSUE TITLE
idek

### ISSUE THREAD

**Issue by MESIR1** [tetrio/issues#1105]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Chromebook 107.0.5304.110

### Browser and version

Chrome 

### Describe the bug/issue

When I left a room, and the same time they started the room, the background became the game???
idk how to explain

### Reproducing

go to a room
At the same time they start, leave
the background becomes the game

### Expected behavior

leave correctly

### Screenshots

![Screenshot 2023-04-11 2 35 44 PM](https://user-images.githubusercontent.com/103009976/231258517-ffbc51c2-eaf5-4491-a2f6-48cb09e2d7ad.png)

![Screenshot 2023-04-11 2 35 32 PM](https://user-images.githubusercontent.com/103009976/231258561-9ef23d78-6cae-452d-a194-4d43e520b3e0.png)

**Comment by Dimentio** [comment]
Seems to have been fixed in the last maintenances, feel free to reopen if still happening!
