### ISSUE TITLE
Got banned

### ISSUE THREAD

**Issue by Ooi517** [tetrio/issues#1106]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

11

### Browser and version

microsoft edge

### Describe the bug/issue

I open tetrio when i was scanning qr code from my whatsapp group using whatsapp web. Then i open my tetrio and got banned.
Ray ID : 7b66ff8e5cea3c44

### Expected behavior

I hope to be unbanned .

**Comment by ZudoB** [comment]
The game is currently down for maintenance, please be patient - it will be back up shortly.

**Comment by MESIR1** [comment]
the game still currently down?
I'm still banned

**Comment by ZaptorZap** [comment]
If you're banned, please contact [support@tetr.io](https://tetr.io/about/support/) with relevant screenshots or ban IDs. This repository is **not** for account support.
