### ISSUE TITLE
Not sure, why I have been blocked?

### ISSUE THREAD

**Issue by skeletonsyndrome** [tetrio/issues#1107]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 10

### Browser and version

Chrome Version 112.0.5615.50

### Describe the bug/issue

I'm not sure why I got blocked it says the 'action you just performed triggered the security solution'. The issue told me to let you guys know if I was blocked by mistake. It didn't tell me where and I could only look for this in the discord server. 

I had a lot of tabs open as I was previously doing some 3D work on maya so I'm not sure how this happened as I was able to play 2 days ago without a problem and most of the same tabs still open. Don't have tetr.io plus or anything similar. Both app and browser not working. 

This is my Ray ID: 7b67128c98a87701 • Protected by Cloudflare

screenshot - (not sure if you can view it) :
![image](https://user-images.githubusercontent.com/130516316/231312060-55812327-0280-4172-925f-163f0d2a9b45.png)

### Reproducing

Windows search bar. 

Tetr.io

### Expected behavior

A few times when I open tetr.io it doesn't let me log in or tells me my password is wrong. I then relaunch it and the same password works.

### Screenshots

![image](https://user-images.githubusercontent.com/130516316/231312333-cc0a1bed-2024-4180-a7b7-8327afd8d129.png)

### Console logs

![image](https://user-images.githubusercontent.com/130516316/231312450-232ab33b-6e7b-4878-bb52-2a7e47790724.png)

**Comment by ZudoB** [comment]
The game is currently down for maintenance, please be patient - it will be back up shortly.
