### ISSUE TITLE
Tetra League Replay Score Bug

### ISSUE THREAD

**Issue by GashDarnit** [tetrio/issues#1111]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop Client

### Describe the bug/issue

Upon visiting current or past Tetra League replays, the winner will be shown winning every round and the score is displayed the same way

### Reproducing

1. Go to the Main Menu > Tetra Channel  > Me > Selecting any replays
2. The winner will be shown to win every round, while the other player will be shown to win none, scores are also displayed as such

Alternatively,
1. Finish a Tetra League Game > Replay
2. The winner will be shown to win every round, while the other player will be shown to win none, scores are also displayed as such

### Expected behavior

The outcome of each round is displayed correctly and the scores accurately show the result

### Screenshots

![screenshot 2](https://user-images.githubusercontent.com/128578806/231339326-8e19cc97-2665-4721-8026-e2b9584c8379.png)
![screenshot 1](https://user-images.githubusercontent.com/128578806/231339343-45189e78-32c1-4cab-81f9-d4cc0b281939.png)

**Comment by soobakjonmat** [comment]
I got this bug too. It probably got introduced in the recent 6.3.3 patch.

**Comment by o5k** [comment]
Fixed!
