### ISSUE TITLE
Matchmaking Queue Bug that does not allow to join rooms

### ISSUE THREAD

**Issue by Littlel0st** [tetrio/issues#1112]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Tetrio Application

### Describe the bug/issue

So I went to cancel my Matchmaking queue for tetra league and tried to join the Quick Play game. However, the game still thinks that I am in Queue and it is not allowing me to join because they still think I am in Matchmaking Queue when I am not, screenshots shown below that the game notification shows it all. I tried matchmaking and cancelling after that but the game still detects that I am in queue when I am not, not allowing me to join the rooms.

### Expected behavior

Able to join the rooms once matchmaking is cancel

### Screenshots

![bug](https://user-images.githubusercontent.com/73583968/231474954-1df54995-1297-4f1f-b029-c9b4e07e50c3.PNG)

### Console logs

![console](https://user-images.githubusercontent.com/73583968/231475261-03bcdff1-0b74-468b-84f3-3e9815893bd2.PNG)

**Comment by o5k** [comment]
This was fixed!
