### ISSUE TITLE
Win streaks dont disappear 

### ISSUE THREAD

**Issue by Godof64** [tetrio/issues#1114]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

W10

### Browser and version

Opera GX(version?)

### Describe the bug/issue

When in a custom room, the winstreaks of every player dont disappear, after not attending other matches, which does not apply to the host of the room

### Reproducing

Make room
Invite 3+ people
Make each player win atleast once

### Expected behavior

The wins will be added, but teh individual winstreaks dont disappear, except for the host, on where they do disappear

### Screenshots

![asdasdasdasdasdadadas](https://user-images.githubusercontent.com/108696070/231541259-9b6b4c18-922e-4dbc-a24b-d26e8d014cc3.png)

### Console logs

![image](https://user-images.githubusercontent.com/108696070/231541694-68945418-a1af-4567-900c-ee42e409d5ee.png)

**Comment by Dimentio** [comment]
Should be fixed!
