### ISSUE TITLE
Can't see any tetra league records

### ISSUE THREAD

**Issue by soobakjonmat** [tetrio/issues#1115]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Microsoft Edge 112.0.1722.34

### Describe the bug/issue

I can't see any tetra league records of any users in both tetr.io and ch.tetr.io

I'm thinking it might possibly be related to this bug fix: https://github.com/tetrio/issues/issues/1111 because (I'm just guessing) it happened right after fixing the replay score bug. 

### Reproducing

1. Go to tetr.io
2. Click "TETRA CHANNEL"
3. Click "ME"
4. Click "TETRA LEAGUE"
5. Says "NO RECORDS" and nothing appears in the records

Alternatively,

1. Go to https://ch.tetr.io/players/
2. Click on any player
3. Click on "VIEW TETRA LEAGUE RECORD"
4. Says "No records in this stream" and nothing appears in the records

### Expected behavior

Should show the records of tetra league

### Screenshots

My tetra league record:
![image](https://user-images.githubusercontent.com/72960101/231629117-a5df8988-c7ae-4e0b-8997-7734ad3e6851.png)

czsmall tetra league record:
![image](https://user-images.githubusercontent.com/72960101/231629280-26240398-2bcb-486b-b6f7-9fbf14e14d30.png)

**Comment by o5k** [comment]
Occasionally TL records are wiped, for example for updates. This is normal behaviour.
