### ISSUE TITLE
Holding key before match start results in broken conrtrols

### ISSUE THREAD

**Issue by jfp1992** [tetrio/issues#1118]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Win 10

### Browser and version

Firefox

### Describe the bug/issue

When holding a key before match starts the controls get broken

### Reproducing

1. start match, for example, clicking start on a 40 line game or between a league match
2. hold a key such as left or right before the match starts
3. controls are broken

### Expected behavior

Controls to work as expected

**Comment by ZaptorZap** [comment]
I can't reproduce this on Firefox. It sounds related to #680 though, which also occurs if **any** other program on your computer takes away focus from TETR.IO while holding a relevant key. Fixing it is as simple as pressing the effected key once again, as this seems to "unstick" the action in question.
