### ISSUE TITLE
Issue of block moving horizontal

### ISSUE THREAD

**Issue by Jeeee23** [tetrio/issues#1119]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome Version 112.0.5615.49 (Official Build) (64-bit)

### Describe the bug/issue

I can't move any of components for only one space. When I tried to move on space, but it always move 2 spaces. Whatever ARR I had tried, but it's also can't work. :D

### Reproducing

Can go to any mode to try

### Expected behavior

Fix the bug

**Comment by ZaptorZap** [comment]
Can you perhaps provide a replay as evidence of the issue?

**Comment by KaneryU** [comment]
Try using a different keyboard, that might help
