### ISSUE TITLE
Using high-width boards during 1v1's blocks half the board

### ISSUE THREAD

**Issue by KaneryU** [tetrio/issues#1120]
### Checklist

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop (it runs electrion right?)

### Describe the bug/issue

When using a board with > 14, during a 1v1 the other player's board blocks your board, causing the leftmost (vertical) lines to be blocked, along with the next queue.

### Reproducing

1. Creae a online room
2. Set board width to something 15 or greater
3. Get into a 1v1
4. the bug happens

### Expected behavior

You can see the part of your board and the next que

### Screenshots

![image](https://user-images.githubusercontent.com/72762358/232315913-e6124bd7-2410-4c2f-a1fd-15bb7dea8cc0.png)
![image](https://user-images.githubusercontent.com/72762358/232315917-0016ed4e-c3ce-45b9-9c22-5f17925c200e.png)

### Console logs

![image](https://user-images.githubusercontent.com/72762358/232316158-45d4aa8d-fe80-4f30-bd2e-858a5b765107.png)
(the blocked elements are most likely ads)

### Additional context

I know having a super wide board isn't intended (as shown by the wonky scaling when using high/low values for height and width) but it should at least be playable, even though it isn't reccomended.

**Comment by Dimentio** [comment]
Fixed in upcoming update
