### ISSUE TITLE
Tetrio Premium

### ISSUE THREAD

**Issue by JadiPlayz** [tetrio/issues#1121]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Everything(etc. roblox)Has premium in the game.
I wanted to give this game a premium.

### Describe the solution you'd like

Monthly Cost: 20 Euro(€)
Yearly Cost:60 Euro(€)
Special Perks:
1: Same benefits as a supporter.
2: "Premium" Title, "Premium chat tag"&" Premium" badge.
3: Custom Room settings: Make player co-host, make players observers.

### Describe alternatives you've considered

I don't have alternatives, sorry.

### Additional context

The title and the badge:
![Premium](https://user-images.githubusercontent.com/118341922/232544516-3749d2cc-c7c8-483a-b627-d17b9249e72a.png)

**Comment by JadiPlayz** [comment]
Editing now

**Comment by o5k** [comment]
we already have supporter, not rly interested in making it a tiered system as that just creates Jank honestly
