### ISSUE TITLE
Random Fluctuations in Performance

### ISSUE THREAD

**Issue by Absolute-Zeero** [tetrio/issues#1123]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Desktop Client v6.3.3-production

### Describe the bug/issue

Framerate fluctuates between 60 and 20fps at seemingly random intervals within menus and a varying amount of time after starting play. Gameplay inputs also gain a slight yet noticeable delay following the initial framerate drop, with no clear reason why.

### Reproducing

1. Start the game on any WebGL renderer or graphics preset.
2. Performance issues in menus begin about 1 second after the main menu loads and music begins to play.
3. Performance issues in gameplay begin immediately after the "GO!" text appears on all gameplay modes.

### Expected behavior

Consistent framerate of 60fps on WebGL 2, with input recognition being perceivably instant.

### Console logs

![image](https://user-images.githubusercontent.com/30351881/232672035-8ba878cf-998b-40c5-8ad0-5a80a90794fe.png)

### Additional context

    This issue was not present until approximately six months ago. Before this, performance was the same as expected behavior. I have not been able to reproduce these issues on any machine other than the one shown in the Console Log. 
    The only hardware issues that could arise within the last six months would stem from storage space and a change in video card + 1 video cable. I am running the game on a 500 GB M.2 SSD, containing my Windows 11 C: drive with ~150 GB of space left. Other drives include an internal 1 TB HDD with ~15 GB of space left and an external 4 TB HDD with ~360 GB of space left. I also changed my video card from an AMD Radeon R9 200 Series to an NVIDIA RTX 3070Ti, replacing a DVI cable used for a second monitor with a DisplayPort cable fed into a DVI adapter, and then the actual monitor. This monitor is **not** used for gameplay.
    Performance issues logged also change depending on what method of monitoring is used. On the in-game performance tracker, framerate decrease to a minimum of ~35fps is present before returning to 60 with untracked input lag. When using the Performance Profiler in the same menu as the Console, framerate decrease to a minimum of ~15fps can be seen around the gameplay state mentioned in the reproduction instructions. No issues are recorded when tracking through metrics pulled from Task Manager and entries recorded in Event Viewer, though this was partly expected.

**Comment by TheStalwart** [comment]
Well, i'm experiencing the same issue. My GPU is RX6700XT, so probably not an NVIDIA-specific issue

**Comment by Absolute-Zeero** [comment]
The issue turned out to be user error. Vertical Sync was enabled in the NVIDIA Control Panel, which caused the frame drops. Disabling it immediately fixed the issue.

**Comment by TheStalwart** [comment]
> The issue turned out to be user error. Vertical Sync was enabled in the NVIDIA Control Panel, which caused the frame drops. Disabling it immediately fixed the issue.

Tried force-disabling VSync in AMD panel, no change, issue is still reproducible

**Comment by zgibberish** [comment]
I also have this issue, only happens on the desktop client and fluctuates between 250fps and stuttering 30-60fps, I forced Vsync off in Nvidia control panel but it's still the same, I have an Nvidia RTX 2060 6G

**Comment by zgibberish** [comment]
this issue has not been resolved, i replied to keep the issue open.
