### ISSUE TITLE
Matched up twice

### ISSUE THREAD

**Issue by runkanrenchu** [tetrio/issues#1124]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome 109

### Describe the bug/issue

I tried to enter a TL game, clicking on the "Enter matchmaking" button. But I cancelled the matchmaking for a few seconds because I was busy, and then re-entered. Whenever I re-entered, I got matched up as usual.

Once I entered the game with the first player, I could only place one or two pieces before the game jumped to a new match window (with the usual versus opening) with the name of an entirely different player, and a warning on the bottom right corner that says "Already in a room".

After that, I got immediately disconnected of that second match with a message saying something along the lines of "the game can't continue because one of the players disconnected", and was awarded two loses.

There were no connection issues present, and no apparent cause for this happening.

I tried to be as concise as possible and show only screenshots of what's needed, but I'm not really sure what to keep in. If more info is needed, I can always provide it. Thank you in advance <3

### Reproducing

- Enter Tetra League menu
- Click "Enter matchmaking" 
- Cancel after 20 seconds or so
- Wait like 7 seconds
- Click "Entermatchmaking"

### Expected behavior

I should've simply gotten matched with one single player, not two.

### Screenshots

![image](https://user-images.githubusercontent.com/91770051/233529480-c2ced238-b351-4a19-9dc9-de6deb9115d6.png)

### Console logs

The logs are insanely extense, but they're about all the same: `ERR_BLOCKED_BY_CLIENT` followed by warnings.
![image](https://user-images.githubusercontent.com/91770051/233530478-c88c23da-016b-421a-8c0f-ece73b2c7bf0.png)
![image](https://user-images.githubusercontent.com/91770051/233530593-99ff285f-94c5-466d-bdc0-0de0ce1d2af4.png)
![image](https://user-images.githubusercontent.com/91770051/233530677-da708289-e9e8-412e-88b0-9e4aeaa94aa2.png)
![image](https://user-images.githubusercontent.com/91770051/233530724-073d3561-098b-4909-a5c9-9f587b5c3b73.png)
![image](https://user-images.githubusercontent.com/91770051/233530740-3b2320e4-cc5e-447a-850a-8a4e7c0db472.png)
![image](https://user-images.githubusercontent.com/91770051/233530821-c06e049a-a344-43d5-a648-d142b24c0724.png)

The screenshots repeat about 30 more times, this is the only different error (around 40 lines after)
![image](https://user-images.githubusercontent.com/91770051/233530907-0b43c983-30f6-4d28-b735-7e15329f24de.png)
![image](https://user-images.githubusercontent.com/91770051/233530939-4a4090d6-0b71-4bc4-b263-5e9204e178ad.png)
![image](https://user-images.githubusercontent.com/91770051/233530960-d349402c-d3d1-45fa-91e7-160067318f8c.png)

### Additional context

Sorry about the screenshots. Truly. I don't have enough dev experience as to really tell which parts are important out of that 147 lines long stack trace :( you're amazing OSK

**Comment by Tomergngn** [comment]
I got the same bug one for one... wanted to cancel joining a match and got two losses. Is it possible to remove those losses and warnings from my account?
IGN: TOMERGNGN

**Comment by Dimentio** [comment]
I believe this was fixed in the latest maintenance, if not feel free to reopen!

**Comment by Dimentio** [comment]
Not fixed, need to be looked into as per this [report](https://discord.com/channels/673303546107658242/1104947562944942090/1104947562944942090)
