### ISSUE TITLE
Row 21+ Piece Lockout

### ISSUE THREAD

**Issue by FlipsideP** [tetrio/issues#1125]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Tetrio App v6.3.3 [chrome]

### Describe the bug/issue

Pieces within modes like Tetra League now no longer top you out upon being placed on rows 21+ unless the next mino's spawn position is blocked. Was not put in patch notes last i checked so am unsure if this is intentional?

### Reproducing

Go to Tetra League [haven't tested other modes]
Either be forced, or stack so that a tetramino placed there would normally force a top out, and place, as now it continues like nothing happened?
https://tetr.io/#R:mab9062iE
[^example is the last round where I place an L piece on row 21-23]

### Expected behavior

Normally upon doing so you'd top out, as I had happen last few days i played tetra league

### Screenshots

![21-1](https://user-images.githubusercontent.com/99229488/233748219-4cef6444-6885-4f87-b0b6-3fc1b6f49ac7.png)
![image](https://user-images.githubusercontent.com/99229488/233748229-5a73665f-8050-4e05-842f-2be9380db581.png)
![image](https://user-images.githubusercontent.com/99229488/233748257-a1dadbc9-a6a2-490d-b1b2-21cda81b7128.png)

**Comment by o5k** [comment]
We are cycling some modes while collecting user feedback. This is intentional while we analyze games and see what the best options are.
