### ISSUE TITLE
Xbox controller 

### ISSUE THREAD

**Issue by Maxamoose7** [tetrio/issues#1126]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Microsoft edge 112.0.2722.32

### Describe the bug/issue

When an Xbox controller is connected, any attempt to map RB, LB, RT, LT, X, or Y just comes up as unidentified in the custom controls.

### Reproducing

1. Go to config
2. Go to controls 
3. Go to custom controls
4. Click on any of the [not set] boxes and attempt to map them
5. Pressing any of the buttons I listed previously will come up as unidentified and not function at all.

### Expected behavior

I expected it to simply say that I now have that button mapped to that control and function when used in a Tetr.io match of any kind.

**Comment by ZaptorZap** [comment]
Do you have any controller-remapping programs open? Any software such as Steam or JoyToKey should be completely disabled first to ensure they're not the cause of these problems.

**Comment by Maxamoose7** [comment]
I'm 100% sure I don't have any remapping programs open I just double
checked.

**Comment by ZaptorZap** [comment]
Well unfortunately I can't reproduce the issue as described on the [Desktop client](https://tetr.io/about/desktop/) using Linux.
![image](https://user-images.githubusercontent.com/64891705/234827970-bee5df62-548a-441c-b59d-ecb049965dcd.png)
I went ahead and tried it on my Windows 11 laptop, with a wired Xbox One controller, and to no avail it works here too.
![image](https://user-images.githubusercontent.com/64891705/234828846-ba478683-8f1c-4320-8f8f-662915ba2bb9.png)

What does https://gamepad-tester.com/ say about the state of your bumpers/triggers/face buttons? Do they work on this site as well?

**Comment by Maxamoose7** [comment]
Yeah on that website it detects the buttons.
