### ISSUE TITLE
TETR.IO client logs you out almost everytime

### ISSUE THREAD

**Issue by Esked-chan** [tetrio/issues#1130]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 Home 22H2

### Browser and version

TETR.IO Desktop 8.0.0, game version 6.3.3

### Describe the bug/issue

After every 2-3 launch, the game asks me to log in again (typing password and 2FA), even though the "Skip login screen" option in the options is set to "Always".

### Reproducing

1.  Open the client
2. Log in

### Expected behavior

Expected behaviour is that the login screen gets skipped, which sometimes happens

**Comment by ZudoB** [comment]
This is a known issue that is being tracked on Discord in a dedicated thread here: https://discord.com/channels/673303546107658242/1067777164453347418

The aim is for this to be resolved through an upcoming infrastructure upgrade - in any case, this issue will remain closed as per previous reports.
