### ISSUE TITLE
Unfocus Disconnection (Mac)

### ISSUE THREAD

**Issue by badgoblin** [tetrio/issues#1131]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

macOS Monterey 12.5

### Browser and version

TETR.IO Desktop 8.0

### Describe the bug/issue

During a custom game I was playing as normal and received a ping on Discord. I switched windows to Discord and was immediately KO'ed and moved to spectators for being AFK.

### Reproducing

I was unable to reproduce this, but noticed that it was different from the Quickplay bug in that:
1. I was in a public custom room separate from it, using 4w mode settings.
2. It happened ONLY to me.
3. The game functioned as normal in rounds I did not do this.

### Expected behavior

I expected the game to display the "TETR.IO is out of focus" popup while I was viewing Discord, and resume normal gameplay when I switched back.

**Comment by Dimentio** [comment]
Fixed in next maintenance
