### ISSUE TITLE
Incorrect country ranking when accessing with ch.tetr.io

### ISSUE THREAD

**Issue by s1072489** [tetrio/issues#1132]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Firefox 114.0b3

### Describe the bug/issue

When checking user rankings on https://ch.tetr.io/u/deadhello my country ranking is shown as 4th (the TETR.IO application doesn't seem to have this problem) This problem is mirrored on other laptops (win 10 running chrome) and different accounts (tristaibnihg8y). When accessing the ranking leaderboard by pressing the label, it puts the users above you into the negatives.

### Reproducing

1. Go to https://ch.tetr.io/u/deadhello

### Expected behavior

This should show my country ranking as 360th

### Screenshots

![image](https://github.com/tetrio/issues/assets/79786672/9937efca-cdd6-4e56-aa18-7935ccad3ab8)
![image](https://github.com/tetrio/issues/assets/79786672/3af043e6-0346-40ca-b30a-42582d3e47e2)

**Comment by o5k** [comment]
Hotfixed - F5 to receive the fix.
