### ISSUE TITLE
poor matchmaking

### ISSUE THREAD

**Issue by Born2rave** [tetrio/issues#1142]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I am at s+ currently and would like to see better matcmaking. currently i am pitched against people with a 30% higher apm than i have which makes the game unenjoyable being sweeped everytime. I climb to s+ only to lose 6 games in a row and fall back to s. average apm of mine and the apponents are 30 and 50 respectively

### Describe the solution you'd like

matchmaking with closer skill difference

### Describe alternatives you've considered

bot when theres a lack of player in the skill range available

**Comment by ZaptorZap** [comment]
Sorry, but I'm closing this issue as non-applicable. Unfortunately, the fact is, [humans are inconsistent](http://tetrio.team2xh.net/?t=faq#inconsistent-ranks), so ditching [the complicated math](https://en.wikipedia.org/wiki/Glicko_rating_system) behind TETR.IO's matchmaking systems in favor of something that vaguely incorporates ingame performance statistics is **far from** a well thought out idea. 

In the past, on the TETR.IO Discord server, we've had exceedingly unproductive conversations about factoring statistics such as APM into matchmaking. The gist of those conversations go: **statistics are _not_ definitively indicative of a given player's skill**. A player may be throwing intentionally to purposefully sabotage such a system, or rely on winning uncharacteristically short games with disproportionately high APM.

Introducing bots is not a solution either. If it was an adept or competent opponent, it would likely be too efficient for its own good, and besides, the playerbase can definitely support matchmaking at a competent rate, with competent results. TETR.IO does not align with the concept of generating fake enemies like other .io games may.

> **Note**

About those results: the end-goal of fair matchmaking systems is a playerbase with 50% winrates across the board. Of course, those at the very top and bottom have to deviate for this goal to be realized, but it's realized convincingly well within TETR.IO. Plotting players in a graph from [this statistics-focused website](http://tetrio.team2xh.net/?t=league), based on TR→Win Rate, shows the below image:
![image](https://github.com/tetrio/issues/assets/64891705/a6aa392f-9367-448e-bcbb-a51186b83d09)

Now then, to achieve this goal, this does mean people have to **lose rounds** to balance the winrate. Currently, assuming you are [BORN2RAVE](https://ch.tetr.io/u/born2rave) ingame, your winrate is **above average** at **63.95%**. This means you will be experiencing relatively stronger enemies as your rank increases. That's the definition of a ranked league.
