### ISSUE TITLE
When watching a Tetra League replay, autoplay the next match after the video for the current one ends

### ISSUE THREAD

**Issue by rajun274** [tetrio/issues#1144]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

When I'm watching a Tetra League replay, especially if it's a friend's replay, I usually want to watch all the games. But it's annoying that when the video for the first round ends, it automatically goes back to the list view, and I need to manually click to watch the video of the second match, and so on.

### Describe the solution you'd like

Add a checkbox, either on the list rounds page, or on the video replay page, that's called "Autoplay next match". Meaning, once the first round ends, Tetrio starts playing the video for the second round. Potentially have this checked by default.

### Describe alternatives you've considered

No checkbox - make this the default behavior of Tetrio.

**Comment by ZaptorZap** [comment]
![image](https://github.com/tetrio/issues/assets/64891705/212b8fa7-61b2-4936-9af6-37c02125a644)
Already exists. Yes, it's something you click anytime the game's reloaded or closed, but this request is fulfilled as-is.

**Comment by rajun274** [comment]
Ah totally didn't realize that, sorry and thanks!
