### ISSUE TITLE
false positive explicit profile picture

### ISSUE THREAD

**Issue by hellokat1111** [tetrio/issues#1145]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 10

### Browser and version

chrome 113

### Describe the bug/issue

I want to upload a picture that isnt explicit but it gives me an image rejected warning where the image detected is potentially explicit
this is the image i am trying to use as my profile pic.

![capyba](https://github.com/tetrio/issues/assets/135402686/4e6af209-20b3-4133-81ff-8e0dd5286373)

### Expected behavior

succesfully add  the pic to my profile pic.

**Comment by ZaptorZap** [comment]
Please view https://tetrio.github.io/faq/personalization.html#notnsfw
