### ISSUE TITLE
glitch in movement of pieces in customs game

### ISSUE THREAD

**Issue by PLextera** [tetrio/issues#1158]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

window's 11

### Browser and version

chrome 

### Describe the bug/issue

Dear, TETRIO i am writing this issue because i would like to report a glitch in customs games.  every single time that i play a custom game in this situation which was today at 10:45 pm 6/28/23 eastern time zone the pieces started moving the opposite direction and dropping more faster than it should have and i am very frustrated because this is not the first time this had happened today i was attemping to complete to the challenge to get the secret grade badge and i was so close but then the incident occured the pieces started moving in the opposite direction as i said and made me fail and this has happened on all the devices that i play TETR. IO on but i thought it was only me so i asked my friends and all of them said that has happened to them. so i ask to please fix this glitch or bug .
-plextera 

### Reproducing

1.go to customs game 
2. press start 
3. keep playing until the stack of block heights gets to the 17-20th bar 
4. then move the pieces left and right 
5. then the issue starts 

### Expected behavior

to not glitch or have the same issue anymore in the future 

### Console logs

[https://clipchamp.com/watch/ZjtkNvxjr0H](url)

**Comment by doktorocelot** [comment]
Your clip appears to not lead anywhere for me. I'm having a bit of trouble understanding the issue. Would you be able to explain exactly what discrepancy happens between your inputs and what the game does? A replay file might also help.
