### ISSUE TITLE
MAKE IT OPEN SOURCE PLEASE !!!!

### ISSUE THREAD

**Issue by RayyanNafees** [tetrio/issues#1159]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

# MAKE IT OPEN SOURCE PLEASE !!!!
It will be a Huge master piece of a game written in Pixi.js

### Describe the solution you'd like

# MAKE IT OPEN SOURCE

### Describe alternatives you've considered

# PROVIDE SOME DOCS OR RESOURCES OF THE PROCESS OF MAKING THIS MASTERPEICE

**Comment by doktorocelot** [comment]
We apologize, but there are currently no plans to make the game open source.
