### ISSUE TITLE
Immediate crash on Linux

### ISSUE THREAD

**Issue by skotishsky** [tetrio/issues#1167]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

fedora linux

### Browser and version

lutris

### Describe the bug/issue

When running the game using Lutris, the game immediately .

### Reproducing

Go on lutris
install the game
launch the game
game crashes without opening a window

### Expected behavior

The game to open a window and start running

### Screenshots

[Screencast from 2023-07-29 12-34-09.webm](https://github.com/tetrio/issues/assets/92538536/278fd746-8357-48b1-a47a-840fd51d11b6)

**Comment by ZudoB** [comment]
Have you tried launching the application directly (i.e. by extracting the tar.gz and running the executable from a terminal?) If so, does the issue recur - and if so, could you share anything logged that may be relevant?

**Comment by skotishsky** [comment]
Running it directly works.  It just doesn't work on with lutris

**Comment by ZudoB** [comment]
In that case, this issue is not valid as it relates to unrelated third party software. You may wish to bring this up in Lutris-related spaces instead.
