### ISSUE TITLE
Rank dissapearing

### ISSUE THREAD

**Issue by Ze05** [tetrio/issues#1168]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 11

### Browser and version

n/a

### Describe the bug/issue

my rank constantly dissapears for league games, and it is quite annoying and I don't know whether this is a glitch or what. I have to replay multiple matches just to get back to the rank I was, it keeps saying I am unranked. my username is: AAAAAHHH 

I put an image here of my screen, you can see I have played a lot of rounds, which wouldn't make sense for me to be unranked even. it is just annoying having to play against people who aren't at my level.

### Reproducing

n/a

### Expected behavior

to get my rank back and remain in my rank and not have it disapear (ranked -S or S)

### Screenshots

![image](https://github.com/tetrio/issues/assets/141002931/c700b8c0-2f4a-4405-8b5b-4c64839311a4)

### Console logs

![image](https://github.com/tetrio/issues/assets/141002931/490b3dd1-0a00-46d7-9528-1103db2d55c1)

### Additional context

n/a

**Comment by ZaptorZap** [comment]
This is intended behavior. Since your last game was 11 days ago, you're now gaining RD at a constant rate of **1 per day.** At 100 RD, you become unranked. **[More information here.](https://tetrio.team2xh.net/?t=faq#placement)**
