### ISSUE TITLE
Captcha no showing up in TETR.IO client 

### ISSUE THREAD

**Issue by RefreshMint74** [tetrio/issues#1171]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Opera GX

### Describe the bug/issue

I can't log in because there is no captcha to solve

### Reproducing

1. Launch Desktop Client
2. Bug Appears

### Expected behavior

i expect a captcha to show up, it only shows up in the browser not on the desktop client

### Screenshots

![Screenshot 2023-08-14 105145](https://github.com/tetrio/issues/assets/86560240/462541da-79e6-43b1-bfd4-d51787db072d)

**Comment by PraxTube** [comment]
same thing on linux. i get the following messages when i open `tetrio-desktop` through the terminal

```
$ tetrio-desktop 
xdg-settings: default-url-scheme-handler not implemented for xfce
(node:24093) unhandledpromiserejectionwarning: error: could not connect
    at socket.onerror (/opt/tetr.io/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at object.oncewrapper (events.js:313:26)
    at socket.emit (events.js:223:5)
    at emiterrornt (internal/streams/destroy.js:92:8)
    at emiterrorandclosent (internal/streams/destroy.js:60:3)
    at processticksandrejections (internal/process/task_queues.js:81:21)
(node:24093) unhandledpromiserejectionwarning: unhandled promise rejection. this error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24093) [dep0018] deprecationwarning: unhandled promise rejections are deprecated. in the future, promise rejections that are not handled will terminate the node.js process with a non-zero exit code.
```

**Comment by DuckCell11** [comment]
Why.... I can't even access it...

**Comment by o5k** [comment]
smells like tetrio-desktop's chromium might be out of date for turnstile (cf captcha)... bit annoying
tetrio-desktop 9 is planned tho so hoping that resolves it

**Comment by o5k** [comment]
Slated for next tetrio-desktop build.
