### ISSUE TITLE
Create a feature to hide country flags for those who want it

### ISSUE THREAD

**Issue by anzaeee** [tetrio/issues#1174]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I liked playing anonymously because of my username but mostly because I'd like to not browse my location.

### Describe the solution you'd like

Just a setting in the profiles section to hide the country flag

### Describe alternatives you've considered

None as far as I could find

**Comment by ZaptorZap** [comment]
Please navigate to this section in the ingame `CONFIG` below: 
![image](https://github.com/tetrio/issues/assets/64891705/96071e2b-7906-497a-aee4-2b420161b29b)
