### ISSUE TITLE
Custom game board width bug

### ISSUE THREAD

**Issue by zajigsta** [tetrio/issues#1176]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 Pro

### Browser and version

Chrome 116.0.5845.111

### Describe the bug/issue

When setting up a custom game with board width other than 10 wide, each player's game is displayed with new width, however the opponent's side will display the original 10 wide. 

Attacks do not send correctly, and game just functions strangely in general.

### Reproducing

1. Start up custom multiplayer game, private or public.
2. Set board width to any except 10.
3. Invite another player to lobby (can be done before or after settings are changed).
4. Start game.

### Expected behavior

Game should play with both players on same game settings.

**Comment by ZaptorZap** [comment]
Definitely still being reported as an active bug. #1178
