### ISSUE TITLE
Out of focus when actively playing pt 2

### ISSUE THREAD

**Issue by kaianinja** [tetrio/issues#1180]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome and Edge lastest version

### Describe the bug/issue

When actively playing, the ads at the bottom cause for the game to go out of focus. This is annoying as it takes more time to complete levels and is unfair when playing against players who do not have this issue. This is a serious issue as it slows down your game. Additionally, sometimes, the block will go to one or the other side after it is out of focus. In other words, when playing, the game will go out of focus, then the direction of the blocks will be affected by the controls of the game and not the keys that I am pressing, which basically makes the game unplayable. This is not an issue only I am experiencing. Keep in mind many players do not have github and cannot interact with the thread without having an account. Additionally, this thread was closed without a solution having been provided and has been a problem since 2022. https://github.com/tetrio/issues/issues/994

### Reproducing

1.Play tetris
2.While playing, wait for it to go out of focus.

### Expected behavior

Game goes out of focus, and then blocks move on their own

**Comment by ZudoB** [comment]
reopening #994 instead
