### ISSUE TITLE
Black screen upon reaching high B2B multiplier in Zen

### ISSUE THREAD

**Issue by JMA-256** [tetrio/issues#1182]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Firefox 117.0.1 (64-bit)

### Describe the bug/issue

While playing Zen and attempting to reach a high B2B multiplier, around x250 the entire screen flashed white, then everything below the window head displayed black. Returning to menu showed correct menu display, but re-entering displayed countdown, music selection and a black screen. Closing tab and starting a new session erased my B2B multiplier and caused game to load correctly.

Unsure where exactly the bug occurred, but I think it happened around the 250 mark. Integer overflow error?

### Reproducing

1. Launch Zen mode in the Firefox web client
2. Reach or otherwise set B2B to a value in the 200s, probably around 250
3. Maintain B2B combo until error occurs.

### Expected behavior

I expected the B2B combo to continue well into higher values (sort of the entire point I was reaching such high values).

### Additional context

I didn't think to note the console logs before terminating the session sorry

**Comment by JMA-256** [comment]
Note: Upon having a go at replicating the bug, I found that I could reach B2B multipliers of over 300x without issue. Hence, I will attach further details.

- This instance of Tetr.io was running for an extended period before the bug occurred, in excess of 24hrs.
- A significant amount of memory was being used by other programs, and multiple other tabs containing large PDF files were open in the same window.
- The issue also caused the PDF files to appear blank. Perhaps an issue is occurring with Firefox itself? I will look through some things on bugzilla.

**Comment by ZaptorZap** [comment]
I tend to agree. There have been reports on Discord of players reaching up to x1370 concurrent back-to-backs with no issue. Nothing regarding B2B should impact the stability of the game—especially not to the degree of integer overflows. JavaScript handles those cleanly by simply displaying `Infinity` as a number, should you reach beyond the language's upper limit for a number: [1.797693134862315E+308](https://www.w3schools.com/jsref/jsref_infinity.asp). 

This certainly sounds like an issue with that high runtime—but I can't imagine remaining memory played a role if the game worked OK beforehand.
