### ISSUE TITLE
In Firefox 118 gets stuck at Loading SFX stage

### ISSUE THREAD

**Issue by eternal-sorrow** [tetrio/issues#1183]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Linux

### Browser and version

Firefox 118.0

### Describe the bug/issue

The game loading gets stuck at the "Loading SFX" stage. In the browser console I get the `Could not load sounds [null]: Decoding audio data failed.`  message. Stacktrace attached in the console log section.

### Reproducing

1. Navigate to https://tetr.io/ website.
2. Press Join.
3. Wait for the game te load.

### Expected behavior

Game loads normally

### Screenshots

![Screenshot 2023-09-27 at 08-52-47 TETR IO](https://github.com/tetrio/issues/assets/4847726/d43da883-79ec-447e-a8b5-9cab423f4b46)

### Console logs

```
Could not load sounds [null]: Decoding audio data failed. bootstrap.js:4269:288710
    onloaderror https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz line 2 > eval:4269
    _emit https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz line 2 > eval:3585
    (Async: setTimeout handler)
    _emit https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz line 2 > eval:3585
    t https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz line 2 > eval:3585
    (Async: promise callback)
    i https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz line 2 > eval:3585
    onload https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz line 2 > eval:3585
    (Async: EventHandlerNonNull)
    a https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz line 2 > eval:3585
    load https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz line 2 > eval:3585
    <anonymous> https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz line 2 > eval:4269
    g https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz line 2 > eval:4269
    <anonymous> https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz line 2 > eval:4269
    <anonymous> https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz line 2 > eval:4269
    onload https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz:2
    (Async: promise callback)
    onload https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz:2
    (Async: EventHandlerNonNull)
    i https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz:2
    d https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz:2
    <anonymous> https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz:2
    <anonymous> https://tetr.io/bootstrap.js?hv=50390e00.cQkizBpvS.Gq82NxMCz:2
```

### Additional context

In the previous version of the browser everything worked fine.

**Comment by ZaptorZap** [comment]
\I can't reproduce this. Using Firefox 118 on Debian. Could you visit `about:support` and try loading TETR.IO under "Troubleshoot Mode"?

**Comment by eternal-sorrow** [comment]
I tried running in thoubleshoot mode, but what I got was "Your browser does not support WebGL" message.

**Comment by ZaptorZap** [comment]
You could try opening `about:config` and setting `layers.acceleration.force-enabled` to `True`. In the past that's helped me on my system.

**Comment by eternal-sorrow** [comment]
Okay, now I restarted the browser back in normal mode and I get the same message in normal mode too. In console there are a lot of messages like this:
```
Failed to create WebGL context: WebGL creation failed: 
* tryNativeGL (FEATURE_FAILURE_NO_DISPLAY)
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)
```
>You could try opening about:config and setting layers.acceleration.force-enabled to True. In the past that's helped me on my system.

I have that set by default to true.

**Comment by ZaptorZap** [comment]
Well that's worrying. I assume compositing still works on whatever desktop environment you're using? Either way it sounds like you may have to revisit your video drivers and ensure they're up to date.

**Comment by eternal-sorrow** [comment]
Okay, that was a problem with Mesa and LLVM vrsion on my system. That was resolved. I still get the "TETR.IO requires WebGL" message in troubleshooting mode though, but not in normal mode. There are a lot of "WebGL is now disabled" messages in the console. I guess troubleshooting mode disables WebGL on my system.

**Comment by eternal-sorrow** [comment]
From what I can see, Troubleshoot Mode disables WebGL, so that's normal.
https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode#w_what-does-troubleshoot-mode-disable

**Comment by ZaptorZap** [comment]
Oh, oops. First time recommending it; guess I should've followed suite here as well.

**Comment by eternal-sorrow** [comment]
What may cause this "Decoding audio data failed' message?  Codec errors?

**Comment by eternal-sorrow** [comment]
Could this be somehow related?

https://bugzilla.mozilla.org/show_bug.cgi?id=1358149

**Comment by eternal-sorrow** [comment]
Okay, I tried opening tetr.io in a new browser profile (something that I should have done before creating this issue) and it worked okay. 

I also tried disabling all the extensions, and it didn't help.

So this is not something related to default browser behaviour, nor the installed extensions. Rather it's something related to my custom browser settings. I guess, you don't have to fix anything in this case and thus the issue can be closed.

I would appreciate though if you would help me investigate the cause of this issue.

**Comment by eternal-sorrow** [comment]
Okay, I discovered, that for some reason vorbis files (.ogg) do not play in my browser. When I open for example a https://tetr.io/sfx/tetrio.ogg file in a separate tab and try playing it, it doesn't even start playback. It's just stuck forever in the beginning of the file.

**Comment by eternal-sorrow** [comment]
Okay, the problem was with `media.ffvpx.enabled=false` in about:config. I had it disabled when it somehow interfered with hardware decoding on linux and did not touch it since.

I guess they did something in the last update that caused it to make vorbis files fail to decode.

Anyway, sorry for bothering everyone.

**Comment by ZaptorZap** [comment]
This was actually an issue plaguing iOS and Safari a while ago—[a patch was issued](https://tetr.io/about/patchnotes/#chlog_6_2_1) that would let the game theoretically fall back on `.mp3` sound effects, but it might be implemented using User Agents or some such.
Anyways, glad you could solve the issue.
