### ISSUE TITLE
180 Spin allows Z-spin?

### ISSUE THREAD

**Issue by Grady1226** [tetrio/issues#1185]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Chromebook

### Browser and version

Chrome 

### Describe the bug/issue

If you spam the 180 button (A) multiple times, it randomly gives me a z-spin even though i didnt tuck it into anything. This happened in Zen mode. I retried it a few times, trying to get a recording, but it didn't count as a z-spin. But after i stopped recording i got it again off camera...

### Expected behavior

The system should not count it as a Z-spin.

**Comment by ZaptorZap** [comment]
This will certainly need more information. Did you enable "stupid spins" from the sidebar? If so, this isn't a bug. 
![image](https://github.com/tetrio/issues/assets/64891705/3b953ae8-b2f4-4570-9653-2a64246230ae)

**Comment by Dimentio** [comment]
Handheld could also do this.

**Comment by Grady1226** [comment]
no, there weren't any "stupid spins". I havent changed any settings in zen

**Comment by ZaptorZap** [comment]
If that's the case, the game should **never** display `Z-SPIN`s under any condition—even valid Z-Spins... 
This is pretty unprecedented.

**Comment by Grady1226** [comment]
I'm just gonna keep trying until i get the weird spin again

**Comment by ZaptorZap** [comment]
Closing due to inaction/lack of evidence.
