### ISSUE TITLE
Host rank can be higher than room rank limit

### ISSUE THREAD

**Issue by dliedke** [tetrio/issues#1187]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

117.0.5938.134

### Describe the bug/issue

Host rank can be higher than room rank limit

### Expected behavior

Host should be in observer mode if higher than room rank limit

### Screenshots

![image](https://github.com/tetrio/issues/assets/16479450/0010ece9-01cc-453f-a007-32c915c184e9)
![image](https://github.com/tetrio/issues/assets/16479450/2513d1f3-4d2a-4b4e-a3b4-aadddad66345)

**Comment by ZudoB** [comment]
This is intentional behaviour, the host can bypass the rank limit. If you're not happy with the way the host is running the room, leave and find/create a new one.
