### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by hoannee** [tetrio/issues#1188]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Macbook Air

### Browser and version

Latest Chrome

### Describe the bug/issue

Games repeatedly disconnects during Tetra League. Internet connection is stable (other tabs are functioning well). Received 3 losses as a result of the abrupt disconnections.![image](https://github.com/tetrio/issues/assets/147695077/ac5b3e0e-9dd7-4bae-a9ec-881a41e45175)

### Expected behavior

Please fix the connection error and lift the penalty for false forfeiting matches. Thank you so much!

**Comment by o5k** [comment]
Sorry, but connection errors are outside of the scope of this issue tracker. This is because such issue reports (aside from usually being very low-quality) generally do not help debug any issues. Instead, we employ multiple internal analytics tools tracking disconnect rates and reasons.
