### ISSUE TITLE
Intermittent lags in game

### ISSUE THREAD

**Issue by branderrp** [tetrio/issues#1191]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop Client, 6.3.4

### Describe the bug/issue

Runs into issues where the game lags and my pieces das all the way to the sides due to it not registering that I have let go of the keys. E.g. After DAS to the left, a single press causes it to DAS back all the way to the right, causing a misdrop.

Pressing F8 to show production builds show the F and GAMEF numbers spiking up when the lag occurs.

Only has started recently (last 1-2 months) while system that tetrio is being played on has remained the same.

### Reproducing

Occurs in the following modes:
1. ZEN
2. Quickplay
3. Tetra League

### Expected behavior

No lag or glitches causing misdrops

### Screenshots

![TETR IO_m2Sc11wihF](https://github.com/tetrio/issues/assets/25095324/58f4a83b-7d72-48fe-b21c-0b39d986fc81)
![TETR IO_tobZZ7eN9C](https://github.com/tetrio/issues/assets/25095324/7d0facb5-216f-4883-8f4e-ce6988fc43b2)

**Comment by NoPurposeInLife** [comment]
bump, it is indeed happening in both tetra league and even single player

**Comment by branderrp** [comment]
Still happens from time to time
