### ISSUE TITLE
bricks colour change when undo/redo and clear lines at ARS kick tabe

### ISSUE THREAD

**Issue by normalRocket** [tetrio/issues#1196]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

deskop client(also hapent when i test on Edge)

### Describe the bug/issue

when i use ARS kick table in game,undo,redo and clear line will made brick's colour change. I will change to green, T will change to red,S will change to blue,and Z will change to pink.

### Reproducing

1.change kick table to ARS at setting,like zen setting or multiplayer setting.
2.start game
3.do a clear line or undo/redo and check brick colour.

### Expected behavior

i have check some record at Tertis Grand Master 3's classic rule and test on my own copy,its wont hapent.so i hope at TETR.IO,its can keep its colour after clean lines or undo/redo.

### Screenshots

![image](https://github.com/tetrio/issues/assets/89451621/83d0d159-569f-408b-9c6d-90ebbb6844e7)
before

![image](https://github.com/tetrio/issues/assets/89451621/b1205696-e58e-4d84-9a55-c05b7c208231)
after

video record that on zen
https://github.com/tetrio/issues/assets/89451621/fff9ae91-a821-4552-8565-486c6f92324b

### Console logs

Bootstrapping for hardver bfd2017c.lVNk6ro3f.ly4lCUjhR
VM44:4263 webgl backend was already registered. Reusing existing backend factory.
t.registerBackend @ VM44:4263
VM44:4263 cpu backend was already registered. Reusing existing backend factory.
t.registerBackend @ VM44:4263
VM44:4263 Platform browser has already been set. Overwriting the platform with [object Object].
t.setPlatform @ VM44:4263
VM44:4269 TETR.IO
VM44:4269 Please be careful when pasting anything in the console. Attackers may be out to steal your login information.
VM44:4269 Up to date. Local version 6.3.4-production | Commit bfd2017c@master (2023/10/10 10:48:12) | Server cycle lVNk6ro3f | Build ly4lCUjhR (2023/10/20 07:20:44)
tetr.io/:1 Mixed Content: The page at 'https://tetr.io/' was loaded over HTTPS, but requested an insecure element 'http://p0.qhimg.com/t0123b39db57bf4d069.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
tetr.io/:1 Mixed Content: The page at 'https://tetr.io/' was loaded over HTTPS, but requested an insecure element 'http://p0.qhimg.com/t0143cd811eb61ac211.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
tetr.io/:1 Mixed Content: The page at 'https://tetr.io/' was loaded over HTTPS, but requested an insecure element 'http://p0.qhimg.com/t015a38552769d8282e.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
tetr.io/:1 Mixed Content: The page at 'https://tetr.io/' was loaded over HTTPS, but requested an insecure element 'http://p0.qhimg.com/t01b00e081180e1d938.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
VM44:4269 home-mega mounted, now 1 mounts
VM44:4269 PixiJS 6.1.3 - WebGL 2
VM44:4269 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.289 Safari/537.36 -CPU: 16-coreMemory: ~8 GBConnection: 3.25 Mbps, 50ms RTT [4g]
VM44:4269 Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)
VM44:4269 InitialConnect > Obtaining Ribbon endpoint...
VM44:4269 home-mega unmounted, now 0 mounts
16The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
VM44:4269 InitialConnect > Obtained Ribbon endpoint /ribbon/gil and 20 spools, fallback available.
VM44:4269 InitialConnect > Getting a spool...
VM44:4269 InitialConnect > Spool > Spooling started
VM44:4269 InitialConnect > Spool >    94ms ap-north-konata [JP] v3 // 0.484375, 0.21875, 0.125
VM44:4269 InitialConnect > Spool >   163ms ap-north-hina [KR] v3 // 0.171875, 0.09375, 0.078125
VM44:4269 InitialConnect > Spool >   228ms ap-south-komori [SG] v3 // 0.1875, 0.15625, 0.109375
VM44:4269 InitialConnect > Spool > Spooled ap-north-konata!
VM44:4269 InitialConnect > Obtained spool ap-north-konata (ap-north-konata.spool.tetr.io) [JP].
VM44:372 Ribbon d0c5557f75543a66 opened
VM44:343 Ribbon d0c5557f75543a66 closed (ribbon lost)
VM44:636 Ribbon d0c5557f75543a66 reconnecting in 5ms (reconnects: 1)
Reconnect @ VM44:636
VM44:349 Ribbon d0c5557f75543a66 resuming
VM44:4269 ResumeRespool > Obtaining Ribbon endpoint...
VM44:372 Ribbon d0c5557f75543a66 resumed
VM44:4269 ResumeRespool > Obtained Ribbon endpoint /ribbon/imamiya and 20 spools, fallback available.
VM44:4269 ResumeRespool > Getting a spool...
VM44:4269 ResumeRespool > Spool > Spooling started
VM44:4269 ResumeRespool > Spool >   211ms ap-north-konata [JP] v3 // 0.40625, 0.21875, 0.125
VM44:4269 ResumeRespool > Spool >   319ms ap-north-hina [KR] v3 // 0.140625, 0.09375, 0.078125
VM44:4269 ResumeRespool > Spool >   271ms ap-south-chiri [SG] v3 // 0.34375, 0.21875, 0.171875
VM44:4269 ResumeRespool > Spool > Spooled ap-south-chiri!
VM44:4269 ResumeRespool > Obtained spool ap-south-chiri (ap-south-chiri.spool.tetr.io) [SG].
VM44:343 Ribbon d0c5557f75543a66 closed (ribbon lost)
VM44:636 Ribbon d0c5557f75543a66 reconnecting in 105ms (reconnects: 2)
Reconnect @ VM44:636
VM44:349 Ribbon d0c5557f75543a66 resuming
VM44:4269 ResumeRespool > Obtaining Ribbon endpoint...
VM44:372 Ribbon d0c5557f75543a66 resumed
VM44:4269 ResumeRespool > Obtained Ribbon endpoint /ribbon/chibimoth and 20 spools, fallback available.
VM44:4269 ResumeRespool > Getting a spool...
VM44:4269 ResumeRespool > Spool > Spooling started
VM44:4269 ResumeRespool > Spool >   248ms ap-north-hina [KR] v3 // 0.078125, 0.078125, 0.078125
VM44:4269 ResumeRespool > Spool >   256ms ap-south-fuuka [SG] v3 // 0.1875, 0.125, 0.09375
VM44:4269 ResumeRespool > Spool >   304ms na-west-sonya [US] v3 // 0.15625, 0.078125, 0
VM44:4269 ResumeRespool > Spool > Spooled ap-south-fuuka!
VM44:4269 ResumeRespool > Obtained spool ap-south-fuuka (ap-south-fuuka.spool.tetr.io) [SG].
DevTools failed to load source map: Could not load content for https://tetr.io/tf.min.js.map: HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
VM44:343 Ribbon d0c5557f75543a66 closed (ribbon lost)
VM44:636 Ribbon d0c5557f75543a66 reconnecting in 5ms (reconnects: 1)
Reconnect @ VM44:636
Open.ws.onclose @ VM44:344
VM44:349 Ribbon d0c5557f75543a66 resuming
VM44:4269 ResumeRespool > Obtaining Ribbon endpoint...
VM44:372 Ribbon d0c5557f75543a66 resumed

### Additional context

i think there re nobody relly use ARS but fix it plz :P

**Comment by ZaptorZap** [comment]
This also occurs on the `TETRA-X` rotation system, since it's the only other one that changes block colors in this way: 
![image](https://github.com/tetrio/issues/assets/64891705/527b35e1-ed3f-4e54-ba1c-8bbe2500def7)

**Comment by doktorocelot** [comment]
Fix ready for next maintenance update. Thank you for the report!

**Comment by doktorocelot** [comment]
We're looking further into a fix due to the special pieces that exist for some events, such as the smaller I and J pieces and the 5-block-long I piece.
