### ISSUE TITLE
TETRIO Zen Garbage Backfire 0.5x Bugging Out Board [low graphics]

### ISSUE THREAD

**Issue by Z0zaf** [tetrio/issues#1197]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Microsoft Edge

### Describe the bug/issue

When going in zen and setting garbage backfire to 0.5x, the garbage bugs. When the garbage tries to send to my board, the entire board disappears. I am on Low Graphics.

### Reproducing

1. Turn on Low Graphics
2. Go into zen
3. set garbage backfire to 0.5x
4. Complete any action that sends more than 2 lines.
5. If done correctly, your board should disappear

https://github.com/tetrio/issues/assets/145713697/4c4cac41-3d46-4f94-8c45-4d1475bb34fb

### Expected behavior

What I expect to happen is for the garbage to send through and the board to remain visible.

### Console logs

https://github.com/tetrio/issues/assets/145713697/e248abe9-f92e-4988-b3a8-98eae662aad8

**Comment by Z0zaf** [comment]
I have just confirmed that garbage backfire 1x and 2x also are bugged. Unclear does not have this issue.

**Comment by o5k** [comment]
Hotfixed - F5 to receive the fix.
