### ISSUE TITLE
Click to focus

### ISSUE THREAD

**Issue by AndyOChan** [tetrio/issues#1198]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome Version 119.0.6045.106

### Describe the bug/issue

When I played a Tetra League game, it kept asking for me to click to focus. I clicked to try to focus again but it didn't work. It kept giving the same message over and over again and I couldn't move any piece in some rounds. But in all of the rounds it asked me to click to focus and went away sometimes. I refreshed the page and started another tetra league game and the same thing happened. 

### Expected behavior

I was expecting that the tap to focus thing would go away when I clicked on the screen.

### Additional context

I don't have any pictures of this bug because I was in a tetra league game and wasn't thinking of taking screen shots. I don't want to go in tetra league again because I'll lose even more rating points because of this bug so I can't take pictures.

**Comment by mhmelai** [comment]
Same thing is happening to me, but w my mac. lost so much TR alr cus i have to keep leaving.

**Comment by Asia1213** [comment]
ive been having the same issue. in custom solo games its been working OK but all other solo games same problem. thank god i start on solo games before multiplayer lol

**Comment by paradoxicallyconvoluted** [comment]
sometimes it doesnt even focus when i click

**Comment by DeltaBill** [comment]
Same issue here. 
Using Chrome Version 119.0.6045.124 (Official Build) (64-bit)
and it seem like when the ad refresh, not for all ads, but some of them takes a second to refresh and stay blank for a moment before loading. In that moment the game goes out of focus and doesn't come back anymore.
I wasn't able to test if the ad change again it makes the focus come back.
in some occasions the game starts already with out of focus message 

For me, several occasions the game goes out of focus on the moment it loads this ad
https://www.xtracars.pt/pt/?utm_medium=rtb&utm_source=dv360&utm_campaign=caetsu_xtrc_brand_not_launch_subscricao-mensal_10.23_pt_web_mob_21283-pt-not&utm_content=728x90_generico&utm_term=pros_cl&adfcd=1699529194.aLYU1__DW020XwKvE8kdPA.MzE1NzUwMywxNDc1NDMy

**Comment by LinuxProjectMaster** [comment]
I also have the same problem.
The bug seems to occur when specific ads are loaded, however, since I generally use a school computer, I can't download an adblocker to get rid of the problem. I am currently using Chrome Version 118.0.5993.124 (Official Build) (64-bit). This bug seemed to occur around the same time Tetr.io was updated yesterday. 
The ad that seem to cause the problem is:
[https://www.jobs-ups.com/driver-helper?ss=paid&utm_campaign=RD360-PROS-23&utm_medium=display&utm_source=TalentBrew360&utm_content=374968317&source=rd_ProgrammaticDisplay&dclid=CNyfiqn3toIDFasbaAgd3_kOCA&gclid=EAIaIQobChMI7vSFp_e2ggMVShSICR2H4wX1EAEYASAAEgKkMvD_BwE](url)

**Comment by o5k** [comment]
Is this still happening after a reload?

**Comment by mhmelai** [comment]
> Is this still happening after a reload?

reload does help but not always. sometimes if i would try to reload, it would say out of focus right away.

**Comment by o5k** [comment]
as in, i just pushed a fix, reload will get you the fix
is it still happening with the fix?

**Comment by DeltaBill** [comment]
Apparently it's okay, so far no bugs! Thanks
I'll keep testing and come back if anything happens

**Comment by LinuxProjectMaster** [comment]
Fixed here too! Thanks for the speedy fix.
