### ISSUE TITLE
Garbage stops sending midway through Custom Survival Timer mode

### ISSUE THREAD

**Issue by TimH98** [tetrio/issues#1199]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

MacOS Ventura 13.6.1

### Browser and version

Firefox 119.0.1 (64-bit)

### Describe the bug/issue

When playing Custom mode with the survival mode set to Timer, garbage stops spawning part way through the run. [Here](https://pastebin.com/raw/JwZEsYE6) is a replay where 40 lines are sent before garbage stops appearing completely.

### Reproducing

The settings I used, anything omitted is left as default:
- Survival
  - Mode: Timer
  - Garbage messiness %: 25
  - Timer interval: 100
- Objective tab
  - Key: Lines
  - Objective: Lines
  - Count: 100

### Expected behavior

"Timer" mode should cause garbage to be spawned at regular intervals for the full duration of the game.

**Comment by TimH98** [comment]
Another example replay, this time it stops after 38 rows are sent: https://pastebin.com/raw/XMkNCQGh

**Comment by o5k** [comment]
Hotfixed - F5 to receive the fix.

**Comment by TimH98** [comment]
I'm still seeing this issue after updating to the newest version. Replay [here](https://pastebin.com/raw/c8azkd2X).

**Comment by SevenSunnySun** [comment]
I have the same issue and [here](https://pastebin.com/raw/WcBRHrvf) is my replay.
