### ISSUE TITLE
You can tab through hidden elements

### ISSUE THREAD

**Issue by Wirtualnosc** [tetrio/issues#120]
### Description
Upon pressing a tab, you can browse through game's input elements. That includes elements that are hidden. For example, you can tab into password fields when you're in main menu.

### Reproduction
Keep pressing Tab key in main menu. You will notice after some time that:
1. Browser will recognize a link to osk's homepage (the address should appear in the status bar)
2. A password manager will recognize password fields

### Expected behavior
Tab key element switch should be disabled.

### Screenshots
![image](https://user-images.githubusercontent.com/6901295/76155335-bb54e580-60e2-11ea-9767-d192b29a2892.png)

### Your setup
Firefox 73.0.1 on Linux

**Comment by o5k** [comment]
Fixed in next patch.

**Comment by Wirtualnosc** [comment]
still happens on countdown screen lul

**Comment by Wirtualnosc** [comment]
also happens at login screen - you can tab through some hidden links
