### ISSUE TITLE
Board doesn't show up when entering game

### ISSUE THREAD

**Issue by luckiecloxer** [tetrio/issues#1203]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10*

### Browser and version

119.0.6045.106*

### Describe the bug/issue

When entering a gamemode e.g. Zen or Tetra league board doesn't show up when it's supposed to and only shows the background. No SFX or anything just a background. Already tried restarting with task manager.

Upon playing Tetra League and getting a match I got disconnected from the server.*

### Reproducing

*

### Expected behavior

Supposed to load up a tetris board to play a normal tetris game.*

### Screenshots

![image](https://github.com/tetrio/issues/assets/137904762/e6e39134-3033-47c2-aed2-8d575c7ef7d0)*

### Console logs

*

### Additional context

*

**Comment by doktorocelot** [comment]
@luckiecloxer Please enter the game, press F8 and send a screenshot
