### ISSUE TITLE
Hanging and disconnection

### ISSUE THREAD

**Issue by Gene1203** [tetrio/issues#1204]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Version 119.0.6045.124 (Official Build) (64-bit)

### Describe the bug/issue

It hangs in the middle of the game. Looks like a spam attack from the opponent player and makes me disconnected from the game and penalizes me for a loss. This happens a lot lately.

### Expected behavior

Fix issue and prevent recurrence.

### Screenshots

![tetrio error](https://github.com/tetrio/issues/assets/150477606/d7a90bfe-16a3-4f84-8b57-079da71e74cd)

**Comment by o5k** [comment]
Sorry, but connection errors are outside of the scope of this issue tracker. This is because such issue reports (aside from usually being very low-quality) generally do not help debug any issues. Instead, we employ multiple internal analytics tools tracking disconnect rates and reasons.
