### ISSUE TITLE
Wii U Pro controller reconized as Nintendo switch controller

### ISSUE THREAD

**Issue by Littlemac123** [tetrio/issues#1206]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

linuxmint 21 XFCE

### Browser and version

i have the .deb Version: 8.0.0

### Describe the bug/issue

I think because the wii u controller is for whatever resin being picked up as a switch controller it seems to auto map the buttons very very wrong auto and its kinda confusing 

### Expected behavior

it to not be switch

### Screenshots

![Screenshot_2023-11-12_23-44-16](https://github.com/tetrio/issues/assets/39867553/28acc40b-ecb0-4cc8-bc3f-3a4f22b0e730)

### Console logs

[tetr.io-1699850729192.log](https://github.com/tetrio/issues/files/13330805/tetr.io-1699850729192.log)

### Additional context

the wii u controller has all these values 
![Screenshot_2023-11-12_23-46-32](https://github.com/tetrio/issues/assets/39867553/eb752a8b-2b67-4044-9e09-19b373326c84)

**Comment by doktorocelot** [comment]
Controller support is handled by the browser. If the buttons are mapped wrong, the browser doesn't properly support the controller.
It says "Nintendo Switch" because the vendor ID is Nintendo's. As far as I know, only Switch controllers are supported by browsers.
