### ISSUE TITLE
Option for mute

### ISSUE THREAD

**Issue by SUSSYBUSSY690** [tetrio/issues#1208]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I'd like to play my own music sometimes while playing this on PC, even though I really do like your choice of music!

### Describe the solution you'd like

Just a "mute" option for music and other sounds. 

### Describe alternatives you've considered

Turning down my PC and using a different device, but it's easier to just use my PC.

**Comment by ZudoB** [comment]
Already implemented from the start, CONFIG > VOLUME & AUDIO or use the scroll wheel (alt-scroll while in menus)
