### ISSUE TITLE
TR update

### ISSUE THREAD

**Issue by minecraftweaper56115** [tetrio/issues#1210]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I am get very upset when I am a D rank and verse a C-, when i win i only get let 36 TR??

### Describe the solution you'd like

I think you guys should make it so when ever you verse someone and win, you should become a higher level then them.

### Describe alternatives you've considered

I have none:|

**Comment by ZaptorZap** [comment]
This request is ill-thought out and would cause massive TR inflation, rendering matchmaking ultimately much less dependable. The impact this would have on the top of the leaderboard would be relatively devastating to the players that have spent so much time to get their top leaderboard placements, only to lose them in a single fateful matchup. 

Regardless, the difference between D and C- rank is largely negligible—D+ rank isn't as large as you may be envisioning.
![image](https://github.com/tetrio/issues/assets/64891705/e7a1331c-fe14-4cd6-837a-71e22a634f4c)

You can render the graph above and see related statistics on https://tetrio.team2xh.net/?t=league.

Furthermore, at the bottom rank, Glicko is "worth" less than it is around the average A ranks, which causes you to lose and earn _less_ TR, despite losing and gaining the same amount of Glicko. This relationship is plotted [here](https://www.desmos.com/calculator/n2mpa885l6). This is what's causing your perceived low TR gain.
