### ISSUE TITLE
Infinite Hold does not work in Zen

### ISSUE THREAD

**Issue by KonSola5** [tetrio/issues#1213]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Firefox 120.0.1

### Describe the bug/issue

Infinite Hold does not work at all in Zen.

(It does work fine in Practice rooms, however.)

### Reproducing

1. Enter Zen.
2. Toggle the "Infinite Hold" to ON.
3. Hold.
4. Notice that the piece in Hold is grayed out, and attempting to Hold again does not do anything.

### Expected behavior

Hold piece should never gray out with the Infinite Hold option, and it should allow holding infinite times per piece.

### Screenshots

https://github.com/tetrio/issues/assets/125081901/b52c4986-422e-4866-bfe1-bfbed0c5d466

**Comment by ZaptorZap** [comment]
This issue has already been resolved, we're just waiting for maintenance to roll out a fix. Until then, if you can't wait to use this feature, you can use this workaround:
![image](https://github.com/tetrio/issues/assets/64891705/b9ee2693-5ded-492c-9a83-c6e144b8738e)
![image](https://github.com/tetrio/issues/assets/64891705/47def393-c429-4420-8b16-fc80fa6915f2)
(on Desktop, the `zenConfig` key is in the `Application` tab)
