### ISSUE TITLE
TETRA CHANNEL isn't showing any replays, always reports an error

### ISSUE THREAD

**Issue by Krelyshy** [tetrio/issues#1214]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Linux

### Browser and version

TETR.IO desktop client and/or Chromium 118.0.5993.70

### Describe the bug/issue

When a replay link is pasted into the Tetra channel input box, it always reports an error stating that "username must be 3-16 characters long and only consist of letters, numbers, dashes and underscores", even though I'm trying to open a replay.

### Expected behavior

Play a replay.

### Screenshots

![tetrachannel](https://github.com/tetrio/issues/assets/33201513/4463514d-21f1-442a-b581-4f59cf2e416d)

### Console logs

Probably an API issue?

```
VM18:4435 TETR.IO
19:47:54.551 VM18:4435 Please be careful when pasting anything in the console. Attackers may be out to steal your login information.
19:47:56.376 VM18:4435 Up to date. Local version 6.4.0-production | Commit 70c76b3b@twc2023vfx (1. 12. 2023 1:23:46) | Server cycle dgCbbQ7-z | Build oHo8-JRpt (1. 12. 2023 1:24:21)
19:47:56.384 VM18:4435 auth-return-lb mounted, now 1 mounts
19:47:56.513 VM18:4435 auth-return-lb unmounted, now 0 mounts
19:48:00.209 VM18:4435 undefined
19:48:04.242 VM18:4435 PixiJS 6.1.3 - WebGL 2
19:48:04.243 VM18:4435 - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 -CPU: 8-coreMemory: ~8 GBConnection: 10 Mbps, 50ms RTT [4g]
19:48:04.243 VM18:4435 Renderer: ANGLE (Intel, Mesa Intel(R) UHD Graphics 620 (KBL GT2), OpenGL 4.6)
19:48:04.265 VM18:4435 InitialConnect > Obtaining Ribbon endpoint...
19:48:04.409 VM18:4435 InitialConnect > Obtained Ribbon endpoint /ribbon/kotarou and 24 spools, fallback available.
19:48:04.409 VM18:4435 InitialConnect > Getting a spool...
19:48:04.410 VM18:4435 InitialConnect > Spool > Spooling started
19:48:05.041 VM18:4435 InitialConnect > Spool >    12+1ms eu-mikoto [NL] v4 // 0.015625, 0.125, 0.125
19:48:05.042 VM18:4435 InitialConnect > Spool >    11+6ms eu-kuroko [FR] v4 // 0.03125, 0.046875, 0.078125
19:48:05.043 VM18:4435 InitialConnect > Spool >    14+3ms uk-ikaros [GB] v4 // 0.265625, 0.125, 0.078125
19:48:05.044 VM18:4435 InitialConnect > Spool > Spooled eu-mikoto!
19:48:05.044 VM18:4435 InitialConnect > Obtained spool eu-mikoto (eu-mikoto.spool.tetr.io) [NL].
19:48:05.179 VM18:312 Ribbon 344ac2584d09607c opened
19:48:29.869 VM18:4435 XHR failed loading: GET "https://tetr.io/api/users/https%3A%2F%2Ftetr.io%2F%23r%3A65622c60ab8739d5b57e5a29/resolve".
eval @ VM18:4435
send @ VM18:4435
get @ VM18:4435
aa @ VM18:4435
t @ VM18:4435
navigateToShortID @ VM18:4435
eval @ VM18:4435
619:50:38.502 XHR finished loading: GET "<URL>".
19:48:39.935 VM18:4435 XHR failed loading: GET "https://tetr.io/api/users/https%3A%2F%2Ftetr.io%2F%23r%3A65622c60ab8739d5b57e5a29/resolve".
```

![obrazek](https://github.com/tetrio/issues/assets/33201513/39b1fcbb-78b7-4b2c-a9e9-65eeadd7bc26)

**Comment by ZaptorZap** [comment]
Short IDs like in https://tetr.io/#R:0Z8pBFPOE also don't work. It's not an API issue and the games are perfectly retrievable if you type only the ID, like these examples:
* https://tetr.io/#R:0Z8pBFPOE → R:0Z8pBFPOE
* https://tetr.io/#r:639f8ce5488eb1e07306e59e → r:639f8ce5488eb1e07306e59e

**Comment by Dimentio** [comment]
Fixed in next maintenance!
