### ISSUE TITLE
Game automatically disconnects me from tetra lague matches

### ISSUE THREAD

**Issue by opacef** [tetrio/issues#1218]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Firefox 120.0.1, browser client

### Describe the bug/issue

Every Tetra League game I have played recently has just disconnected me as soon as the game starts. This only happened during the middle of a session and only when I was above somewhere around 19.2k tr. Specifically, the game gets frozen once the text on the screen says 0 and I can control a piece.
I've never had much of a problem with this before, I am using a stable connection.
This doesn't happen with my opponents at all.

### Expected behavior

No more random dce's

### Additional context

Only happens when I'm above a certain amount of tr.
I am using a VPN (windscribe) I do this because tetr.io is blocked on my home wifi for no reason. I tried useing both france and german servers and the problem still persists.
The ip adress of the vpn is not blocked by tetrio.

**Comment by o5k** [comment]
Sorry, but connection errors are outside of the scope of this issue tracker. This is because such issue reports (aside from usually being very low-quality) generally do not help debug any issues. Instead, we employ multiple internal analytics tools tracking disconnect rates and reasons.
