### ISSUE TITLE
Problem moving the falling piece left or right

### ISSUE THREAD

**Issue by igorfranb** [tetrio/issues#1221]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Brave, latest version

### Describe the bug/issue

When I try to move the falling piece left or right, it goes all the way in that direction. All the other movements or controls work right.

### Expected behavior

I expected it moves correctly.

**Comment by ZudoB** [comment]
What are your handling settings? ARR, DAS and SDF

**Comment by igorfranb** [comment]
> What are your handling settings? ARR, DAS and SDF

I've reset those settings and it have worked, thx
