### ISSUE TITLE
Server connection issues

### ISSUE THREAD

**Issue by alexwf1** [tetrio/issues#1222]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

WIndows 10

### Browser and version

Firefox 120.0.1 (64-bit)

### Describe the bug/issue

Repeated server connection issues which I am sure were not on my end. My Internet connection did not get cut at any point; everything on the website worked perfectly fine up until I attempted to play a ranked match. The match would load and countdown normally, but as soon as the game actually started it froze and ended up disconnecting me. This happened 3 times (2 in a row, and a 3rd time some minutes later, after I'd been browsing other websites with no issues), causing me 3 unwarranted losses in ranked matches. 

In accordance to the error message, I am reporting this issue and requesting that my account is not punished for this; I don't know if there's anything to be done about the 3 losses by disconnection, but above all I don't want to jeopardize my account over server connection issues. At the moment, I am too afraid to attempt playing a ranked match again, seeing as the issue might just happen again and get my account punished. 

(My account username is ALEX_WF.) 

### Expected behavior

I expected my ranked matches to play out normally, seeing as my Internet connection was stable and there were absolutely no signs of connection issues on my end. 

### Additional context

The 3rd time the issue happened, I copied this info from the error message. 

SOCKET ID: 1ea3e144f78950b2
WORKER: AKANE
SPOOL: UK-IKAROS

**Comment by OH5000** [comment]
My end also happened this issue recently. I can play normally in some games, but some times the game frozened in the middle of it. I had check my Wi-Fi connection and internet speed, all of them are connected smoothly.
My username is OH5000
And here's the error message.(5th time)
SOCKET ID: 5eaf8939674c1669
WORKER: SAKUYA
SPOOL: AP-SOUTH-NOZOMU

My internet speed.
![螢幕擷取畫面 2023-12-21 004543](https://github.com/tetrio/issues/assets/126638918/b57aa2bb-3e7d-49ea-91aa-da3d69e2054f)
The notifications I got.
![螢幕擷取畫面 2023-12-21 004544](https://github.com/tetrio/issues/assets/126638918/ddcedcfe-3016-4fa9-ba3e-124f082bb317)

**Comment by o5k** [comment]
Sorry, but connection errors are outside of the scope of this issue tracker. This is because such issue reports (aside from usually being very low-quality) generally do not help debug any issues. Instead, we employ multiple internal analytics tools tracking disconnect rates and reasons.
