### ISSUE TITLE
No rank also count

### ISSUE THREAD

**Issue by Maylit336** [tetrio/issues#1223]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I played c rank practice room and There is letteraly was only pros with unspecified rank

### Describe the solution you'd like

can you add feature that The maximum rank in custom rooms also works for an unspecified rank. There is such a text in the profile “somewhere near (x or u, or ss or s and etc)" 

### Describe alternatives you've considered

Add feature in custom room "include "?" rank" where if you turn it on. The game will look at what rank the player is at. 

### Additional context

i laso have issue, when Moderators ban me. i I asked forgiveness. and when they unbanned me. I lost my rank. I am now "?" rank although he clearly had B rank. Now I'm already somewhere A-rank. I have about 10,000 tr. but I'm still "?" rank and I don’t know how to understand when I will get a certain rank. The game just tells me to play and I play. but at what point will the rank be returned to me?

**Comment by ZaptorZap** [comment]
This feature is already implemented. It's the "allow unranked users to play" option, and it is enabled by default. This feature works precisely as described, unless the "limit by top rank" feature is enabled, in which case, the game uses that metric instead. 

Unfortunately, the moderation fitness of a public room is not up for debate in this Github issues forum. The host may have allowed anonymous users to play—which simply will massively thwart its effectiveness with the benefit of getting more players, and thus, a higher spot in the room list. If you're not a fan of this policy, you're welcome to make your own room with saner settings.

You will regain your active rank once you have lowered your **R**ating **D**eviation to below 100. You may read more about Rating Deviation [**here**](https://tetrio.github.io/faq/mechanics.html#rd).
