### ISSUE TITLE
Network Connection Problem - Wifi Signal is fine and worked earlier

### ISSUE THREAD

**Issue by ToucanSam12** [tetrio/issues#1226]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome

### Describe the bug/issue

I was able to play earlier today and I had no problems up until an hour ago. Since then I cannot connect to the online servers and have tried multiple things on my end with my wifi connection. I have even tried plugging my ethernet cable into my PC. This is the first time I have had this issue and I have played on the website and app before multiple times using this same connection.

### Expected behavior

I expected to be able to connect to the servers and play the online multiplayer game modes

**Comment by ZaptorZap** [comment]
This network issue has been detailed on https://status.osk.sh/ and has been resolved. The issue was submitted during this known incident so I will presume it's a direct cause.
