### ISSUE TITLE
no Keyboard event in Game

### ISSUE THREAD

**Issue by jpx40** [tetrio/issues#1229]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

MacOS Sonma

### Browser and version

Chromium 120

### Describe the bug/issue

Hey, 
i can't use any keyboard in an Game. Only tested in Singleplayer Modi.

### Reproducing

Space key, and File keys were used

### Expected behavior

Input should be regonized

**Comment by doktorocelot** [comment]
I'm sorry, I don't quite understand exactly what you mean. Are you saying the game isn't responding to any inputs from your keyboard? I'm unsure of what you mean by 'File' keys.

**Comment by jpx40** [comment]
> I'm sorry, I don't quite understand exactly what you mean. Are you saying the game isn't responding to any inputs from your keyboard? I'm unsure of what you mean by 'File' keys.

sry meant the arrow keys
