### ISSUE TITLE
I piece can kick to the side in ARS

### ISSUE THREAD

**Issue by KonSola5** [tetrio/issues#1230]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Firefox 121.0

### Describe the bug/issue

Because TETR.IO seems to follow the TGM1/2 ARS, according to https://tetris.wiki/Arika_Rotation_System, the I piece should **not** kick to the left/right.

Despite this, TETR.IO lets the I piece kick 1 space left/right.

### Reproducing

1. Build a 9-0 stack. Make sure the stack is as flat as possible.
2. Place an I-piece on the ground.
3. Rotate the I piece.
4. The I-piece kicks into the well.

### Expected behavior

The I-piece should not kick in this scenario.
You should need a 2-wide well to rotate the I-piece.

## TETR.IO

https://github.com/tetrio/issues/assets/125081901/1c830845-9ba3-4f45-ac5e-eaa3a4fb7627

## Tetra Legends Ultimate
(this fork of Tetra Legends made by Talon has an Arcade mode, simulating TGM2's Normal mode, which is accurate)

https://github.com/tetrio/issues/assets/125081901/fa8df65a-07fa-4acc-b621-6e4504f869f1

**Comment by doktorocelot** [comment]
> (this fork of Tetra Legends made by Talon has an Arcade mode, simulating TGM2's Normal mode, which is accurate)

Correction, Talon did _not_ write the ARS in Tetra Legends. I did.

I still haven't touched it in this game because I don't know if the design is an intentional QoL. I will have to see if it is worth touching.

**Comment by ZaptorZap** [comment]
I am reminded of this extremely early question I once asked, so it's definitely intentionally not 1-1 vanilla:
![image](https://github.com/tetrio/issues/assets/64891705/15ce0e73-524f-48b0-a1b0-ec428f4f80e5)

**Comment by doktorocelot** [comment]
After discussing this with osk, this is an oversight. The I piece should never kick in original ARS. I will work on fixing the implementation.
