### ISSUE TITLE
Disconnected from Tetra League - Bot verification without captcha

### ISSUE THREAD

**Issue by SaundersCox** [tetrio/issues#1232]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Version 120.0.6099.111 (Official Build) (64-bit)

### Describe the bug/issue

1. Connectivity issues against an opponent in Tetra League
2. Get disconnected
3. "Please verify you're not a bot" shows with missing captcha

### Expected behavior

1. Play Tetra League
2. Get disconnected
3. Captcha verification screen with captcha shows

### Screenshots

![image](https://github.com/tetrio/issues/assets/34501844/e2af8d9c-880f-410c-b4bf-04ba75d363cd)

### Console logs

Could not load Console

**Comment by ZudoB** [comment]
https://status.osk.sh/
