### ISSUE TITLE
The Catptcha isn't even showing on desktop version!!

### ISSUE THREAD

**Issue by DuckCell11** [tetrio/issues#1233]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Downloaded Version - Windows

### Describe the bug/issue

It won't let me in. The only thing I would see is The screen in the following image, with _**No Captcha**_.
The Web version would, but it would just mess up my reputation with the laggy gaming.

### Reproducing

1. Enter the Downloaded Version.
And that is all you need to do.

### Expected behavior

Enter the game as always.

### Screenshots

![Screenshot 2023-12-22 103418](https://github.com/tetrio/issues/assets/154564001/368944e4-bece-4b79-a7a0-f01b84ba6aca)

### Console logs

![Screenshot 2023-12-22 104517](https://github.com/tetrio/issues/assets/154564001/8121ce6a-2ed8-49e3-8064-8e5c9f0003e8)

**Comment by ZudoB** [comment]
https://status.osk.sh/ - also you are using T+ so this is invalid regardless
