### ISSUE TITLE
ghost player

### ISSUE THREAD

**Issue by StevieSmiley** [tetrio/issues#1234]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

win 11

### Browser and version

application 

### Describe the bug/issue

a player disappears in-game. but still playing. this is noticed by everyone. I've deturmined that this is somehow a client side issue due to leaving the observer mode then reentering it. at this point the invisible player can be seen ( by the person that does this )

### Reproducing

1 play the game. 
2 it seems like a random occurrence. havent been able to identify cause.
3. exit observer mode if you are observing. 
4. reenter observer mode to show hidden player.
5. 

### Expected behavior

i was expecting to see the player that's playing.

**Comment by Falkonx9** [comment]
me and some friends found the same thing, it happened after the third player was knocked out and there were two left, only one player would show up, no mater who, if you were the one playing you wouldn't be able to see the other player and for spectaters they only saw 1 random player. Players in lobby: FALKONX9, PEACHIIMEACH, UNCLE_BEN, RAYLINKRAY
![Screen Shot 2023-12-29 at 8 58 46 PM](https://github.com/tetrio/issues/assets/155207420/acd55d6d-74e8-48b8-ab21-a35c1faf1d87)
![Screen Shot 2023-12-29 at 8 59 00 PM](https://github.com/tetrio/issues/assets/155207420/bbf1b97b-70a0-41a7-9fc4-a82799a1da44)
