### ISSUE TITLE
A bug on the special version of the BGM 'Aerial City'

### ISSUE THREAD

**Issue by 035966-L3** [tetrio/issues#1235]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 7

### Browser and version

Chrome 109

### Describe the bug/issue

I'm sorry that I might disturb you, but it seemed that you just forgot to update the BGM 'Aerial City' in the MUSIC ROOM in ABOUT page.

### Expected behavior

To hear the special version of the BGM 'Aerial City'.

**Comment by ZaptorZap** [comment]
_Christmas City_ is included in the music room. It's a separate song.
![image](https://github.com/tetrio/issues/assets/64891705/17fd63eb-08f8-4b47-a69d-71ef38286afb)
