### ISSUE TITLE
Random disconnects

### ISSUE THREAD

**Issue by ILSLT** [tetrio/issues#1238]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome Version 120.0.6099.130 (Official Build) (64-bit)

### Describe the bug/issue

Each time I play tetris of late, this happens. Please see screenshot.

### Expected behavior

NA

### Screenshots

![image](https://github.com/tetrio/issues/assets/86853842/a79d80ee-40f1-4f31-b99b-1a2f7742bbb8)
![image](https://github.com/tetrio/issues/assets/86853842/e4183a0f-549a-4554-b445-043a93c72830)

**Comment by o5k** [comment]
Sorry, but connection errors are outside of the scope of this issue tracker. This is because such issue reports (aside from usually being very low-quality) generally do not help debug any issues. Instead, we employ multiple internal analytics tools tracking disconnect rates and reasons.
