### ISSUE TITLE
Again Disconnected 

### ISSUE THREAD

**Issue by ILSLT** [tetrio/issues#1239]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome Version 120.0.6099.130 (Official Build) (64-bit)

### Describe the bug/issue

I always get "timed out" or disconnected which results in my forfeiting a game.

### Expected behavior

Play per normal!

### Screenshots

![image](https://github.com/tetrio/issues/assets/86853842/bcc8b43c-6cc9-4c5a-8298-948d9c81eae7)

**Comment by SeedyZ** [comment]
Seconding this. I had a disconnect error 13 days ago and just now. I'm on Windows 10 with the desktop client up to date.

**Comment by o5k** [comment]
Sorry, but connection errors are outside of the scope of this issue tracker. This is because such issue reports (aside from usually being very low-quality) generally do not help debug any issues. Instead, we employ multiple internal analytics tools tracking disconnect rates and reasons.
