### ISSUE TITLE
Boards inconsistent with actual plays

### ISSUE THREAD

**Issue by Letitbebuilt** [tetrio/issues#1241]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Firefox 121, Chrome 109

### Describe the bug/issue

When observing opposing player boards (either while playing or spectating) the board will periodically show incorrect information (ex pieces hovering, pieces disappearing, pieces landing in wrong spot, etc), later syncing to correct itself or not at all. Several cases where someone allegedly gets eliminated but is still in game. Observed by multiple individuals in my play group. 

### Reproducing

1) Play in a lobby of at least 3, but 4+ optimal for observing

### Expected behavior

Pieces reflect opposing plays / elimations

### Screenshots

![image](https://github.com/tetrio/issues/assets/20408414/0373e867-2a58-443b-96b9-aca87ed2aa0b)
![image](https://github.com/tetrio/issues/assets/20408414/db773e33-f786-41e9-a1ab-6d5d688c6214)
![image](https://github.com/tetrio/issues/assets/20408414/29d6af1c-0b33-4dc4-9718-cb52627f41be)

### Console logs

```Loading failed for the <script> with source “https://moon.kagari.moe/matomo.js”. [tetr.io:1:1](https://tetr.io/#DVMM)
webgl backend was already registered. Reusing existing backend factory. [bootstrap.js:43:45](https://tetr.io/bootstrap.js?hv=874c76e3.pVnezSInw.vNeTSMmVTE%20line%202%20%3E%20eval)
cpu backend was already registered. Reusing existing backend factory. [bootstrap.js:43:45](https://tetr.io/bootstrap.js?hv=874c76e3.pVnezSInw.vNeTSMmVTE%20line%202%20%3E%20eval)
Platform browser has already been set. Overwriting the platform with [object Object]. [bootstrap.js:43:45](https://tetr.io/bootstrap.js?hv=874c76e3.pVnezSInw.vNeTSMmVTE%20line%202%20%3E%20eval)
WebGL context was lost. [bootstrap.js:701:39554](https://tetr.io/bootstrap.js?hv=874c76e3.pVnezSInw.vNeTSMmVTE%20line%202%20%3E%20eval)
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. [bootstrap.js:4203:101438](https://tetr.io/bootstrap.js?hv=874c76e3.pVnezSInw.vNeTSMmVTE%20line%202%20%3E%20eval)
An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page. 2 [bootstrap.js:3519:24329](https://tetr.io/bootstrap.js?hv=874c76e3.pVnezSInw.vNeTSMmVTE%20line%202%20%3E%20eval)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.enthusiastgaming.net/scripts/cdn.enthusiast.gg/script/eg-aps/production/eg-aps-bootstrap.bundle.js?site=tetr.io. (Reason: CORS request did not succeed). Status code: (null).

Ceriad provider could not be loaded. [bootstrap.js:43:45](https://tetr.io/bootstrap.js?hv=874c76e3.pVnezSInw.vNeTSMmVTE%20line%202%20%3E%20eval)
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. [bootstrap.js:4203:533298](https://tetr.io/bootstrap.js?hv=874c76e3.pVnezSInw.vNeTSMmVTE%20line%202%20%3E%20eval)
Ribbon 135635a246892800 changing endpoint (new endpoint: wss://na-mid-maho.spool.tetr.io/ribbon/yoshino) [bootstrap.js:43:45](https://tetr.io/bootstrap.js?hv=874c76e3.pVnezSInw.vNeTSMmVTE%20line%202%20%3E%20eval)
Source map error: Error: request failed with status 404
Resource URL: null
Source Map URL: tf.min.js.map```

### Additional context

_No response_

**Comment by Dimentio** [comment]
Has been fixed actually
