### ISSUE TITLE
CORs access issue in Tetr.io API

### ISSUE THREAD

**Issue by SpartanApple** [tetrio/issues#1243]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Ubuntu 20.04

### Browser and version

Firefox 107.0 

### Describe the bug/issue

I believe currently the API only supports CORS from `tetr.io` domain, which makes it difficult to utilize the API in browser applications. 
```
access-control-allow-headers	Authorization, Content-Type
access-control-allow-methods	GET, POST, OPTIONS
access-control-allow-origin	https://tetr.io
```

Error:
`CORS missing allow origin`

### Expected behavior

Able to make API request through browser rest calls

**Comment by ZaptorZap** [comment]
I believe this is intended. You'll need to use a CORS proxy or something similar to achieve what it is you plan on doing. https://tetr.fires.bz/overlay/ and https://cankyre.github.io/tetostats/ are proven examples of this, the latter of which being [open source](https://github.com/Cankyre/TetoStats), albeit offline right now.

**Comment by o5k** [comment]
This is intentional — direct browser use is hard to work with from our side, as it's easy for such use to scale into far too many requests. Please set up a simple proxy for it!
