### ISSUE TITLE
Out of focus enables when random notification pops up

### ISSUE THREAD

**Issue by Patricenko** [tetrio/issues#1246]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Brave v1.61.114

### Describe the bug/issue

during gameplay when notification pops up game enables out of focus alert and game cannot be played until clicked on screen. Even if i didn't click on anything else.

### Expected behavior

no out of focus should be enabled - or - the game should be playable even without clicking on board again

**Comment by doktorocelot** [comment]
Would you mind providing more information on exactly what notification you're talking about? Is this a notification within the game or outside, and what is the notification for?

**Comment by Dimentio** [comment]
Duplicate of #994
