### ISSUE TITLE
Slight typo: "7BAG" instead of "7-BAG" in Custom Game

### ISSUE THREAD

**Issue by KonSola5** [tetrio/issues#1247]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Firefox 121.0

### Describe the bug/issue

The "Random Bag Type" should be "7-BAG" by default, but upon opening the Custom Game for the first time the bag type is set to "7BAG" (without a hyphen).

### Reproducing

1. Refresh TETR.IO.
2. Go to Solo -> Custom.
3. In general tab, notice that the Random Bag Type is set to "7BAG".
4. Change the bag type to 7-BAG.
5. Now the text is correct "7-BAG".

### Expected behavior

The "Random Bag Type" should be "7-BAG" by default.

### Screenshots

![7bag](https://github.com/tetrio/issues/assets/125081901/d1cf060b-211f-4532-975e-bd3f4905c13b)

### Additional context

This is not gamebreaking, since 7-bag is the default (and fallback?) randomizer.

This was already fixed in custom multiplayer rooms (#841), but not in a custom game.

**Comment by doktorocelot** [comment]
Thank you for the report. This will be fixed in the next patch!
