### ISSUE TITLE
Game fades to black instead of showing ending stats after game finish

### ISSUE THREAD

**Issue by Apophius001** [tetrio/issues#1249]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

ChromeOS Version 119.0.6045.214 (Official Build) (64-bit)

### Browser and version

Google (?)

### Describe the bug/issue

So far I have been unable to recreate this bug, though that may be because I saw it on 40 lines and attempted to recreate it on Blitz. It's very simple. After you finish a solo match (try 40 lines like I did), there's a chance that the game simply fades to back and never shows you the ending screen, no matter what you interact with, forcing you to reload.

### Expected behavior

The game to show me the ending screen with my finishing stats, like time, lines finished and stuff like that.

### Console logs

Doesn't work on my ChromeOS

### Additional context

I also have a theory this occurs when you get disconnected from live servers in the middle of a solo match, but I'm not sure.

**Comment by Dimentio** [comment]
If you can still reproduce this issue, please provide console logs. I assume you hit an uncaught error, it might have been fixed since so I'll close this issue.
