### ISSUE TITLE
Tetr.io doesn't load in Safari browser

### ISSUE THREAD

**Issue by lpla** [tetrio/issues#134]
### Describe the bug/issue
Tetr.io is not loading in Safari browser from a Mac.

### Reproducing
1. Go to 'tetr.io' and click on 'ENTER INFDEV' (obviously, you must have your IP whitelisted)
2. Click on 'JOIN 1720 PLAYERS'
3. See endless black screen.

### Expected behavior
Load like in any other browser I tested (Firefox, Chrome).

### Screenshots
Endless black screen:

<img width="1710" alt="Captura de pantalla 2020-03-10 a las 17 07 49" src="https://user-images.githubusercontent.com/1533393/76333294-b6b24c00-62f1-11ea-8eb7-8ab60583a137.png">

### Your setup
 - **OS and version**: macOS Catalina 10.15.3, MacBook Pro (15-inch, 2017)
 - **Browser and version**: Safari Versión 13.0.5 (15608.5.11)

### Additional context
Console screenshot (all normal):

<img width="1710" alt="Captura de pantalla 2020-03-10 a las 17 11 16" src="https://user-images.githubusercontent.com/1533393/76333736-54a61680-62f2-11ea-8ef0-3cbae0c70c21.png">

**Comment by o5k** [comment]
Safari is currently not supported. I am looking into getting it to work it there.

**Comment by isametry** [comment]
Hello, any progress update on this? :)

**Comment by lpla** [comment]
@github-actions, the issue is still relevant. Just tested using Safari 13.1.1 (15609.2.9.1.2) in Catalina 10.15.5 (19F101) and I get the same freeze in the same place.

**Comment by lpla** [comment]
Still not fixed. Tested in Safari 13.1.2 (15609.3.5.1.3), Catalina 10.15.6 (19G73). Please, @o5k, increase the github-action stale bot timeout or stop it completely, as closing issues that are still relevant but not active or a priority doesn't improve things.

**Comment by katagaki** [comment]
I did some digging on this issue (currently using the Electron app, but I previously tried using Safari to sign in). It seems like tetr.io is using ogg files for its media? As far as I am aware, ogg files are not supported natively in Safari, you will need to use a library, like ogv.js: https://github.com/brion/ogv.js/ to play audio on Safari. 

(Either that, or audio support could be temporarily disabled for Safari, to ensure that the loading progresses.)

I've attached the console error from my end. The loading gets stuck particularly at 'LOADING SFX...'.

![image](https://user-images.githubusercontent.com/68231035/143454901-b5febd2a-6d8d-4387-8413-a5ca2c1df29e.png)

**Comment by LeonLiur** [comment]
As of macOS Monterey Safari 15.1, this issue is not yet resolved.

**Comment by faroutnovelty** [comment]
Safari on MacOS 12.2 (and previous MacOS sub-version) black screens on tetr.io after clicking "join" on the "welcome back to tetr.io" screen. It has been doing this for at least a month now. The main menu thus doesn't load and the game cannot be played. I have no extensions enabled, and Tetr.io works correctly on Chrome. I am using Safari 15.3 (stable) on an M1 Max (ARM-based CPU) Macbook Pro 16.

**Comment by o5k** [comment]
Next patch will include a sound format for special snowflake Safari. Can't guarantee everything will work well, as I cannot debug Safari, but it should allow the game to load.

**Comment by lpla** [comment]
It is working now. Thank you.
