### ISSUE TITLE
Configuration presets for multiplayer rooms

### ISSUE THREAD

**Issue by Wirtualnosc** [tetrio/issues#157]
### Is your feature request related to a problem? Please describe.
Multiplayer rooms currently have a lot of settings. Heavily customized rooms currently take a while to set up.

### Describe the solution you'd like
An ability to export and import settings, just like singleplayer custom games have.

**Comment by trudnorx** [comment]
An option to add it to a list of your own presets and allow to share it with other users, maybe showing a list of most liked presets.

**Comment by ZaptorZap** [comment]
This sort of functionality was mentioned in the TETR.IO Discord server today, so I figured I'd wake this issue up. I'd totally love to collect custom rulesets and distribute them the next time someone asks about the exact settings Tetra League uses, for instance.

**Comment by deedeeen** [comment]
This issue shall not be stale and closed.

**Comment by danik00111** [comment]
yeah there should be import/export of multiplayer room seetings as .json

**Comment by ChapperNi** [comment]
Strange how this isnt added yet, would be a huge QoL update.

**Comment by ZaptorZap** [comment]
It....has been added in _some capacity_. The presets are simply hardcoded right now, but there's about 12 of them if you count gamemodes. (which, by default, Battle Royale mode is the current Quick Play preset)
