### ISSUE TITLE
DAS not consistent

### ISSUE THREAD

**Issue by limgw1** [tetrio/issues#181]
Compared to jstris and nullpomino the DAS in tetr.io seems more "slippery". 
I've checked with npm and jstris to ensure this isnt an issue with my skill/keyboard.
Sometimes it slides over too fast and sometimes it slides over too slow, it seems to fluctuate.

**Comment by o5k** [comment]
Has this improved since 2.2.6?

**Comment by 020m** [comment]
I just tried out some jstris and tetr.io games to see and compare. Seems like it hasn't improved. There were some instances were tapping left two times resulted in the tetromino being moved left three times instead. 

Other times the piece is launched all the way to the wall. From what I can tell, it looks like sometimes the DAS charge is kept between pieces despite releasing the right/left key before dropping, which should stop the DAS charge from being preserved on the next piece. 

Tetr.io feels skittery compared to jstris, but not many others have complained about the controls -- I don't know if 5 people liking this post counts as a sizeable amount relative to the activity of this forum. 

Maybe we're just not used to this engine? ¯\_(ツ)_/¯

>Game settings
ARR: 10ms
DAS: 95ms
>Web browser
Google Chrome

**Comment by limgw1** [comment]
It has improved abit, not sure if its actual improvement or I got used to it, but there is still slipperiness. I think the easiest way to compare with jstris or nullpomino, then the difference can be felt

**Comment by o5k** [comment]
Please try again in 4.0.0 and see if it's improved!

**Comment by o5k** [comment]
Finally, finally closing as many have now reported good DAS!
