### ISSUE TITLE
All Clear Battle mode (multiplayer)

### ISSUE THREAD

**Issue by MattMayuga** [tetrio/issues#198]
**Description**
Play with predefined maps against other players in a time-limited mode where the player with the most All Clears wins!

**Gameplay**
All Clear Battle is based on the All Clear mode in TE. The objective of this mode is to get as many All Clears as possible within the time limit using predefined map. Every map that will come up can be fully cleared. When clearing a map or a piece is misdropped, the map will change to a different one (in the case of misdropping a piece, it doesn't count as an All Clear). There are also predefined pieces for every map.

**Mode Settings**

- Time limit: Change how long the match will last in seconds. Default: 180 (3 minutes)

**Comment by o5k** [comment]
Related to #212
