### ISSUE TITLE
Game should produce visible message when it can't load custom background

### ISSUE THREAD

**Issue by Wirtualnosc** [tetrio/issues#214]
It is confusing for most people first coming to tetr.io that you can't change your background to a custom one, and no explanation is given when an image is rejected. It is not obvious for most people why an image wouldn't load in first place. I think that a message should be shown to the user why background loading cannot proceed (and/or possibly offer an alternative way of loading background when CORS is rejected).

**Comment by RainbowBoyVN** [comment]
Game is not support for 32-bit?

**Comment by MahdeenSky** [comment]
cant import custom backgrounds (using imgur)
