### ISSUE TITLE
Allow finesse options in custom games

### ISSUE THREAD

**Issue by Wirtualnosc** [tetrio/issues#238]
### Is your feature request related to a problem? Please describe.
I want to practice my finesse in a different environment than what 40L or Blitz provides.

### Describe the solution you'd like
Add finesse counter with alerts/retries to custom games.

**Comment by o5k** [comment]
How would this work with the other rotation systems?

**Comment by Wirtualnosc** [comment]
Each would need its own finesse table I think. NRS is different enough from SRS in that some pieces shift only one way when rotating, plus lack of kicks makes it harder. Such finesse tables would be different enough between other rotation systems too, I believe. I'm not sure if such tables are available anywhere, but coming up with such shouldn't prove too difficult after investing some time, I think.

**Comment by SphyxDev** [comment]
Could you please reopen this?

I don't think we need this option for other rotation systems, it's fine if it's just SRS and/or SRS+.

Also, maybe not custom games but I would really appreciate the "Alert on Finesse Fault" option in Zen mode specifically. We can already view our finesse by changing the display from the Zen menu, but the alert would help.

#275 is also somewhat related I guess.
