### ISSUE TITLE
Basic social system

### ISSUE THREAD

**Issue by mat1jaczyyy** [tetrio/issues#24]
Does not have to be too complex.

* Friend people to be able to see if they're offline/online/in solo/in multi.
* Directly message with friends.
* Friends can be directly invited to a game, which would either create a new room to play in, or if you're already in a room invite them to said room. The invited person would have a non-disruptive but noticeable popup notification in a corner of the screen.
* Profile pictures
* Ability to link socials such as Twitter, Discord, YouTube or Twitch (optionally public or private depending on the user's choice) to aid in people connecting and enjoying the game.

**Comment by troynguyen8** [comment]
Just wanted to chime in and say that I was looking for this exact functionality today. I paired up with someone in tetra league three times and wanted to friend them so we could 1v1 sometime :)

**Comment by o5k** [comment]
took almost a year but it's here :^)

**Comment by deedeeen** [comment]
nearly 8 months late but what about social media linking? :P

**Comment by deedeeen** [comment]
ah, thx
