### ISSUE TITLE
Direct leaderboard comparisons in Blitz mode

### ISSUE THREAD

**Issue by Cublex** [tetrio/issues#242]
In Tetris Dekaris/Tetris Giant, the score challenge has a 1,000 place leaderboard that you get directly compared to as you play. I think that'd be interesting to have for Blitz mode, although likely difficult to implement.

**Comment by o5k** [comment]
It would be possible, but only for the top 1000. I am planning to have pace detection for 40L (detects if you're on PB/WR pace), so perhaps a live position thing for Blitz could be cool

**Comment by eito-okada** [comment]
commenting bc i love this
