### ISSUE TITLE
EXPORT/IMPORT user settings

### ISSUE THREAD

**Issue by julf0** [tetrio/issues#245]
If the settings are not going to be stored in our users. Consider the possibility of export and import button on user settings. Ex. I use incognito tab in others PCs

**Comment by trudnorx** [comment]
I'd rather have #7 but not necessarily keep the graphics settings. Way easier/better for everyone. And allows for keeping options easily for people who always use incognito windows. Could still have the option to import/export or just keep multiple setting profiles stored on server if people want that.

**Comment by o5k** [comment]
Added in next version.
