### ISSUE TITLE
Add a survival mode to the game 

### ISSUE THREAD

**Issue by haxeado** [tetrio/issues#264]
### Is your feature request related to a problem? Please describe.
No, isn't related to a problem

### Describe the solution you'd like
There's not a problem

### Describe alternatives you've considered
It should a good idea adding a survival mode like tetris ultimate what is clearing lines and the lines are increasing and increasing.

### Additional context
I don't have screenshots or any other context

**Comment by deltadex7** [comment]
I can help you out with a context. In [Tetra Legends](tetralegends.app), there is a survival mode. Probably worth looking.

**Comment by o5k** [comment]
This is implemented by Zen. A standalone mode might be made at some point but no promises.
