### ISSUE TITLE
Saving replays for multiplayer games

### ISSUE THREAD

**Issue by Neeko-iko** [tetrio/issues#267]
### Is your feature request related to a problem? Please describe.
I mean tbh its not really a problem 
### Describe the solution you'd like
be able to download multiplayer games as a .ttr file 

### Describe alternatives you've considered
have obs open 24/7 idk

### Additional context
for menus that have a similar menu to quickplay you could do like this where the "download replay" button is in the top right
![image](https://user-images.githubusercontent.com/45524401/79477271-e32b4900-7fbe-11ea-87d5-2ff1209c596e.png)

maybe something like this for tetra league?
![image](https://user-images.githubusercontent.com/45524401/79479100-1cfd4f00-7fc1-11ea-9a1f-193cc61caa4d.png)

**Comment by Wirtualnosc** [comment]
I already discussed this a bit with osk before, but it would be nice for tetra league to have a history of 10 last played matches.

**Comment by Neeko-iko** [comment]
adding onto what this feature could look like
you know how in Puyo Puyo Champions it shows when a chain starts so that you can seek to when that happens?
That'd be a nice feature to have with spikes so that you can analyze what you could've done better to deal with a spike (or just watch how cool it looked, if you wanna)
also just for replays in general, allowing seeking in the replay (going back and fourth) along with the speed would be greatly appreciated.

**Comment by o5k** [comment]
Added in next version!

![](https://kagari.moe/:/mari_mami.png)
