### ISSUE TITLE
Alternative "Retry Upon Finesse Fault" Option

### ISSUE THREAD

**Issue by limgw1** [tetrio/issues#275]
### Describe the solution you'd like
A different type of redo where instead of resetting the whole game, it resets that one piece upon a finesse fault, much like the on **Tetresse** when you select the redo option.
Link : https://tetresse.harddrop.com/

(Additional feature that is not important: To show the hints or suggested solution to the finesse issue like Tetresse, but I understand it would be hard or not viable to brute force all the solutions in unless can look at the source code)

**Comment by limgw1** [comment]
I forgot to consider the ranking thing. So either it makes the sprint game unrankable OR as a feature in custom lobby.

**Comment by Beethoven-n** [comment]
I want to reopen this issue, but have this functionality added to Zen mode instead so it doesn't mess up rankings. Tetresse is good and all, but my hold key is Tab, which messes it up.

**Comment by SphyxDev** [comment]
Now that we have the undo/redo in Zen thanks to #543, could this perhaps be easier now?
