### ISSUE TITLE
Optimise Tetra League Leaderboard

### ISSUE THREAD

**Issue by clxxiii** [tetrio/issues#290]
**Is your feature request related to a problem? Please describe.**

The Tetra League Leaderboard screen can drop below 30 fps.

**Describe the solution you'd like**

Render a handful of players at a time, so the webpage isn't as graphics intensive

**Describe alternatives you've considered**

The XP leaderboard doesn't lag. This is on a $400 graphics card, I don't know about stuff even lower than that

**Additional context
Add any other context or screenshots about the issue.**

Using an NVIDIA 1060 6gb graphics card on Chromium Edge. Tetrio is running on high graphics settings

**Comment by o5k** [comment]
The 1000-player leaderboard is a temporary system - it will soon be locked back to 100, with a proper long (infinite scroll) leaderboard on a seperate page.

**Comment by o5k** [comment]
Fixed in next version.
