### ISSUE TITLE
Username Changes

### ISSUE THREAD

**Issue by clxxiii** [tetrio/issues#291]
**Is your feature request related to a problem? Please describe.**
I would like to be able to change usernames on an account

**Describe the solution you'd like**

On the account screen, be able to change your username. Possibly after a password prompt.

**Describe alternatives you've considered**

If I wanted to add ttv to my ign so people knew I was streaming, I would need to have two accounts. If I could change my name, I could play Tetra League on stream without smurfing.

**Comment by o5k** [comment]
Added in 4.1.0!
