### ISSUE TITLE
Post-match breakdown

### ISSUE THREAD

**Issue by Tenchi2xh** [tetrio/issues#297]
A game-by-game breakdown displaying stats for each game played during a league match would be quite nifty. Here's a mockup:

![image](https://user-images.githubusercontent.com/4116708/80810345-e8de7c80-8bc3-11ea-905c-4276a1f431db.png)

Not included in the mockup: VS score

The best PPS and APM could be highlighted

Future improvement: APM and PPS PBs (using match history, #296) (gold split!)

The "save replay" button is of course only possible if #267 is implemented

**Comment by Tenchi2xh** [comment]
Since it would be hard to include this amount of information in the end result screen, maybe we could take advantage of the fact that there's already a chat during the matches, and display the result of each match + stats after the conclusion of each game!

For example:

```
[SYS] started the game
TENCHI glhf
FOOBAR glhf
[SYS] game 1: victory for FOOBAR
[SYS] game 1: FOOBAR 110 APM / 3.5 PPS
[SYS] game 1: TENCHI 35 APM / 1.3 PPS
TENCHI damn you're good
FOOBAR hehe
[SYS] game 1: victory for FOOBAR
[SYS] game 1: FOOBAR 110 APM / 3.5 PPS
[SYS] game 1: TENCHI 35 APM / 1.3 PPS
...
[SYS] game finished
TENCHI gg
FOOBAR gg
```

**Comment by Tenchi2xh** [comment]
Another info worth noting after each game: the game duration

**Comment by o5k** [comment]
wakey wakey

**Comment by o5k** [comment]
Added in next version!

![](https://kagari.moe/:/shōko_tamao.png)
