### ISSUE TITLE
Weird Sound Glitch

### ISSUE THREAD

**Issue by Anna1234ihrs** [tetrio/issues#298]
### Reproducing
Steps that lead up to the behavior:
1. I started a solo game using the standard custom rules.
2. I clicked off the tab so I could use the bathroom really quick.
3. When I got back and clicked on the tab again no sound would play.
4. I tried refreshing the tab, closing and reopening, even closing chrome all together but nothing changed.

### Expected behavior
I expected music and sound effects to play

### Screenshots
Shown here is proof that I have the volume on at normal levels but no sounds will play.
![Screen Shot 2020-05-01 at 1 05 37 PM](https://user-images.githubusercontent.com/61763729/80824503-8cbc2e00-8bac-11ea-8bfe-85be534ec3fa.png)

### Your setup
 - **OS and version**: OS X Mojave
 - **Browser and version**: Chrome 78.0.3904.108

### Additional context
I have been playing for a few days now, and I have been experiencing similar problems to this frequently, although most of them were easily fixable.

**Comment by o5k** [comment]
What's in the console? (F12 → Console)

**Comment by LayneTheEpic** [comment]
Did you check that when you clicked on the tab you didn't accidentally mute it? Or does sound stop playing once defocused

**Comment by Anna1234ihrs** [comment]
It would stop playing when defocused and never came back on. I checked several times if the site was muted, and it wasn’t
