### ISSUE TITLE
Automatic music change during extended solo gameplay sessions

### ISSUE THREAD

**Issue by csq-curiosity** [tetrio/issues#300]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
When playing long-term games on solo, especially when restarting your games a lot of times, it can be tedious to listen to the same music over and over again. When "random", "random:calm" or "random:battle" is chosen, let the game automatically play music in random order after a certain time and/or loop has passed.

**Comment by Tenchi2xh** [comment]
Maybe the trigger for that option could be levels?

**Comment by csq-curiosity** [comment]
I was more or less imagining ~~Blink's stream~~ a jukebox-like effect while going on, for example, long sessions of sprint PB grind, so playing at a certain pace, user level or game level would not affect it. But that may also be an option later when new modes are added into the game.

**Comment by csq-curiosity** [comment]
I'll say that I'm still waiting for this feature. It is _kinda_ available in zen if you enable levelling, but not in ways I envisioned in 40 lines mode or maybe other modes upcoming soon. Although that being said this may be a request that needs further details in the context of current nonexistent modes.

For now, I'll close this thread and maybe do another request, or reopen this thread when it seems appropriate.
