### ISSUE TITLE
Local background support

### ISSUE THREAD

**Issue by deltadex7** [tetrio/issues#303]
### Is your feature request related to a problem? Please describe.
Possibly related to #101.

### Describe the solution you'd like
A feature to add background from local file and access it by either reading it locally (workaround required for browser) or upload it to the server and read from there. Note that uploaded files should be tied to the user account and is limited (e.g. 5 images of 1080p).

### Describe alternatives you've considered
Should there be any alternatives, I recommend adding more stock images and also an image picker, as suggested in #266 and #101. Other alternative is a base64 image format, probably needs an encoder for this, therefore no need for image upload (but data text is big in this format).

### Additional context
I will add further context later in the comments, if I find anything relevant.

**Comment by Houdini111** [comment]
I'd like to add that I'd like this to allow for selecting a folder to rotate through instead of having to use a comma separated list.
