### ISSUE TITLE
Option to disable hard-dropping while moving piece sideways

### ISSUE THREAD

**Issue by Jeremiidesu** [tetrio/issues#305]
### Is your feature request related to a problem? Please describe.
Playing on a DualShock 4, I find myself accidentally hard dropping twice as I accidentally press my hard drop key (dpad up) while starting to move the piece sideways (dpad left/right)

### Describe the solution you'd like
An option that prevents harddropping when trying to move sideways

**Comment by Darksidez910** [comment]
I hate to hear this! 

This is a known fault with Dualshock 4 controllers, you will have to adjust to this controller or change your playstyle, or just simply slow down. 

These controllers have a connected D pad, which can result in missed inputs. Definitely try this controller on other tetris games and see if you get the same issues. There are some youtube tutorials that can try and help you learn how to play with a Dualshock 4, or you can buy a 20-40 dollar controller online (I have a recommendation for what I use if you'd wish).

Until then make sure all your settings in game are adjusted properly. 

Home screen > Config > Controls > Controller Sensitivity
Home screen > Config > Handling > Prevent Accidental Hard Drops

Best of luck with this bro!

**Comment by Jeremiidesu** [comment]
> These controllers have a connected D pad, which can result in missed inputs.
I am well aware of this fact, which is why I like it a lot

> Definitely try this controller on other tetris games and see if you get the same issues.
TETR.IO is the only Tetris game on which I am experiencing these issues. My main reference points for DualShock 4 gameplay are Puyo Puyo Tetris and Tetris Effect (VR) on PC, in which I don't experience that issue. If I was, I probably wouldn't even be playing PC Tetris games in the first place.

I'm not sure how controller sensitivity is going to affect the DPad but I'll experiment with that.

**Comment by Darksidez910** [comment]
Theres not much you can do, it's just how the controller is created. Those are the only 2 settings I could think of.

If you put alot of pressure on left or right you will notice that's when missed inputs happen

**Comment by Darksidez910** [comment]
I got tetris effect on PS4 and it was impossible for me to play with a dualshock 4.
It's just gonna take adjustments

**Comment by Darksidez910** [comment]
This also isn't a guideline tetris game so some things arent going to feel the same. Try some setting changes, or possible adjust your playstyle

**Comment by Jeremiidesu** [comment]
What worked for me was to set a non-zero ARE. Another relevant feature for dualshock 4 players could be instead a slider to force a delay between hard drops on the local player, so that the need for a non-zero ARE would be removed

**Comment by Darksidez910** [comment]
Do you mean ARR?

**Comment by Jeremiidesu** [comment]
No, I mean ARE, the one you can set on custom games. No block, no hard drop
![ARE](https://user-images.githubusercontent.com/20820425/81023699-7a264b00-8e71-11ea-8958-3e452c1a6f08.png)

Alternatively, playing on my phone also resolves the issue, but I'd assume mobile TETR.IO is out of scope.

**Comment by Jeremiidesu** [comment]
In any case, even when playing on keyboard, I enjoy games which prevent hard-dropping while moving the piece sideways, so the feature this issue originally requests shouldn't exclusively be related to DS4 quirks
