### ISSUE TITLE
A More Calm, Map Based Mode

### ISSUE THREAD

**Issue by ZaptorZap** [tetrio/issues#309]
### This is one for farther down the line, as it can't exist until #212 has been implemented

# The Idea
Ever heard of Mario maker and it's endless challenge? I was thinking we parody them and create a tetrio endless challenge of our own! The idea is simple; once we have a large list of maps published, this mode shall pull from it, creating a seamless, _calmer_ mode.

# Some Specifics
This mode would be accessed from the solo player modes, as it is one. The gameplay would consist of clearing a map, then a small break to load the next map, switch the music, and let the player rate the map they just played. 

# The Short Break Room
This "Short Break Zone" would consist of a 31x10 (not shown in example) board, while a mino is used to select the rating, or skip the rating. This mino has zero gravity afflicting it, and perhaps the DAS and ARR should be lowered, to avoid being annoying to go through. After rating the map, the player would be asked if they'd like to continue, or stop for the time being. 

![tetrio concept](https://user-images.githubusercontent.com/64891705/81372414-2bfe8b00-90af-11ea-997d-421f29f45b2e.png)
(There would also be a report function, by moving into the left wall for, say 2 seconds)
(You might also want to add another column, so the mino could be centered. I can't be bothered to update this to show either of these changes.)

# Music Selection
As a calmer mode, the _calm_ category of music would be used. During the break period, a mixture of a low-pass filter + some volume adjustments (trending downwards, of course) could be used. During all of these filters, the currently playing track would be switched out for a new calm song.

# Ending a Chill Session
The idea I'm going for is something like this; you pick up this chill mode when you've got free time, and don't feel like dragging yourself through some multiplayer, or doing some regular marathon. Being able to quit at any time is key with this idea, so forfeiting would save that point in time, for you to pick up later. The aforementioned break period would also host an easy way out, after completing a map. It'd also be neat to have a "maps completed" counter, to keep track of things. Would also be a fine stat to track in leaderboards, so maybe three other people can get that # 1 badge.

**Comment by ZaptorZap** [comment]
shoot, disregard lol
turns out i am bad at clicking buttons :p

**Comment by ZaptorZap** [comment]
frankensteined this one back from the dead. grrrr slippy hands!

**Comment by Devetec** [comment]
Good idea!
