### ISSUE TITLE
Navigate to previous/next piece in the replay mode

### ISSUE THREAD

**Issue by eight04** [tetrio/issues#311]
### Is your feature request related to a problem? Please describe.
I want to find a specific timestamp in the replay but there is no way to navigate backward.

### Describe the solution you'd like
Add a shortcut (left/right) to jump to the frame that the previous/next piece spawns.

### Describe alternatives you've considered
Or, jump to the frame that the previous/next piece is locked. This might be even better since we can view the replay like a fumen.

### Additional context
In Jstris, there is a list of timestamp of each clear which is also acceptable. Though I prefer a keyboard shortcut:

* Space - pause the replay
* Left/Right - previous/next piece
* Up/Down - increase/decrease replay speed

**Comment by Neeko-iko** [comment]
:)

**Comment by o5k** [comment]
Added in next version!

![](https://kagari.moe/:/anno_moeka.png)
