### ISSUE TITLE
Zen mode

### ISSUE THREAD

**Issue by Cabbage-Roll** [tetrio/issues#314]
### Is your feature request related to a problem? Please describe.
There is really no incentive to logging in on daily basis and playing other than gaining experience.

### Describe the solution you'd like
I would suggest adding zen mode, where you can get a empty board to fill it with pieces and people can go to your profile to see the board you pick to show. But pieces will be really slow to get.

### Additional context
Here is my idea how you should get them:
Limit of pieces you can get daily is 5 no matter what (maybe increase it for donators?)
When you get a piece, it will be completely randomly picked.
For logging in you get 1 piece, if you have logged in consecutively for over a week you get 2 pieces daily until the chain stops.
You can get pieces in quick play, for surviving more than 30 seconds you get quarter of piece (to make it fair for bad people), top 3 and 2 get two quarters of piece while winner gets whole piece.
By quarter, it will go into a buffer, when the buffer reaches 4 quarters random piece is given.

Now the gameplay goes like this:
Gravity is set to zero.
There is no queue or hold, you choose what piece you want to place.
You play normally, but if line is cleared you get your quarters of pieces back (this time not into buffer, but corresponding pieces)
You can undo up to five moves.
If you top out, you can either undo or reset the board, giving you back all the pieces.
In case you got too many pieces, you can add a new fresh board and fill it separately from the previous one.
By quitting, board states get saved and you can continue filling it later.
And finally, you pick one board you want to show on your profile when someone clicks "my board" button.

I will add illustrations later to show you how i imagine it.

**Comment by Cabbage-Roll** [comment]
You click on piece to choose it
Unlocking pieces is manual process
x(number) means number of pieces, +(number) means number of quarters.
[https://imgur.com/a/cL6TNLT](url)

**Comment by rustMotherboard** [comment]
this has got to be one of the _worst_ tetr.io ideas i've seen yet, what's the point of this mode?

> There is really no incentive to logging in on daily basis and playing other than gaining experience.

you're excluding tetra league, solo modes, quick play, AND private/public multiplayer matches from that, y'know

((also giving donators perks during gameplay can be considered pay-to-win which is bad on it's own))

**Comment by Maxio68** [comment]
> ((also giving donators perks during gameplay can be considered pay-to-win which is bad on it's own))

While I don't think this mode is a good idea (maybe with a few changes, like removing the limit), it doesn't feel like pay-to-win; there's no leaderboard, and it doesn't have effects on other modes.
