### ISSUE TITLE
I lost my 40lines challenge records

### ISSUE THREAD

**Issue by floreariza** [tetrio/issues#315]
Hello,

My account is FLORENTINOARIZA. Just now I found that my records of 40 lines challenge have all been lost, while my blitz records are still there. I would like to know if I can get them back because I spent the whole afternoon breaking my pb in 40 lines... Thank you.

**Comment by o5k** [comment]
Do you have a TTR file?

**Comment by Wirtualnosc** [comment]
I think there might be more people affected. I don't think I've ever had a 40L standing since alpha release, yet I've got one right now. I remember losing mine in Blitz as well, but I got one again.
![image](https://user-images.githubusercontent.com/6901295/81726371-2e7e2d80-947f-11ea-8e9b-d0d6b8a3836d.png)

**Comment by AndyThePie** [comment]
I have also lost my challenge records - all but three 40L records. Is this by any chance linked to the replay migration thing?
(I do have a few old TTR files, as well as some old replay IDs, but I don't know if they'll be of any help)

**Comment by justinkkwan** [comment]
I also lost my record (maybe?). I got a 22.xx using Chrome. But then today I got a "new record" of 23.5 on Firefox.

I was about to report a bug with using multiple browsers to play but then I saw this issue already existed and it might actually just be that my 22.xx was deleted.

**Comment by ZaptorZap** [comment]
showing up here to say i got these problems as well. my first sub minute has disappeared ;-;
can't give you much information, or a .ttr file. all i can give you is this image alongside a (general) timestamp of the play in question: https://discordapp.com/channels/673303546107658242/673303546564968566/709261059873046589

**Comment by LayneTheEpic** [comment]
I lost my sub-1 as well, have the TTR on hand
