### ISSUE TITLE
API showing more data 

### ISSUE THREAD

**Issue by JaibreyonLourens** [tetrio/issues#318]
### Is your feature request related to a problem? Please describe.
I just figured out how to use the API to get my data on a stream overlay but some things I wanted to get weren't there. I've made an program that updates my rating and rank on the overlay and would like to put some more things on it 

### Describe the solution you'd like
The things I would like to see if possible are Best Time and your current Level

### Describe alternatives you've considered
writing them in plain text 
### Additional context

**Comment by clxxiii** [comment]
Were you planning on making the overlay public? I'd love to use it!
