### ISSUE TITLE
Text Formatting Bug

### ISSUE THREAD

**Issue by atome1ectron** [tetrio/issues#325]
### Describe the bug/issue
Overlapping test on the home screen when Tetr.io is window-split (when you drag a window to the far side of your screen so you can be in two windows at once with each taking up half of the screen).

### Reproducing
1. Go to 'tetr.io'
2. Drag window to the very edge of screen, so it takes up half of the used monitor
3. Look at the "Multiplayer", "Solo", "Tetra Channel", and "Config" Selections and you'll be able to see the clipping text.

### Expected behavior
I expected the text and graphic sizes to adjust for the change in window size.

### Screenshots
https://imgur.com/a/ASWmcG0

### Your setup
 - Windows 10
 - Chrome 81

### Additional context
Nope, but I hope you're having a great day.

**Comment by o5k** [comment]
TETR.IO isn't meant to run in portrait mode-esque viewports yet. Once it does, this too will be fixed.
