### ISSUE TITLE
Add option for Single DAS / disable inactive direction DAS

### ISSUE THREAD

**Issue by RayRay26** [tetrio/issues#326]
### Is your feature request related to a problem? Please describe.
From what I observed, if you hold both directions and release one, it slingshots in the other direction.

### Describe the solution you'd like
I would like an option in Handling where when you let go of one direction, DAS is reset but it immediately moves in the new direction, almost like if you just pressed the button.

### Describe alternatives you've considered
I was considering increasing the DAS delay in order to get used to double DAS, but it would make movement feel more sluggish.

### Additional context
If you're not sure what I'm talking about, hold Left, then while hold Left, hold Right until it hits the right wall. Then release Right and it should zoom to the left side again. What I want is after releasing Right, move left once and charge DAS again.

**Comment by o5k** [comment]
Fixed in next version.
