### ISSUE TITLE
Show your current XP in your profile

### ISSUE THREAD

**Issue by MattMayuga** [tetrio/issues#327]
Currently, you can only see the amount of Experience Points you have in the XP bar after a completed game. You can see the percentage towards next level by hovering the cursor over your level with your mouse. Without the mouse, you can't actually see it, so the only way to see it is completing a game. For this feature request, I would like to have the XP bar appear in a player's profile, which shows how close you are to levelling up. This makes it so that you don't have to use a mouse to see your Exp. Points.

![An illustration of a conceptual XP bar on a player's profile.](https://i.fiery.me/YZaki.png)

**Comment by UniQMG522** [comment]
Possible alternative idea: Using the badge as an xp meter.
![firefox_GwVWWtMFIw](https://user-images.githubusercontent.com/48872143/83346273-da24db80-a2cf-11ea-9a7c-282bb18105b9.png)

Code used to achieve this (Could use a better handling of the shine, currently just puts it halfway through the active region):
```javascript
var elems = [...document.getElementsByClassName("leveltag")];
for (let elem of elems) {
	let progress = parseInt(elem.title);
	elem.style.setProperty('--xp', progress + '%');
}
```
```css
.leveltag::after {
  --shine: calc(var(--xp)/2);
  
  background: linear-gradient(
    to top,
    var(--color-active) 0%,
    var(--color-shine) var(--shine),
    var(--color-active) var(--xp),
    var(--color-inactive) var(--xp),
    var(--color-inactive) 100%
  ) !important;
}
.leveltag.lt_shape_color_0::after {
  --color-active: #c9c9c9;
  --color-shine: #e4e4e4;
  --color-inactive: #646464;
}
.leveltag.lt_shape_color_1::after {
  --color-active: #fd3535;
  --color-shine: #ff6d6d;
  --color-inactive: #7e1a1a;
}
.leveltag.lt_shape_color_2::after {
  --color-active: #f56200;
  --color-shine: #ffa162;
  --color-inactive: #7a3100;
}
.leveltag.lt_shape_color_3::after {
  --color-active: #e9d41e;
  --color-shine: #edde5f;
  --color-inactive: #746a0f;
}
.leveltag.lt_shape_color_4::after {
  --color-active: #90dd21;
  --color-shine: #b5f856;
  --color-inactive: #486e10;
}
.leveltag.lt_shape_color_5::after {
  --color-active: #23ee53;
  --color-shine: #7df89a;
  --color-inactive: #117729;
}
.leveltag.lt_shape_color_6::after {
  --color-active: #22f0da;
  --color-shine: #8afdf1;
  --color-inactive: #11786d;
}
.leveltag.lt_shape_color_7::after {
  --color-active: #1f6cec;
  --color-shine: #84b2fe;
  --color-inactive: #0f3676;
}
.leveltag.lt_shape_color_8::after {
  --color-active: #8644ff;
  --color-shine: #bb96ff;
  --color-inactive: #43227f;
}
.leveltag.lt_shape_color_9::after {
  --color-active: #e81bea;
  --color-shine: #fea4ff;
  --color-inactive: #740d75;
}```

**Comment by o5k** [comment]
This will be available on ch.tetr.io when it appears, but would be too much clutter in the main game UI.
