### ISSUE TITLE
Switching to Spectate Mode just before a Custom Game with "Best of 2 (or more)" Starts

### ISSUE THREAD

**Issue by DanKruse731** [tetrio/issues#328]
### Issue?
A few frames before a game in a custom room was started, I switched to Spectate mode. However, I was put into the game. After winning the first round, the game put me into spectate mode for the second round. Thus, I couldn't control my board and the connection timed out.
**NOTE: THIS WAS IN A CUSTOM ROOM WITH THE "FIRST TO 2 WINS" SETTING.**

### Reproducing
1. Enter a Custom Room (First to 2 or more wins)
2. Click on Spectate just before the game is initiated
3. If you are in the game, even after switching to Spectate Mode, play the first round
4. The next round may result in a crash.

### Expected behavior
I clicked it just before it started, so it should've put me into Spectate Mode.

### Screenshots
![Screenshot (1201)](https://user-images.githubusercontent.com/26609059/82634736-2bdcb000-9bc4-11ea-8b4a-8534454ff621.png)

### Your setup
 - Windows 10
 - Google Chrome

**Comment by o5k** [comment]
Fixed in next version.
