### ISSUE TITLE
Tetr.io Desktop on macOS doesn't quit when window is closed or exit button is pressed

### ISSUE THREAD

**Issue by danyisill** [tetrio/issues#330]
### Describe the bug/issue
Tetr.io Desktop should quit when the window is closed. While it is the Mac philosophy for document based applications, I don't think it should be applicable for a video game -- all video games I`ve seen quit on close. 

### Reproducing
1. Click exit button
or
1. Press the red traffic light

### Expected behavior
Process quits and the icon is not visible in the Dock.

### Screenshots
![Screenshot 2020-05-22 at 23 27 6](https://user-images.githubusercontent.com/23189912/82707023-df58a980-9c83-11ea-9cbd-3b3edae2ce26.png)
![Screenshot 2020-05-22 at 23 27 38](https://user-images.githubusercontent.com/23189912/82707026-e089d680-9c83-11ea-9d31-9edc64a4978e.png)

### Your setup
 - **OS and version**: macOS X 10.14.6
 - **Browser and version**: Desktop Client for Mac OS 1.0

**Comment by Tenchi2xh** [comment]
As mentioned on Discord earlier,

I have seen a similar behavior in some other Electron apps under macOS: the first CMD+Q closes the window, and then the app stays windowless while waiting for a second CMD+Q

Maybe this discussion on another app could be useful
https://github.com/SabakiHQ/Sabaki/issues/157

**Comment by Tenchi2xh** [comment]
Still relevant

**Comment by LayneTheEpic** [comment]
It seems to be an Electron [issue](https://github.com/electron/electron/issues/9966), so osk can overengineer the close mechanism or wait until that gets fixed

**Comment by o5k** [comment]
Fixed in next version.
