### ISSUE TITLE
Header isn't tall enough on about page

### ISSUE THREAD

**Issue by lifeofchrome** [tetrio/issues#336]
### Describe the bug/issue
On the about page (https://tetr.io/about/) and on the login screen, the purple header (gray on login screen) is not high enough for the logo, making it look weird.

### Reproducing
1. Go to the about page
2. Look at the header

### Expected behavior
There should be some space under the logo so the border doesn't overlap with the logo.

### Screenshots
![image](https://user-images.githubusercontent.com/8226943/82713569-f8943280-9c50-11ea-95bd-dc2664a98a78.png)

### Your setup
 - **OS and version**: Elementary OS 5.1.2/Ubuntu 18.04.3
 - **Browser and version**: Chrome 80
- Also reproducible with tetr.io desktop v2 (when the login screen is briefly visible)

### Additional context
https://discordapp.com/channels/673303546107658242/673305614318960671/713486764425347173

**Comment by o5k** [comment]
This is as intended. I may change the design of it later, though.
