### ISSUE TITLE
Download Tetrio Client button in the tetrio client

### ISSUE THREAD

**Issue by clxxiii** [tetrio/issues#337]
### Is your feature request related to a problem? Please describe.
It's redundant to advertise the Tetrio client on the client

### Describe the solution you'd like
If possible, don't show the get client button on the login screen

### Additional context

![image](https://user-images.githubusercontent.com/46410314/82715858-f4711080-9c62-11ea-938e-b682778f9e78.png)

**Comment by o5k** [comment]
This icon does hide, but during the loading phase it doesn't have the time to yet :/
