### ISSUE TITLE
Add a license to desktop client?

### ISSUE THREAD

**Issue by Denton-L** [tetrio/issues#339]
AFAICT, there's no license for the desktop client. There's a license for the bundled Chromium and Electron but not for the client itself.

It would be nice to know under what terms the client is distributed. That way, I can properly fill in the license array in the tetrio-desktop AUR package: https://aur.archlinux.org/packages/tetrio-desktop

**Comment by StardustAlpha** [comment]
If i recall correctly, osk said the lack of a license was temporary. It will probably be fixed at some point.

**Comment by Denton-L** [comment]
Yep, still active.

**Comment by Denton-L** [comment]
Still active.

**Comment by o5k** [comment]
Fixed in next version.
