### ISSUE TITLE
Controller input not recognized in Chrome but works in Edge

### ISSUE THREAD

**Issue by shaggnanigans** [tetrio/issues#340]
### Describe the bug/issue
When trying to use a controller the a controller was connected message shows twice but the controlled is not recognized when using Chrome. If I (reluctantly) switch to Microsoft Edge my controller works but I cant use the chat system at all. I also tried the new Tetr.io Desktop launcher and it has the same issue.

I also notice Tetr.io functions fine on my low end Chrome book.

This was working at one point and then it stopped I believe after a windows update and I have tried the usual restart, and reinstalled Chrome with no change

### Reproducing
1. Pair 8bit do sn30 pro + controller to computer through bluetooth
2. open Tetr.io in Chrome or Desktop launcher
3. press controller inputs
4. controller is recognized 
5. try to create a button map and no inputs are read
6. Launch Tetr.io in Microsoft Edge
7. repeat steps 3-5 in Edge
8. Map buttons.
9. play game normally with being able to type in chat

### Expected behavior
Once the controller is paired I should be able to map the buttons and use the controller normally in Chrome.

### Screenshots
sorry, don't have any

### Your setup
 Windows 10, version 1909, os build 18363.836 
Chrome 83 I think, as far as I can tell it is the latest version

### Additional context
Not sure if this is what you are looking for, but I tried to get you some browser logs
TETR.IO
index.js:163 Please be careful when pasting anything in the console. Attackers may be out to steal your login information.
index.js:163 Up to date. Local version 3.0.1-production | Commit d943ea6 (5/23/2020, 8:01:02 AM) | Server cycle TV6oG8LEr | Build AALWo3wPY (5/23/2020, 8:06:16 AM) | PID 22819
index.js:163 PixiJS 5.2.2 - WebGL 2
index.js:163 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 -CPU: 12-coreMemory: ~8 GBConnection: 10 Mbps, 50ms RTT [4g]
index.js:163 Renderer: ANGLE (AMD Radeon RX 5700 XT Direct3D11 vs_5_0 ps_5_0)

Thanks for all you do, I am super impressed with Tetr.io and love playing it. I hope I am not wasting your time. Feel free to reach out out to me for more information.

Shaggy

**Comment by Darksidez910** [comment]
Well, hey there shaggy! It's been a while.

Anyways, I have this same issue. My school chromebook worked perfectly fine with my controller, but as soon as I used my normal laptop the controller will connect but left/right wont keybind to the site on chrome or edge.

**Comment by o5k** [comment]
Do you know which Windows update caused this?

**Comment by Darksidez910** [comment]
Dont think I did any windows updates?

**Comment by Darksidez910** [comment]
Its been an issue for me for a month or something. I've tried a brand new controller, and tested on that site like you told me and everything works fine elsewhere

**Comment by shaggnanigans** [comment]
Unfortunately I don't know which update this started happening either.

I typically use the controller wirelessly so today I tried plugging it in
and that made no difference.

It has been slow at work so I tried the same controller wired with my work
computer on chrome and it worked fine.

I saw someone mention a button combo to limit the frame rate and that made
it work for a complete session with the desktop version but it didn't work
the next day. I forget the button combo or I would try it again.

**Comment by Mr-Turnip** [comment]
I have seen that the Bluetooth on chrome books is better than on windows (10) most of the time.

**Comment by Darksidez910** [comment]
I use a wired controller and always have

**Comment by Darksidez910** [comment]
I can sync my controller and keybind every button besides left/right

**Comment by shaggnanigans** [comment]
I have noticed the last few days that if I launch Tetrio desktop and then
pair the controller to my PC it works normally.

**Comment by o5k** [comment]
Cannot reproduce this still, all buttons seem to work for me on Xbox 360 controller over USB...
