### ISSUE TITLE
Let people spectate the game when they join a lobby

### ISSUE THREAD

**Issue by Oascany** [tetrio/issues#341]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when I join a lobby and I can't spectate the match and have no way of knowing if a match just started or if it's about to end.

### Describe the solution you'd like
When anyone joins a lobby, along with being able to see the rules, there should be a tab that can be clicked so they can spectate the ongoing game.

**Comment by ZaptorZap** [comment]
I'd like to reference this: https://blog.osk.sh/post.php?p=5e76725469c492.94375614
relevant bit: "It's impossible to spectate a match that's already begun right now. I'd like to make it possible to do so - it just requires a bit of headache code-wise."

**Comment by ZaptorZap** [comment]
Nope, you still can't spectate an ongoing game at the moment.

**Comment by o5k** [comment]
Added in next version!

![](https://kagari.moe/:/ohta_ayami.png)
