### ISSUE TITLE
Improved Quick-Play Balancing 

### ISSUE THREAD

**Issue by Xelitik** [tetrio/issues#343]
===Problem:===
An important part of being a game developer is making sure your game has appeal to a wide range of players. Quick-play is the default multiplayer room for this game. Considering the overall majority of players based on rank, most of these players are in the lower skilled, and from what I've seen in quick-play, it is mostly filled by these lower leveled and skilled players.

In Jstris, you would typically see the newer players in the default room, while the higher skilled players make their own custom rooms. In TETR.IO it is a little off. Even with just one high skilled player, quick-play can be a mess where lower skilled players have no chance to play for long (and either have to just stay and wait long periods of time or leave into a custom room). You typically see Noob Rooms made for lesser skilled players, that can easily be invaded by higher skilled players with less players that could be easily dominated. So I propose a solution.

===Solution:===
Make Quick-play more appealing to lower players without completely alienating higher skilled players. You can do this in a multitude of ways: 
- Garbage Cap similar to 99 that slowly goes away over time (Edit: including Interactive Delayed Garbage like 99 that would also go away over time)
- Enforced Handling that gives slower players a bit of an edge against ridiculous fast players.
- Better and more useful Targeting that can focus on dominating players either based on PPS, APM, Lines sent, KO's, or whatever you feel would be the most effective.
- Jstris-like handicaps such as PPS caps, no-4w, etc.
- These are only some proposals but you should think of your own if you wish. These ideas can also be tweaked to fit TETR.IO.

===Results/Effects:===
This should make quick-play more appealing while also forcing more experienced and knowing players to create their own custom rooms. Newer players would be able to quickly experience TETR.IO at its defaults while stronger players will have custom rooms, Tetra League, and still access quick-play with a lower skill ceiling, resulting in a more appealing game.

**Comment by clxxiii** [comment]
Enforced Handling is already a setting in custom rooms

**Comment by o5k** [comment]
I don't like forcing people to play slower, etc. Once we have enough players, we can see if we can have Quick Play break itself up (in a pseudo-matchmaking sense).

**Comment by alex-ong** [comment]
One thing with jstris is that it self-healed these problems by *gasp* increasing player count. It's a bit different from tetr.ios perspective because the curve of playerbase is completely different. 

I'm not sure if intervention is required or not since the way the player count changed over time is different for both games.

**Comment by SebatheDragonbear** [comment]
This could have a similar impact to Tetris 99's Invictus lobby
