### ISSUE TITLE
Option to display garbage output (and spike counter) in custom solo mode

### ISSUE THREAD

**Issue by Volleo6144** [tetrio/issues#345]
### Is your feature request related to a problem? Please describe.
...Not really, except that (in the absence of official documentation that's more readable than tetrio.js below) it might be nice to not have to have other people playing (or, in the extreme case, to not have to have internet at the time) to see, for example, how exactly b2b chains work.

### Describe the solution you'd like
An option to display the amount of garbage each clear would do in a multiplayer setting, in custom solo (perhaps with the same yellow numbers it already does in multiplayer). And also the spike counter (perhaps with the 10-line(?) threshold removed), because it looks cool.

### Describe alternatives you've considered
Particularly tech-savvy players may be able to find the algorithm in the [source code](https://tetr.io/js/tetrio.js), but for most players, there really isn't any official documentation for how exactly B2B chaining affects garbage output.

### Additional context
I was going to write something here about my surprise at the presence of actual numbers in tetrio.js for how many lines (10) and points (2600) a T-spin quad gets, but I'm pretty sure this might actually be attainable with stupid spins on.

(also I've probably spent way too much time revising this)

**Comment by o5k** [comment]
> there really isn't any official documentation for how exactly B2B chaining affects garbage output

There is:
![](https://kagari.moe/:/2020-05-30_02-07-18.png)

**Comment by o5k** [comment]
This is now implemented by Zen.

**Comment by brickyosu** [comment]
hello, i would really like this addition because i want to see how much i can spike on a 4-wide board!! zen doesn't allow changing the side of the board so i would like this to be added :)
