### ISSUE TITLE
You can "Spectate" the other player in a 1v1 

### ISSUE THREAD

**Issue by ZaptorZap** [tetrio/issues#347]
### Describe the bug/issue
You can change who you're "spectating" in a final two situation. This will mess with the layering, causing action text to fall behind the player on the left.
### Reproducing
1. Head into quick play, or custom, room with the setting "Show Duels Side By Side" on
2. Head into spectator mode, or play as normal and end up dead before the final two
3. Click right board, and see the results of the action text.
### Screenshots
![image](https://user-images.githubusercontent.com/64891705/83204337-1c68e400-a13b-11ea-9e1f-ce9c22048448.png)
See the "Double 1 Combo" text
### Your setup
 - **OS and version**: Windows 10 1903
 - **Browser and version**: Firefox 76.0.1, confirmed with TETR.IO v4

**Comment by o5k** [comment]
This is technically on purpose - you should be able to switch who is on the left and right. It's not easily possible for me to fix the layering bug though, due to how the renderer works :/
