### ISSUE TITLE
Tetr.io Custom Skins

### ISSUE THREAD

**Issue by PressKk** [tetrio/issues#348]
If Tetr.io had custom skins for the game, changing the look of tetrominoes or background or grid etc., I think that would be a great feature.
For example in osu! you can download a skin from the internet or make one yourself. Especially making a skin by yourself would be great.

**Comment by clxxiii** [comment]
There is an extension on Firefox that allows you to use and make custom skins, along with several other things.

**Comment by ZaptorZap** [comment]
I would also like to touch on osk's thoughts on the matter, as shared through the qna hosted by blink some time ago:

> Blink: Ah okay. "Do you have any plans to extend the level system in TETR.IO?"

> osk: Level system as in player level or?

> Blink: Yeah I'm guessing the player level stops at 130 something or whatever. The level just from playing? Is that what you're asking Tanarus? Wait, who asked that? It was Kinetic, if you want to clarify your question.

> osk: I mean if it's just about player level then yeah. Generally I don't know what I can do with it right now. What I might do at some point is make it, if you wanted to, tokens for it, and you can have some skins that actually show to other players right? There's already a really really cool plugin that allows you to use custom skins. It only works on Firefox, but it's a really cool plugin.

> Blink: Oh, I haven't seen that yet. I didn't realise that you could us- Only on Firefox?

> osk: Yep, it only works on firefox so of course other people can't see your skin right? So I might do some sort of thing with the level system later on, where you can build towards unlocking those skins. I know what chat's thinking right now, but I don't want to take it in the direction of pay to win or having to do microtransactions to unlock them, because I just really don't like that.

> Blink: How would that be pay to win? Skins shouldn't affect the gameplay right? 

> osk: Well not pay to win, but rather in general, micro payments.

**Comment by o5k** [comment]
Closing in favor of #359
