### ISSUE TITLE
20G related things

### ISSUE THREAD

**Issue by macyayaya** [tetrio/issues#351]
### Is your feature request related to a problem? Please describe.
The current 20G behaves weirdly as all blocks will shown at the top and drop after a moment, so they are not "instant". Also gravity is not performed before movement in this scenario, causing holes to be escape-able (e.g. a O can slide over a 2-block wide hole, provided that DAS is low enough.)

### Additional context
Would be great if:
* one can set a specific DAS/ARR/SDF at a custom game w/o the need to go back to settings everytime
* options to show NEXT and HOLD at top
* options to open/close the custom room and a solo mode in the room, so one can test out the settings before open it to public

**Comment by o5k** [comment]
> options to show NEXT and HOLD at top

?

**Comment by csq-curiosity** [comment]
I think the author was thinking of a TGM-like GUI in the game. Well... adding a different GUI layout into the game sounds like a completely different beast from... let's say adding a new skin.

Kinda related, but the 20G in this game is pretty janky, as macyayaya mentioned. Idk the exact figures, but anything below 2 ARR is prone to be glitchy. I would suggest for 20G, the game should pre-calculate where it should land instead moving and then applying gravity.

**Comment by flashwave** [comment]
if these are still wanted/aren't implemented yet it'd probably be better to create separate feature requests for each so they could be marked implemented individually
