### ISSUE TITLE
A Different Path To The Flames (Extra Fire Meter Aquirement Methods)

### ISSUE THREAD

**Issue by ZaptorZap** [tetrio/issues#352]
As I've noticed from limited personal experience, and patch note language, it seems the only way to get toasty is to take bloodshed upon others. Now that's all fine and dandy, however I've noticed quick play rarely heats up due to the overall spiky nature killing off those close to the element. A simple fix would go as follows:

- We could tie spikes to the meter, think a very nonlinear graph. A 10 spike wouldn't fill more than a simple lighter (1-2%), but an 18 spike could net you 18% perhaps?
- High line clears could add to the heat, as your playstyle warms up as well. Tense moments call for tense atmosphere, y'know? 
- A good back to back frenzy could add up quickly in terms of temperature. 2% every 3-chain, 5% each level 2 back-to-back you continue, and a good 15% once you hit the big ranks of 24 chains.

As usual, all of these are examples. Feel free to change the intricacies of the values, I'm sure nobody will notice.

**Comment by ZaptorZap** [comment]
Oh, and one more thing! Killing someone with a flame meter of any level should reward yours with half of theirs upon KO completion.

**Comment by o5k** [comment]
Technically, spikes and b2b already reward you, just too little to be noticable RN... Also, KOs of people with high flames already gives you fire as well! If you KO a high-fire target, it even shows how filled their flame meter was (100% being 700 fire points, the absolute maximum (500 is needed to reach On Fire))
