### ISSUE TITLE
Lose screen doesn't disapear when clicking on the "Finding Match" button

### ISSUE THREAD

**Issue by Haxel59** [tetrio/issues#354]
### Describe the bug/issue
When you click on the "Finding Match" button while on the lose screen of any solo mode, the screen doesn't disapear.
The real problem is if you get into a match with the lose screen still oppenned.

- If you click "retry", a sprint/blitz will start, while still being in the match. 
- If you click "back to title", you'll get back at the main menu but the match will still be in the background.

### Reproducing
1. Go to Tetra League and enter matchmaking
2. Get into a solo mode
3. Lose
4. Click on the "Finding Match" button
5. (Start a game and click on retry/back to title)

### Expected behavior
The menu you get when losing should disapear if you click on the "Finding Match" button

### Screenshots

![Menu on top of the Tetra League screen](https://user-images.githubusercontent.com/15271192/83951537-5cfae880-a832-11ea-93e6-58763f01f052.png)
![If you click retry](https://media.discordapp.net/attachments/460779763695616047/718882291216023632/unknown.png)
![If you click Back to Title](https://i.imgur.com/zSBOrqd.png)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Tetrio Desktop v3

**Comment by o5k** [comment]
Fixed in next patch.
