### ISSUE TITLE
Interactive buttons for Discord Rich Presence

### ISSUE THREAD

**Issue by aznguymp4** [tetrio/issues#357]
### Interactive Buttons to view other players' game status in a custom public room/quick play room.
Buttons won't appear if they're in a **private** room.
Desktop client only, of course. ![image](https://cdn.discordapp.com/emojis/682196590068236374.png?size=32)

![image](https://user-images.githubusercontent.com/48527495/83979695-ef07fd00-a8d5-11ea-8445-362c4ca2b90d.png)
### or
![image](https://user-images.githubusercontent.com/48527495/83980105-a867d200-a8d8-11ea-8499-a74e8b3c43ca.png)

**Comment by o5k** [comment]
Not possible due to the way Discord handles these and the TOS surrounding them :/
