### ISSUE TITLE
Watch Replays Without Logging In

### ISSUE THREAD

**Issue by Houdini111** [tetrio/issues#360]
### Is your feature request related to a problem? Please describe.
I'd like to be able to share replays with those who do not play Tetr.io but they cannot see them as they do not have accounts.

### Describe the solution you'd like
I'd like them to be able to click the replay link and watch the replay without having to make an account and log in. 

### Describe alternatives you've considered
I don't think there are any alternatives. Either the log in is required or it isn't.

### Additional context
I'm not sure what you're doing to require them to make an account to watch the replays. If it's a matter of not wanting them to be able to move around the interface (and thus play) without making an account then I think replacing the "back" button the page with a "log in/register" button would suffice to restrict their ability to navigate.

**Comment by o5k** [comment]
I mean, making an anonymous account isn't particularly hard...
