### ISSUE TITLE
A Quick Improvement For Specating 3+ Player Games

### ISSUE THREAD

**Issue by GrubbsGaben** [tetrio/issues#362]
### Is your feature request related to a problem? Please describe.
I think so, cause you can barely see who is the avaliable gamer to choose for spectate

### Describe the solution you'd like
**Hovering** the mouse **over** on the right side, (where you can see others, and click on them to spectate them) their names **gets bigger**, so you dont have to click on them to know who that random person is, cause you can read the name easily if its bigger.

### Describe alternatives you've considered
 *( [ZaptorZap said i should delete this part](https://discordapp.com/channels/673303546107658242/673303546564968566/719431057983799296) )*

### Additional context

![spect](https://user-images.githubusercontent.com/60812485/83996528-b2331900-a95c-11ea-8cee-761a632e1421.jpg)

**Comment by o5k** [comment]
Added in next patch.
