### ISSUE TITLE
Sound bug report

### ISSUE THREAD

**Issue by BlueVen0m** [tetrio/issues#363]
### Describe the bug/issue
(I'm french , sorry for my bad english)
When i start the game, no sound is heard
I looked in the Windows sound mixer if the game was not at 0%, and the game doesn't appear.
I've try to restart the game , and my PC but nothing changes

In the browser game , the sound work

### Screenshots
![Screen](https://user-images.githubusercontent.com/43078827/84062834-45ea0100-a9c0-11ea-88f3-eac7a9f65e40.PNG)

### Your setup
 - **OS and version**: Last version of Windows10 (64bit)
 - **Prossessor** : AMD A4-5000 APU with Radeon

**Comment by o5k** [comment]
Do you have a console log?
