### ISSUE TITLE
Feature request for Solo: Clear Garbage Mode

### ISSUE THREAD

**Issue by Icerite** [tetrio/issues#371]
I'd like to request a new feature for Solo play.

The requested mode (as the title says) is a garbage clear mode which we have to clear a certain amount of garbages. It's exactly like the Cheese Race in Jstris or Driller in TetrisOnlinePoland. Here are two screenshots from TetrisOnlinePoland:
![tetris_2020-06-13_17-18-40](https://user-images.githubusercontent.com/63966304/84572434-32f97700-ad9a-11ea-96b8-9646b63c346a.png)
![tetris_2020-06-13_17-18-46](https://user-images.githubusercontent.com/63966304/84572435-342aa400-ad9a-11ea-864e-e3b659ba3d43.png)
For the first example, you can choose, which difficulty you want to play and how many lines of garbages you want to clear. The harder the difficulty is, the faster new garbage lines appear as shown on the second screenshot.

While implementing this mode, you can do a leaderboard of who's the fastest clearing 100 lines of garbage or such. Pretty sure this will give an incentive to the players of who's able to clear the fastest and to improve the time.

The reason why I want this implementation is because I enjoy playing this mode and clearing garbages. Sometimes I use this mode to practice cleaning the board more efficient on Jstris or TOP. It's just kinda boring to play the mode in Jstris without any kind of music and my eyes kinda start hurting rather fast if I'm playing Driller on TOP.

Overall I think it's a fun mode which also helps players improving to clear garbage more efficiently during either ranked or quick play after misdropping tetriminos.

**Comment by LayneTheEpic** [comment]
See #224

**Comment by o5k** [comment]
This is implemented by Zen. A standalone cheese mode may come at some point, but no promises.
