### ISSUE TITLE
Twitch Live Link are broken when Twitch display name is set

### ISSUE THREAD

**Issue by eai04191** [tetrio/issues#377]
### Describe the bug/issue
The Tetra Channel's Twitch Live link will use that in the URL if the streamer has set a display name on Twitch. However, the link destination does not exist because it is not the channel ID.

### Reproducing
1. Go to Tetra Channel
2. Find the streamer live with the display name.
3. Click the link.
4. The link does not exist

### Expected behavior
Streamer's Twitch channel opens

### Screenshots
![2020-06-21_10-52-46_TETR IO](https://user-images.githubusercontent.com/3516343/85215033-d572b500-b3ad-11ea-8861-f27c16f095f9.png)
![2020-06-21_10-52-54_TETR IO](https://user-images.githubusercontent.com/3516343/85215035-d86da580-b3ad-11ea-9e9b-fff86c7e4e33.png)

The display name of this streamer is `샘물남`. but the channel ID is `zzzzydh`.
Therefore, the link must be `https://www.twitch.tv/zzzzydh`.

**Comment by o5k** [comment]
Fixed in next patch.
