### ISSUE TITLE
need 32-bit version for tetr.io desktop

### ISSUE THREAD

**Issue by vyishere** [tetrio/issues#378]
tetr.io desktop version only support 64-bit software so i want you to improve tetr.io that support 32-bit software and help me and other players who also running 32-bit can play the game

**Comment by micwoj92** [comment]
just use browser lol

**Comment by o5k** [comment]
As of now, browser fills the compatibility gaps that the Desktop client offers. I may consider adding 32-bit later, but doubling the amount of builds for a very small percentage of the playerbase (who will get bad performance either way) is iffy.
