### ISSUE TITLE
Nationality

### ISSUE THREAD

**Issue by giffacebookmeow** [tetrio/issues#379]
I see that Tetris has communities around the world, so I think this game should have national flags for each player. (sorry i'm not fluent in english)

![Annotation 2020-06-21 111416](https://user-images.githubusercontent.com/42277250/85216581-66e32680-b3b0-11ea-9b37-a3f3386f6f72.png)
![Annotation 2020-06-21 111311](https://user-images.githubusercontent.com/42277250/85216582-69458080-b3b0-11ea-98b3-eacc87320477.png)

**Comment by o5k** [comment]
Added in 4.1.0!
