### ISSUE TITLE
DAS continuous use blocker delay

### ISSUE THREAD

**Issue by farteryhr** [tetrio/issues#380]
when the ARR (ARInterval to be stricter) is near 0, and for those who don't always strictly release L/R button **before** pressing harddrop/rotate, the piece is moved to the side when it's not expected to. i think this is the source of so-called slippery.

### Describe the solution you'd like
add another type of DAS delay and state (usually to be set at some value around just 1f, 16ms), which is entered when some effecting L/R button is pushed, but the DAS is blocked, then, harddrop/rotate button is pushed. after that delay, the repeating phase will be entered again.

### Additional context
somehow this is the opposite of "synchro" feature of what TGM players proposed. but if the program flow is carefully designed such that, for example, when this delay is set to 0, it means the move check is instantly performed before gravity, both features may exist and can be chosen by the player with this setting.

in frame based engine, depending on the order of moves processed and the exhautiveness of "instant" check (imagine the possible variants of outcome for instant DAS against instant gravity with 0 lock delay 0 spawn delay), there may be 0 or 1 frame delay here, and it affects the feeling of controlling.

**Comment by o5k** [comment]
What games do this?

**Comment by farteryhr** [comment]
Cultris II has a bit of it. maybe 1 or 2 frames, easily observable.

in tetr.js (maybe also nullpomino, TGM or some other frame based game emphasizing 20G experience), there's an order of intra-frame processing: hold, rotate, move, drop. in tetr.js, after dropping, the next piece instantly spawns(real 0-frame ARE), gravity (only if 20G) will be processed (die-in-one-frame if 20G gravity 0 ARE 0 lock delay), but 20G DAS will not (only the first piece DAS's). once the move button is relesed before the next frame kicks in, the next piece won't shift. that may be considered equivalance of 1 frame "das blocker delay".

a third example with a long story.

in old times, a tetris game in "QQ game hall" [huopin tetris](https://harddrop.com/forums/index.php?showtopic=4727) had been popular. it's a pure event based game, and there is no DAS, but pro players have made external DAS emulator. in some of the latest version, if set to infinite ARR, being treated specially, it could be described "instant repeated move just triggers one-shot, then nothing will happen even if the button is still pushed". or say it enters infinite delay (in the framework proposed by me)

many expert players have got used to DAS with this detail. if they do "rotate, das-to-wall", they make sure das kicks in before they push rotate button; but also, they're used to not releasing moving button before pushing rotate button on "das-to-wall, rotate (so that the piece leaves the wall)" cases. and they don't reuse das across pieces at all.

to note that this was intended, because when set to finite ARR (up to 10000/min (~3G under 60fps, can be used as almost infinite)), repetition just smoothly continues at least after any rotation (i use this setting when i play it). but i don't remember if harddrop interrupts DAS. more likely it always does.

i have implemented an option "DAS Cut" just to replicate this behavior, for introducing a big huopin expert to play my tetr.js.

**Comment by farteryhr** [comment]
would you please implement this any time soon? this is the the real cause of so-called "slippery" issue since many who still complain about it are 0-ARR users, (not the one made into diagram that's related to non-0 ARR, imo. but it is a valuable fix too), if it makes sense to emphasize.

**Comment by bberna** [comment]
I admit I would really like this to be implemented. I guess I can just git gut instead, but it seems jstris has it, so it would be nice to have that on tetr.io too.

**Comment by o5k** [comment]
so to get this straight, the concept is basically that once you drop/rotate a piece, any _ongoing_ DAS will pause for a (customizeable) amount of frames? Is this correct?

**Comment by farteryhr** [comment]
yes this is one of the reasonable ways to implement it (i think more specifically "ongoing DAS being blocked", as making the matrix to sway), and should work fine. if the details were worked out correctly, the "synchro" behavior can also be toggled by this.

**Comment by o5k** [comment]
Hmmm, I'm playing around with it now, I do feel it feels a bit better, although I don't 0ARR so I can't particularly tell.

What should the default cut time be? Right now im in between 0F (off, so, as it was before) and 1F

**Comment by o5k** [comment]
Gonna stick with 0 for now and let people enable it by choice, if people like it I may made 1 or 2F default

**Comment by farteryhr** [comment]
just had a try, it feels nice!
a further suggestion is, the "prevent accidental hard drop" is also a little delay working in a similar way, let it be specified too. since they're both very short, they may be merged into a single row.
even more, along with the SDF, which i think nobody will use a very low value and really be interested in the "factor" way (instead of fixed speed) (if you're interested, softdrop can also have an initial delay. misamino client supports this.), that only need to range from maybe 30Hz (slow enough!) to 60Hz to 120, 600, infinity. if you liked all 4 of them, then two rows.

btbtw.. about the "cancel das when changing direction".....
at first i thought it was the "push-left push-right wait release-right" case...
after some try i think i've got it's just the "push-left push-right" case. hope i didn't get it wrong.
but i think it's strange (definition-wise). if the button of the opposite direction is pushed the moment before the former direction's das kicks in, one get opposite das equivalently arbitrarily close to 0, but after it kicks in, another full das is to be waited. in some sense (the farter's perfectionist sense™️), you might need to introduce another "minimal das-after-changing-direction" value and also "gradually recovering dynamic reverse das" system to make it "complete™️".
but also, cross-piece behavior, it might interfere with DCD. consider the "push-left hard-drop (before/after the moment the das has a DCD-length left)push-right" "push-left push-right (same branches as above) hard-drop" cases, how will the das count....?
