### ISSUE TITLE
Connection Error: Transport Error

### ISSUE THREAD

**Issue by hexagonforce** [tetrio/issues#381]
### Describe the bug/issue
Cannot join multiplayer even with working internet connection

### Reproducing
1. Click "JOIN" in the TETR.IO splash
2. Click on Multiplayer
3. Then there is a popup with a message that says 
```
a connection error has occured and the connection was closed unexpectedly. 
check your internet connection or report this issue
REASON: transport error
```

### Expected behavior
User is able to join the multiplayer server

### Your setup
 - Debian Linux Stretch
 - Firefox ESR 68.9.0

### Additional context
```
Firefox can’t establish a connection to the server at wss://tetr.io/socket.io/?EIO=3&transport=websocket&sid=d984YD7lE2nwMbBbADgN. socket.io.js:8:6092
The connection to wss://tetr.io/socket.io/?EIO=3&transport=websocket&sid=d984YD7lE2nwMbBbADgN was interrupted while the page was loading. socket.io.js:8:6092
```

**Comment by 1lann** [comment]
A screenshot of the network tab of developer tools in your browser immediately after the error message comes up would probably be helpful. It should look something like this:
![image](https://user-images.githubusercontent.com/804919/85364914-19aea400-b4d9-11ea-9c78-0cefff03b9a2.png)

Also are you on a special type of network such as at a school, workplace, or public place? Are you aware of any notable firewalls? Are you using non-personal computer equipment/software? Are you able to view the multiplayer menu when using a VPN/proxy?

**Comment by hexagonforce** [comment]
![2020-06-23-152849_1920x1080_scrot](https://user-images.githubusercontent.com/24777815/85373986-a5badd00-b566-11ea-9909-a3836b3c9d31.png)
