### ISSUE TITLE
Zen mode display changes do not persist between games

### ISSUE THREAD

**Issue by unascribed** [tetrio/issues#384]
### Describe the bug/issue
If you set the Zen sidebar's display to one of the options, e.g. "speed", then forfeit and start Zen again, there will be no counters until you click any of the options again.

### Reproducing
1. Enter Zen mode
2. Select a display option in the Zen sidebar
3. Forfeit the game
4. Return to Zen mode; observe there are no displays, despite one being selected on the sidebar

### Expected behavior
The selected display should appear when starting the game without changes.

### Screenshots
![image](https://user-images.githubusercontent.com/6185037/85335756-5efbb300-b492-11ea-8028-e051a6292aa7.png)

### Your setup
 - **OS and version**: KDE neon (like Kubuntu) 18.04
 - **Browser and version**: Chromium 83.0.4103.61, with options `--disable-gpu-sandbox --enable-webgl2-compute-context --enable-high-resolution-time --autoplay-policy=no-user-gesture-required --disable-background-timer-throttling --disable-renderer-backgrounding --gamepad-polling-interval=8 --disable-blink-features=PreloadMediaEngagementData,AutoplayIgnoreWebAudio,MediaEngagementBypassAutoplayPolicies`, in app mode

### Additional context
```
index.js:163 Up to date. Local version 4.0.0-production | Commit dbce324 (6/22/2020, 1:20:56 PM) | Server cycle URDlCVBiS | Build yKC21RVjJ (6/22/2020, 1:21:10 PM) | PID 4384
index.js:163 PixiJS 5.2.2 - WebGL 2
index.js:163 - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/83.0.4103.61 Chrome/83.0.4103.61 Safari/537.36 -CPU: 16-coreMemory: ~8 GBConnection: 1.7 Mbps, 200ms RTT [4g]
index.js:163 Renderer: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.33.0, 5.3.0-59-generic, LLVM 9.0.0)
```

**Comment by o5k** [comment]
Hotfixed, F5 for the fix.

**Comment by unascribed** [comment]
That was fast! Thanks for all your work on this game!
