### ISSUE TITLE
Unable to spectate games after leaving zenmode

### ISSUE THREAD

**Issue by rmohan91** [tetrio/issues#385]
### Describe the bug/issue
When I click on the Zenmode icon during quick play and I subsequently exit zenmode I am no longer able to spectate other players. When I asked in the lobby, other people were also experiencing this same issue (not sure if it was intended). 

### Reproducing
1. Go to quick play
2. Click on zen mode
3. Click on "zen mode while waiting" to exit zenmode
4. Screen looks like the initial start screen when first joining the lobby (no spectate).

### Expected behavior
I expected to still be able to spectate other players after exiting. 

### Your setup
Windows 10
Desktop (Ubuntu 18.04)

**Comment by o5k** [comment]
Once you hit Zen, you can no longer spectate the match you were in, sorry.

**Comment by rmohan91** [comment]
Ah I wasn't sure if it was intended, thanks for clarifying. Hope you keep working on tetrio, really appreciate it!
