### ISSUE TITLE
Zen Mode Menu Keybinds Don't Work

### ISSUE THREAD

**Issue by m4r1o148** [tetrio/issues#387]
### Describe the bug/issue
Keyboard controls do not work on the zen mode screen.

### Reproducing
1. At the main menu, go to the "Solo" page.
2. Click on "Zen."
3. Try to exit the screen or select "Start" using the menu control keybindings.

### Expected behavior
Obviously, you should be able to control the menu with your keyboard on this screen, but it seems that the screen's functionality was forgotten.

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Browser Client

**Comment by o5k** [comment]
Fixed in recent patches.
