### ISSUE TITLE
Zen Mode button is enabled while in the multiplayer countdown.

### ISSUE THREAD

**Issue by Lustyn** [tetrio/issues#388]
### Describe the bug/issue
It is possible to start a Zen game while in the game countdown.

### Reproducing
1. Start a multiplayer game
2. Quickly click on the Zen button under the timer at the bottom
3. You are now in Zen and multiplayer at the same time, both mirroring your keypresses.

### Expected behavior
Zen button should be disabled while countdown is going on, but also better state management (two games of TETR.IO at once should probably not be possible at all.)

### Screenshots
![a game of zen open while in a multi](https://justyn.is/cool/7wf5.png)
![a game of zen open while in the game end screen](https://justyn.is/cool/kjIe.png)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Firefox 77.0.1

### Additional context
It is also possible to click the Zen button after you die in multi and then proceed to play 2 games of Zen at once. This could probably introduce even worse bugs.

**Comment by o5k** [comment]
Fixed in next patch.
