### ISSUE TITLE
TETR.IO REQUIRES WEBGL

### ISSUE THREAD

**Issue by Kouji25** [tetrio/issues#390]
![PROB](https://user-images.githubusercontent.com/67305408/85362112-3934e380-b550-11ea-9899-2963e5d99ae0.png)

This always popup when I open tetr.io, it also crashes the app and my whole laptop.
I'm using the desktop version

**Comment by ZaptorZap** [comment]
Hey there, if you're using chrome could you head to `chrome://gpu/ ` (paste that into the url bar) and screenshot what it says under "**WebGL**"?

**Comment by Kouji25** [comment]
> Hey there, if you're using chrome could you head to `chrome://gpu/ ` (paste that into the url bar) and screenshot what it says under "**WebGL**"?

I'm using the desktop version
This doesn't happen before

**Comment by ZaptorZap** [comment]
Tried simply restarting the computer yet?

**Comment by Kouji25** [comment]
I already tried it and it still didn't work

**Comment by o5k** [comment]
What are your specs?

**Comment by Kouji25** [comment]
> What are your specs?

![Capture](https://user-images.githubusercontent.com/67305408/85672987-088eae80-b6f6-11ea-8b1b-4a77a466fc8b.JPG)

**Comment by alete89** [comment]
Experiencing this on ubuntu 20.04, Google Chrome 84.0.4147.105

![image](https://user-images.githubusercontent.com/4999277/89132686-50220a80-d4ec-11ea-8f0a-f922f495838c.png)

**Comment by PastMoments** [comment]
I am also experiencing this exact issue with the desktop client.

**Comment by beastelassi** [comment]
I solved this on Windows by installing a driver for my graphic device, instead of using the included "Microsoft Basic Display Adapter".

This Issue was only happening on Google Chrome, and I could access the website fine using Mozilla Firefox.

**Comment by apes0** [comment]
Experiencing this issue as well on the desktop client *(OS: Ubuntu 20.04.2)*

**Comment by CATboardBETA** [comment]
Still experiencing this, client windows. Always worked in the past.

**Comment by CATboardBETA** [comment]
Attempted @beastelassi 's solution, didn't work.
