### ISSUE TITLE
Tetris table rotated 45 degrees

### ISSUE THREAD

**Issue by mikota** [tetrio/issues#392]
### Describe the bug/issue
The tetris table rotated 45 degrees, and stayed like that

### Reproducing
Happened to me after the transition from level 2 to level 3 in zen mode

### Expected behavior
not this lmao

### Screenshots
https://imgur.com/a/v7vdYyW

### Your setup
 - **OS and version**: [Windows 10]
 - **Browser and version**: [Chrome 83.0.4103.116]

### Additional info
Bug went away after closing zen and re-entering it.

**Comment by UniQMG522** [comment]
Also noticed this, particularly while lagging.

**Comment by o5k** [comment]
Hotifxed.
