### ISSUE TITLE
Access Zen mode from the Tetra League queue

### ISSUE THREAD

**Issue by Denton-L** [tetrio/issues#393]
### Is your feature request related to a problem? Please describe.
I would like to be able to access Zen mode while I'm queuing for a league match, similar to how I can use Zen mode while waiting for a quickplay game. I know that I can back out and access it by backing out and entering the solo play menu but that feels like too many clicks.

### Describe the solution you'd like
A Zen button, similar to the the button in that's available for quickplay to access Zen mode while queuing for a league match.

**Comment by o5k** [comment]
> too many clicks

Still better than awkwardly fumbling the button into the UI somewhere.
