### ISSUE TITLE
Zen mode lingering B2B text on top out / reset

### ISSUE THREAD

**Issue by iitalics** [tetrio/issues#394]
### Describe the bug/issue

In Zen mode, the B2B indicator text lingers after you reset the game, displaying your previous B2B counter even though it is internally reset.

### Reproducing

1. Begin Zen mode.
2. Increase the B2B counter by getting a few quads or T-spins.
3. Top-out or reset the game manually (without breaking B2B).
4. Get a quad or T-spin on an empty board. Notice that the old B2B indicator is still present.
5. Get another quad or T-spin. Notice that the indicator now shows "B2B x1".

### Expected behavior

Since the B2B counter is internally reset when you top out or reset, it should clear the B2B indicator, in the same manner that breaking B2B clears it.

**Comment by o5k** [comment]
Hotfixed.
