### ISSUE TITLE
Disconnects

### ISSUE THREAD

**Issue by TetrioQSK** [tetrio/issues#395]
### Describe the bug/issue
Servers are bad :(

### Reproducing
1. Go to Online matches
2. Play games
3. Wait for servers to kick you out b/c they're garbage after 4.0.0

### Expected behavior
Not this

### Screenshots
sorry dont have one :(
### Your setup
 - **OS and version**: Mac OS 1.10.5
 - **Browser and version**: Chrome

### Additional context
disconnects while doing tetra league make me sad :( at least fix those...

**Comment by TetrioQSK** [comment]
this may seem like a joke, but it is 100% real...

**Comment by o5k** [comment]
what's the disconnect message..?
