### ISSUE TITLE
You Can Affect Yourself With Chat Commands

### ISSUE THREAD

**Issue by ZaptorZap** [tetrio/issues#398]
### Describe the bug/issue
You can ignore, and kick yourself, with chat commands.
### Reproducing
1. Simply join a room with chat available (custom rooms, quick play, presumably tetra league)
2. Type in `/ignore <player name>` (in this case, it'd be zaptor) or `/kick <player name>`
3. See the effects via typing in chat and not seeing your own messages, or being kicked by the room owner (in this case the room owner is yourself)
### Screenshots
![05TNUP3c4s](https://user-images.githubusercontent.com/64891705/85679342-dc087180-b6b8-11ea-922a-67a2d3defa93.gif)
(ignoring yourself)
![BiGbuKNVOv](https://user-images.githubusercontent.com/64891705/85679384-e4f94300-b6b8-11ea-9d22-ca171610b1c1.gif)
(kicking yourself)
### Your setup
 - **OS and version**: Windows 10, 1903 
 - **Browser and version**: Firefox 77.0.1

**Comment by o5k** [comment]
Fixed in next patch.
