### ISSUE TITLE
Free play while waiting for next game

### ISSUE THREAD

**Issue by alex-ong** [tetrio/issues#40]
### Is your feature request related to a problem? Please describe.
Lots of players are trash, and die early in big rooms. They need something to do. This is especially good for newer/trasher players who would just leave immediately.

### Describe the solution you'd like
Ability to play 40L or Dig.

### Describe alternatives you've considered
A few buttons to choose mode while spectating

**Comment by Wirtualnosc** [comment]
I think games might end way earlier than you'd be able to finish either 40L or Dig, but some sort of free play (like how it was done in Tetris Friends in Arena mode) would definitely be nice.

**Comment by alex-ong** [comment]
> I think games might end way earlier than you'd be able to finish either 40L

Right, but jstris does 40L and i often finish a game (including 1-2 restarts) while waiting for next game. This is with just a room of 6. Either way 40L is essentially freeplay with the bonus that you could potentially get a record. On top of that, the nice thing about tetr.io is that there is a 30 second warning before match starts so you could (depending on implementation) choose between bailing 40L or playing the game.

I think that dig mode would also be good. Blitz i agree is probably "wrong" since there's no way you could play a 2 minute game.

**Comment by o5k** [comment]
Closed in 4.0.0!
