### ISSUE TITLE
Supersampling/'Render at a high resolution' option, or a general increase of internal texture resolution

### ISSUE THREAD

**Issue by UniQMG522** [tetrio/issues#402]
Supersampling/'Render at a high resolution' option, or a general increase of internal texture resolution. Mostly a request to try and deal with the poor handling of pixel-imperfect block skins. I tried poking around and increasing the res on minos manually but its a lot more complicated than I can deal with.

This isn't directly useful to the unmodded base game right now, but in the future once official custom skins are released it may improve the appearance of skins with fine details. Currently, you can zoom out as a 'workaround' to increase the resolution.

Example:

![](http://tetrio.team2xh.net/images/skins/pixel_ratio.png)

**Comment by Tenchi2xh** [comment]
I think the main issue is that the renderer downscales the images a lot when generating the gl textures. The ingame resolution right now is already high enough and should be able to display nice minos, and doesn't need to be increased.

Increasing the resolution would actually decrease performance, whereas increasing the textures' resolution (i.e. downscaling less) wouldn't hinder framerate at all (just take a tiny bit more video memory)

**Comment by Tenchi2xh** [comment]
Bumpy

**Comment by UniQMG522** [comment]
Still an issue, compare default behavior at 240% zoom vs tetrio plus advanced skin loading (which bypasses the downscaled canvas rasterization thing and passes the texture directly to pixijs to be used as an atlas) with the default skin at 240%:

Default:
![firefox_NOIwH5yEih](https://user-images.githubusercontent.com/48872143/97347848-9b795a00-184a-11eb-9ba1-b375311a4b06.png)

Tetrio Plus:
![firefox_AYNmceBlfj](https://user-images.githubusercontent.com/48872143/97347851-9d431d80-184a-11eb-9ef0-e2baca7276eb.png)

**Comment by UniQMG522** [comment]
bump

**Comment by o5k** [comment]
Implemented in to-be-merged branch, closing as this issue is confirmed coming
