### ISSUE TITLE
Music Room menu acting unusual

### ISSUE THREAD

**Issue by xXRT5** [tetrio/issues#404]
### Describe the bug/issue
Music Room menu glitching out

### Reproducing
1. Go to 'About'
2. Click on 'Music Room'
3. See error

### Expected behavior
List not acting erratically

### Screenshots
<img width="2651" alt="Screen Shot 2020-06-28 at 9 30 43 AM" src="https://user-images.githubusercontent.com/67547519/85949013-1c1e5d00-b922-11ea-9fba-9fc3be539bdb.png">

### Your setup
MacOS Big Sur Developer Beta (11)
 Chrome 83 (MacOS)

### Additional context
Log is listed here -> [tetr.io-1593351285556.log](https://github.com/tetrio/issues/files/4842332/tetr.io-1593351285556.log)

**Comment by o5k** [comment]
Looks like a GPU/browser issue, and not something I can fix :/
