### ISSUE TITLE
DAS cancel and others

### ISSUE THREAD

**Issue by macyayaya** [tetrio/issues#406]
Just some features:

- DAS cancel, where the DAS momentum is canceled if the direction holding changed
- statue system in the room (AFK, available, etc.)
- RANK UP/DOWN hint, though maybe not possible since I don't know whether the points awarded/lost is calculated after the match or not

**Comment by alex-ong** [comment]
DAS cancellation is at odds with double-dassing (keeping both directions charged at all times). I'm not sure what is "better", but from my experience, having separate counters for both and only cancelling on key-up has quite a few advantages, especially in slower das games like PPT.

Also the way DAS is currently implemented, the auto-shift is determiend by last keypress, so it should already work as intended.
E.g.
assuming 100ms charging time and instant.

Without cancellation (current)
```
Hold left (100ms) 
Keeping holding left, hold right
Harddrop.
Release right
harddrop
```
will result in one piece 1 away from wall then next peice against left wall, without losing DAS.

With Cancellation (proposed)
```
Hold left(100ms)
Keeping holding left, hold right
harddrop.
Release right
Harddrop
```
Will result in one piece 1 away from wall, then next piece in centre

**Comment by o5k** [comment]
Das is a duplicate of #326 

> though maybe not possible since I don't know whether the points awarded/lost is calculated after the match or not

It is calculated after.

**Comment by LayneTheEpic** [comment]
Besides, in what scenario would you be still holding left (in alex's example)?
