### ISSUE TITLE
The game doesn't play sound effect anymore

### ISSUE THREAD

**Issue by eight04** [tetrio/issues#408]
### Describe the bug/issue
The game doesn't play sound effect anymore. Including UI and in-game.

Background music works fine. Including lobby and in-game. Music also mutes when I switch to another tab.

### Reproducing
1. Go to tetr.io and login.
2. Try to hover/click buttons or even start a game.

### Expected behavior
Play sound effect.

### Screenshots
![image](https://user-images.githubusercontent.com/1324510/86267036-aacbfc00-bbf8-11ea-9320-24ce0ac54e80.png)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Firefox Developer Edition 79.0b2

### Additional context
Console
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ bootstrap.js:23:10
TETR.IO bootstrap.js line 60 > eval:7291:7576
WebGL context was lost. bootstrap.js line 60 > eval:11:33209
Please be careful when pasting anything in the console. Attackers may be out to steal your login information. bootstrap.js line 60 > eval:7291:7855
Up to date. Local version 4.0.2-production | Commit 6fe42a1 (7/1/2020, 9:17:10 AM) | Server cycle kRKQtqNZV | Build jPKwxt2kn (7/1/2020, 9:24:20 AM) | PID 20951 bootstrap.js line 60 > eval:7291:15432
PixiJS 5.2.2 - WebGL 2 bootstrap.js line 60 > eval:7291:300159
- Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0 -
CPU: 4-core
Memory: <unknown>
Connection: <unknown> bootstrap.js line 60 > eval:7291:301441
Renderer: ANGLE (NVIDIA GeForce 820M Direct3D11 vs_5_0 ps_5_0)
```

This might be a Firefox bug. I can't reproduce this issue on Chrome.

**Comment by o5k** [comment]
Try CTRL+F5?

**Comment by eight04** [comment]
It works now with 79.0b4. Still don't know what is the cause.
