### ISSUE TITLE
Keyboard inputs not functioning bug

### ISSUE THREAD

**Issue by Bigblue23456** [tetrio/issues#410]
### Describe the bug/issue
Keyboard inputs are not going through properly at all. I have made sure to go as far as to even switch out different keyboards and the results are the same. My keyboard does work outside of Tetrio on the same system.

### Reproducing
1. Go to Tetr.io
2. Click on "Log in"
3. Click on "Start"
4. Click on "Solo"
5. Click on "Start"
6. Endeavor to perform playing with keyboard controls to later realize that they do not function

### Expected behavior
I expected for my inputs to appear normally as when playing Tetrio.

### Screenshots
N/A

### Your setup
 Windows 10
 Firefox 77.0.1

### Additional context
N/A

**Comment by o5k** [comment]
What does your config look like?

**Comment by Bigblue23456** [comment]
Oh, didn't even know there was a config section.
The game must of automatically put me in some sort of custom configs after some update with nothing set to controls. 
The game is now working for me, my apologizes for noticing the config tab.
