### ISSUE TITLE
3p to 1v1 layout transition is distracting

### ISSUE THREAD

**Issue by alex-ong** [tetrio/issues#411]
### Is your feature request related to a problem? Please describe.
When transitioning from 3p to 2p, the field moves, which is distracting. It is quite a hard thing for my brain to deal with.
Inb4 git gud.

### Describe the solution you'd like
Make the 3p+ layout have the primary field on the left (same as 1v1), then expand the 2nd player as usual.

**Comment by IceDynamix** [comment]
there an option called "show duels side-by-side" already, which can be found under gameplay. it will keep the board centered at all times with no movement while transitioning, if disabled. it's not the left board layout, but it removes the movement.

**Comment by alex-ong** [comment]
Thanks for the comment; i wasn't clear in the my request.
Unticking "show duels side by side" makes your board centered, but now in 1v1 you can't see your opponents field, which is pretty important for knowing when to time spikes.

Ticking "show duels side by side" makes your board centered for 3p and left/right for 1v1, and the transition is annoying. I am suggesting to get the best of both worlds by showing your board on the left for 3p+, and then transitioning the last player from 3p+ (when others are eliminated) to the right hand side.

Hope I cleared it up.

**Comment by o5k** [comment]
how would this work when in a 30+ player room, when players are shown on both sides?

**Comment by alex-ong** [comment]
Oh crap i've never been in a 30+ player room. Obviously having 60+ players on right side instead of 30 on each is way less aesthetic; but maybe moving to the 2p layout when you hit 30~ instead of 2? But that has its own implications of course; since the current behavior (moving board when its 2p remaining) signifies you've got one opponent left which is quite dramatic and nice. I can't think of a neat solution to >30 player rooms ;(
