### ISSUE TITLE
Tetr.io desktop app not launch

### ISSUE THREAD

**Issue by benz-phan** [tetrio/issues#413]
### Describe the bug/issue
When i click it, it didn't launch the cilent.
### Reproducing
1. Launch it.

### Expected behavior
Launch the app

### Screenshots
http://g.recordit.co/r8xKmWRpNM.gif

### Your setup
 - **OS and version**: Window 10 insider preview 200605-1502
 - **Browser and version**: Tetr.io desktop cilent ver. 4.0.0

### Additional context
It work a while ago. no idea why this time it never launch.

**Comment by o5k** [comment]
try reinstalling?

**Comment by benz-phan** [comment]
It still doesn't load. It maybe a bug with my pc maybe?

**Comment by tilda** [comment]
Is there anything in `%appdata%\TETR.IO\logs`? I haven't had this problem, but there might be a file in there that could help solve this issue

**Comment by benz-phan** [comment]
> Is there anything in `%appdata%\TETR.IO\logs`? I haven't had this problem, but there might be a file in there that could help solve this issue

Actually, I can't find the logs folders. So TETR.IO was never install?

**Comment by benz-phan** [comment]
Hey @o5k 

IT LANCHED! Finally, after i run Program Compatibility Troubleshooter. It said to run Tetr.io in compatibility mode. Everything is working fine now.
