### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Lobster-Hat** [tetrio/issues#415]
when I try to login into the desktop version of tetr.io I get logged out instantly with the message "You were logged out. Please log in again".  This is for the the desktop version but has happened to me on the browser version which was much easier to fix (close, reopen tab) but doesn't for desktop
![image](https://user-images.githubusercontent.com/64714884/87091584-0861e780-c28e-11ea-98f0-89061be6452c.png)

Also when I took the screenshot the login thing isn't loading anymore
Happens when you press enter twice while trying to login 
![image](https://user-images.githubusercontent.com/64714884/87091226-6d690d80-c28d-11ea-825d-4c683ea82381.png)

I haven't restarted my computer yet. But that would be pretty bonkers if you ask me, I have too much "Homework" tabs open and I would much prefer I didn't need to randomly restart my computer to play I game that I enjoy so much. I'm also running the Windows 10 version if that helps.

**Comment by Lobster-Hat** [comment]
I just looked at benz-phan review and I think I just got flexed on. 
https://github.com/tetrio/issues/issues/413
so much better than mine I think.

**Comment by o5k** [comment]
Hotfixed - hit F5
