### ISSUE TITLE
Login Glitch...?

### ISSUE THREAD

**Issue by ZmanAce** [tetrio/issues#419]
### Describing the bug/issue
I tried to log in upon booting up the desktop application for TETR.IO (second boot up). It went to asking for my account's password immediately, but when I entered the password for my account (Account is ZMANACE123), it gives the notification "YOU WERE LOGGED OUT. PLEASE LOG IN AGAIN!" So I tried again, and again, and again. Same message every time.

### Reproducing
1. Boot up "TETR.IO" on your desktop
2. Enter account password
3. Look at bottom-right corner to see error

### Expected behavior
Expected to be logged in, having access to the game and contents

### Manuel Fix?
While writing this bug, I found that by pressing F5, you can login successfully!

### How to "Manuel Fix"
1. Reproduce the original error 
2. Press F5 on "Enter Password" screen
3. Login as normal. That's it.

**Comment by ZmanAce** [comment]
Tohny123 ran into the same issue, just so you know.

**Comment by Shadowtail117** [comment]
I can reproduce this as well. I always use desktop, have it skip the login screen. It logged me out for no reason and gives the same error as above when trying to log back in.

**Comment by tilda** [comment]
Can repro on latest version. The fix works as well, thanks

**Comment by ZmanAce** [comment]
No problem.

**Comment by o5k** [comment]
DUplicate of #415 - hit F5 on this screen to fix the issue
