### ISSUE TITLE
Lost TR For Opponent Disconnecting

### ISSUE THREAD

**Issue by adcanada** [tetrio/issues#422]
So I was playing some tetra league as an A- and got matched with a B+. at the start of the game, I said 'glhf' and he said 'matchmaking kek' and then the connection dropped (I got put back to the main menu). I have a very stable connection, and this hasn't happened before, I figured that he disconnected and it counted as a win for me. However, upon logging back in, I had lost TR (I was at about 12100, I got set to 11400). I know that this is only a minor inconvience, and I could get back to where I was quite quickly, but I would like to make sure that this doesn't happen to me or others again.

**Comment by o5k** [comment]
nope, that was your internet, not theirs
