### ISSUE TITLE
Bug Report 7/10/2020

### ISSUE THREAD

**Issue by bcan1204** [tetrio/issues#424]
### Describe the bug/issue
When logging into the Desktop Version of Tetrio I am prompted to input my username and password, entered correctly I get an error message saying "You were logged out"

### Reproducing
1. Go to 'Tetrio Desktop'
2. Click on 'Login'
3. Input Username and Password

### Expected behavior
To successfully log in

### Screenshots
![image](https://user-images.githubusercontent.com/48307660/87187842-d1a2c600-c2bb-11ea-8de4-5b0fdb6dae7d.png)

### Your setup
 - **OS and version**: [e.g. Windows 7]
Windows 10
 - **Browser and version**: [e.g. Chrome 76]

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)
I can log in on the browser to make sure my password is right but still can't log in on desktop

**Comment by o5k** [comment]
Hit F5. 

**READ THE CLOSED ISSUES BEFORE REPORTING AN ISSUE**
