### ISSUE TITLE
bootstrap.js error when the service worker fails to install

### ISSUE THREAD

**Issue by UniQMG522** [tetrio/issues#426]
### Checklist (issue will be disregarded & closed if incomplete!)

- [✓] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [✓] I am using the **newest version** of TETR.IO.
- [✓] I know **how to reproduce the issue**.
- [✓] I am using a **supported browser** or the Desktop Client.
- [❌] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [✓] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
`ReferenceError: arguments is not defined` in a catch handler when installing the service worker from `bootstrap.js` fails. Only function context is an arrow function, so no `arguments` exists.

This is only reproducible with tetrioplus installed on desktop client (or by manually blocking the request from devtools) to block the service worker, but is a bug in tetrio code that might cause issues later.

### Reproducing
1. Install tetrio plus on desktop
2. Ensure the 'Bypass bootstrapper' option is disabled
3. Attempt to launch the game

Alternatively without tetrio plus (a bit convoluted):
1. Unregister the existing service worker
2. Open devtools, `fetch('sw.js')` to list the request in the network panel then from the network panel block the request
3. Refresh the page

### Expected behavior
The error about not being able to load the service worker is logged. Ideally the game also launches.

### Screenshots
![TETR IO_Ovh8Dp8fti](https://user-images.githubusercontent.com/48872143/87217509-cb820900-c2fe-11ea-872d-15e8ea1c5c48.png)
![ApplicationFrameHost_6ktcJwNx3l](https://user-images.githubusercontent.com/48872143/87217510-ccb33600-c2fe-11ea-8d8c-7ee7ea59e6bb.png)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Desktop Client v3

**Comment by o5k** [comment]
Hmmmm, think the obfuscator had a moment with this one, will see if I can build a version w/o this bug

**Comment by o5k** [comment]
nvm im just stupid

**Comment by o5k** [comment]
Should be hotfixed now!
