### ISSUE TITLE
Personal rank information displays even in Tetra Channel

### ISSUE THREAD

**Issue by periodically-makes-puns** [tetrio/issues#427]
### Checklist (issue will be disregarded & closed if incomplete!)

- [✓] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [✓] I am using the **newest version** of TETR.IO.
- [✓] I know **how to reproduce the issue**.
- [✓] I am using a **supported browser** or the Desktop Client.
- [✓] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [✓] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When completing a Personal Best (or anywhere within the top 10), the information shows for all detailed replays, even when viewing others' results.

### Reproducing
1. Obtain a personal best, or anywhere in the top 10 on Blitz or Sprint
2. Click back, and enter Tetra Channel.
3. Enter Leaderboards, click any name to open a detailed view of their sprint/blitz run.

### Expected behavior
No personal rank information should display, as it is not pertinent.

### Screenshots

![image](https://user-images.githubusercontent.com/34005746/87237813-7e6a6980-c3c8-11ea-9931-977950823f48.png)

![image](https://user-images.githubusercontent.com/34005746/87251576-ac889180-c43a-11ea-8c1b-65780eea4004.png)

### Your setup
 - **OS and version**: Manjaro 20.0.3 Lysia
 - **Browser and version**: Chromium 83.0.4103.97

**Comment by periodically-makes-puns** [comment]
Note: the screenshot is of VinceHD's sprint record viewed in Tetra Channel, with my personal rank from a blitz game, for extra contrast.

**Comment by periodically-makes-puns** [comment]
The issue also exists for the global rank display. I didn't get a screenshot of this one, and haven't reproduced it yet (because it would be tied to my ability to get another blitz PB).

**Comment by o5k** [comment]
Hotfixed.
