### ISSUE TITLE
Black borders over buttons in linux

### ISSUE THREAD

**Issue by SlawekNowy** [tetrio/issues#428]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
On linux the shadow over buttons nad labels sometimes gets rendered as black square.
Happens as soon as you run desktop client.
![Przechwycenie obrazu ekranu_2020-07-12_17-53-03](https://user-images.githubusercontent.com/38943477/87251019-086a0f00-c469-11ea-9798-f16fb4385879.png)
![Przechwycenie obrazu ekranu_2020-07-12_17-53-30](https://user-images.githubusercontent.com/38943477/87251020-0a33d280-c469-11ea-9901-b99a8636a729.png)

### Your setup
 - Linux Manjaro 18
 - Desktop client

**Comment by o5k** [comment]
What GPU, and what drivers (nouveau?)

**Comment by SlawekNowy** [comment]
Using NVIDIA geforce 940MX (driver 440.82)

**Comment by SlawekNowy** [comment]
Still present as of 4.2.2.

**Comment by o5k** [comment]
Still happening?

**Comment by SlawekNowy** [comment]
It's worse. Now there's only black screen. Menu still functional though.

**Comment by o5k** [comment]
What if you hold F4?

**Comment by periodically-makes-puns** [comment]
Can confirm similar issue occurs with Manjaro, geforce MX250 (driver version 450.66), PRIME offload. Enabling safe mode does not help.

**Comment by SlawekNowy** [comment]
I have discovered that more applictions have this bug.
Closing as this is X11 bug.
