### ISSUE TITLE
SVG doesn't need to go away

### ISSUE THREAD

**Issue by Tenchi2xh** [tetrio/issues#430]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

I have seen a long discussion that happened while I was asleep, and one point raised was about why the skins had a gap of 1 px: because when rasterizing the SVG to pixels, the edges of adjacent minos might bleed on each other.

But this can easily be remedied in software! Instead of: rasterizing first and then splitting into textures (which will have bleed if you don't have a pixel gap),

You can instead first crop to individual squares *in SVG* (doesn't matter if the original skin is SVG or PNG for this method), then rasterize, and make a texture.

To easily crop without any bleed ever, just embed the skin, whether SVG or PNG, in an SVG with a 30 x 30 view box and blit at an offset:

```svg
<svg viewbox="0 0 30 30" width=128 height=128>
  <image x="{i * -31}" y="0" width="372" height="30" xlink:href="https://tetr.io/res/minos.svg" />
</svg>
```

(the width and height of 128 is just for demonstration purposes)

You can hard-code 12 of these or generate them on the fly, doesn't matter. The result is clean individual minos that will never bleed even if there's no pixel gap: https://codepen.io/Tenchi2xh/pen/abdjwOd

![image](https://user-images.githubusercontent.com/4116708/87277716-1bb9c080-c4e3-11ea-8205-1756a99cd699.png)

Please don't remove SVG support I like it a lot! 😁

**Comment by o5k** [comment]
I will be attempting a different tactic to try and stop AA between tiles first, as SVG is still preferred due to space constraints.
