### ISSUE TITLE
Allow for single financial contributions via another payment platform like PayPal

### ISSUE THREAD

**Issue by tylerw51** [tetrio/issues#431]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.

I would like to contribute a small financial amount I determine one time to support your development. But, Patreon only allows for set amounts to be contributed regularly.

### Describe the solution you'd like

It would help you raise more money for you to add an alternative to regular Patreon contributions. Like a means to contribute an amount the giver chooses one time via another payment platform, such as PayPal.

### Describe alternatives you've considered

Currently, the only way I would be able to contribute would be to become a Patreon at one of the pre-set levels, and then cancel my subscription after a month or two. I'm not comfortable doing this, because starting a new subscription makes me anxious that I will need to remember to cancel it later.

### Additional context

I really love Tetr.io and would like to help it continue to grow, even if it's only in a small way! You've made the funnest Tetris game I've ever played.

**Comment by o5k** [comment]
Now supported using Xsolla!
