### ISSUE TITLE
Sometimes when switching tabs or alt-tabbing, enemy display gets weird in Tetra League

### ISSUE THREAD

**Issue by GhtGhoster** [tetrio/issues#433]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
I was playing some practice in jstris when I heard a match found and switch tabs via Ctrl+PgUp. Then this happened, the enemy field was rendering over my next pieces making it very uncomfortable to play. I wasn't meddling with any scripts or html or what have you, no console being opened or anything. It fixed itself after the first round.

### Reproducing
1. Go to Tetra League
2. Join queue
3. Switch tabs or windows
4. See error (not consistent but common)

### Expected behavior
I'd expect it to render correctly either where it should be, minimized in the top right corner or at least render behind my own playing field

### Screenshots
![image](https://user-images.githubusercontent.com/32255934/87692670-48dccc00-c78c-11ea-9f9a-bea0ea3962c9.png)

### Your setup
 - **OS and version**: Windows 7
 - **Browser and version**: Chrome 84

**Comment by o5k** [comment]
Tabbing out in browser is currently undefined behaviour. Please use the Desktop Client as a quick fix.
