### ISSUE TITLE
Ghost of the ghost piece after clearing lines

### ISSUE THREAD

**Issue by GhtGhoster** [tetrio/issues#434]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
The ghost of the previous harddropped piece stays visible for about half a second after the drop and lines get cleared. This is especially confusing when downstacking as it makes the field look different than it should be.

### Reproducing
1. Set visuals to Ultra
2. Go to whatever gamemode
3. Clear a line
4. See the piece you just dropped linger on the screen

### Expected behavior
I expect the field to be clean and to only have the blocks that are on the board rendered on the board.

### Screenshots
![image](https://user-images.githubusercontent.com/32255934/87697999-2dc18a80-c793-11ea-8e07-301eea3c92aa.png)

### Your setup
 - **OS and version**: Windows 7
 - **Browser and version**: Desktop app

### Additional context
config file:
[config.zip](https://github.com/tetrio/issues/files/4932837/config.zip)

**Comment by o5k** [comment]
Disable this by lowering _Piece Flash_.

**Comment by GhtGhoster** [comment]
Piece flash was at the lowest value as shown in the config file
