### ISSUE TITLE
TETR.IO Desktop shows the wrong version number in control panel, and in the executable's properties

### ISSUE THREAD

**Issue by ZaptorZap** [tetrio/issues#436]
### Checklist
- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----
### Describe the bug/issue
It's a little hard to see the desktop client version number as is, as every spot for the version number outside the game is set to "1.0.0.0" or "1.0.0". It's most certainly *not* V1, as V1 isn't supported. You can still see the version number ingame however.
### Screenshots
![tetrio version number discrepancy](https://user-images.githubusercontent.com/64891705/87748363-32169380-c7e5-11ea-9d92-b98c862a571e.png)
(screenshots of control panel, then the file's properties, then the ingame version number)

**Comment by o5k** [comment]
Fixed in next version.
