### ISSUE TITLE
Game fails to start after banning every song, assignment to const

### ISSUE THREAD

**Issue by UniQMG522** [tetrio/issues#437]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Game softlock occurs when banning every song, assignment to const error in console.

### Reproducing
1. Ban every song
2. Start any game

### Expected behavior
Game shouldn't softlock

### Screenshots
Stack trace without tetrio plus:
![firefox_wID8rVOMDx](https://user-images.githubusercontent.com/48872143/87831779-46847b80-c839-11ea-9dba-3037c253071d.png)

Stack trace acquired with tetrio plus + bypass bootstrapper:
![firefox_gZIZOQQRZM](https://user-images.githubusercontent.com/48872143/87831782-484e3f00-c839-11ea-8272-a1434436fbb8.png)

### Your setup
 - **OS and version**: W10
 - **Browser and version**: Firefox 79, Desktop v3

### Additional context
Discovered using custom music from tetrio plus, reproducible by banning every vanilla song without tetrio plus.

**Comment by o5k** [comment]
Hotfixed - F5 to receive the fix.
