### ISSUE TITLE
Cant log in, change email or change password

### ISSUE THREAD

**Issue by vickyguareschi** [tetrio/issues#439]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x ] I am using the **newest version** of TETR.IO.
- [ ] I know **how to reproduce the issue**.
- [x ] I am using a **supported browser** or the Desktop Client.
- [x ] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x ] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
I created my account when there was this bug that completed everything in CAPS. I can login to my account as I have saved the password on my browser, but if I wanna reset it, Icant. My email was saved in CAPS and I cannot change because every time I try to change it it says my password is incorrect. But I am able to login. So I can only use my account on this browser. I cannnot login anywhere else and I cannot change my email so I get the password reset email. 

### Reproducing
2. Click on '...'
3. Scroll down to '...'

### Expected behavior
I want to be able to change my email and password but I cant becaise i have no idea whats going on. 

### Screenshots
-

### Your setup
 - **OS and version**: Windows 10 Pro
 - **Browser and version**: Chrome 

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
are you sure you didnt mistype your password

either way this isnt a bug, please try your password with diff. capitalization or email/dm me
