### ISSUE TITLE
T-spin text vanishing too early

### ISSUE THREAD

**Issue by Ricardito10** [tetrio/issues#441]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
After 4.1.1, where the T-spin clear text is fixed, the T-spin text is cleared as soon as a new piece is dropped, even if it wasn't a clear.

### Reproducing
1. Go to any mode and start a game (I personally used ZEN)
2. Perform a T-spin of any kind (I used T-spin double)
3. Drop a piece immediately after the T-spin is cleared

### Expected behavior
The T-spin clear text should stick around like the normal clear text (Double, Triple, ETC), unless another clear is made.
### Screenshots
Its hard to explain without a gif, so I will post a replay link to a dummy 40-line run to exemplify.

### Your setup
 - **Windows 10 1909**
 - **Desktop Client 4.1.1**

### Additional context
https://tetr.io/#R:wP4Z5WKI_

Around 37 seconds into the run is where it is shown. There's also a T-spin mini somewhere in there that also gets cropped out.

**Comment by o5k** [comment]
Hotfixed, F5 for the fix
