### ISSUE TITLE
socket.io fails to load, possibly serviceworker related

### ISSUE THREAD

**Issue by UniQMG522** [tetrio/issues#442]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [nah] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Someone in the discord server was having an issue connecting to multiplayer. It looks like the issue is the result of socket.io not loading for them. They're able to load it in chrome but not the desktop client. Clearing application data through `Devtools -> Application -> Clear storage` resolves the issue.

### Reproducing
No decent steps to reproduce yet, but possibly a result of a spotty internet connection.

### Expected behavior
All resources requested by the game should load properly. Possibly add an automated check for malformed resources served from the service worker, or an in-game option to clear the sw cache.

### Screenshots
![image](https://user-images.githubusercontent.com/48872143/88266300-de43f880-cc83-11ea-9d83-87552d6173a2.png)
![image](https://user-images.githubusercontent.com/48872143/88266307-e1d77f80-cc83-11ea-9104-98d57bf9a731.png)

### Your setup
 - **OS and version**: 
 - **Browser and version**: Desktop Client

**Comment by o5k** [comment]
why was this still open i dont even use socketio anymore
