### ISSUE TITLE
Hyper Velocity not present in music tweaker

### ISSUE THREAD

**Issue by LayneTheEpic** [tetrio/issues#443]
### Checklist
- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
The 'music value', or how likely a song is to be picked, does not exist for Hyper Velocity.

### Reproducing
1. Open 'Tweak Music'
2. Scan through list. It's not present.

You can double-verify by using `Ctrl+F` on the ***website's*** tweaker and searching for it.

### Expected behavior
It should be there.

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Desktop Client

-----

**Comment by ZaptorZap** [comment]
Neither is Arial City. Something tells me this is intended behavior though, as there are no other tracks to replace Hyper Velocity in blitz, the only mode it plays in.

**Comment by o5k** [comment]
As intended, since Hyper Velocity is not present in any randomizer.

**Comment by ProjectHSI** [comment]
This issue is a false issue. As Hyper Velocity Is a special track just for blitz.
