### ISSUE TITLE
Custom Room: Game Start Countdown + Room Auto Shut Down

### ISSUE THREAD

**Issue by Lexitik** [tetrio/issues#444]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
It can be tedious for a host to NEED to start a match after every game, or for people to wait for an inactive host to start a match. Sometimes an inactive host can make people needlessly wait for a room that will not start (whether on purpose or not) and the room dies. This creates another problem. Sometimes players may join a room to find an inactive host and the room is needlessly open.

### Describe the solution you'd like
A countdown similar to the one in Quick-play would be nice. I suggest the countdown to default at 30 seconds and be adjustable by the host. It would be toggle-able in the ROOM tab in custom rooms (might be better on by default). Saved changes of the countdown's length come into effect after a game is played. The host can bypass the Countdown and manually start a game. They may also halt the countdown manually, temporarily disabling it until another game is played. If there is only 1 player in the room you could either: a) have the countdown automatically disable itself or b) let the countdown run to 0 to allow players to join, and if a game cannot start, the countdown resets.

Rooms that have not had any games after a set period of time should alert the host with a prompt stating that the room will automatically shut down if no actions are made. The prompt would show a timer starting at 60 seconds which will shut down the room once it reaches 0. A button to cancel the auto shut down, displayed on the prompt, will be available to the host.

**Comment by Xelitik** [comment]
Bump. At the time of writing there's been a custom room called "Don't Join" with an inactive Host in spectate. I'm sure it's been inactive for at least 24 hours

**Comment by Xelitik** [comment]
Bump 2

**Comment by jydiw** [comment]
I agree that this would be nice. My friends and I have been trying to host a small tournament amongst ourselves. With multiple rooms and someone streaming, it would be nice if there was a way for people to indicate that they are ready to play and for the host of the room to spectate.

**Comment by Dimentio** [comment]
Added in next update!
