### ISSUE TITLE
Blitz + 40 Lines score saving broken?

### ISSUE THREAD

**Issue by Mocha2007** [tetrio/issues#445]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
On Blitz and 40 Line modes, when the game is over, it says something like "something suspicious was with the timing, please refresh the page" (it appears and disappears too quickly)

### Reproducing
1. Play Blitz or 40 Line mode
2. See Error
3. Cry in despair

### Expected behavior
It shouldn't say that, and should save the scores.

### Your setup
 - **OS and version**: Windows 7 SP1 64-bit
 - **Browser and version**: Vivaldi 3.1.1929.45 64-bit

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

I noticed this in the console:

> /api/games/submit:1 Failed to load resource: the server responded with a status of 422 ()

**Comment by o5k** [comment]
This was fixed in an earlier update.
