### ISSUE TITLE
please fix a issue about i am disconnecting for no reason it says transport error PLEASE FIX THIS tetrio name Shano12345

### ISSUE THREAD

**Issue by shanowali** [tetrio/issues#446]
### Checklist (issue will be disregarded & closed if incomplete!)

- [ ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [ ] I am using the **newest version** of TETR.IO.
- [ ] I know **how to reproduce the issue**.
- [ ] I am using a **supported browser** or the Desktop Client.
- [ ] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [ ] I am certain this is a **bug**, not a feature request.

-----

### Reproducing
2. Click on '...'
3. Scroll down to '...'

### Your setup
 - **OS and version**: [e.g. Windows 7]
 - **Browser and version**: [e.g. Chrome 76]

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
![](https://kagari.moe/:/moe_atsumi.png)
![](https://kagari.moe/:/makiko_eri.png)
https://twitter.com/tetriogame/status/1286974541764407297

have you considered reading
