### ISSUE TITLE
Revengeance

### ISSUE THREAD

**Issue by kitokofox** [tetrio/issues#449]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

Basically a mode that lets you have fun with the other players when you're KO'd. When turned on, if you top out it will give you the ability to send garbage to the others at a reduced rate, like half or third damage. Except, you cannot control who you're targeting and cannot see the attack marker, except when manual targeting is on. If you KO a bunch of players, you can have a couple ghosts following you trying to send you garbage so be careful! Ooooooh scary.... Maybe it'll have you think carefully about using the eliminations targeting strategy.

It would also be nice if the garbage multiplier for ghosts could be configured too if it ever becomes a thing. And no, you cannot target other ghosts.

**Comment by s1gmoyd** [comment]
Could work if players you knocked out cannot send garbage to you as a ghost.
