### ISSUE TITLE
Leveling up in Zen breaks B2B

### ISSUE THREAD

**Issue by kitokofox** [tetrio/issues#450]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
If you are currently on a back-to-back long enough to have a back-to-back multiplier (3 or higher) Zen does odd things with Back-To-Back. If you level up or reset the board and clear a line normally, you'll still get the back-to-back fail horn. The Back-to-back count will also reset.

### Reproducing
1. Enter zen mode.
2. Get a back-to-back of 3 or higher to activate at least some bonus.
3. Reset the playfield or enter the next level.
4. The B2B count is gone!
5. Clear another line without getting another B2B.
6. HONK. B2B broken.

### Expected behavior
I expected the B2B to carry onto the next level and be kept, while the B2B and sound resets on reset button.

### Your setup
 - Desktop client and Chrome.

### Additional context
I'm not sure whether it's intended for the B2B to reset or not on level-up.

**Comment by Dr-Ocelot** [comment]
I will mention that the btb_break sound plays after a level up even though there is no B2B chain.

**Comment by Dimentio** [comment]
will look into this
