### ISSUE TITLE
Game display and features not working 

### ISSUE THREAD

**Issue by AJ-Guy** [tetrio/issues#453]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Reproducing
2. Click on '...'
3. Scroll down to '...'

### Screenshots
![image](https://user-images.githubusercontent.com/57297929/88589915-ddb2b580-d027-11ea-86c2-a80ffa8140c2.png)
![image](https://user-images.githubusercontent.com/57297929/88590023-0d61bd80-d028-11ea-8654-323b0514f1f1.png)
![image](https://user-images.githubusercontent.com/57297929/88590063-1d799d00-d028-11ea-9f6b-4fb8a16a55b6.png)
![image](https://user-images.githubusercontent.com/57297929/88590156-3da95c00-d028-11ea-9aff-dc101ed4c4bf.png)
![image](https://user-images.githubusercontent.com/57297929/88590217-544fb300-d028-11ea-8497-8fbd75e3dd6c.png)

The entire game looks like this. I can hear audio from the game, and when hovering over the buttons, however nothing is                                                                                                                                                                        clickable. This  makes the client completely unusable. 

### Your setup
 - Windows 10
 - Desktop Client

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
Is this still happening?
