### ISSUE TITLE
Show Registration Date On The Player Card

### ISSUE THREAD

**Issue by ZaptorZap** [tetrio/issues#459]
### Checklist 
- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.
-----
Just a quick n simple request from yours truly, this is just another little thing for the player card. It'd be neat to get a specific date of registration instead of a vague "3 months ago" on hover, as the screenshot below shows:
![image](https://user-images.githubusercontent.com/64891705/89115352-fe8b6880-d476-11ea-9b96-fe9316786c9f.png)
(this here follows the format specified from other "specific dates" such as badge earned dates and replay submission dates)

**Comment by o5k** [comment]
Added in Tetra Channel.

**Comment by ZaptorZap** [comment]
Dunno why I held off on mentioning this for so long, but y'know what they say; better late than never! I still think this could go on the profile card to continue the whole "Hover over anything and get an explanation" thing going on around TETR.IO, and I really don't see much of a reason *not* to implement this (t's not like you're cramming any other info on a hover over the name/registration date) unless you're killing off these little cards entirely.
