### ISSUE TITLE
Gamepad Not Mapping Properly

### ISSUE THREAD

**Issue by AgentCPU0** [tetrio/issues#460]
My gamepad isn't getting mapped properly to Tetr.io. The keys I'm having issues with are regarding my d-pad. Left, right, and down all get recognized as the same button input, as shown by the first screenshot. I can confirm this is an issue with Tetr.io, as I have them properly mapped in other programs, such as Steam, as shown in the second screenshot.
![Untitled](https://user-images.githubusercontent.com/45923848/89132989-d84ce380-d4dd-11ea-8c79-608bf053e11c.png)
![Untitled2](https://user-images.githubusercontent.com/45923848/89132991-db47d400-d4dd-11ea-9241-3981e2667016.png)

**Comment by saffaffi** [comment]
I'm having the same problem with my ps5 controller

**Comment by doktorocelot** [comment]
> I'm having the same problem with my ps5 controller

The PS5 controller is currently not supported in TETR.IO Desktop. We rely on support upstream (Chromium), so if you'd like to use your DualSense for TETR.IO natively, you must use an up-to-date Chromium-based browser. This problem will go away in TETR.IO Desktop when we eventually update the chrome version.

**Comment by ruguysgoingtrickortreating** [comment]
Could this be reopened cause it's still an issue

**Comment by icyki** [comment]
Having this issue on firefox with a DS5 as well.
