### ISSUE TITLE
Can We Get an "Undo" Button?

### ISSUE THREAD

**Issue by DanKruse731** [tetrio/issues#461]
- [ YES ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [ YES ] I am using the **newest version** of TETR.IO.
- [ YES ] I am certain this is a **feature request**, not a bug.
- [ YES ] I've **thought this feature through** properly.

-----

### Problem
I'm tired of accidentally placing blocks where I don't want them to be. Misdrops have ruined so many matches for me countless times.

### Solution
I would like an "Undo" button that lets you undo the mistake that has been made.

### Alternatives
Sadly there have been no alternatives to fix such a tragic problem.

**Comment by o5k** [comment]
you can undo making this issue
