### ISSUE TITLE
Game stalling

### ISSUE THREAD

**Issue by s1gmoyd** [tetrio/issues#462]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [ ] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Game stalling for 1-2 seconds then returning to normal, treated as a single frame by the Desktop Client. Once every 5 minutes on average.

### Reproducing
Steps to reproduce the behaviour:
1. Go to Tetra League
2. Find a game
3. Play the game
4. Keep playing the game until this happens

I am able to live stream on request.

### Expected behaviour
No game stalling, especially for a high specs machine.

### Your setup
 - Windows 10 version 2004
 - Nvidia GeForce GTX 1050 Ti
 - AMD Ryzen 5 2600G
 - 2x8GB RAM

### Additional context
FPS was capped.
Desktop Client was not full screen.

**Comment by o5k** [comment]
cant rly find a way to reproduce this :/
