### ISSUE TITLE
Show when someone is typing in chat...

### ISSUE THREAD

**Issue by Kully** [tetrio/issues#463]
- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

I want to see when an opponent is typing a response in chat post match. Then I will know they are still there, and won't leave the chatroom. This goes both ways.

### Describe the solution you'd like
I'd like to see a little ellipses `...` animation just above the input for the chatbox.

This is a codepen of a Facebook-similar solution: https://codepen.io/arthak/pen/rmqvgo

...

### Describe alternatives you've considered
A similar but different solution is to show the text `{opponent} is typing...` with `{opponent}` being the username of the person you are up against.

### Additional context
![image](https://user-images.githubusercontent.com/10369095/89354905-0c640800-d688-11ea-9a88-f93ad7e4018d.png)

![image](https://user-images.githubusercontent.com/10369095/89354916-1259e900-d688-11ea-8cbf-9af8012bffb6.png)

**Comment by Kully** [comment]
@Not-A-Normal-Robot Thanks for prompting this to be reopened.

Is it possible for us to contribute to this PR, as a regular dev?

**Comment by szymon221** [comment]
This is a much needed feature. I have quit too many games just as a new message has come through.
