### ISSUE TITLE
In a room, changing from Player to Spectators while host starts game makes you not be able to control board anymore.

### ISSUE THREAD

**Issue by TheoKushi123** [tetrio/issues#465]
### Checklist (issue will be disregarded & closed if incomplete!)

- [Check] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [Check ] I am using the **newest version** of TETR.IO.
- [Check ] I know **how to reproduce the issue**.
- [Check ] I am using a **supported browser** or the Desktop Client.
- [Check ] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [ Check] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue

Bug 1.a: In a multiplayer room (might not work in quick play), if a player "Playing" the room switches to "Spectator" while host is starting the game, the player is both playing and spectating at once (but you're mostly playing). The first game will proceed normally as if you were a player. If playing on ft2 or more, after the first game the player won't be able to see their board and consequently, not move it. 

Bug 1.b: There are also some weird effects when doing the opposite: if a player "spectating" moves to "players" while host starts the game. This needs at least three players to function, and if a player "spectating" does switch to "players" while host initializes the game, you'll be in a similar limbo state both playing and spectating (but you're mostly spectating). On the first game, you're just spectating the other players. If playing on ft2 or more, on the next games you will be playing with a board that doesn't interact with the other players; doesn't recieve garbage/ send garbage. 

### Reproducing
For bug 1.a:
1. Make a room (private/public). Use higher than ft1.
2. You need at least 2 people (including yourself) to be in that room, **"playing."** Note that you can reproduce the bug by yourself if you open two different accounts, although doing it by yourself is a bit harder (you must start game and then on the other tab switch player state).
3. Start the game, and then immediately move the other player (or tell whoever's helping you) to move to **"spectator."**

For bug 1.b:
1. Make a room (private/public). Use higher than ft1.
2. You need at least 3 people (including yourself) to be in that room, at least **2 "playing", and 1 "spectating".** Note that you can reproduce the bug by yourself if you open three different accounts, although doing it by yourself is a bit harder (you must start game and then on the other tab switch player state).
3. Start the game, and then immediately move the other "spectator" (or tell whoever's helping you) to move to **"players."**

### Expected behavior
The first round will go normally. 

In bug 1.a, you will be playing the first round normally as if nothing happened. After round 1, you won't be able to see your board, only the other player/s' board/s. You can't control the board either.

In bug 1.b, you will be spectating the first round normally as if nothing happened (however, you might notice that you can target people with the different targeting buttons. After round 1, a board will appear which you can control. However, you can't send garbage, or be sent garbage, since you're not technically in the game.
### Your setup
 - **OS and version**: [e.g. Windows 7]
macOS Mojave v.10.14.6
 - **Browser and version**: [e.g. Chrome 76]
Chrome 84

Bug 1.a (testing on TheoKushi1234)
![Screen Shot 2020-08-07 at 12 11 43 PM](https://user-images.githubusercontent.com/69361059/89674943-aad1b280-d8ae-11ea-97c8-dbaa4bef1896.png)
On first round you're playing normally.
![Screen Shot 2020-08-07 at 12 11 50 PM](https://user-images.githubusercontent.com/69361059/89674952-aefdd000-d8ae-11ea-8f21-e8f869b328b9.png)
On the next round/s, TheoKushi1234's board is gone, and all he can do is spectate TheoKushi123's board.
![Screen Shot 2020-08-07 at 12 12 05 PM](https://user-images.githubusercontent.com/69361059/89674957-b02efd00-d8ae-11ea-9d82-dc565f0fc536.png)
Bug1.b (testing on TheoKushi1234. Ignore TheoKushi12345)
![Screen Shot 2020-08-07 at 12 16 45 PM](https://user-images.githubusercontent.com/69361059/89674960-b0c79380-d8ae-11ea-9d32-36067037b533.png)
Again, first round TheoKushi1234 is spectating as normal. However, he can target the other players with the targetting buttons.
![Screen Shot 2020-08-07 at 12 18 06 PM](https://user-images.githubusercontent.com/69361059/89674962-b1602a00-d8ae-11ea-8a39-c750bb3d2a7c.png)
After round 1, TheoKushi1234 is playing, although he doesn't send garbage, recieve garbage, and him losing/winning doesn't affect the results of the game.
![Screen Shot 2020-08-07 at 12 18 36 PM](https://user-images.githubusercontent.com/69361059/89674964-b2915700-d8ae-11ea-9cbe-cf6d6c0c4c85.png)

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
Fixed in next version.
