### ISSUE TITLE
The current VS score doesn't seem to represent skill accurately

### ISSUE THREAD

**Issue by csq-curiosity** [tetrio/issues#466]
### Checklist (issue will be disregarded & closed if incomplete!)

- [O] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [O] I am using the **newest version** of TETR.IO.
- [O] I am certain this is a **feature request**, not a bug.
- [O] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
The game's VS score takes into consideration of attack per piece and downstack per piece, effectively covering another aspect of gameplay skill.

The problem with the current VS score is that it doesn't cover a particular defensive playstyle, which is players intentionally cancelling quads/tsds with quads/tsds. Since the garbage is neither sent nor cleared, neither APM nor VS score captures this aspect of skill.

### Describe the solution you'd like
From what I can see of the game registering cancelled lines as blue text, (as opposed to sent attacks which is yellow text) the game does keep track of cancelled lines. I would suggest adding an element of cancelled lines into the VS score equation, in order to represent a wider skill range.

### Describe alternatives you've considered
I don't think there is an alternative to this, although I am open to more suggestions.

### Additional context
Whether cancelled lines should be taken into account in APM is another story. I would personally suggest not doing that.

**Comment by cosin307** [comment]
Cancelled lines are taken account to APM therefore also to VS score. It also can be said that it also accounts for defensive style of playing.
I'd suggest if you want to add something that doesn't account cancelled lines you might want to ask about adding SPM(sent per minute) into the statistics.

**Comment by csq-curiosity** [comment]
Does it? I didn't know that. Maybe I was misreading the apm and vs stats. :P
