### ISSUE TITLE
White spaces are not stripped from lobby id or URL

### ISSUE THREAD

**Issue by 2press** [tetrio/issues#468]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
A lobby link (URL) that has leading or trailing white space is not working under Multiplayer -> "enter room id or url nd hit enter". This is especially annoying as when copying the URL from other sources one often copy additional white space by accident.

### Reproducing
1. Make a public or private lobby, copy lobby link, send it to another person.
2. This person adds one or more white spaces to the beginning or start of the link.
3. This persons copies the valid lobby link including white spaces and pastes it into the "enter room id or url nd hit enter" field under Multiplayer.
4. The link is not accepted due to the white spaces even so it is valid.

### Expected behavior
Strip the lobby URL or ID to remove white spaces and except the lobby link none the less.

**Comment by o5k** [comment]
Fixed in next version.

**Comment by 2press** [comment]
@o5k it is still not fixed.
