### ISSUE TITLE
Specific input ignorance

### ISSUE THREAD

**Issue by Rklplol** [tetrio/issues#469]
### Checklist

- [x] I've checked both open and recently closed issues to ensure this issue is not already reported.
- [x] I am using the newest version of TETR.IO.
- [x] I know how to reproduce the issue.
- [x] I am using a supported browser or the Desktop Client.
- [x] I am not using anything that modifies game code (e.g. TETR.IO+).
- [x] I am certain this is a bug.

### Description
Under certain circumstances some inputs may be ignored.

### Reproducing
1. Enter any mode
2.1 Perform **clockwise** rotation, leave this button **pressed** and move the piece **right** at the same time (or vise versa)
2.2 Or perform **counter-clockwise** rotation, leave this button **pressed** and move the piece **left** at the same time (also works vise versa)

### Expected behavior
Perform both actions.

### Actual behavior
Second action is ignored for exactly one input.

### Setup
 - Windows 10
 - Chrome 84.0.4147.105

### Additional context
To be fair, other actions work fine, e.g. CR+Left, CCR+Right and both cases of 180-rotation.

**Comment by o5k** [comment]
Cannot reproduce

**Comment by Manabender** [comment]
What exactly are the keybinds for the relevant buttons?

I've never had this issue, ever. And I very frequently DAS and rotate at the same time. If it was caused by software, I'd have noticed it. My best guess is that your specific keyboard is causing this, on a hardware level.

**Comment by Rklplol** [comment]
Rotations: clockwise - num6, counter-clockwise - num4.
Movement: arrows.

**Comment by Rklplol** [comment]
I'll check other keybinds.

**Comment by Manabender** [comment]
Definitely sounds like your keyboard is getting rightarrow and num6 confused. Especially if you have numlock on. Different keybinds should fix this.

**Comment by Rklplol** [comment]
Changed rotations to "A" and "D". Worked fine, indeed.

**Comment by o5k** [comment]
Ooh, you have Num Lock off, don't you? If NumLock is off, many keyboards will refuse to press both num2/num4/num6/num8 and arrow keys at the same time.

**Comment by Rklplol** [comment]
Totally true, o5k, ha-ha!

**Comment by Rklplol** [comment]
Thanks for your fast responses!
