### ISSUE TITLE
Frame rate limit causes fluctuating framerate on Linux, Nvidia

### ISSUE THREAD

**Issue by rednir** [tetrio/issues#470]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Turning the frame rate limit on causes the game to run worse than expected, fluctuating between 35-45fps. With the frame rate limit off, fps is always 100+

### Reproducing
1. Enable frame rate limit (hold f4)
2. Look at fps counter

### Expected behavior
Frame rate limit should keep the game at a relatively consistent 60fps with no fluctuation.
### Your setup
- GTX 960M + Intel HD graphics 530
 - Arch Linux
 - Proprietary NVIDIA drivers 450.57
 - Using desktop client

### Additional context
This issue doesn't happen when switching to Intel graphics nor does it seem to happen at all in Windows, and it persists through the Linux distributions I've tried. A simple hotfix could be to let the user choose the frame rate limit.
Also [this](https://stackoverflow.com/questions/18005674/limiting-webgl-framerate-via-setinterval-severely-decreases-performance) kind of describes my issue but I don't know if it's the same cause.

**Comment by benz-phan** [comment]
Did you try using any browser on it? It run fine on my Ubuntu laptop.

**Comment by rednir** [comment]
I'd still rather use desktop client, it's just easier to use and has way better performance. Browser version runs poorly for me anyways.

**Comment by o5k** [comment]
Fixed in next version.
