### ISSUE TITLE
Cannot see main manu after required update installation.

### ISSUE THREAD

**Issue by SlawekNowy** [tetrio/issues#471]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
After installing the update, the view will be stuck in main tetr.io page instead of menu.
You can interact with menus as normal.

### Reproducing
1. Wait until an required update.
2. Run the game.

### Expected behavior
The main menu should be visible as normal.

### Your setup
 - Linux Manjaro.
 - Running on Nvidia GeForce 940MX
- Desktop Client

### Additional context
Confirmed also on Windows

**Comment by o5k** [comment]
..do you have a screenshot?
