### ISSUE TITLE
Renderer Crash

### ISSUE THREAD

**Issue by mrchapstik** [tetrio/issues#474]
### Describe the bug/issue

When playing on the desktop client my game crashed with a pop-up stating "Rendered Crashed. Report this to Osk." Most of the time I cannot get through one match before it crashes. Just the other day I had never had any issues using the browser version, but the desktop version is unplayable in my situation. 

### Reproducing

To see this happen, all I do is launch the game and start playing. It happens in 40L, multi, anything. sometime the game immediately crashes also without even playing anything. 

### Expected behavior
The application simply crashes and a pop-up states "Rendered Crashed. Report this to Osk."

### Screenshots

![Tetrio console in menu](https://user-images.githubusercontent.com/55471275/90289674-60ba7500-de4a-11ea-98d7-0e227ed68db5.PNG)

![Tetrio crash during custom game](https://user-images.githubusercontent.com/55471275/90289675-61530b80-de4a-11ea-98a1-469e69e231d2.PNG)

### Your setup
 - Windows 10 Pro (Latest)
 - Chrome Version 84.0.4147.125 (Latest)

**Comment by o5k** [comment]
An attempted fix is in the next version.

**Comment by kaianimatez** [comment]
> An attempted fix is in the next version.

i keep getting the error render crashed(out of memory) please report to osk even in ver 5.3
