### ISSUE TITLE
Custom playfield size inside of rooms

### ISSUE THREAD

**Issue by Cweepaw** [tetrio/issues#475]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] #726
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Describe the solution you'd like

I'd like an option for custom playfield sizes, so you can keep it normal (20x10), bigger tetriminoes, (10x5), smaller tetriminoes, (40x20), or a board large enough that the pieces are like really hard to see (80x40). Or just an instant kill screen. (1x1).

**Comment by orangetriangle** [comment]
> Please reopen

agreed

**Comment by Cweepaw** [comment]
tbh would be kinda fun but might be reaaally broken

**Comment by deedeeen** [comment]
can be balanced tho; still needs reopening

**Comment by Cweepaw** [comment]
close enough

**Comment by ZaptorZap** [comment]
There has been several custom rooms with custom board sizes, so it's proven to at least work already with some rough edges(such as garbage still only spawning in rows 1-10, even in smaller boards (causing PENTA and even HEXA line clears, as a garbage line generates a full line which is cleared upon the next piece)), but alas, only osk can directly set these values from the server's side, so, this still functionally remains unimplemented. (afterall, the intial title *is* "Custom playfield size inside of **rooms**")

**Comment by ZaptorZap** [comment]
Now implemented as of [6.3.2](https://tetr.io/about/patchnotes/#chlog_6_3_2)!

**Comment by Cweepaw** [comment]
this is it. time to come back to tetrio

**Comment by Cweepaw** [comment]
cool
