### ISSUE TITLE
Board not loading

### ISSUE THREAD

**Issue by Haxel59** [tetrio/issues#476]
### Describe the bug/issue
Sometimes, when a game starts (solo or multi), the board(s) doesn't load and the game stays on a black screen (if you're in the tetra league matchmaking, clicking on it twice puts you back on the tetra league screen)

### Reproducing
1. Go in a game
2. Get a black screen (if not, quit and go back)

### Expected behavior
The board is supposed to load

### Screenshots
![image](https://user-images.githubusercontent.com/15271192/90558430-5f67b000-e19c-11ea-8a2f-ddbef84a8f6c.png)

### Your setup
 - **OS and version**: Win 10
 - **Browser and version**: Desktop Client 4.2.3-production

**Comment by o5k** [comment]
Are you using a custom background?

**Comment by shuhaowu** [comment]
I'm getting this when I exit out of a quick play game and attempt to load another game (quick play, solo, doesn't matter)

![Untitled](https://user-images.githubusercontent.com/338100/99457253-a9c20f80-28f8-11eb-889e-f009de495842.png)

In this black screen, the out of focus message works, I can move my pieces and top out, and I will be kicked back out to the menu which still works. Loading another game results in the same behaviour.

I've also noticed graphical glitching (black dots) on the corner of the screen when I'm in the menu.

I'm using Linux desktop client on a AMD RX 580.

**Comment by shuhaowu** [comment]
I've also noticed that resizing the window causes my frame rate to drop to about 30fps, which makes the game somewhat unplayable. 

Also, here's a screenshot of the graphical tearing I frequently see on the top left side of the screen:

![Screenshot from 2020-11-18 18-15-41](https://user-images.githubusercontent.com/338100/99599943-6041f500-29ca-11eb-85ba-47416bc4eca7.png)
