### ISSUE TITLE
Timeline in Replay Window

### ISSUE THREAD

**Issue by adcanada** [tetrio/issues#477]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
Whenever I'm watching a replay and see something cool/useful (such as a new TSD setup) that I want to watch again to see what happened, I have to close the replay, open it up again, and fast forward to the spot where the cool thing happened.

### Describe the solution you'd like
I would like to add a feature where there is a timeline at the bottom of the replay window which lets you jump around the replay.

### Describe alternatives you've considered
An alternative to this would be adding a feature where if you keep pressing left after hitting 0.25x speed, you can go into negative speed, reversing time.

### Additional context
I imagine it would look something like this (in Blitz the time counts down):
![timeline](https://user-images.githubusercontent.com/64662897/90960773-0c2e7f80-e472-11ea-9cd5-6185c1456f24.png)

**Comment by eight04** [comment]
Relate to #311

**Comment by o5k** [comment]
Added in next version!

![](https://kagari.moe/:/satoko_saku.png)
