### ISSUE TITLE
Specific RNG seeds cause the game to softlock

### ISSUE THREAD

**Issue by 04meta** [tetrio/issues#479]
### Checklist (issue will be disregarded & closed if incomplete!)
- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported. (well, #113 exists, but it's a random seed, not a meaningful number)
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
If you enter a Custom Game with the seed set to `-2147483646` (or 1 "less" than any other negative multiple of [2147483647](https://en.wikipedia.org/wiki/2,147,483,647), so `-4294967293` etc. too), the game softlocks at slightly different times depending on the chosen randomizer (all do this eventually).
Retry and forfeit still work, though.

### Reproducing
1. Go to the 1P Custom menu
2. Turn off Use Random Seed and set the random seed to `-2147483646` (fortunately, you can't use non-random seeds in multi, and the random seed selection always picks something positive)
3. Place a piece (maybe more than one if you're not using 7-bag)
4. The next piece never spawns, and the developer console gets spammed with `Uncaught TypeError: Cannot read property 'preview' of undefined`.

### Expected behavior
...These seeds should probably behave as _something_... (and shouldn't give you the same piece over and over in total mayhem, but that hasn't been the issue yet)

### Screenshots
<img width="1792" alt="A TETR.IO desktop client window with 'YEET' in the centre as a custom game title and no board in sight." src="https://user-images.githubusercontent.com/38385509/91489758-ee4c8a80-e876-11ea-916e-679971c0f706.png">
"The board should be here by now."

### Your setup
 - **OS and version**: macOS Catalina 10.15.6
 - **Browser and version**: Desktop client

### Additional context
I discovered this while trying to write something to see what seed gave you the most consecutive (any type, `i` preferred) pieces at the start of the game with Total Mayhem (or Classic) RNG (statistically, it should be around 11 for Total Mayhem, but I haven't actually checked).

This is caused by the RNG initializer (which divides your seed by 2147483647, takes the remainder of the same sign as the original, and adds 2147483646 if it's less than or equal to zero) returning zero instead of the intended range of `1` to `2147483646`.

This seems more serious than most other 1P-related crashes, because "yo dude I found this cool seed it's `-2147483646` on classic" feels like a much more believable lie than "yo dude something really cool happens if you ???? with the leveling settings in this really weird way" or "yo dude something cool happens if you set the pre-game countdown to 3 million million¹ years". At least retry and forfeit work in this case.

¹ not a typo

**Comment by DuePatronousREAL** [comment]
This now soft locks with a J piece on the top and the preview being T pieces

**Comment by Dimentio** [comment]
Fixed in next patchnote!
