### ISSUE TITLE
Account Deletion Process

### ISSUE THREAD

**Issue by PaxUnda** [tetrio/issues#480]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
I forgot my password after making my account but before registering an email, making it impossible for me to delete it.

### Describe the solution you'd like
Allow users to delete their accounts without a password requirement if they do not have an email registered - there can be a warning about this upon account creation.

### Describe alternatives you've considered
Allow users to change their password without needing the old password, warned about upon account creation. Create a one-time emergency password recovery for those who don't have an email registered.

### Additional Context
If it's still stored somewhere, can you provide me the password to my account? It was named "Paxie", I made it around 9pm EST if you need some evidence of ownership.

**Comment by o5k** [comment]
Please contact me in Discord DMs or email me. I do not wish to make the account system less secure for the sake of some people ignoring the very large popups on the bottom right.
