### ISSUE TITLE
Make force-discrete-gpu an option

### ISSUE THREAD

**Issue by MyK00L** [tetrio/issues#485]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
I changed ```app.commandLine.appendSwitch('--force-discrete-gpu', '1');```
to ```app.commandLine.appendSwitch('--force-discrete-gpu', '0');```
in resources/app.asar
and it stopped overheating my laptop while keeping the same framerate (not capped)

### Describe the solution you'd like
Make that flag an option

### Describe alternatives you've considered
stop using js :laughing: 

### Additional context
I hate js, so I wanted to make a rust client for the game, I opened resources/app.asar to see if I could find clues about networking stuff, and I stumbled upon this flag, so I decided to try and change it, and to my surpurise when I restarted the game, the fans weren't loud as usual.
Also I found that you can hold F4 to toggle framerate limit only after this, maybe I'm just stupid idk

**Comment by x18349276** [comment]
I tried to change `app.commandLine.appendSwitch('--force-discrete-gpu', '1');`
to `app.commandLine.appendSwitch('--force-discrete-gpu', '0');`
in the latest version of tetr.io desktop (4.0.0), but it doesn't work.
This error appears:
```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Error parsing /home/thescrasse/Downloads/tetrio-desktop-4.0.0/resources/app.asar/node_modules/electron-store/package.json: Unexpected token : in JSON at position 7
    at parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:268:20)
    at readPackageExports (internal/modules/cjs/loader.js:308:15)
    at applyExports (internal/modules/cjs/loader.js:450:20)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:637:31)
    at Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:919)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
```
