### ISSUE TITLE
Beginner Rooms.

### ISSUE THREAD

**Issue by MaxACartwright** [tetrio/issues#486]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
I'm always frustrated when I get put into rooms with pro players

### Describe the solution you'd like
I would want a Newbie room that would be helpful for people who are new to TETR.IO or Tetris in general

### Describe alternatives you've considered
Practicing on solo mode to get better

### Additional context
Not really, no

**Comment by hourssincetalebcalledsomeoneafraud** [comment]
@MaxACartwright remove the spaces in your `[x]`s so that it marks correctly as completed :)

**Comment by Ads20000** [comment]
@MaxACartwright remove the spaces in your [x]s so that it marks correctly as completed :)

**Comment by MaxACartwright** [comment]
It should work now.

**Comment by o5k** [comment]
"Beginner rooms" sound like a great way to get people to smurf just to enter them, plus it sounds kind of.... belittling? to be put in a "beginner room"

Plans are:
- make Quick Play have soft matchmaking, to split up and merge quick play rooms as needed, split generally by skill level
- allow custom rooms to set rank requirements and the such

Can't say when these features would be in though, as I don't do ETAs for things I cannot 100% ensure I'll meet
