### ISSUE TITLE
Add a mute music button

### ISSUE THREAD

**Issue by fedelway** [tetrio/issues#487]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
Sometimes when playing i'm listening to other music. For example, when i'm searching for a game, i go and check other browsers tabs and listen to music. When the game starts, i switch to the tab to play and the tetrio music starts playing. Now i have two different songs playings at the same time which can be annoying. This way i'm forced to stop my music to play and be focused.

Other times, i'm not listening to external music, and i want to listen to the tetrio music (which is awesome by the way).

### Describe the solution you'd like
There should be a button "Mute Music" in the in-game screen. This button should stop tetrio music (or re-enable). This way we can have the flexibility of choosing in game, what music i want to listen, or if i don't want to listen to any music.

### Describe alternatives you've considered
Right now we can go to the main screen, then enter `Config` , and then scroll down to `Volume & Audio`. Then I have to swipe music volume slider all the way down to 0. There are too many steps and is not flexible enough. Specially when we are in-game.

### Additional context
I believe this could be implemented with a little button with an icon (♫) and a tooltip.
Additionally we could have the mute sounds button, which should mute the in-game sounds but not the music. I personally never want to mute the in-game sounds, but some people surely will appreciate the option.

**Comment by flashwave** [comment]
While ingame you can scroll to adjust the volume.

**Comment by o5k** [comment]
Additionally, if not ingame, you can hold alt while scrolling to achieve the same effect.

**Comment by fedelway** [comment]
I just tried the mouse wheel and it works. Is it documented somewhere? I've played lots of hours and never realised this option was available. 
Additionally, in mobile most users dont have the mouse scrolling available.
