### ISSUE TITLE
Discord rich presence not working

### ISSUE THREAD

**Issue by Trixciel** [tetrio/issues#488]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
The discord presence isn't working

### Reproducing
1. Launch Discord
2. Open TETR.IO Desktop
3. No discord presence

### Expected behavior
Discord should recognize the game, show the icon and info in what's the player doing, and their rank, etc

### Screenshots
![image](https://user-images.githubusercontent.com/59417613/93003426-e101f200-f53e-11ea-9bde-f08cc556bab1.png)

### Your setup
 - Windows 10 v2004
 - TETR.IO Desktop
- Discord Stable 66949 (latest) and Discord Canary 66953 (latest as well)

### Additional context
None

**Comment by ZaptorZap** [comment]
Hey there, you gotta add the game manually by following these steps:
1. Right click the settings icon and open game activity
![12, 19;33;23](https://user-images.githubusercontent.com/64891705/93003517-ebb48b00-f52e-11ea-9d46-732b50c709a3.gif)
2. Hit the blue text that says "Add it!"
3. Look for TETR.IO, then add it
