### ISSUE TITLE
Tetrio desktop changing window size constantly

### ISSUE THREAD

**Issue by DrBiet** [tetrio/issues#490]
### Checklist (issue will be disregarded & closed if incomplete!)

- [O] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [O] I am using the **newest version** of TETR.IO.
- [O ] I know **how to reproduce the issue**.
- [O ] I am using a **supported browser** or the Desktop Client.
- [O ] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [O ] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
I recently started using Tetrio Desktop, after using the browser one for the longest time. I've noticed that half of the time I open Tetrio Desktop, it opens at different window sizes. It wasn't really noticeable until I made the window super tiny, and re-opened it again. It would open in that same super tiny size a couple of times, and then open up in a really large window after a few times. The main reason it's an issue now is that the automatic resizing messes with my stream overlay and I have to keep manually resizing the window each time I open Tetrio.

### Reproducing
1. Open Tetrio Desktop
2. Look at window size
3. Manually resize window (make it a lot bigger or smaller to be able to see difference later on)
4. Close Tetrio Desktop
5. Re-open Tetrio Desktop
6. Sometimes it will open at what I manually resized it to. Sometimes it will open at a completely different size.

### Expected behavior
Should always open at the window size I manually resized it to

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Latest version of Tetrio Desktop

### Additional context
If there is potentially a way to fix the window size of Tetrio Desktop, then that would probably be the easiest way to resolve this.

**Comment by o5k** [comment]
Fixed in next version.
