### ISSUE TITLE
Control binding menu not scrolling

### ISSUE THREAD

**Issue by Trixciel** [tetrio/issues#491]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
If menu navigation keys are bind, go in the settings menu and try to go down the menu with the menu : down key.
When in the control binds part, the menu isn't scrolling correctly, and goes up instead of down

### Reproducing
1. Go to the Options Menu
2. Choose custom controls
3. Bind a key to "menu : down"
4. Quit and re-enter the options menu
5. Hold the "menu : down" key to scroll through control mappings, until the selected option goes off-screen, and disappears.
6. The menu isn't scrolling

### Expected behavior
The menu should scroll down instead of not moving.

### Screenshots
![image](https://user-images.githubusercontent.com/59417613/93780023-f1455b80-fc27-11ea-8cb9-1810d21b679f.png)
![image](https://user-images.githubusercontent.com/59417613/93780050-f7d3d300-fc27-11ea-901a-f3e295d81666.png)
Scroll until you don't see your selection anymore
![image](https://user-images.githubusercontent.com/59417613/93780188-22259080-fc28-11ea-9daa-247832a757b4.png)

### Your setup
 - Windows 10 1908
 - TETR.IO Desktop Client

### Additional context
None

**Comment by o5k** [comment]
This happens when holding down the scroll button. It's a bug in how browsers smoothscroll, sorry :/
