### ISSUE TITLE
Framerate Limiter Doesn't Work After Restart

### ISSUE THREAD

**Issue by atome1ectron** [tetrio/issues#493]
### Checklist (issue will be disregarded & closed if incomplete!)

- [+ ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [+ ] I am using the **newest version** of TETR.IO.
- [+ ] I know **how to reproduce the issue**.
- [+ ] I am using a **supported browser** or the Desktop Client.
- [+ ] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [+ ] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
-The "Framerate Limiter" resets after restarting the desktop client even though the option still appears selected.

### Reproducing
1. Go to 'CONFIG'
2. Go to 'TETR.IO DESKTOP'
3. Press 'F8' and take note of FPS
4. Click on any of the 'VSYNC', '120 FPS', or '240 FPS'
5. Take note of framerate limit adjusting to fit
5. Restart TETR.IO Desktop Client
6. Go to 'CONFIG'
7. Go to 'TETR.IO DESKTOP'
8. Press 'F8'
9. Take note of the unlimited framerate and the option previously chosen appearing to still be selected

### Expected behavior
- When selecting the 'VSYNC' option, I expect the framerate to be limited to be around 60FPS after the restart.
- When selecting the '120FPS' option, I expect the framerate to be limited to be around 120FPS after the restart.
- When selecting the '240FPS' option, I expect the framerate to be limited to be around 240FPS (or trying to because my laptop isn't very good) before or after the restart

### Screenshots
I attached a .zip file of a video of me going through the procedures and a demonstration of the problems.
[5.0.0 Tetrio framerate limit bug.zip](https://github.com/tetrio/issues/files/5295358/5.0.0.Tetrio.framerate.limit.bug.zip)

### Your setup
- Windows 10

### Additional context
I am using a Lenovo Gaming Laptop.

**Comment by o5k** [comment]
Hotfixed - F5 to receive the fix.
