### ISSUE TITLE
Personal best replay redirects do not work from a main user's page on the standalone Tetra Channel site.

### ISSUE THREAD

**Issue by ZaptorZap** [tetrio/issues#496]
### Checklist (issue will be disregarded & closed if incomplete!)
- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When attempting to view a personal best directly off of someone's profile in the standalone Tetra Channel site; it seems to redirect to an incorrect URL, causing the replay in question to not load. The game will simply insist that the replay does not exist.
### Reproducing
1. Head to https://ch.tetr.io
2. Use the provided fields to reach a standalone profile page. 
3. Click on the "➔ VIEW PERSONAL BEST" text below the 40 Lines or Blitz record stats.
4. Watch as the issue takes form in the style of an error that simply states: "NO SUCH GAME"
### Expected behavior
The replay loads as normal.
### Video
https://i.fiery.me/coCQJ.mp4
Here's a video, starting at step three detailing the process.
### Your setup
 - **OS and version**: Windows 10 1903
 - **Browser and version**: Firefox 81.0 + Desktop V4

### Additional context
You can still, however, access the player in question's personal best by following the "➔ VIEW ALL 40 LINES RECORDS" link and accessing the replay from the list that follows. 
![image](https://user-images.githubusercontent.com/64891705/94497980-6ac0e900-01e8-11eb-971c-707e121a950c.png)
(a picture of the redirect that works in my case)

**Comment by o5k** [comment]
Hotfixed - F5 to receive the fix.

**Comment by ZaptorZap** [comment]
Can confirm over here, good job on the quick fix!
