### ISSUE TITLE
tetra league lag

### ISSUE THREAD

**Issue by dlzeng243** [tetrio/issues#497]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [ ] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
I was playing Tetra league with Koro-ook(?) (U rank around 24000), and there were two games where on my screen it displayed him/her being knocked out, but the round not ending. They could still send lines to me, but they could not receive my lines, and the round only ended once I was knocked out.

### Reproducing
2. Click on '...'
3. Scroll down to '...'

I have no idea, could be a very bad lag issue.

### Expected behavior
Normal Tetra league gameplay.

### Your setup
 - **OS and version**: [Mac OS High Sierra 10.13.6]
 - **Browser and version**: [e.g. Chrome 85]

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
Hotfixed - F5 to receive the fix.
