### ISSUE TITLE
Cannot search for players in ch.tetr.io on mobile

### ISSUE THREAD

**Issue by n0mori** [tetrio/issues#499]
### Checklist (issue will be disregarded & closed if incomplete!)

- [ x ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [ x ] I am using the **newest version** of TETR.IO.
- [ x ] I know **how to reproduce the issue**.
- [ x ] I am using a **supported browser** or the Desktop Client.
- [ x ] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [ x ] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When on mobile, I can type the name of the player I want to search for (for example myself, n0mori) but I can't submit the search

### Reproducing
1. Go to [ch.tetr.io](ch.tetr.io)
2. Click on "enter a username to view..."
3. Type the username in the search box
4. I try to press enter to see if anything happens
5. Nothing happens

### Expected behavior
I should be able to submit this input and search for players on mobile.

### Screenshots
I don't think it is necessary to provide screenshots for this

### Your setup
 - **OS and version**: Android 10, Mi A3 Build/QKQ1.190910.002
 - **Browser and version**: Chrome 85.0.4183.127

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
Hotfixed - F5 to receive the fix.

**Comment by flashwave** [comment]
works for me on Firefox with the default iOS keyboard and on Android with Swift Key, have you tried other keyboards?
