### ISSUE TITLE
Chrome inspect tool keeps popping up mid-game

### ISSUE THREAD

**Issue by covlllp** [tetrio/issues#500]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x ] I am using the **newest version** of TETR.IO.
- [x ] I know **how to reproduce the issue**.
- [x ] I am using a **supported browser** or the Desktop Client.
- [x ] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x ] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue

Mid-game, when pressing CTRL + i Chrome's inspection tool pops up.

This is a problem when you use CTRL and i for controls in the game.

### Reproducing
1. Play game (single player or multi)
2. Click CTRL + i
3. Chrome inspection tool pops up, escaping focus from the game

### Expected behavior
The inspection tool shouldn't pop up

### Screenshots
![Screenshot 2020-09-29 100343](https://user-images.githubusercontent.com/8731183/94569183-6bcf3600-023b-11eb-9757-0d38358fe92f.png)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Chrome 85 (but also using the desktop client)

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by LayneTheEpic** [comment]
Yeah, it should only appear on `Ctrl+Shift+I` I believe

**Comment by covlllp** [comment]
controls have been changed with ctrl to hold and i to rotate clock-wise. The issue is more that if you change your controls to certain combinations, it should override previous default events and prevent event propagation.

**Comment by LayneTheEpic** [comment]
Makes sense, perhaps there could be a checkbox that toggles whether or not devtools can open while ingame.

**Comment by covlllp** [comment]
This still happens, the inspect tool opens on Ctrl + I

**Comment by o5k** [comment]
Fixed in next patch.
