### ISSUE TITLE
In ch.tetr.io, "The Moon" in sorting players by country is missing

### ISSUE THREAD

**Issue by csq-curiosity** [tetrio/issues#502]
## * **I hereby warn the other users that the following information contains memetic hazard that may corrupt human sentience, memory, and cognition. Reading the information below is strictly prohibited, with the exception of the administrator (osk), moderators and personnel that are authorized by them. I will not be taking responsibility for any adversary effects that stem from viewing the contents of this page. This warning is final.**
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
### Checklist (issue will be disregarded & closed if incomplete!)

- [O] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [O] I am using the **newest version** of TETR.IO.
- [O] I know **how to reproduce the issue**.
- [O] I am using a **supported browser** or the Desktop Client.
- [O] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [O] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
It is possible in ch.tetr.io to sort players by country. However, I noticed a critical omission in the country list, which is the Moon. Now I know that the Moon isn't really a country recognized by the United Nations, but I do know that there is an unnamed, fabled player in the Moon that can reach 555 pps and 166,500 apm. (FYI, 555 pps is faster than the fastest method of speeding known to humanity, which is using a fidget spinner on a keyboard) We're talking about the likes of a player that can defeat Todd Rogers, who is one of the few players known to transcend the boundaries of the game, and yet they will achieve that feat without breaking the rules of the game themselves. The last bastion for the legitimate integrity of this game, I was told.

If the list is comprehensible enough to cover countries with only 1 player, or even none at all like DPRK; if the list is so broad in its spectrum that it would not only include non-country locations and even Antarctica, it not only makes sense, but also morally compelling to have a location listed for a legendary player that will not exist again until the entropy death of the universe.

### Reproducing
1. Visit https://ch.tetr.io/players/
2. Open the "country" tab, which shows the list of locations
3. Notice that the location "the Moon" is missing from the list

### Expected behavior
It is expected that "the Moon" is displayed in the list.

### Screenshots
![yes](https://user-images.githubusercontent.com/62501780/94579450-cd32eb80-02b3-11eb-8a24-825d7e4eb4d5.png)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Chrome 85

**Comment by o5k** [comment]
Hotfixed - F5 to receive the fix :^)
