### ISSUE TITLE
Tetra Channel: Countries are sorted by local name, but displayed by English name

### ISSUE THREAD

**Issue by mat1jaczyyy** [tetrio/issues#504]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Countries are sorted by local name in Tetra Channel, but displayed by English name. Resulting in some countries placed in odd spots.

### Reproducing
https://ch.tetr.io/players/

### Expected behavior
Proper country sort

### Screenshots
![image](https://user-images.githubusercontent.com/13300194/94918460-e8b81500-04b2-11eb-875e-207adb3b7239.png)

### Your setup
any

**Comment by o5k** [comment]
Hotfixed - F5 to receive the fix.
