### ISSUE TITLE
Garbage Handling Options

### ISSUE THREAD

**Issue by Neeko-iko** [tetrio/issues#507]
### Checklist (issue will be disregarded & closed if incomplete!)

- [ X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested. --- I did a small short search, if its already been requested by a different name feel free to close instantly
- [ X] I am using the **newest version** of TETR.IO.
- [ X] I am certain this is a **feature request**, not a bug.
- [ X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.

a LOT of people complain about garbage always being a little too forgiving especially with huge attacks.  "Spike Tennis" is a term used frequently.

could also be useful for casuals

### Describe the solution you'd like

Not everybody wants to have PPTs style of garbage (though i think it'd be nice as an option in custom games), but having a sort of algorithm to split up the straight lines might be nice

example: A TST sends 6 lines (assuming its not countering anything), instead of just sending a straight 6 it could split it up between 2 columns, sending a straight 3 to 1 column and another straight 3 to an adjacent column.  (doesn't always have to be half/half, it could even be random on how much it splits up, 40/60 might be good)

bigger and better attacks would send longer holes and potentially stretch across more columns depending on implementation.

### Describe alternatives you've considered

no garbage anymore sorry :(

**Comment by Neeko-iko** [comment]
bump so the bot doesn't get angry

**Comment by Neeko-iko** [comment]
bump

**Comment by KonSola5** [comment]
Recent TETR.IO update added the ability to change the garbage messiness, both during attack and between attacks.

So probably implemented.

**Comment by ZaptorZap** [comment]
I'm pretty sure this is a request for something described in [**(legacy)** Character System concepts](https://characters.osk.sh/#characters). Example:
![image](https://github.com/tetrio/issues/assets/64891705/f0ae35b7-3c31-47ee-b79d-57082f618809)
You can't strictly do this with the new options, but considering the lapse in activity I'm willing to close this anyways.
