### ISSUE TITLE
Quick player profile no longer shows APM/LPM

### ISSUE THREAD

**Issue by alex-ong** [tetrio/issues#508]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
In the 5 seconds before my match I like to see the LPM/APM of the player i'm vsing. This is more important to me
than their Blitz score

### Describe the solution you'd like
Keep Sprint time, but remove Blitz and revert back to LPM/APM of last 10 games as it was.

As a soft-dev, i also hate implementing shiny new features only to have entire userbase want it "just like it was"
:(

### Describe alternatives you've considered
Clicking their full profile takes too long to load

**Comment by Ads20000** [comment]
Fixed in [5.1.0 released today](https://tetr.io/about/patchnotes/)

![Screenshot from 2020-10-15 14-54-53](https://user-images.githubusercontent.com/3178485/96139151-7570c300-0ef6-11eb-89a2-df0f0140d481.png)
