### ISSUE TITLE
Disconnection

### ISSUE THREAD

**Issue by lirio22** [tetrio/issues#510]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Since there was that change on the nertwork code in Tetr.io I get randomly disconnected while I'm playing.

### Reproducing
1. Start a versus game
2. Sometimes there is that icon saying that it's trying to reestablish the connection
3. Usually it fails

### Expected behavior
Not disconnect while playing.

### Screenshots
![image](https://user-images.githubusercontent.com/26855589/95666419-c025c000-0b2f-11eb-8b95-c78e9424bea8.png)

### Your setup
 - Windows 10
 - Firefox 81.0.1 64bits

### Additional context
None

**Comment by o5k** [comment]
can you show me console logs? hit f12 and go to the console tab, ribbonjs is quite vocal in console logs about what it's trying to do

**Comment by lirio22** [comment]
I played another round after I printed the error, I hope the info you need is still there. There you go.

![image](https://user-images.githubusercontent.com/26855589/95666660-1dbb0c00-0b32-11eb-96e5-a6b8ed03e688.png)

**Comment by o5k** [comment]
well, it didnt disconnect entirely at that point, but what i can tell is that its a ping timeout
......theres very little i can do here, theres basically 3 possible causes
1) Cloudflare had a hiccup (this is very, very common, it's the entire reason this Ribbon thing exists), I may get my own websocket CDN at some point but I'd need a far larger money pool for that
2) The server is having trouble (while the backend is a mess rn and im redoing it, the server load looks nominal so i dont think thats it)
3) your connection is just bad.

im going with a connection of 1) and 3) here, very little I can do rn for you

**Comment by Mikalxzone** [comment]
This happens to me too and it's really annoying. 
I have a screenshot, hope this is enough information to fix this. It is not my internet problem either, I checked multiple times.
![image](https://github.com/tetrio/issues/assets/149622377/aab8cf0a-fbb6-4100-a843-8104b956ca15)
