### ISSUE TITLE
Downloading Tetr.io desktop app from Tetra Channel section

### ISSUE THREAD

**Issue by francocosta555** [tetrio/issues#511]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Downloading TETR.IO desktop from Tetra Channel webpage raises a 404 error.

### Reproducing
1. Go to '[https://ch.tetr.io](https://ch.tetr.io)'
2. Click on 'Download Button'
3. Get redirected to '[https://ch.tetr.io/about/desktop](https://ch.tetr.io/about/desktop)'
4. See 404 error

### Expected behavior
Download of the desktop TETR.IO desktop version.

### Screenshots
N/A

### Your setup
 - **OS and version**: Windows 10 
 - **Browser and version**: Opera GX LVL2 (core: 71.0.3770.234)

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
oops
