### ISSUE TITLE
High CPU usage desktop client

### ISSUE THREAD

**Issue by MedicOP** [tetrio/issues#512]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
TETR.IO uses 100% of 1 CPU core regardless of whether the game is in focus, in the menu or game screen, or what graphical settings are used. Also tried messing with desktop-client settings like frame limiter, disabling Discord integration, etc.

CPU usage is fine when using Safe Mode.

### Reproducing
1. Start up the game. Watch high CPU usage
2. CPU usage becomes normal when entering safe mode

### Expected behavior
CPU usage is low, especially when not even playing.

### Screenshots
It shows TETR.IO is using 25% CPU in Task Manager.

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Not applicable
 - **GPU**: GTX 1660Ti

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by dooglus** [comment]
I have the same issue on Debian Linux. All I need to do is run the desktop client and it starts using a lot of CPU. It keeps doing this until I quit the program. The game runs fine, but it causes the fan to run constantly. Here's a screenshot of 'htop' filtering on 'tetrio' after starting the game and leaving it to run without touching any inputs for a few minutes.

![Screenshot_2020-11-16_07-25-45](https://user-images.githubusercontent.com/573356/99273266-a25a1380-27dd-11eb-8a71-ba68a7e10090.png)

I've noticed this same behavior for several month now through multiple versions of the game. I always let it update itself when it wants to. I'm currently running v5.1.3-production, commit 674961. Here's the F8 info:

![Screenshot_2020-11-16_07-33-40](https://user-images.githubusercontent.com/573356/99273629-214f4c00-27de-11eb-925c-16f5ba7e40b7.png)

If I turn on "make tetr.io run slowly to keep other programs running smoothly" in config it cuts the CPU usage roughly in half, but still keeps the fan running constantly. The frame rate drops to 60 from ~90. I'm not sure I need 60 frames per second when the screen is static between games. Neither changing the graphics quality to 'minimal' nor switching between webgl modes fixes the problem either.

**Comment by o5k** [comment]
This should be fixed in the next version (5.2.0, client v5), which will drop in a little bit. Please let me know if it isn't, by then.
