### ISSUE TITLE
Add interface scaling option

### ISSUE THREAD

**Issue by leduyquang753** [tetrio/issues#513]
### Checklist

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Issue description
(*Is your feature request related to a problem? Please describe.*)

My laptop is not one of the beefy and newer ones out there, so I have to shrink the desktop client's window quite significantly to reduce the number of pixels needing being drawn and thus reduce the lag. However, the interface elements stay the same size as when the window was big, thus they have quite no space to go to.

I tried pressing `Ctrl` + `-` and `Ctrl` + `=` as what I would do on a browser, however the game doesn't make those available.

### Proposed solution
(*Describe the solution you'd like.*)

A slider should be added to the *Config* section to change the interface zoom, and/or `Ctrl` + `-` and `Ctrl` + `=` should be made available.

### Possible alternatives
(*Describe alternatives you've considered.*)

The interface scale can be made automatically adjusting based on the window size.

### Additional context
(*Add any other context or screenshots about the feature request here.*)

Current in-game screenshot when the window is small:

![image](https://user-images.githubusercontent.com/26449060/96130965-d0b8aa80-0f22-11eb-9aa7-52dbbeb1b56c.png)

In-game mockup:

![image](https://user-images.githubusercontent.com/26449060/96131983-0d38d600-0f24-11eb-9b60-971d85284ed4.png)

**Comment by InkstainTheBat** [comment]
I'd like this as well. My laptop's screen is small and, while the website is scaling correctly, fractional scaling doesn't seem to be applying to the app (wayland/hyprland on Arch)

**Comment by Sokuto-Desu** [comment]
I'm on Arch/Wayland/Plasma. Having this issue too, but instead the UI is too small. Wondering if this'll ever be fixed
