### ISSUE TITLE
Linear counter bonus when there's more player targeting you.

### ISSUE THREAD

**Issue by chiefnhanle** [tetrio/issues#516]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
So you know how when you join a quick play match and you can sometimes get targeted by 4 players at the same time and get spiked to death. Well, I don't think this is fair because why multiple people can target you at once and you can't do anything about it. In other Tetris game like Tetris 99, when players get targeted by multiple players at once, they receive a linear bonus on the number of lines they send out. This kinda create a stale meta because people will abuse this.
Example:
https://www.youtube.com/watch?v=cat9TbAwRWU

### Describe the solution you'd like
so my solution is simple. Make it so that players block more spikes with their own attack when they are CURRENTLY targeted by multiple people.
EG: player a get targeted by 4 players. now, his tsd will block 4*4(or some rate here, you can balance the game out) lines. This will allow a new dynamic, like players can now plan ahead with their game, to either sends attack or wait and block attacks but at the same time don't break the game, as this only affect that one individual player and if he can't block those attack, he will still lost what should happens normally.
please consider this change as it will help out intermediate players a lot, especially in quick play.

**Comment by rocamocha** [comment]
This would cause the problem of making quickplay just feel like a 1v1 essentially because now it just doesn't matter since the extra blocking power basically just makes it so you are only receiving the garbage equivalent of one opponent. For around B+ to S- rank gameplay I think it would take a lot of the fun out of quickplay when there isn't a U or X player in the room.
