### ISSUE TITLE
CORS causes backgrounds to silently fail

### ISSUE THREAD

**Issue by craftxbox** [tetrio/issues#522]
- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Background URL's with no CORS headers fail to load due to the CORS policy.

### Reproducing
1. Upload an image to a website without Access-Control-Allow-Origin CORS header
2. Set the background URI to the uploaded image
3. Open the inspector

### Expected behavior
CORS to not apply in this case, or atleast, to see an error that the image couldnt load.

### Screenshots
![](https://crxb.cc/klu79bhx)

### Your setup
 - **OS and version**: Win 10
 - **Browser and version**: Desktop Client 5.1.1-production Build Sr26gK4cS

**Comment by LayneTheEpic** [comment]
This is a known issue and is probably implemented for security reasons. From the start, it has been advised to use services that use proper CORS headers, such as [safe.fiery.me](https://safe.fiery.me). I do agree that there should be a better warning about not loading the image, though,

**Comment by craftxbox** [comment]
I don't believe there are any security implications here, The user is explicitly loading these files themselves, so CORS is useless here, as the user could just as easily sent the requests directly, instead of using the tetrio client. CORS isnt to pretect tetrio here, it's to protect the remote server.

**Comment by ZaptorZap** [comment]
As craftxbox implied, I do not believe this is about security either. In fact (the update that caused this requirement)[https://tetr.io/about/patchnotes/#chlog_1_0_2] seems to imply this is a performance fix.

**Comment by LayneTheEpic** [comment]
Hmmmmm, interesting

**Comment by craftxbox** [comment]
Yes, this is still relevant. One possible solution incase disabling the cors requirement isnt possible, is just to listen for the cors failure and notify on it.

**Comment by ZaptorZap** [comment]
Yep, this is still relevant. In fact, UniQMG has made [a standalone site](https://you.have.fail/ed/at/tetrio/backgrounds/) to help alleviate this issue, however, since it isn't the most popular or obvious website, this doesn't stop many users from complaining about their backgrounds failing to load on TETR.IO.

**Comment by Dimentio** [comment]
Added some feedback in upcoming patchnote!
