### ISSUE TITLE
 WebGL issue

### ISSUE THREAD

**Issue by Galactical4** [tetrio/issues#523]
### Checklist (issue will be disregarded & closed if incomplete!)

- [ √]  I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [ √] I am using the **newest version** of TETR.IO.
- [ √] I know **how to reproduce the issue**.
- [ √] I am using a **supported browser** or the Desktop Client.
- [ √] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [ √] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Currently I was trying to start playing TETR.IO. When I did turn on WEB GL the website still won't let me start the game even though I turn on the WEBGL. Second, I tried to enable HARDWARE ACCELERATION. HARDWARE ACCELERATION was already on. The game still won't let me start the game. My browser was currently up to date.
### Reproducing
2. Click on '...'
3. Scroll down to '...'

### Expected behavior
At least TETR.IO would let me play the game.

### Your setup
 - **OS and version**: MacOS High Sierra
 - **Browser and version**: Chrome Version 85.0.4183.83

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by ZaptorZap** [comment]
Hey there Galactical, could you type in `chrome://gpu` into the address bar and copy over the status of WebGL?

**Comment by Galactical4** [comment]
WebGL: Software only, hardware acceleration unavailable
Use hardware acceleration when available was on on Google Settings.

**Comment by ZaptorZap** [comment]
Alright so I have seen this issue around before. This message means your GPU is one of many on Google's GPU blocklist, however the blocklist can be manually disabled like so:
1. Head to `chrome://flags`
2. Go ahead and search for "override software rendering list" or "#ignore-gpu-blocklist"
3. Switch it from "Default" to "Enabled"
4. Restart every open instance of Chrome
TETR.IO should work now

**Comment by Galactical4** [comment]
It works, thanks
