### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by Niquolas** [tetrio/issues#526]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
Potentially, but it's more of a peace-of-mind thing rather than an issue that's affecting me. It's always nice to have 2FA available to avoid potential unauthorised account use. May be more useful for staff and verified users who are at a higher risk of account takeover.

### Describe the solution you'd like
Implement TOTP (e.g. Google Authenticator) two factor authentication for TETR.IO accounts.

### Describe alternatives you've considered
There's always the option of SMS or proprietary 2fa services, but these (a) cost money and (b) are either less secure or less accessible. 

### Additional context
Considering the backend is using Node.js, this package: https://www.npmjs.com/package/node-2fa may be useful

**Comment by craftxbox** [comment]
I dont like the idea of sms-based 2fa, not only would it cost extra for osk to utilize, it's also very, very incredibly more insecure than standard TOTP/HOTP. Carriers are known for replacing 'your' sim card without any proper verification, or even accepting number porting requests (!!!) without authorization.

**Comment by Niquolas** [comment]
>not only would it cost extra for osk to utilize, it's also very, very incredibly more insecure than standard TOTP/HOTP.

This is exactly why I'm suggesting TOTP

**Comment by SebatheDragonbear** [comment]
Google Authenticator Is broken, If you happen to do a factory reset on your phone, and you dont have anywhere to fall back to, say goodbye to your account

**Comment by Niquolas** [comment]
@SebatheDragonbear That's... what recovery codes are for

**Comment by SebatheDragonbear** [comment]
At the time my pc was formatted at the same time so the recovery codes were also gone

Cloud backups seems fine

**Comment by craftxbox** [comment]
If you lose your codes, It's your fault. Not the 2fa system's fault. Making it less secure or just... not including it because theres a chance someone can "accidentally" lose their codes AND recovery codes is just... stupid.

**Comment by SebatheDragonbear** [comment]
just the lone fact that that can happen makes It not worth it, Its ALL of your data, and then people dont do shit to transfer the accounts.

**Comment by Niquolas** [comment]
With all due respect, that is some of the most dreadful security advice I've ever heard.

**Comment by UniQMG522** [comment]
> just the lone fact that that can happen makes It not worth it, Its ALL of your data, and then people dont do shit to transfer the accounts.
> 
> At the end, the thing that is supposed to secure the data, makes it more subseptible to being lost

2FA is optional, you don't have to use it.

**Comment by craftxbox** [comment]
> just the lone fact that that can happen makes It not worth it, Its ALL of your data, and then people dont do shit to transfer the accounts.
> 
> At the end, the thing that is supposed to secure the data, makes it more subseptible to being lost

You wouldn't say a padlock is bad security because you can lose the keys, the same applies to 2FA.

**Comment by Niquolas** [comment]
thanks osk <3
