### ISSUE TITLE
School IP Address ban

### ISSUE THREAD

**Issue by CatManChaos** [tetrio/issues#528]
This isn't a bug but it is something I want you guys to know.
Me and everyone else in my school who plays on tetrio is either silenced, restricted or banned as tetrio thinks we are all playing on alternative accounts. but we are not as there are many students playing on the same IP Address so could you please unsilence/ban/restrict.
Thank you

**Comment by ZaptorZap** [comment]
Note that public IP's, such as the school you're using, are indeed mentioned on the official alt policy **[readable here.](https://tetr.io/about/rules/)**
Specifically:
![image](https://user-images.githubusercontent.com/64891705/97821801-9cc3e000-1cab-11eb-9eb5-f0e226057d3b.png)

Furthermore, the staff of TETR.IO (which I am **_not_** apart of) cannot act upon this issue without a Ban ID or IP to lookup.

**Comment by aidswidjaja** [comment]
This is an issue our school has too. Some guy decided he'd be a prick in chat 3 days ago, and my 3-day old account is now infinitely silenced. 

I don't think we could sacrifice moderation effectiveness in favour of letting kids like me game in class, but a warning on alt accounts would be a great idea to
- deter alt account users
- warn that an account may be immediately IP banned if they create their account.

**Comment by o5k** [comment]
why is this a bug report

**Comment by aidswidjaja** [comment]
Probably invalid label - would be better classified as an improvement / feature request @CatManChaos
