### ISSUE TITLE
Progress does not get saved on the desktop client or the website.

### ISSUE THREAD

**Issue by Captain-Hax** [tetrio/issues#529]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
It does not seem to save the time and score when playing 40L sprint or blitz, the screen goes blank after finishing and I have to close and reopen the browser if I want to play it again, when checking my scoreboard it does not show the time I just achieved.

### Reproducing
1. Play a full game of blitz or 40L solo.
2. By the end the screen will go blank and nothing will work.

### Expected behavior
It is supposed to show summary of the game I just played.

### Screenshots
https://imgur.com/a/eCUiX6W

### Your setup
 - Windows 10
 - Chrome 86.0.4240.111

**Comment by deltadex7** [comment]
Are you sure this is *not* a network issue? Typically I have this problem,
but the game is saved eventually. Sometimes I have to wait a whole minute
to show the results. This can happen (on my end at least) if I use a slow
network.

**Comment by o5k** [comment]
This would definitely be a network issue, as everyone else seems to be able to submit them fine, and your browser setup isnt unusual

If it's still happening, comment with a console log
