### ISSUE TITLE
issue playing game on linux

### ISSUE THREAD

**Issue by Pretuer** [tetrio/issues#530]
### Describe the bug/issue
When installing the .deb version of Tetr.io on a non-Ubuntu platform it buggs out. I am running [Parrot OS](https://parrot.sh) all other games I try to play work very well for me and I don't get any issues. I recently installed the game on my Machine and it wouldn't open at all. I then attempted to open in in the terminal then I got this response

`[63144:1102/181929.343283:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/TETR.IO/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
`

### Reproducing
1. Go to 'Parrot OS home/Security (install game)'
2. Type 'tetrio-desktop' in the terminal
3. See error

### Expected behavior
error pops up
### Your setup
 - **Parrot OS (Latest)**: 
 - ** Brave (Latest)**:

**Comment by tnorris** [comment]
I may have a workaround for you!

> You need to make sure that /opt/TETR.IO/chrome-sandbox is owned by root and has mode 4755.

The following invocations will do that:
```
sudo chown root:root /opt/TETR.IO/chrome-sandbox
sudo chmod 4755 /opt/TETR.IO/chrome-sandbox
```

**Comment by szymonszl** [comment]
you shouldnt have to suid an electron binary, just run with `--no-sandbox` instead (which should actually be set automatically, so it's a bug)
my chrome-sandbox is not suided, and tetrio runs just fine, and the argument is properly set
