### ISSUE TITLE
Tetr.io Running in the Background after Closing the Window

### ISSUE THREAD

**Issue by csq-curiosity** [tetrio/issues#531]
### Checklist (issue will be disregarded & closed if incomplete!)

- [O] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [O] I am using the **newest version** of TETR.IO.
- [✕] I know **how to reproduce the issue**.
- [O] I am using a **supported browser** or the Desktop Client.
- [O] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [O] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
There are instances of tetrio running in the background despite that I have closed the window. This can be detected by tetrio consuming huge amounts of CPU and... in some cases by your computer overheating.

### Probable cause
_This is a speculation. Why or how the bug occurs (or even **when** it started to occur) is not very clear at this time, as it seems to be inconsistent to reproduce. It is also most likely impossible to read the console logs because... well there is no window to hit ctrl shift I in the first place._

Tetrio's proper termination of the app is intended to be Exit icon from the main menu, at which the game prompts "Exit tetr.io?" pop-up in app. Usually, the same pop-up appears when you try to end the app by pressing the x icon on the title bar, given that you play on windowed mode and not fullscreen. However, when you press x, there are cases that tetrio's window is closed without the pop-up prompt, including but not limited to:
- Game lagging severely
- Pressing x before the game fully loads (this includes the login screen)
- Pressing x _multiple times_ (necessary condition) after the "Exit tetr.io?" pop-up prompt appears
- Game seemingly _forgetting_ the pop-up prompt for no apparent reason (indicated by the game waiting few seconds before closing the window)
Most of the time game is terminated with the window closing. However, it seems like somewhere along the lines the message gets lost and tetrio continues to run in the background, using CPU to do things to the window... that doesn't exist.

### Expected behavior
It is expected that all tetrio processes are terminated properly and not to be run on the background.

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Chrome 86

### Additional context
- The nature of the bug likely indicates that this only affects the desktop version only.
- If you launch a new tetrio while having the "background tetrio" running, it is deemed as a separate process. Hence, interacting with the new tetrio doesn't affect the background tetrio in any way, which includes the termination.

**Comment by csq-curiosity** [comment]
Updated the main thread with new info regarding the bug.

Idk if it would help, but I found some minor things on the task manager. Basically, tetrio runs multiple sub-processes in the background (averaging 5~6 and up to 10+) and this is indicated by the number next to the app if you're watching task manager on advanced. When tetrio is improperly closed and causes the background running bug, it is almost always the process(es) that consumes a significant amount of CPU that remains. (around 30% in my case) I believe this is important to note, because there aren't many sub-processes that consumes a lot of CPU. (2~3 at least when I inspect tetrio in the task manager while running)

Also I was fortunate to stumble upon this bug again shortly after I reported. IIRC the last tetrio session I played ended uneventfully, leaving multiplayer room, bringing me to the multiplayer menu. (Tetra League/Quick Play/Make room/Custom room selection) It was at this precise moment that I closed the tetrio window by pressing x on the title bar, triggering the "Game forgetting the pop-up prompt" event. There is not much I know that could have gone wrong other than what I just noted, as this is the only notable "sign" of the bug possibly triggering.

**Comment by ZaptorZap** [comment]
Just found this issue after I went digging for similar reports on the TETR.IO [Discord server.](https://discord.gg/ufDb2XJ) I've personally haven't experienced this issue as I don't use the desktop client very often, but I've talked to many who have. I'm just gonna post all of their issues here so it's clear this isn't a local issue for @csq-curiosity and nobody else.
From the oldest post i've found with a blanket "running background" search, dated the ninth of October, 7:03PM UTC [as posted by Leo_#3955:](https://discord.com/channels/673303546107658242/673303546564968566/764201406227283979)
> need help
> ![image](https://cdn.discordapp.com/attachments/673303546564968566/764201544521875516/unknown.png)
> tetrio is not even open
> running in background :thonk:

Dated the second of November, 3:23PM UTC [as posted by Vojta#9179:](https://discord.com/channels/673303546107658242/673303546564968566/772843235068084318)
> just running in the background bcs why not i guess
> ![image](https://cdn.discordapp.com/attachments/673303546564968566/772843233167540234/unknown.png)

That same day, this very issue, issue #531, would be created. Dated the sixth of November, 9:23 PM UTC [as posted by smk#0745:]
> so many people have experienced tetrio still running in the background right? just wondering

My response at the time:
> yeah i've seen others have the issue but i've never had it myself, milk

smk:
> ah
> i recently found myself with it after multiple instances were running in the background

Dated the twenty-first of November, 3:35 PM UTC, [as posted by Kenrryr Lauren#7671:](https://discord.com/channels/673303546107658242/673303546564968566/779550596633460757)
> Tetrio Desktop Just starts himself suddenly and consumed 4GB ram lol
> I didn't even Play it today

My response back then:
> ohhh yeah you might wanna kill tetrio from the task manager then
> it shouldn't be running in the background

Kenrryr Lauren#7671:
> Yeah but, it started suddenly
> I was playing Genshin and almost died for the lag

Dated the twenty-first of November, 9:22 PM UTC, [as posted by Thiena#9740](https://discord.com/channels/673303546107658242/673303546564968566/779637809722949674)
> aaa wtf where did this tetrio ghost process come from
> i thought it wouldn't get me
> but it did
> .-.
> i swore i close it way earlier
> which is weird
> maybe i'm tripping balls
> but yeah it was using 11gigs or memory or some shit
> and i'm like
> THE FUCK?

Dated the twenty-forth of November, 4:18AM, [as posted by ploo#3831](https://discord.com/channels/673303546107658242/673303546564968566/780648469655453717)
> ![image](https://cdn.discordapp.com/attachments/673303546564968566/780648467088932884/unknown.png)
> ![image](https://cdn.discordapp.com/attachments/673303546564968566/780648500014743592/unknown.png)
> e
> i didnt even know it was open
> i havent opened tetrio in like a day
> and it just happened to me a few minutes ago

After this report by ploo, I decided to round em all up and comment it out here. I *theorize* that killing TETR.IO's service workers from the devtools could help with this problem. As I understand it, service workers run in the background, so perhaps TETR.IO is failing to kill them all when the game is told to shut down. This would explain why I myself haven't ran into this issue, as I frequently use TETR.IO+ which disables all service workers by default. Of course there's the slight downside of killing offline support, as TETR.IO relies on these service workers to work offline from what I can tell.

**Comment by DontTouchAnything** [comment]
![image](https://user-images.githubusercontent.com/42194320/100065754-2e81c180-2e02-11eb-83de-4a2c93d57887.png)
![image](https://user-images.githubusercontent.com/42194320/100066146-aea82700-2e02-11eb-9ff8-df4372c4cc9a.png)

**Comment by o5k** [comment]
This should be fixed in the next version (5.2.0, client v5), which will drop in a little bit. Please let me know if it isn't, by then.
