### ISSUE TITLE
You can hear others' next pieces.

### ISSUE THREAD

**Issue by craftxbox** [tetrio/issues#532]
- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
With `Hear next piece` enabled, when in a 1v1, the next pieces of your opponent are heard aswell as your own.
This does not happen when not in a 1v1, or with 'Show duels side-by-side' disabled.

### Reproducing
1. Enable 'Hear next piece' in audio settings
2. Get into a 1v1.

### Expected behavior
To only hear your own next pieces.

### Your setup
 - Windows 10 2004
 - Desktop client v4, 5.1.2-production commit 1b43539

**Comment by Niquolas** [comment]
Have you got "Hear Other Players" turned on?

**Comment by craftxbox** [comment]
Yes, I can confirm it doesn't happen with it off. I guess this technically is 'working as intended' then? but i still think that hear next should be excluded from hear others

**Comment by Niquolas** [comment]
Might want to wait and see if @o5k has an answer in that case.

**Comment by o5k** [comment]
Fixed in next version.
