### ISSUE TITLE
Orange Selector Gets Stuck on "My Page"

### ISSUE THREAD

**Issue by TheDuck8283** [tetrio/issues#533]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When the orange selector hovers over "My Profile" in Tetr Channel > Me, input freezes completely, requiring you to use the mouse. 

### Reproducing
1. Go to 'Tetr Channel'
2. Click on 'Me'
3. Scroll down to 'My Page' (with the orange selector hovering over it)
4. Notice that you cannot move the orange selector anymore, plus selecting other options with the orange selector and going back doesn't work.

### Expected behavior
You are supposed to be able to move the orange cursor to select the options in the menu. Going back should also work.

### Screenshots
Screenshot of the bug:
![image](https://user-images.githubusercontent.com/70354525/98194254-2fe35c80-1edc-11eb-9bd9-417cb03212ee.png)

### Your setup
 - **OS and version**: Windows 10 2004
 - **Browser and version**: Tetr.io Desktop

### Additional context
When trying to move the orange selector it may make the sound of it moving.

**Comment by o5k** [comment]
Does left/right work?

**Comment by o5k** [comment]
oops didnt mean to close

**Comment by TheDuck8283** [comment]
@o5k I just tested it right now, left and right doesn't seem to work. I'm actually pretty unsure if this is just on my end because now it only lets you move the orange selector for a few seconds. It's probably just me :|
