### ISSUE TITLE
TETR.IO won't work

### ISSUE THREAD

**Issue by chilledfork** [tetrio/issues#536]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [ ] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
TETR.IO won't open on the client. It works on the browser, it just doesn't work on the client. I tried to reinstall the game but it didn't work. It just says it's installing and doesn't do anything; I checked in Task Manager to see if it really was installing by checking the disk usage but it wasn't using almost anything. Before I tried to reinstall the game, it would get stuck in the "Looking for updates" screen, after a few minutes it would go to the "Loading TETR.IO" screen and even though i waited over 10 minutes it wouldn't even say that it tried to load at least 2 times. The 3 times it actually loaded it would say that there was an error loading it and that there's something very wrong going on. I read the first 5 pages of issues and I don't think anyone has mentioned this.

### Reproducing
1. Open TETR.IO. I have no idea what caused this to happen.

### Expected behavior
The game would open smoothly, ask me to log in and allow me to play.

### Screenshots
I haven't taken any screenshots.

### Your setup
 - Windows 10 build 2004
 - TETR.IO 4.0

### Additional context
I deleted the entire game directory to reinstall it so I also deleted the logs. :(

**Comment by o5k** [comment]
check firewall?

**Comment by chilledfork** [comment]
I allow my firewall on every application I use. I checked it, probably not what's causing it.

**Comment by Halleyakutake** [comment]
i have the same issues but i fixed it by just waiting and ill log you on on the game. I think its because its trying to connect to the servers you're in. So wait patiently about 1-5minutes
