### ISSUE TITLE
Skip countdown in solo games

### ISSUE THREAD

**Issue by pedrominicz** [tetrio/issues#537]
### Checklist

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
It is nice to be able to play solo games while match making. However, the countdown on solo games takes too much time in this scenario, specially since games don't take long to find.

### Describe the solution you'd like
Add an option to skip the countdown at the start of solo games.

### Describe alternatives you've considered
Write a Greasemonkey script to remove it or play Tetris in another app.

### Additional context
There are two pre-game animations: the game name and the countdown. It would be nice to be able to disable both separately. Disabling both would allow for super quick solo games starts. That would be pretty cool.

**Comment by ZaptorZap** [comment]
Hey Pedro, have you tried toggling the "Stride Mode" checkbox before you hit "START" on the Blitz or 40 Line sprint modes? They speed up the start and restart animations *greatly.* Alternatively, have you considered setting up a solo custom game for this sort of thing? You can entirely disable every entry animation from the "META" tab available in that mode.
![image](https://user-images.githubusercontent.com/64891705/98489895-c343c700-2227-11eb-9d28-1d746e8fdec2.png)
(Each highlighted setting is one I changed. With them on, they accomplish this request.)

**Comment by pedrominicz** [comment]
Thanks @ZaptorZap, the alternatives proposed word perfectly. Good to see the game already possesses this functionality.
