### ISSUE TITLE
Audible hissing on latest & recommended AMD drivers

### ISSUE THREAD

**Issue by ThatBebx** [tetrio/issues#538]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
"Hissing" plays constantly in the background of tetr.io alongside all other audio. This issue is worsened when image sharpening is enabled, playing another set of hissing that isn't typically audible in the intro logo cutscene. This is also exclusive to the client and does not occour on the web edition of tetr.io.

### Reproducing
1. Ensure you are on recent AMD drivers
2. Launch tetr.io, and listen closely
3. Hear background hiss 

### Expected behavior
There should not be background hiss in tetr.io, and it should sound exactly like it does on the web client.

### Screenshots
Unfortunately, this issue does not show in video. However, it is extremely noticible when hearing.

### Your setup
 - **OS and version**: Windows 10 version 1909
 - **Browser and version**: Firefox version 82.0.2
- **Relevant hardware specifications**: CPU: AMD 2600; GPU: RX 5700XT
- **Drivers edition**: 20.9.1

### Additional context
I do remember that this was not an issue on older driver versions. This just started one day and I don't remember what caused it. But after doing some testing, it is plain to see that it *is* the AMD drivers that cause this. Enabling sharpening adds hiss where there usually is not, and uninstalling my drivers completely removes the hiss. It also tanks FPS. Go figure.

**Comment by deedeeen** [comment]
How else would you describe the _hiss_ and would you care to record it outside of the game client, id est using an external microphone unrelated to the targeted computer?
