### ISSUE TITLE
Bring Tetr.io to Steam

### ISSUE THREAD

**Issue by zhongdeliu** [tetrio/issues#540]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
As a lot of people, myself included, are managing their games with a launcher, e.g. Steam. It would be great to have Tetr.io their, too.

### Describe the solution you'd like
Tetr.io is available in Steam. Maybe with some more Steam integration mechanism? 

### Describe alternatives you've considered
Current workaround is to add Tetr.io as a NonSteam Game. However this doesn't help with connecting other people/friends etc...

### Additional context
This request is focuses on Steam. Of course their are other launchers as well....

**Comment by o5k** [comment]
ehhhhhh, while being on Steam does open up a large potential stream of new players, it also means you have to keep up w/ Steam policies and the such, and become notoriously susceptible to takedowns from a certain company.. id rather not risk that
