### ISSUE TITLE
Undo feature for zen mode

### ISSUE THREAD

**Issue by mpayne77** [tetrio/issues#543]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

I'd love to see an "undo" feature in zen mode where you can roll back and retry a single piece, or maybe even multiple pieces. Basically <ctrl-z> but for tetrominos. Would be really helpful for practicing new setups/openers/strats/etc. in zen mode.

**Comment by Gabba727** [comment]
this would be vary cool to see, and would be vary helpful for practice tool there are already things like four-tris that allow you to do this but it would be so nice if it were supported natively.

**Comment by kylescousin** [comment]
This option would be so useful... Especially in modes where you get alerts on finesse fault.

**Comment by xXbaodeptraiXx** [comment]
yeah it would be awesome for practicing, i would love to have this, like in fourtris

**Comment by Dimentio** [comment]
Added in next update!

**Comment by rajun274** [comment]
Hot damn, amazing!! Thank you!

**Comment by xXbaodeptraiXx** [comment]
> Added in next update!

wait what really? when?
