### ISSUE TITLE
drastic memory usage increase after playing tetra league games

### ISSUE THREAD

**Issue by PastMoments** [tetrio/issues#545]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
After finishing a tetra league game, memory usage increases by approximately 200 MB. This increase appears to be unbounded. This was discovered after a crash on the desktop client with the message "WebGL is disabled on your browser". After checking with the task manager, the process was using up 8557 MB of memory.

### Reproducing
1. Observe memory usage in lobby
2. Play a tetra league game
3. Repeat to observe unbounded memory usage

### Expected behavior
Memory usage should not increase like this.

### Screenshots
After starting the program, in the menu.
![image](https://user-images.githubusercontent.com/3858420/99198970-ed3a4380-2769-11eb-80c9-cb3155f1db7f.png)

After two Tetra League games, in the menu.
![image](https://user-images.githubusercontent.com/3858420/99198942-c714a380-2769-11eb-8adc-d9c2fea265d5.png)

After the crash.
![image](https://user-images.githubusercontent.com/3858420/99198921-a9473e80-2769-11eb-9fa2-0a4fb7be02e9.png)

### Your setup
Windows 10.
Desktop Client 5.13

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
This should be fixed in the next version (5.2.0, client v5), which will drop in a little bit. Please let me know if it isn't, by then.

**Comment by CATboardBETA** [comment]
I am also having this issue, still. Please look into fixing this. Tetrio goes from ~1GB to anywher from 4-7GB after only a few Tetra League matches.
