### ISSUE TITLE
Video freezes upon alt-tabbing out

### ISSUE THREAD

**Issue by Shadowtail117** [tetrio/issues#546]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When alt-tabbing out and back into the game as a match is about to start, there is a chance that the video of the game freezes. Audio and controls work fine, but nothing can fix the video freeze except force-closing the application. **This even applies to Tetra League matches and I've had to quit in the middle of them twice now because of this.**

### Reproducing
1. Be in a lobby (or searching for a Tetra League match) and alt-tab out of the game to another application.
2. As the countdown to start the game starts (or the you vs. opponent screen shows up for Tetra League), go back to Tetr.io.
3. The video of the game will irreversibly freeze while the controls and audio will still work.

### Expected behavior
Ideally, it should not freeze.

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Desktop (main browser is Chrome 86)

**Comment by AKJee** [comment]
Meet same thing every time I do alt+tab, but not only when search, lobby, but any time when game open, example on vid - blitz

[Vid](https://drive.google.com/file/d/1s4Us2JHpL8zlZjv35Gi4pXBSEeldGRoD/view?usp=sharing)
*after 1:00 just complaining in url bar so skip :)

**Comment by Mykesss** [comment]
same problem V4 had this problem as well but it fixed it itself after restarting V5 just freezes everytime i go to other windows

**Comment by AKJee** [comment]
> 
> 
> V4 had this problem as well but it fixed it itself after restarting

Same for me tho

**Comment by Jason-S-Wu** [comment]
I am having the same issue for v5 as well.

**Comment by Pulucas** [comment]
have the same problem as author. Video freezes, and game is still running because i can hear it. For me, It's happening while i'm in a lobby, and that lobby ends. The game freezes on that ending screen. I am on m1 mac, so I can't say anything about it being an alt-tab thing.
