### ISSUE TITLE
desktop client process does not terminate after the program is closed

### ISSUE THREAD

**Issue by PastMoments** [tetrio/issues#547]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
As in the title, there is sometimes still a process running after the game is closed.

### Reproducing
1. Open the program
2. Play some games
3. Close the program
4. Check task manager

### Expected behavior
All TETR.IO processes should terminate.

### Screenshots
![image](https://user-images.githubusercontent.com/3858420/99248942-4a201300-27d7-11eb-8d77-0105b9095555.png)

### Your setup
 Windows 10.
 Desktop client.

### Additional context
Can't reproduce 100% of the time, but will encounter it regularly.

**Comment by csq-curiosity** [comment]
Looks like a dupicate of #531

**Comment by o5k** [comment]
This should be fixed in the next version (5.2.0, client v5), which will drop in a little bit. Please let me know if it isn't, by then.
