### ISSUE TITLE
Make Multiplayer Room IDs Non-Case Sensitive

### ISSUE THREAD

**Issue by dginovker** [tetrio/issues#548]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Describe the solution you'd like
When my friend says the room is "AJZK", I'd like to be able to type "ajzk" instead of using all caps

### Describe alternatives you've considered
Idk but it's pretty sick that # can be omitted

### Additional context
Especially great QOL for newbies

**Comment by o5k** [comment]
Added in next version!
