### ISSUE TITLE
WebGL no longer works in Firefox 83

### ISSUE THREAD

**Issue by DaMatrix** [tetrio/issues#549]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [ ] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Just upgraded Firefox to version 83.0, and tetr.io no longer works. I don't know whether or not Firefox is even supported (it's mentioned in the issue template that I should be using a "supported browser", but I couldn't find a list of "supported browsers", only something that *recommends* that I use something Chromium-based). Anyway, I now get the following message when trying to load the game:

```
TETR.IO requires WEBGL

it seems WEBGL is disabled in your browser. WEBGL is required for the game to render properly.

please check your browser settings to ensure WEBGL is enabled in your browser, then try again.

this often happens if HARDWARE ACCELERATION is turned off in your browser. try enabling it in browser settings.

if nothing works, try upgrading your browser
```

It worked fine before updating, and I know WebGL is working correctly (I tried a number of WebGL tests/benchmarks and all of them ran flawlessly).

### Reproducing
Install Firefox 83.0 and try to use tetr.io...

### Expected behavior
That it'd work

### Screenshots

![error message](https://i.daporkchop.net/jDOMbOLL.png)

### Your setup
 - **OS and version**: kubuntu 20.04
 - **Browser and version**: Firefox 83.0+build2-0ubuntu0.20.04.1

**Comment by Tisawesomeness** [comment]
I can also confirm this bug, since tetr.io was working before Firefox updated and broke after the update. Currently on the same firefox version, ubuntu 20.04. It works on Chromium 87.0.4280.66, so the issue seems to be specific to Firefox. Can anyone on Windows test this?

**Comment by UniQMG522** [comment]
Not seeing any issue on W10 on Firefox 84.0b2 (beta channel)

**Comment by ziggystar** [comment]
I've tracked it down to the following problem:

* Under linux hardware-compositing is disabled (by platform). This can be checked under `about:support`
* It can be forced under `about:config` using `layers.acceleration.force-enabled` and restarting firefox. Then tetr.io works as expected

The big question for me is, why did the check start failing? Was it a change in Firefox, or was it a change in tetr.io. Also apparently tetr.io has been running fine for me before forcing the compositor to be enabled. Is this check needed at all? Does it come from some library?

**Comment by Tisawesomeness** [comment]
In the console I have
`Failed to create WebGL context: failIfMajorPerformanceCaveat: Compositor is not hardware-accelerated.`
The debugger shows pixi.js threw the error, and since the page source says pixi was compiled in April, I doubt it's a change in tetr.io. We'll need to take up the issue with Firefox.

**Comment by DaMatrix** [comment]
>     * It can be forced under `about:config` using `layers.acceleration.force-enabled` and restarting firefox. Then tetr.io works as expected

thank you for this! i figured there would be a temporary workaround like this, but had no idea where to look. hopefully an official fix arrives soon.

**Comment by roynico** [comment]
I confirm the issue. I also get the error message since I updated to FF 83.0 (64-bit)

**Comment by o5k** [comment]
This seems to be due to a change through https://bugzilla.mozilla.org/show_bug.cgi?id=1679671 - I have found a bypass though which will go in effect next patch
