### ISSUE TITLE
In-game Chat Commands Create A Link To A Player Card That Doesn't Exist

### ISSUE THREAD

**Issue by ZaptorZap** [tetrio/issues#550]
### Checklist (issue will be disregarded & closed if incomplete!)
- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.
-----
### Describe the bug/issue
Upon using a chat command, you may receive a message in chat from "user" "`[CMD]`' with additional information. If you click `[CMD]`'s "username", TETR.IO will attempt to load `[CMD]`'s player card, which does not exist as brackets are not valid username symbols. 
### Reproducing
1. Log Into TETR.IO as either a registered account, or an unregistered anon.
2. Head into the "MULTIPLAYER" menu.
3. Either create a private room, or join a public custom room from the ROOM LISTING, or join QUICK PLAY, or find a TETRA LEAGUE match.
4. Click on chat, found in either the bottom right or bottom left corners.
5. Type in a command that'll get `[CMD]` to respond, such as "/help" or "/kagari"
6. Click on `[CMD]`'s name, and witness TETR.IO attempt to load its player card 
### Expected behavior
Perhaps you should still be able to hover on `[CMD]`, and even click on it to open a special player card verifying that that is indeed a system message and not some fake account. 
### Footage
![24, 08;53;23](https://user-images.githubusercontent.com/64891705/100071165-a667e000-2e32-11eb-9ade-370fa1abf4a6.gif)
(a looping gif of steps 5 and 6)
### Your setup
 - **OS and version**: Windows 10 Version 2004
 - **Browser and version**: Firefox 81.0.2
### Additional context
Worth mentioning there's a "`[SYS]`" "user" as well. It only shows up for global announcements such as big tourneys starting and ending, and miscellaneous announcements such as planned server maintenance periods, big milestones, etc. I could see this issue being applicable to this chat curiosity as well, however I cannot test with this special chat message considering I'd have to wait great amounts of time to report this issue :p
![image](https://user-images.githubusercontent.com/64891705/100068057-eb8a1300-2e2e-11eb-86db-2766e05ee592.png)
(pictured above, the `[SYS]` account announcing TETR.IO passing 100k players [as posted by user lightshatterz#2041](https://discord.com/channels/673303546107658242/673303546564968566/736280641502707714) on the TETR.IO [Discord server](https://discord.gg/ufDb2XJ))

**Comment by o5k** [comment]
Fixed in next version!
