### ISSUE TITLE
Attack of all clear wasn't offset

### ISSUE THREAD

**Issue by Pantaris** [tetrio/issues#551]
### Describe the bug/issue
Attack of all clear by me wasn't offset on TETRA LEAGUE.
But it by enemy attacked me.

### Reproducing
It is difficult to reproduce and not done.

### Expected behavior
Our attacks is offset.

### Screenshots
https://youtu.be/LASrfEpHFS8?t=6248

### Your setup
 - **OS and version**: [e.g. Windows 10]
 - **Browser and version**: [e.g. Vivaldi 3.0.1874.38 (Stable channel) (64-bit)]

### Additional context
I don't have log.

**Comment by o5k** [comment]
This is called **passthrough** and is an intended feature. A special sound plays when this occurs. To avoid it, simply time better - take good notice of when the attack _actually hits your board_, and only then attack. That said, this feature it pretty controversial, discussed more in #435

**Comment by Pantaris** [comment]
Thanks o5k.
I don't think a puzzle game needs such action elements.
