### ISSUE TITLE
Report Hackers in Tetrio

### ISSUE THREAD

**Issue by MasterofFire9999** [tetrio/issues#553]
There seems to be hackers in Tetrio, since if you look at the leaderboards the top one does not even look like a human playing. He only went for back-to-back tetrises while score does NOT matter in a 40-line. And also I joined a public room and the host  ALWAYS won. And then doesn't chat at all and also he always places/moves blocks at the same time. I think if you add a report button, you can ban these hackers and make the playing field fair to everyone.

**Comment by UniQMG522** [comment]
These are legitimate replays. Back to back quads on column 7 are the most efficient way to stack. (They're not the most efficient way to gain score in blitz though). The public room also likely isn't a hacker, but if you do believe they're hacking there's an in-game report button on their profile.

**Comment by MasterofFire9999** [comment]
Sorry I did not see that button.

**Comment by ZaptorZap** [comment]
To access their profile, click on their name either in the chat, the player list, or head to the ingame TETRA CHANNEL section and type their name into the only field provided. it should be quite obvious where the report button is from there:
![image](https://user-images.githubusercontent.com/64891705/100494760-b3d7df80-313c-11eb-891e-26dce1d6c1a9.png)

**Comment by o5k** [comment]
[It's real, you can be this good!!](https://www.youtube.com/watch?v=MJDz4-pr9J4)

That said, there is a reporting function, since hackers do exist - see above.
