### ISSUE TITLE
Game freeze before/after playing any multiplayer match in Linux

### ISSUE THREAD

**Issue by myr1299vfx** [tetrio/issues#555]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
The game (and my device) freezes right before the match starts and after the match finish, happens in any multiplayer modes. tried to open the game from Terminal and got this log after freezing:

`tetrio-desktop
xdg-settings: default-url-scheme-handler not implemented for xfce
(node:2144) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (/opt/TETR.IO/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (events.js:417:26)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:2144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2144) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

### Reproducing
1. Open the game
2. Play any multiplayer match several times

### Expected behavior

- the game freezes right before the match countdown starts
- the game freezes 1-3 seconds after the match finished.

### Screenshots
![log](https://user-images.githubusercontent.com/75353665/100839242-78277780-34a6-11eb-9c9c-8b2ed400899d.png)

### Your setup
 - Manjaro Linux 20.2

**Comment by o5k** [comment]
This may be fixed soon (once the next version, 5.2.0 (client v5) drops). Please let me know if it isn't.
