### ISSUE TITLE
Attempting to join room multiple times sometimes hangs on 'joining room' instead of erroring

### ISSUE THREAD

**Issue by UniQMG522** [tetrio/issues#557]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Seems like the `you are already in this room` error commands aren't sending or are getting dropped. Seems to fail *most* of the time. Reproducible from both client and bot.

### Reproducing
1. Create a room
2. Attempt to join it from a second tab

### Expected behavior
Server should send a `you are already in this room` error

### Your setup
 - **OS and version**: W10
 - **Browser and version**: Firefox 84.0b3, Ribbon-based client

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)
<details>
  <summary>Bot logs + screenshot</summary>
<img src="https://user-images.githubusercontent.com/48872143/102144897-26bea700-3e1b-11eb-830a-43ae8c920c15.png"></img>

<pre>
Ribbon null reconnecting in 5ms (reconnects: 1)
2020-12-14T22:42:30.747Z null in {
  command: 'hello',
  packets: [],
  id: 'bcc267092bcce3ef',
  resume: '4828dccba8adbd5b66dab55844352ed4fa138d905f52acd76bec5bd57bf67c42'
}
Ribbon bcc267092bcce3ef opened
2020-12-14T22:42:31.187Z bcc267092bcce3ef out {
  id: 1,
  command: 'authorize',
  data: {
    token: '&lt;removed&gt;',
    handling: { das: 0, arr: 0, sdf: 0, safelock: false },
    signature: {
      mode: 'production',
      version: '5.1.3',
      countdown: false,
      commit: [Object],
      serverCycle: 'tFOIyndcf',
      build: [Object],
      process: 467383
    },
    i: undefined
  }
}
2020-12-14T22:42:31.370Z bcc267092bcce3ef in {
  id: 1,
  command: 'authorize',
  data: {
    success: true,
    maintenance: false,
    worker: { name: 'rewrite-chihaya', flag: 'NL' }
  }
}
State changed: READY
joining room
2020-12-14T22:42:31.373Z bcc267092bcce3ef out { id: 2, command: 'joinroom', data: 'UBWF' }
waiting for joinroom
2020-12-14T22:42:31.548Z bcc267092bcce3ef in {
  id: 2,
  command: 'migrate',
  data: {
    endpoint: 'wss://tetr.io/ribbon-lucia',
    name: 'rewrite-lucia',
    flag: 'NL'
  }
}
Ribbon bcc267092bcce3ef changing endpoint (new endpoint: wss://tetr.io/ribbon-lucia)
Ribbon bcc267092bcce3ef closed (ping timeout)
Ribbon bcc267092bcce3ef resuming
2020-12-14T22:42:32.211Z bcc267092bcce3ef in {
  command: 'hello',
  packets: [
    { id: 1, command: 'authorize', data: [Object] },
    { id: 2, command: 'migrate', data: [Object] },
    { id: 3, command: 'migrated', data: [Object] }
  ],
  id: 'bcc267092bcce3ef',
  resume: '4828dccba8adbd5b66dab55844352ed4fa138d905f52acd76bec5bd57bf67c42'
}
Ribbon bcc267092bcce3ef resumed
2020-12-14T22:42:35.465Z bcc267092bcce3ef in { command: 'pong' }
2020-12-14T22:42:40.529Z bcc267092bcce3ef in { command: 'pong' }
2020-12-14T22:42:45.463Z bcc267092bcce3ef in { command: 'pong' }
2020-12-14T22:42:50.454Z bcc267092bcce3ef in { command: 'pong' }
2020-12-14T22:42:55.465Z bcc267092bcce3ef in { command: 'pong' }
2020-12-14T22:43:00.466Z bcc267092bcce3ef in { command: 'pong' }
</pre>
</detail>

**Comment by o5k** [comment]
wait i thought i closed this

**Comment by o5k** [comment]
(was fixed a while ago, was indeed error messages getting dropped causing the client to just kinda... wait)
