### ISSUE TITLE
Mod/Verified application

### ISSUE THREAD

**Issue by HyperfireRS** [tetrio/issues#560]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.

- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
I just want to be able to apply for moderator or verified badge.

### Describe the solution you'd like
I want an applications page.

### Describe alternatives you've considered
Mods to be serious when i ask for help about this

### Additional context
none!

**Comment by HyperfireRS** [comment]
hi

**Comment by HyperfireRS** [comment]
hello?

**Comment by iloverenge** [comment]
Please tell me if you ever figure it out
