### ISSUE TITLE
Countdown for game start plays when you enter Spectator mode mid-game

### ISSUE THREAD

**Issue by GlitchyPSIX** [tetrio/issues#562]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Even though the game is already playing when you spectate mid-game, the countdown to start the game starts regardless.

### Reproducing
1. Enter a live match **that is already in progress** (Quickplay, for example)
2. Click on "Spectate" to join as spectator mid-game
3. Click a board if in Grid mode
4. Wait.

### Expected behavior
There is no countdown instead.

### Screenshots
[Quick recording of the reproduction steps being followed](https://i.imgur.com/WytZqbD.gif)

### Your setup
 - **OS and version**: Windows 10 Home
 - **Browser and version**: Opera 72 (Chrome 86)

**Comment by o5k** [comment]
Hotfixed - F5 to receive the fix.
