### ISSUE TITLE
Resizing the window breaks the game

### ISSUE THREAD

**Issue by b4u7** [tetrio/issues#563]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
After updating the game from v4 to v5, whenever I open it and resize the window, shortly after the game has finished loading, the UI doesn't resize/update but there's still sounds and I can still click on buttons even though the UI itself doesn't change. After this I am only able to close the game via the taskbar manager and by doing so the game throws an error.
This doesn't happen if I wait a few minutes after the game as finished loading.

### Reproducing
1. Open the game
2. Resize the window shortly after the game has loaded

### Expected behavior
The UI should resize to fit the window resolution and the game should be playable

### Screenshots
![image](https://user-images.githubusercontent.com/10912932/102492965-5adbd700-406a-11eb-839c-1f4e90f4875c.png)
![image](https://user-images.githubusercontent.com/10912932/102493145-a55d5380-406a-11eb-8daa-099254bc4a0a.png)

### Video showcase
URL: https://imgur.com/14ljX23

### Your setup
 - Windows 10 64 bits Version10.0.19041 Build 19041
 - Desktop Client v5

**Comment by o5k** [comment]
Can anyone else reproduce this? I cannot...

**Comment by ovandermeer** [comment]
A similar thing happens to me when I try to fullscreen the game with F11. The game just freezes, and I need to stop the Tetr.io desktop client from task manager. It doesn't give me an error, it just permanently freezes without fullscreening

**Comment by unnamedau** [comment]
I had this problem right after updating to v5 - I usually play fullscreened and wasn't able to make it past the changelog. The game is still responsive (hovering over where the buttons are still changes the mouse cursor, and with a bit of muscle memory I can get it to quit), there's just no video updating. This also seems to be Desktop Client-exclusive if it helps, nothing of the sort happens in my browser.

**Comment by AngelMashiro** [comment]
I too have a similar issue. When I start up the game everything seems to be running fine and I can actually play the game, however, when I tab out and tab back in the UI just doesn't seem to update. I play on fullscreen as well, switching to windowed with F11 does the same thing. When I start the game in windowed the game does seem to be running fine and I can tab out and tab back in without any issue, until I try fullscreening again.

**Comment by GertjanDS** [comment]
Exact same issue here. Loading the game non-fullscreen and then resizing it to any other window size leaves visuals hanging. Game is still responsive and cursor is updated when hovering over buttons but have to completely kill the game with task manager and restart to let the video update again. I'm on latest version of the desktop client.

**Comment by o5k** [comment]
Seems to be a bug in Electron 11. I will publish tetrio-desktop v6 as an optional update in a few minutes, which will run on Electron v9 (same version as tetrio-desktop v3). Let me know if you still see the same issue then.
