### ISSUE TITLE
Add possibility to retry in settings test

### ISSUE THREAD

**Issue by hickatheworld** [tetrio/issues#568]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
It is not a problem itself, but I think that we should be able to restart the game in Settings test. Likewise, it would be preferable to have the game restarting when you lose it, instead of being brought back to the settings page. While testing new settings, you're likely to make mistakes in the game and to want to restart easily, instead of having to forfeit and restart when you missplace. Testing with a messy board isn't practical.

### Describe the solution you'd like
The Settings test game should act, basically, like Zen mode. Then, pressing the `Retry game` hotkey would just clear the board and the next pieces to come. And, like in Zen again, just clear the board when you reach the top. You'd leave the test game using your `Forfeit game` hotkey.

### Describe alternatives you've considered
There is no real alternative to this. Perhaps, making the game act like 40l/Blitz when losing the game and giving you the choice to either Retry or go back to settings page, but this isn't an enjoyable ux in my opinion.

### Additional context

**Comment by Dimentio** [comment]
Added in next update!
