### ISSUE TITLE
active playing games do not show when spectating 1v1. only the chat sidebar shows

### ISSUE THREAD

**Issue by trogfield** [tetrio/issues#569]
when spectating in 1v1 in a 2 player max game with spectators, the active playing games do not show. only the chat sidebar shows.

this happened after i force quit the app when playin a ft3 game to give the other player host, then played 1v1 against him, then spectated a 1v1 once, then both players disconnected somehow. I think the room some how was active with 0 people in it. i rejoined, spectated, and no games showed. i closed the app, rejoined and the current game showed, but the next remade game did not show.

running windows 10 updated
desktop app
running on surface pro 7

trigger of bug not known

erase and reinstall not tried

![image](https://user-images.githubusercontent.com/22109189/102619873-f9f7e180-40f1-11eb-953f-0fe2719015b6.png)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [ ] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Reproducing
2. Click on '...'
3. Scroll down to '...'

### Your setup
 - **OS and version**: [e.g. Windows 7]
 - **Browser and version**: [e.g. Chrome 76]

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)
![image](https://user-images.githubusercontent.com/22109189/102619868-f6fcf100-40f1-11eb-8b82-82f0b819b020.png)

**Comment by o5k** [comment]
Seems to be a bug in Electron 11. I will publish tetrio-desktop v6 as an optional update in a few minutes, which will run on Electron v9 (same version as tetrio-desktop v3). Let me know if you still see the same issue then.
