### ISSUE TITLE
dragging app from 1824k to 4k screen make game unresponsive

### ISSUE THREAD

**Issue by trogfield** [tetrio/issues#571]
dragging app from 1824 to 4k screen make game unresponsive

restarting fixes the problem

sometimes the game works when dragging from screen one to screen 2

pressing windows key left to move screen to display 2 might sometimes work

i did not try this with a 1080p external display

running windows 10 updated
desktop app
running on surface pro 7

trigger of bug not known

erase and reinstall not tried

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Reproducing
2. Click on '...'
3. Scroll down to '...'

### Your setup
 - **OS and version**: [e.g. Windows 7]
 - **Browser and version**: [e.g. Chrome 76]

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
Seems to be a bug in Electron 11. I will publish tetrio-desktop v6 as an optional update in a few minutes, which will run on Electron v9 (same version as tetrio-desktop v3). Let me know if you still see the same issue then.

**Comment by trogfield** [comment]
> Seems to be a bug in Electron 11. I will publish tetrio-desktop v6 as an optional update in a few minutes, which will run on Electron v9 (same version as tetrio-desktop v3). Let me know if you still see the same issue then.

I haven't used the same tv to see if it crashes. It probably is fixed, and is a minor bug that probably nobody will encounter. Thanks for the fast response!
