### ISSUE TITLE
game controller does not work most of the time when surface keyboard connected

### ISSUE THREAD

**Issue by trogfield** [tetrio/issues#572]
game controller does not work most of the time when surface keyboard connected

the surface typecover/ keyboard is detected as a game controller. 

connecting the typecover then a xbox wireless controller with usb makes the game controller not functional.
disconnecting both then reconnecting the game controller makes the game controller work.

disconnecting both then reconnecting the keyboard makes the keyboard work

not known if this issue happens when launching the game with both the keyboard and controller connected.

this issue should not matter because nobody uses the surface pro 7

running windows 10 updated
desktop app
running on surface pro 7

trigger of bug not known

erase and reinstall not tried

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Reproducing
2. Click on '...'
3. Scroll down to '...'

### Your setup
 - **OS and version**: [e.g. Windows 7]
 - **Browser and version**: [e.g. Chrome 76]

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
Merging this into #396
