### ISSUE TITLE
The game board sometimes becomes upside down

### ISSUE THREAD

**Issue by Enter-tainer** [tetrio/issues#573]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [ ] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue

The game board sometime becomes upside down, like this:

![SS{H990M%{X WW5NPR_UQRA](https://user-images.githubusercontent.com/25521218/102624029-66b8bd80-417e-11eb-8b68-25d697cb728b.jpg)
![image](https://user-images.githubusercontent.com/25521218/102624124-89e36d00-417e-11eb-92ac-6bed102fd1a5.png)

### Reproducing

Sorry but I don't actually know how to reproduce. But it seems that this bug occurs after switching between windows (when playing online games). After this bug is triggerd, all games started afterwards will become upside down.

Though it can be funny to face this bug in solo mode, I encountered this bug when I was in a Tetra League Game.😂

### Expected behavior
The board should be in correct orientation.

### Screenshots
See above sections

### Your setup
 - **OS and version**: Windows 10 2004
 - **Browser and version**: Tetr.io desktop client 5.2
![image](https://user-images.githubusercontent.com/25521218/102624412-f2cae500-417e-11eb-8d69-c48172399847.png)

### Additional context
I will provide console messages the next I see this bug.

It seems that this bug is newly introduced. I only see this kind of situation after I update my client yesterday.

**Comment by Enter-tainer** [comment]
UPD(browser log):

```
tag.min.js:3 fun-hooks: referenced 'registerAdserver' but it was never created
(anonymous) @ tag.min.js:3
tag.min.js:82 
    AdinPlay v2.0 ✰ TTI ✰ v4.10.0 aip     ads by http://www.adinplay.com/     
VM122:7652 webgl backend was already registered. Reusing existing backend factory.
t.registerBackend @ VM122:7652
VM122:7652 cpu backend was already registered. Reusing existing backend factory.
t.registerBackend @ VM122:7652
VM122:7652 Platform browser has already been set. Overwriting the platform with [object Object].
t.setPlatform @ VM122:7652
VM122:7658 TETR.IO
VM122:7658 Please be careful when pasting anything in the console. Attackers may be out to steal your login information.
VM122:7658 Using the Desktop Client
VM122:7658 Up to date. Local version 5.2.0-production | Commit 9098aed (12/18/2020, 7:22:10 AM) | Server cycle ZkTSGYqZE | Build HTzRCtq82 (12/18/2020, 7:33:24 AM)
VM122:7658 PixiJS 5.2.2 - WebGL 2
VM122:7658 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tetrio-desktop/5.0.0 Chrome/87.0.4280.88 Electron/11.1.0 Safari/537.36 -CPU: 16-coreMemory: ~8 GBConnection: 9.1 Mbps, 0ms RTT [4g]
VM122:7658 Renderer: ANGLE (AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0)
VM122:190 Ribbon cb91aa2acd616bda opened
VM122:387 Ribbon cb91aa2acd616bda changing endpoint (new endpoint: wss://tetr.io/ribbon-shizuru)
SwitchEndpoint @ VM122:387
VM122:161 Ribbon cb91aa2acd616bda closed (ribbon lost)
VM122:167 Ribbon cb91aa2acd616bda resuming
VM122:190 Ribbon cb91aa2acd616bda resumed
256[.WebGL-000001C8456C0890] GL_INVALID_OPERATION: Object cannot be used because it has not been generated.
tetr.io/:1 WebGL: too many errors, no more errors will be reported to the console for this context.
DevTools failed to load SourceMap: Could not load content for https://tetr.io/tf.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by Enter-tainer** [comment]
Another bug might be related is that, when playing, my board suddenly disappears.

![image](https://user-images.githubusercontent.com/25521218/102637311-c3bd6f00-4190-11eb-9f98-abf4f42c4a24.png)

**Comment by o5k** [comment]
Seems to be a bug in Electron 11. I will publish tetrio-desktop v6 as an optional update in a few minutes, which will run on Electron v9 (same version as tetrio-desktop v3). Let me know if you still see the same issue then.
