### ISSUE TITLE
dying without reason

### ISSUE THREAD

**Issue by benjiman16** [tetrio/issues#575]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x ] I am using the **newest version** of TETR.IO.
- [x ] I know **how to reproduce the issue**.
- [x ] I am using a **supported browser** or the Desktop Client.
- [x ] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x ] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
when i am near the top, and i have been recently my game calls the defeat. whilst im still playing 

### Reproducing
1. Go to '..replay file. R:Ck6AmQvbZ

 '
2. Click on '.. the very last game.'
3. Scroll down to '.the lst few seconds of the game..'

### Expected behavior
i expected to place my O piece. get a t-spin and keep playing the game

### Your setup
 - **OS and version**: [ubuntu 20.04]
 - **Browser and version**: [chromium 87.0.4280.88]

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)
i have the ttrm file with the replay also.

**Comment by o5k** [comment]
Ah, you pressed HOLD:
![](https://kagari.online/yoda_hatsue.png)

Pressing HOLD would overlap with the stack, as I've shoddily drawn here:
![](https://kagari.online/akamine_ryoko.png)

So, this game over condition is correct. That said, I do plan to have an auditory and visual warning if pressing HOLD will kill you (e.g. a warning triangle over the hold box, or smth like that).

**Comment by benjiman16** [comment]
Hey OSK

Thanks a lot my man, I never even thought about that, thanks for the quick
response (: good luck further bettering tetrio and the Tetris scene (:


Op vr 18 dec. 2020 23:39 schreef osk <notifications@github.com>:
