### ISSUE TITLE
Rotation not working while pressing another key

### ISSUE THREAD

**Issue by Trixciel** [tetrio/issues#579]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Rotations don't work when pressing another kay at the same time on tetrio browser

### Reproducing
- Play a game of tetrio in a browser
- Press and hold a letter key down 
- Push a rotation key (cw, ccw, 180)
- See the error

### Expected behavior
The piece should rotate, but it doesn't.
The bug only works on tetrio in a browser.

### Your setup
 - **Windows v1909**: [e.g. Windows 7]
 - **Opera GX v2**: [e.g. Chrome 76]

### Additional context
None

**Comment by o5k** [comment]
Cannot reproduce this at all, sorry

**Comment by iMiluum** [comment]
Sorry, I know that this is 4 years old but I want to leave this comment here for future reference: Microsoft PowerToys' quick accent feature can interfere with your arrow keys. 

If you have this issue, check your 3rd party software; it may likely be the culprit.
