### ISSUE TITLE
Replay loads fail

### ISSUE THREAD

**Issue by sc2ad** [tetrio/issues#580]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
After saving any MULTIPLAYER replay via the Desktop application, loading fails.

### Reproducing
1. Play a multiplayer match on the desktop application
2. Complete the match and download the replay. Manually specify the extension of the file as a `.ttr` (otherwise TETR.IO will say it does not recognize the file)
3. Exit multiplayer and return to the main menu. Attempt to load the replay, which will provide you with an error.
4. The specific error is: "File load failed!" and it occurs when attempting to load the replay on both the PC application and on the web browser.

### Expected behavior
The replay to be loaded and be able to be played. I do not expect there to be an error when loading a replay saved from TETR.IO itself.

It should also be noted that single player replays work perfectly fine, which is understandable given the error from the console.

### Screenshots
![image](https://user-images.githubusercontent.com/10663758/102762181-c5bc3500-432c-11eb-8a64-e78a96fae8b0.png)
This image is after attempting to load three unique replays _in the desktop application_ downloaded from the results screen of a multiplayer match.
![image](https://user-images.githubusercontent.com/10663758/102762396-1469cf00-432d-11eb-999a-5a2594d18aee.png)
This image is after attempting to load one of the three replays _in browser_ downloaded from the results screen of a multiplayer match.

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Used Desktop Application. When reproduced in browser, used: Google Chrome: 87.0.4280.88

### Additional context
![image](https://user-images.githubusercontent.com/10663758/102762229-d8366e80-432c-11eb-96e7-ccf7c0fc0a1f.png)
![image](https://user-images.githubusercontent.com/10663758/102762396-1469cf00-432d-11eb-999a-5a2594d18aee.png)
Also note that _singleplayer_ replays work fine (if you go into 40 lines, for example, they load just fine on both the browser and desktop, assuming you properly change the extension of the downloaded file from the desktop application to `.ttr`)

In addition, I have NOT yet tried to see if this still occurs when downloading the multiplayer replays from the results screen from the web browser version, I will follow up on this issue once I have.

I have also attached the replays I used below, feel free to laugh at my poor play and fantastic names (assuming you can watch them) ;)
[TetrReplays.zip](https://github.com/tetrio/issues/files/5723536/TetrReplays.zip)

**Comment by ZaptorZap** [comment]
Multiplayer replays are actually defined with the `.ttrm` file extension, which these files seem to be missing. Renaming the file to include this previously absent "m" fixes this issue quickly as shown in the video attached below:
https://user-images.githubusercontent.com/64891705/102763679-ece92580-4371-11eb-85e1-0f78c92a32c7.mp4

**Comment by sc2ad** [comment]
Ah. So it seems the underlying reason here is actually the fact that the desktop application doesn't like to specify what extension to save the replays under. Thanks for the quick response, I appreciate it!
