### ISSUE TITLE
Alt account linking for improved accountibility

### ISSUE THREAD

**Issue by DontTouchAnything** [tetrio/issues#581]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

While playing on an alt in order to improve my PCs by not completing a round unless I PCOed, I thought about how accountability may be a problem in the future if keeping track of the integrity of players becomes a larger burden on administration. Though I cannot speak for osk or the staff that make this community possible, here is a concept I conjured.

I think a smart idea would be to have in the future alt accounts linked to main accounts. On the player side, this would allow seamless switching without logging out. On the administration side, alt accounts could be identified and tracked by main account names with more accountability. 

Linking accounts would also make it easy to add additional features. Level or account age restrictions could be put in place. Players could describe the intention of the account for more transparency. In order to not clutter the player database, if someone wants to try a new strat or playstyle, they could recycle their account by requesting a stat reset. And gameplay modifications could be slapped on alt accounts for ease of use. e.g. Hard drop disabled for soft drop only alts.

This concept may be too much of a long shot and some elements might be totally unnecessary, but it might lower player and administration burden in the future.

Thanks for checking this out!

**Comment by o5k** [comment]
Issue has become irrelevant w/ new policy
