### ISSUE TITLE
ReferenceError: event is not defined Basilisk/Pale Moon

### ISSUE THREAD

**Issue by micwoj92** [tetrio/issues#583]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [ ] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Tetr.io does not accept inputs on Linux on UXP based browsers; Pale Moon and Basilisk.

### Reproducing
1. Go to https://tetr.io/
2. Start any game
3. Game will not receive inputs

### Expected behavior
Moving pieces

### Your setup
 - **OS and version**: Arch Linux
 - **Browser and version**: Basilisk 2020.11.25 and Pale Moon 28.17.0

### Additional context
bunch of `ReferenceError: event is not defined` errors

**Comment by o5k** [comment]
Seems to affect supported browsers FF56 as well, investigating

**Comment by o5k** [comment]
Hotfixed - F5 to receive the fix.

**Comment by micwoj92** [comment]
Yup it works fine on both browsers now. I have 2 questions, where can one see supported browsers list and if there's a chance of these browsers being added to said list?
