### ISSUE TITLE
Zen start animation is unnecessarily long

### ISSUE THREAD

**Issue by rednir** [tetrio/issues#584]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
Currently it takes 7 seconds of waiting to load into zen if started from the main menu, which gets mildly annoying after a while. Zen is a very casual mode that doesn't require a countdown.

### Describe the solution you'd like
Removal of the countdown and the "ZEN" text.

### Describe alternatives you've considered
Stride mode, like 40L and Blitz. Perhaps this could also get rid of the hold to reset.

**Comment by DontTouchAnything** [comment]
And don't forget, the between level animation is also quite a nuisance.

**Comment by SebatheDragonbear** [comment]
I consider that the Long animations and the wait time adds to the Zen experience
I wish there were more options to enhance this like adding custom ARE and line ARE on the zen menu

**Comment by deedeeen** [comment]
You have more time to set everything up in that 7s. That's enough time to do stuff, LOL.

**Comment by rednir** [comment]
You can set options at any point during gameplay if you need to. Besides, if you don't need to change any settings, you would still be forced to sit through the 7s waiting time with I personally think is counter-intuitive.

Perhaps the gravity should temporarily be set to 0 if you are hovering over the options sidebar? So if people need time to set options, they can do that without relying on the countdown.

**Comment by Clauvin** [comment]
Suggestion: make the animations togglable at the Options menu, this way those who like the animation and timer and those who dislike those can both have what they want.
