### ISSUE TITLE
Topped Out after doing a mini T-spin and canceling it outside the 10x20 grid

### ISSUE THREAD

**Issue by Andrematomer** [tetrio/issues#586]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Topped Out around 1 second after doing a mini T-spin and canceling it outside the 10x20 grid/ play area

### Reproducing
1. Stack high.
2. Create a mini T-spin set up outside the 10x20 grid without getting topped out.
3. Do a mini T-spin and cancel it.
4. Move the T piece to a safe place. (dropping the T-piece is not required)
5. Topped Out.

### Expected behavior
The game keeps going.

### Screenshots

https://user-images.githubusercontent.com/76654693/103173990-1386ef00-4891-11eb-86da-0676dbabbe3d.mp4

### Your setup
 - Windows 10
 - Chrome on Windows | 87.0.4280.88

### Additional context
Tested in Zen with 0 gravity.

**Comment by o5k** [comment]
I can't seem to replicate this:

https://user-images.githubusercontent.com/52112045/103174112-c63e5980-485f-11eb-8c6f-3cbc339e4aff.mp4

Are you sure it's not locking in at the top? After 15 rotations/movements, a piece will instantly lock in if it's touching anything, unless you're using **subzero** gravity.

**Comment by o5k** [comment]
In your video, it kinda looks like you accidentally held right too long, and your piece DAS'd _onto_ the I-pieces. That's also why it's not visible at all - it locks out enterely outside of the screen.

**Comment by Andrematomer** [comment]
I did a further testing and I think you're right. The T-spin doesn't matter. It's just any piece placed outside visible area. Which means my report is invalid and sorry for wasting your time.

**Comment by Andrematomer** [comment]
But this lead to another question. Why the piece locked with 0 gravity? Is that another bug or intended?

**Comment by Neeko-iko** [comment]
> Are you sure it's not locking in at the top? After 15 rotations/movements, a piece will instantly lock in if it's touching anything, unless you're using **subzero** gravity.

in short, yes, that's intended for **0** gravity.
