### ISSUE TITLE
Add option to play Zen Mode while waiting to find match for Multiplayer

### ISSUE THREAD

**Issue by yolita15** [tetrio/issues#588]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
Sometimes, when you are playing Multiplayer Tetra League Mode, you are waiting for a **long** time to find a match. 

### Describe the solution you'd like
It would be nice to have an option to play **Zen Mode** while waiting for a match like when you are in a room of players and you are waiting for the game to start again.

**Comment by p1nkl0bst3r** [comment]
You can play all the solo modes while waiting for a Tetra League match.

https://user-images.githubusercontent.com/45999708/103357741-37764a80-4ab4-11eb-9506-42e4db2956eb.mp4

**Comment by yolita15** [comment]
I meant adding a button like in the rooms - "Play zen while waiting"
