### ISSUE TITLE
Issue with particular replay

### ISSUE THREAD

**Issue by SRVirtual** [tetrio/issues#591]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When playing this particular replay, after selecting the 'Jump to next round after end' button while looking at the second round, it just exit the replay after it ends, not jumping to the third round. While playing the first round, after the end of the replay, it will automatically jump to second round, as it should be.

### Reproducing
1. Open this particular replay; https://tetr.io/#R:VOoQEkZDG
2. Play the replay from the first or second round, with 'Jump to next round after end' feature activated.
4. See the error when the second round ends.

### Expected behavior
The replay suddenly exit itself after the end of the second round.

### Screenshots
![image](https://user-images.githubusercontent.com/76832683/103434697-92847a80-4c37-11eb-9521-b7007ce195ec.png)

https://user-images.githubusercontent.com/76832683/103434804-e774c080-4c38-11eb-9267-9892f66e275f.mp4

### Your setup
 - Windows 10 64-bit
 - Using both the Microsoft Edge Version 87.0.664.66 (Official build) (64-bit) and the latest TETR.IO Desktop Client

### Additional context
Can contact me via reply if the link already expire, I'll send the replay file.

**Comment by o5k** [comment]
oh oops this was fixed a bit ago already I think
