### ISSUE TITLE
Tetrio Desktop V6 Incorrect Dialog Due to Update

### ISSUE THREAD

**Issue by DontTouchAnything** [tetrio/issues#595]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Loading tetrio desktop v6 after skipping the update dialog in the latest version causes the game to loop "Installing a required update" dialog. Console says the desktop version is out of date with the server.

This issue is similar to #594 but I feel because this is on desktop, it should have its own container.

### Reproducing
1. Open desktop V6
2. Skip update

### Expected behavior
The dialog should tell players that V6 is not supported.

Running V7 avoids this.

### Screenshots
![image](https://user-images.githubusercontent.com/42194320/103559544-4b3ef980-4e84-11eb-9fdb-fcfaea0e17dd.png)

### Your setup
 - **OS and version**: [Win 10]
 - **Hamburger**: [Desktop V6]

### Additional context
have a blessed day

**Comment by o5k** [comment]
This is fixed in v7, hence why the issue doesn't appear in v7
