### ISSUE TITLE
Tetrominoes unintentionally moving sideways during a hard drop

### ISSUE THREAD

**Issue by CorentinJ** [tetrio/issues#600]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported, the closest I found is #305.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When hard dropping a tetromino then pressing a sideway movement key, the tetromino will sometimes move sideways even though I pressed the hard drop key before the movement key. This happens in a single frame, so the piece is dropped one block off its shadow in the previous frame. I believe the same can happen with rotations, but I don't have enough evidence for that.

### Reproducing
Using the settings I gave below, hard drop piece quickly followed by a sideway movement.

### Expected behavior
I'd expect tetrominoes not to move sideways during a harp drop.

### Screenshots
Here are my settings:
![image](https://user-images.githubusercontent.com/12038136/104813393-432e7480-5809-11eb-8122-b51a22adf00d.png)
Here is an example of the issue happening, see the timestamp between each image, they are just one frame apart.
![image](https://user-images.githubusercontent.com/12038136/104813407-59d4cb80-5809-11eb-9eb4-2c1407faaeda.png)

### Your setup
 - **OS and version**: Win 10
 - **Browser and version**: Chrome 87.0.4280.141 64 bits

**Comment by LieutenantLark** [comment]
I've noticed this happening as well, i just thought it was me pressing too many buttons  :}

**Comment by CorentinJ** [comment]
Some of my friends have it as well. I'm forced to put my movement settings to something much slower, it's really frustrating. On jstris this problem does not occur at all.

**Comment by o5k** [comment]
send a replay file or consider staying there

**Comment by p1nkl0bst3r** [comment]
This happened to me today.
replay file: [lBCbuzBTM.ttrm.txt](https://github.com/tetrio/issues/files/5928132/lBCbuzBTM.ttrm.txt)
replay link: https://tetr.io/#R:lBCbuzBTM
It happened in round 4 at frame 9970.
Excerpt from the replay file (this time looking at the right person):
```
{'frame': 9960, 'type': 'keydown', 'data': {'key': 'moveLeft', 'subframe': 0.4}}
{'frame': 9970, 'type': 'keydown', 'data': {'key': 'hardDrop', 'subframe': 0.4}}
{'frame': 9975, 'type': 'keyup', 'data': {'key': 'moveLeft', 'subframe': 0.4}}
{'frame': 9976, 'type': 'keyup', 'data': {'key': 'hardDrop', 'subframe': 0.5}}
```

**Comment by subortc** [comment]
I also noticed some slipperiness of the pieces in TETRIO, but it also exists in Jstris if you put a large das and arr and try to put pieces during shifting(holding L/R) (I may be wrong, maybe I have a bad reaction or something else),but if you compare it in TETRIO it is felt much more often than in Jstris and there is some instability that knocks your keeping PPS

**Comment by o5k** [comment]
Just looked at the replay, this is working exactly as expected. Your DAS is 10F.
You press the moveLeft key at frame 9960.4. 10F later, so at 9970.4, the piece will move again.
9970.4 passes, and the piece moves left. On that same subframe, you press the hardDrop key, also at frame 9970.4.
So, the game is working as intended. 10 frames passed, so your DAS triggers!

**Comment by spudpiggy** [comment]
I'm gonna necro this: I can't play on my Wii Classic Controller because I keep accidentally pressing up left and accidentally hard dropping. Please add a toggle to disable diagonal hard drops like Tetris Effect has. It really helps with sensitive dpads.
