### ISSUE TITLE
Incorrectly Sized Playfields in Super Lobby

### ISSUE THREAD

**Issue by orangetriangle** [tetrio/issues#601]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When resizing the browser during Super Lobby, the background playfields, and occasionally the tetrominoes in the playfield in focus, are incorrectly sized.

### Reproducing
1. Go to a Super Lobby
2. Resize your browser window
3. Observe that the size of the background playfields is incorrect; however, newly spawned background playfields are sized properly. Occasionally, the tetrominoes in the playfield in focus are also incorrectly sized.

### Expected behavior
The boards should be sized properly.

### Screenshots
![bug](https://user-images.githubusercontent.com/77557642/104828539-8522df00-5838-11eb-8310-9972e98db811.PNG)

### Your setup
 - Windows 10
 - Chrome 87.0.4280.141

**Comment by orangetriangle** [comment]
still relevant

**Comment by Dimentio** [comment]
I've not seen this issue mentioned in a long time, I cannot reproduce it anymore on my side so I assume it got fixed, feel free to re-open if still occurring!
