### ISSUE TITLE
Anti-Smurf in Tetra Leage

### ISSUE THREAD

**Issue by LieutenantLark** [tetrio/issues#604]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
Tetra League is a game mode everyone (including alt accounts (or smurfs)) can join. This is unfair as i have played 5 different smurf accounts in tetra league, and therefore lost 500 points.

### Describe the solution you'd like
An anti-alt account tetra league addition that prevents alt account from joining that playlist until they login to their primary account.

This would prevent smurf accounts from even playing tetra league, therefore making tetr.io a better, more fair environment.

### Describe alternatives you've considered
Not Applicable

### Additional context
I really hope this gets fixed, osk.

**Comment by o5k** [comment]
The alt finder cannot be run on such an automatic basis, aside from false positives

Expect a policy change very soon though
