### ISSUE TITLE
Topping out when it shouldn't

### ISSUE THREAD

**Issue by p1nkl0bst3r** [tetrio/issues#605]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Died while being able to survive.

### Reproducing
1. Go to https://tetr.io/#R:_SBhexGym
2. End of the 5th match
3. Didn't hard-drop and the S-piece didn't touch another piece.

### Expected behavior
https://knewjade.github.io/fumen-for-mobile/#?d=v115@TewhIewhGeRpwhi0DeRpwhRpg0AtBeQ4hlQ4RpBtBe?R4glB8AeI8AeI8AeI8AeI8AeJ8AeI8AeI8AeI8AeI8AeI8A?eH8AeO8AeI8AeI8AeI8AeA8JeAgHvhHX3H07HJOIdTIudIS?kIsiIAgH
This way it would counter it.

### Screenshots
![image](https://user-images.githubusercontent.com/45999708/105098187-fd440b80-5aa9-11eb-81f5-f36909bcab98.png)
ttrm file: [_SBhexGym.ttrm.txt](https://github.com/tetrio/issues/files/5838916/_SBhexGym.ttrm.txt)

### Your setup
 - **OS and version**: Manjaro Linux
 - **Browser and version**: Desktop client

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
if you let the replay play until end, you can see you dont choose to counter, and instead drop the piece somewhere random and top out
note that when replay lengths dont match, Pause On Replay End may not show the very last frame for both replays

**Comment by p1nkl0bst3r** [comment]
When I looked in the ttrm file the last key press was: {"frame":2369,"type":"keyup","data":{"key":"moveLeft","subframe":0.2}}
Why doesn't it show me dropping the piece?

**Comment by o5k** [comment]
because you were looking at the wrong person

**Comment by p1nkl0bst3r** [comment]
I see now, sorry for wasting your time.
I thought since the replay ended at frame 2369/2370 that the last key press would be there. 
But you are right:
`{"frame":2378,"type":"keydown","data":{"key":"moveLeft","subframe":0.9}},{"frame":2386,"type":"keydown","data":{"key":"hold","subframe":0.9}},{"frame":2386,"type":"keydown","data":{"key":"hardDrop","subframe":0.9}},{"frame":2386,"type":"end","data":{"reason":"garbagesmash","export":{"successful":false,"gameoverreason":"garbagesmash"`
