### ISSUE TITLE
TETR.io Doesn't Save Handling Controls After Computer Restart (or shutoff)

### ISSUE THREAD

**Issue by LieutenantLark** [tetrio/issues#606]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
After restarting my computer (Chromebook), all of my handling controls are reset to default values.

### Reproducing
1. Go to 'TETR.IO' on a Chromebook
2. Set some handling controls
3. Restart computer
4. Go back to tetr.io, and login
5. play some zen (or something else) and notice that all settings were erased.

### Expected behavior
I expected my account settings to be the same after a computer shutoff or restart.

### Screenshots
Not Applicable

### Your setup
 - **OS and version**: Chrome 87
 - **Browser and version** :Google Chrome 87.0.4280.152 (latest version)

### Additional context
Not Applicable

**Comment by csq-curiosity** [comment]
*Possibly* related to #7 and #245.

Restarting computer doesn't reset controls for me though, so could this be either a Chromebook issue or something that causes to clear browser cache data when restarting the computer?

**Comment by LieutenantLark** [comment]
>so could this be either a Chromebook issue
i'm pretty sure Chromebooks save all cache on restart or reboot

>or something that causes to clear browser cache data when restarting the computer?
If it cleared all cache, my graphics and control settings would also change (which they don't) so i am unsure what the problem is.


Whatever it is, im sure it can be fixed somehow.

**Comment by o5k** [comment]
Are you sure this isn't also happening to other settings? This seems like a Chromebook setting

**Comment by LieutenantLark** [comment]
I have no clue, honestly
