### ISSUE TITLE
i cannot login

### ISSUE THREAD

**Issue by n0tmystic** [tetrio/issues#609]
### Checklist (issue will be disregarded & closed if incomplete!)

- [ ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [ ] I am using the **newest version** of TETR.IO.
- [ ] I know **how to reproduce the issue**.
- [ ] I am using a **supported browser** or the Desktop Client.
- [ ] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [ ] I am certain this is a **bug**, not a feature request.

-----

### Reproducing
2. Click on '...'
3. Scroll down to '...'

### Your setup
 - **OS and version**: [e.g. Windows 7]
 - **Browser and version**: [e.g. Chrome 76]

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by ZaptorZap** [comment]
The screen you should be prompted to enter a username in actually doubles as a login form (the one shown below):
![image](https://user-images.githubusercontent.com/64891705/105784791-55f22900-5f2e-11eb-9334-9d36d05c4e3b.png)
To login, enter your account's username, then its password, as shown in the video below:
https://user-images.githubusercontent.com/64891705/105784815-6904f900-5f2e-11eb-96c6-584f5e7b65f0.mp4
If you're not seeing this screen, then there's a good chance your browser is failing to load TETR.IO in the first place. Check the console (F12) for any errors.
