### ISSUE TITLE
Have a changeable resolution of the game

### ISSUE THREAD

**Issue by Kouji25** [tetrio/issues#611]
A feature where you can change the resolution of the game so that it can run smoother(will result to blurrier game tho)
This is helpful for those low end devices such as mine : )

**Comment by o5k** [comment]
This exists already, as a toggle under Video settings.

**Comment by Kouji25** [comment]
> This exists already, as a toggle under Video settings.

what I mean is to change the display resolution of the game
for example: change 1280p x 720p to 720p x 420p or to any lower res
sorry for not clarifying it
