### ISSUE TITLE
Game freezing when I try to join a match.

### ISSUE THREAD

**Issue by MCUniversity** [tetrio/issues#612]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
I cannot join any gamemode. The main menu and config work, and so do gamemode select menus. But the moment I try to join any multiplayer or solo gamemode the game bugs out. The screen glitches out, and then freezes. I can hear the game sounds happening in the background but I cant see the game. It sounds like I can still control the blocks falling even though I cant see them.

### Reproducing
1. Open the game
2. Try to join any gamemode (solo or multiplayer).
3. Screen glitches out then freezes allthough I can hear the game sounds happening in the background.
### Expected behavior
1. Open the game
2. Try to join any gamemode (solo or multiplayer).
3. Game I joined starts and I can play normally

### Screenshots
One screenshoot of the game bugging out:
![image](https://user-images.githubusercontent.com/42188518/106305197-acc46f00-625c-11eb-9bca-039ffbab9c64.png)

### Your setup
 - **OS and version**: [e.g. Windows 7] Windows 10
 - **Browser and version**: [e.g. Chrome 76] Firefox 86.0b1 (64-bit) 

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)
![image](https://user-images.githubusercontent.com/42188518/106306214-024d4b80-625e-11eb-8efb-f198a72afc16.png)

**Comment by o5k** [comment]
This definitely looks like some GPU issue, combination of problems probably

Does it work in Chrome/Chromium? Can you play other games correctly? Lastly, does https://get.webgl.org/ show a spinning cube?

**Comment by MCUniversity** [comment]
No, I do not get a cube. The game does work normally in the desktop app, tho I prefer to play in the browser. I just updated my graphics drivers to the latest version and I still dont get a cube and the game still doesen't work. I am downloading chromium rn to test if it works there.

**Comment by MCUniversity** [comment]
I just downloaded chromium and it works there too.

**Comment by o5k** [comment]
Weird, since you don't get a cube there's sadly little I can do, it definitely seems to be a problem either on Firefox's or your GPU's end then :/
