### ISSUE TITLE
Tetr.io unable to load after server restart

### ISSUE THREAD

**Issue by LieutenantLark** [tetrio/issues#618]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Tetr.io is stuck in an infinite loading loop on Chrome OS 

### Reproducing
1. Go to 'Tetr.io' on Chrome OS
2. See error

### Expected behavior
I expected to be able to play after the servers were brought back up.

### Screenshots
![Screenshot 2021-02-03 at 1 46 54 PM](https://user-images.githubusercontent.com/73004856/106813784-57a2a780-6626-11eb-9bc8-46c278a5c671.png)

It is stuck in an infinite reloading loop with that blue message at the bottom right.

### Your setup
 - **OS and version**: Chrome OS
 - **Browser and version**: Chrome 88.0.4324.146

**Comment by o5k** [comment]
have you tried doing as the message says

**Comment by LieutenantLark** [comment]
on chrome, the closest thing to a force reload is ctrl r
and yes, i have done this

**Comment by o5k** [comment]
press ctrl while hitting the reload button

**Comment by LieutenantLark** [comment]
it...worked.... i thought i pressed it before
i feel dumb lol
thanks

**Comment by LieutenantLark** [comment]
do i just delete this now?
