### ISSUE TITLE
I don't know what happened

### ISSUE THREAD

**Issue by UU6202** [tetrio/issues#620]
After a 40 line game with 9 all clears, a warning message which has words such as cheating or hacking. I couldn't see it clearly though. After that, all my games states that replay will not be saved. I definitely did not take part in any hacking action.

**Comment by o5k** [comment]
Do you still have console logs? (F12, then go to the Console tab)

**Comment by UU6202** [comment]
what do I have to do?

**Comment by UU6202** [comment]
also, the 'replay will not be saved' message on bottom left is now gone

**Comment by ZaptorZap** [comment]
I believe I know what's going on here. Considering the run had 9 All Clears, there's a good chance it took @UU6202 quite a while to figure those out, and in the case that they took more that ten minutes to get this close to the perfect run, the server would reject the replay for simply being longer than ten minutes. If this is the case, then this would not be the first time this happened, as [I've spoken to someone else who's experienced this exact issue before, user Mio#7788 on the TETR.IO Discord server,](https://discord.com/channels/673303546107658242/673303546564968566/751719836878503996) regarding their All Clear run which lasted more than ten minutes. Here is what the error looked like on their side: 
![image](https://user-images.githubusercontent.com/64891705/107095718-24931c00-67be-11eb-98e0-e8aafec4109d.png)
Here is the evidence I am basing this comment on, [once again taken from the TETR.IO Discord server](https://discord.com/channels/673303546107658242/673303546564968566/715339502205272135): 
![image](https://user-images.githubusercontent.com/64891705/107095339-76877200-67bd-11eb-9c27-cfc88191c19e.png)
