### ISSUE TITLE
Connection Error; Reason Ribbon Lost

### ISSUE THREAD

**Issue by Eddyland** [tetrio/issues#621]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Reproducing
1. Go to 'Tetra League / Quick Play'
2. Click on '...'
3. Scroll down to '...'

### Expected behavior
I get connection error message in about half of my Tetra League games upon loading into the match.

### Screenshots
Attached file

### Your setup
 - **Windows 10**: 
 - **Google Chrome Version 88.0.4324.150 + Tetrio Desktop client**

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)
[tetr.io-1612552821045.log](https://github.com/tetrio/issues/files/5934846/tetr.io-1612552821045.log)
![Capture](https://user-images.githubusercontent.com/78618234/107080841-cebf7380-67bf-11eb-8102-41d56aff3111.JPG)

**Comment by o5k** [comment]
cant do anything w/o additional info, cannot reproduce
