### ISSUE TITLE
Redefining Spins in All-Spin

### ISSUE THREAD

**Issue by UU6202** [tetrio/issues#622]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

All spins is an option which can be set to in game -> general -> allowed spins. It awards bonuses for all pieces. You may not be a fan of all spins as it might be too powerful, in terms of standalone piece-spin and back-to-back chaining, or familiar with this . However, I am aware of this as it feels rewarding and also utilises the SRS kicks more.

Observation:
In a game with "all-spin" as the option of "allowed spins", the definition of a spin for the T piece is same to when "allowed spins" is "T-spins", that is using the corner check - when 3 blocks diagonally adjacent to the centre block of the T piece in the final position are occupied. Let's not talk about spin minis for now.
On the other hand, the definition of a spin for other pieces (L, J, S, Z, I) is when the piece cannot move left, right, up or down, similar to the method "immobile" used in The New Tetris.

Suggestion
Isn't this a double standard? In addition, it leads to certain misleading situations such as [this](https://harddrop.com/fumen/?m115@3gB8IeA8DeD8AeH8BeH8BeE8Je2AnvhAerQLAuH98A?QPmYEwOxCA). [See more examples](https://harddrop.com/fumen/?m115@BhF8FeD8FeH8AeE8JeWLnvhAOrQyAKE7QEJG98AwfR?oDFM98AQ+brDFbUVEVDlaEFbMLEmoo2AF7A3DtkjhDJDVTA?SbAAABhF8DeBAHehHDeD8gHA8NeVruAAvhANrQ4AUE7QEJG?VABG46ACFbcfEO3MXEFbEcEo488AQLhDElN98AwWXTASo78?Ay9mGEP0FDEloY9ALhAAEeC8AeQLEeC8AeQLQpNeuquAAvh?AWrQyAu32TASorkEFG98AwNpTASoKTASYV5DHt2TASI7QEh?1UTAS4MhE0oo2AKE7QEJ2BAARhC8glAeAAIeDAKeNruAAvh?A1wQNAUE7QEJG98AwD2JEJBAAAWhQLHeSLMeOruAAvhA2wQ?jAJoo2A3HhDEkoo2AzwJyDl92TAS4WtATJ2JEFbcEEJGmCA?VhgHIeiHMeuruAAvhAWxQjAJoo2A3HhDEkoo2AzwJyDl92T?AS4WtATJ2JEFbcEEJGmCA).
Due to the nature of the shape of the T piece, if 3 corners are filled and 2 of them are at the side the piece points to (excludes mini and floorless TST kick), it is always immobile. I suggest other pieces should also use the method of checking the surrounding blocks. Please refer to [this fumen](https://harddrop.com/fumen/?m115@vhAAg0UAmXyTASYbSASoiJEkoo2AKow2BzgC8BeH8B?eH8CeI8AeN8JeuguDAFbkAAChwSRewSAewSWeGmumACj7kD?rN98AwNpTASoFeDnIReEhoo2ABMVTAS4wrDxQWXEFnBAAUh?wSQLwwQpWeFmunAjHvQEBMVTASYlNEFbEcEoe0TASo78A4S?GeEooo2Areg/DFr4AA2gA8AeAAGeA8AeQLQeQpA8QLXe+hu?DAFbkAAAhwSTewSAewSWeGmuGAFbcRASYAAA2gAAIeQLB8R?eQpA8QpWeuguDAFbkAA/gwSAewSRewSAewSXeWmu3ABGCUA?SoeRASICvDFbEcEo488AQr78AQjUNEjh0TAS4MrDsn9TASo?saEFbUVElKZ5DyoaCAugE8CAIeQpA8QpAAGeB8HeQpAAQLX?eWcuDAFbkAADhwSGewSKewSGewSOe+mu3ABGCUASoeRASIC?vDFbEcEo488AQr78AQjUNEjh0TAS4Q5DHt2TASosaEFbUVE?lKZ5DyoaCABhwSIeQLIewwIeQpOe9muTAjHvQEBMVTASYlN?EFbEcEoe8CAvfwwAewwRewwAewwmeEAFeHAQLAeQLGABeHA?QLAeQLMAJeW+tvAU9MXEFajXElow2BFbEcEo488AQr78AQj?UNEjh0TASoynDqSQrDOP98AQuzCAvhCW+tqAU9UTASYcNEJ?22TASICvDFbEcEo488AQySOCFbkOEpYQrDFb8bDOnBAAW+t?sAhoo2ACj7kDroo2AhN98AQ+brDFbUfDhNVTASoCXEloo2A?y4vhEJM9nDW+tiA0H98AQR0CEJ3zdEloo2AJP98AwR0TASo?KTASI7QEJ2BAAvfQLAeQLReQLAeQLnfAAtUAmXyTASIrSAS?oiJEkoo2Aaow2BHhC8BeI8BeN8JechuDAFbkAAMhwSGewSZ?eEmuGAFbcRASYAAAzgC8BeH8BeE8EeQpGeQpZesguDAFbkA?AMhwSGewSZeEmuGAFbcRASYAAAugE8CABeAAGeB8AAGeA8A?eQLGeQpAeA8XeUXuDAFbkAABhwSTewSXecmuGAFbcRASYAA?AyfwwGewwyeEAFeHAQLAeHABeHAAeQLNAJeU5tfAU9MXEFa?jXElow2BFbEcEo488AQr78AQjUNEjh8CAvhAU5tuAmXyGEJ?mZTASoKTAS4opEzno2AyY4dEBmBDEloo2ABMVTAS4wrDxQW?XEFnBAAyfQLGeQL3eC8AeI8AeI8AeI8DeM8JepguKAmXyTA?SoUSAy0AAALhwSAewSEewSDewSEewSBewSMeBruwAJoo2Ao?C7rDuoQOB0oo2AjHvQEso2rDsW98AQ5NyDVM9nDFbMLEVP9?8AwV9dE2gA8AAIeCAFeA8QLAeQpEeQpA8AeB8QpEeQpBeQp?MeZhf2gwSBewSEewSDewSEewSBewSgeRhfzgCAQLAeAAQLE?AQLDeQLEAQLAeAAQLGAAeOAJeAAtSAun9TASI7QEJG98AwD?2JEp9BAA9gC8GeC8GeC8AeP8JeWmuDAFbkAAJhwSIewSAew?SYeuluNAKE7QEJG98AwD2JEJBAAA/gwSIeQpketluTAjHvQ?EBMVTASYlNEFbEcEoe8CAzgC8BeE8BeQpBeE8FeD8BeQpA8?QpYeuguDAFbkAAChwSRexSXeWmuGAFbcRASYAAAtgF8CAJe?A8AeQpIeA8GeAAQLQpXe2buDAFbkAAAhwSAewSIewSheemu?dAVpRXEB3UTASYlNEFbUVEl7gDEBM98Aw8N5DOBAAAyfwwR?exwleFAEeHAQLAeQLGABeQLGABeOAJeW+t5AU9kaEloo2Az?no2ACj7kDrN98AwByrDFbUVElKZ5DyoSTAS4FNEyoo2AKE7?QEJG98AwD2JEJBAAAufg0AewwAeQLg0AewwBei0Bei0Bexw?AeRLwwAewwkfAAt6AU9UTAS4wrDhtDKEFbMmEoW98AwN88A?Q2FoDuoQOB0oo2AtiSrDFbEcEo488Aw2+1DFM98AQbAAAtf?A8gHAeQpA8AegHAeQLAeA8iHA8AeiHAeA8RpAeA8AeQLAeQ?LAeC8AeA8EeB8BeA8EeE8Kfu3tpAU9taEFbsYEoHhDEEG98?AXO98AQzUTASoKTASI7QEJG98AwD2JEJBAAAwfwSRewSqfW?9eCgwSQpIeAAIeA8WfV9tTAjHvQEBMVTASYlNEFbEcEoe8C?AufB8QpAeA8BeB8AeC8AeA8CeA8AeQpAeA8AeB8AeB8BeB8?AeB8AeB8CeA8AeB8AeB8EeB8AeB8FfO6tSAU9taEFbsYEl4?2aEFbMLEGqBAA1fwSSewSkf2/eHgAAA8HeAAA8HeAAA8HeA?AA8Hf1/tTAjHvQEBMVTASYlNEFbEcEoe8CAtfFABeQLGACe?GAAeAAQLGAAeIAAeIAAeCATeC8GeC8GeC8AeP8JeUhuDAFb?kAAJhwSIewSAewSYesluNAaE7QEJG98AwD2JEJBAAAzgC8B?eE8EeE8BeQpCeD8BeQpA8QpYesguDAFbkAAChwSRexSXeUh?uGAFbcRASYAAAtgF8CAJeA8AeQpIeA8GeAAQLQpXe0WuDAF?bkAAAhwSAewSIewShe8ludAVpRXEB3UTASYlNEFbUVEl7gD?EBM98Aw8N5DOBAAApfxwCeBtwwBeBtDeBtBewwBtCexwneF?AEeHAQLAeQLGABeQLGABeOAJeAAt4AU9taEFbsABFbUfDsn?g/Dzoo2ABMVTAS4wrDxQWXEF388AQZjXEFbUEDt8N5Duoo2?AtOJ5DoeA8wwA8BeA8wwCeywBeywBeA8DeA8AeA8LeA8wwA?8CewwA8BeywBeywDeA8BeQpQLA8BeBPQLBeBPBewwg0whAP?BewhAPwhBeg0xhBei0BewwEexwKewwg0wwCeBtwwBei0CeB?tDewwCexwGexwCeBtwwBeBtCewwBtBewwBtUeAAt5APSNXE?2+EoElsCSASYjrDGP98AwByrDFbsYEwO5aEFLHSAS4Q5DHt?2TASoCXEloo2AtOJ5DTBAAA). Blocks in magenta are the blocks to check. I made that the spin eligibility are similar to what we do using the T piece, but mostly involves kicks. Spins (not in their mini form) are always immobile. You can see this as more restrictions in addition to immobile. This also fixes the above hurdle J-spin double problem.

I don't know how much of an issue this is or whether should this be implemented as this game option is not very popular. I'm here just to point out how the definition of spins of other spins can be improved. Thank you for taking time reading this. Please tell me your thoughts.

**Comment by UU6202** [comment]
How is this issue related?

**Comment by Dimentio** [comment]
I've implemented a new spin option called **Handheld** which uses 4-corners detection for every pieces except I piece, under your example it does trigger a J-Spin, I'd like to mention that under this rule though we unfortunately lose a few S/Z Spins triple detections. Anyway added in next update!
