### ISSUE TITLE
Client Crashing and Board Invisible to Other Players in Browser

### ISSUE THREAD

**Issue by xAmbiguityx** [tetrio/issues#631]
- [x ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x ] I am using the **newest version** of TETR.IO.
- [x ] I know **how to reproduce the issue**.
- [x ] I am using a **supported browser** or the Desktop Client.
- [x ] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x ] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
My desktop client kept crashing on it's own randomly, so I switched to an incognito Google Chrome window and played the Tetra League there. People started telling me they couldn't see my screen and they thought I was hacking.

### Reproducing
1. Open the desktop client and let it run.
2. Wait for it to crash.
-----------------------------------------------
1. Open Tetr.io in an incognito Google Chrome Browser.
2. Play in the Tetra League.
3. Wait for people to report you for hacking because they can't see your board, but you can see theirs.

### Expected behavior
I expected the client to run without crashing randomly, and I expected the browser version to run normally without making people think I'm hacking.

### Screenshots
![Capture](https://user-images.githubusercontent.com/73198176/108134616-1bd2fd80-707c-11eb-9226-d4cc5ee4dc45.PNG)

### Your setup
 - Windows 10 Professional
 - Google Chrome Version 88.0.4324.150 (Official Build) (64-bit)

### Additional context
Chrome's console log:
api.adinplay.com/libs/aiptag/pub/TTI/tetr.io/tag.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
moon.kagari.moe/matomo.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
5ddec3d66e17b51fd03babd0.jpg:1 Failed to load resource: the server responded with a status of 404 ()
VM27:7669 webgl backend was already registered. Reusing existing backend factory.
t.registerBackend @ VM27:7669
VM27:7669 cpu backend was already registered. Reusing existing backend factory.
t.registerBackend @ VM27:7669
VM27:7669 Platform browser has already been set. Overwriting the platform with [object Object].
t.setPlatform @ VM27:7669
VM27:7675 TETR.IO
VM27:7675 Please be careful when pasting anything in the console. Attackers may be out to steal your login information.
VM27:7675 First boot - welcome to TETR.IO!
VM27:7675 Autoselected graphics mode low
VM27:6989 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
_ @ VM27:6989
VM27:6989 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
_ @ VM27:6989
VM27:7675 Eligible for feecof test.
VM27:7675 Up to date. Local version 6.0.0-production | Commit 811fddb (2/10/2021, 2:03:06 PM) | Server cycle 0dzNlp7EI | Build N1YkG3Q4S (2/10/2021, 2:04:46 PM)
VM27:7675 tetr-io_728x90_8 mounted, now 1 mounts
VM27:7675 Feecof test starting...
tetr.io/:1 The resource https://cdn.xsolla.net/img/favicon.ico was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
tetr.io/:1 The resource https://secure.xsolla.com/favicon.ico was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
VM27:7675 Feecof test completed with score of 2561021 feecof.
VM27:7675 First boot - welcome to TETR.IO!
VM27:7675 Autoselected graphics mode high
VM27:7675 tetr-io_728x90_1 mounted, now 2 mounts
VM27:7675 PixiJS 5.2.2 - WebGL 2
VM27:7675 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 -CPU: 12-coreMemory: ~8 GBConnection: 10 Mbps, 100ms RTT [4g]
VM27:7675 Renderer: ANGLE (NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0)
VM27:7675 tetr-io_728x90_8 unmounted, now 1 mounts
VM27:192 Ribbon 2eb880097e0130a6 opened
VM27:7675 tetr-io_728x90_1 unmounted, now 0 mounts
VM27:7675 tetr-io_728x90_3 mounted, now 1 mounts
VM27:7675 tetr-io_728x90_3 unmounted, now 0 mounts
VM27:7675 tetr-io_728x90_6 mounted, now 1 mounts
VM27:7675 tetr-io_728x90_6 unmounted, now 0 mounts
VM27:7675 tetr-io_728x90_6 mounted, now 1 mounts
VM27:7675 tetr-io_728x90_6 unmounted, now 0 mounts
VM27:7675 tetr-io_728x90_6 mounted, now 1 mounts
VM27:7675 tetr-io_728x90_6 unmounted, now 0 mounts
VM27:7675 tetr-io_728x90_3 mounted, now 1 mounts
VM27:7675 tetr-io_728x90_3 unmounted, now 0 mounts
VM27:7675 tetr-io_970X250_1 mounted, now 1 mounts
VM27:7675 tetr-io_970X250_1 unmounted, now 0 mounts
VM27:7675 tetr-io_728x90_3 mounted, now 1 mounts
VM27:7675 tetr-io_728x90_3 unmounted, now 0 mounts
VM27:7675 tetr-io_728x90_6 mounted, now 1 mounts
VM27:7675 tetr-io_728x90_6 unmounted, now 0 mounts
VM27:7675 tetr-io_728x90_3 mounted, now 1 mounts
VM27:7675 tetr-io_728x90_3 unmounted, now 0 mounts
VM27:7675 tetr-io_728x90_6 mounted, now 1 mounts
VM27:7675 tetr-io_728x90_6 unmounted, now 0 mounts
VM27:7675 tetr-io_728x90_6 mounted, now 1 mounts
VM27:7675 tetr-io_728x90_6 unmounted, now 0 mounts
DevTools failed to load SourceMap: Could not load content for https://tetr.io/tf.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by o5k** [comment]
> Wait for people to report you for hacking because they can't see your board, but you can see theirs.
Is this still happening in the most recent release? I have implemented a hotfix earlier today.

**Comment by xAmbiguityx** [comment]
That part seems to be fixed so far, I'll check on the crashing later.

**Comment by xAmbiguityx** [comment]
Crashing seems to be fixed too. Thank you.
