### ISSUE TITLE
TETR.IO does not function under Firefox 85.0.1 [Ubuntu 20.04.2 LTS]

### ISSUE THREAD

**Issue by Dogecode6502** [tetrio/issues#632]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
I recently switched to Ubuntu 20.0.4.2 LTS on my PC and found that WebGL no longer works on TETR.IO. It would seem to be a problem with the site rather than my configuration, as WebGL is enabled on my end and works on other pages which utilize the API. Issue #549 already reported this but it was mentioned there that the problem would be fixed in the next patch; evidently the bug fix either fails to work at least on the latest Ubuntu version of Firefox or it was never implemented. The workaround provided in that issue:
>     * It can be forced under `about:config` using `layers.acceleration.force-enabled` and restarting firefox. 
>       Then tetr.io works as expected
does still resolve the problem.

EDIT: While the workaround did allow the site to work, graphical animations were poor and playing for just a few minutes resulted in a system-wide freeze requiring a hard reboot of the PC. Not recommended.

I can confirm that the site works as expected on the same version of Firefox under WIndows 10.

### Reproducing
1. Try to visit TETR.IO using Firefox 85.0.1 on Ubuntu 20.04.2 LTS
2. The WebGL error message should appear even if WebGL is enabled and functioning properly.
### Expected behavior
TETR.IO would recognize WebGL and run properly.

### Screenshots
![image](https://user-images.githubusercontent.com/75445519/108254294-d3254e00-7128-11eb-9770-6d47dc565a72.png)

### Your setup
 - **OS and version**: Ubuntu 20.04.2 LTS
 - **Browser and version**: Firefox 85.0.1
 - **GPU**: nVidia GeForce GTX 1660 Ti on the nVidia proprietary driver [version 460.32.03]

**Comment by kokon** [comment]
I had the same problem as this. This is likely caused by the "Firefox Crash Guard" determined that the graphics driver installed may not be stable, and automatically disabled it.
To override this behavior, go to `about:config`, click the blue "I accept the risk!", then search for these two options:
- webgl.force-enabled
- layers.acceleration.force-enabled

and set the values for both to `true`. Restart firefox, and your tetr.io should now load.

**Comment by o5k** [comment]
This is sadly a browser issue, not much I can do here
