### ISSUE TITLE
Can't friend/unfriend banned user

### ISSUE THREAD

**Issue by gkaply532** [tetrio/issues#633]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
There's no ui for unfriending banned users.

### Reproducing
1. Check the in-game profile of any banned user
2. Can't unfriend

### Expected behavior
To be able to unfriend the user

### Screenshots
![image](https://user-images.githubusercontent.com/48455693/108611863-df90fb80-73f3-11eb-9a53-8b666fe7a88e.png)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Desktop client

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
Fixed in next patch.
