### ISSUE TITLE
IP Address of user is displayed by default on server error pages.

### ISSUE THREAD

**Issue by EnsignN7** [tetrio/issues#634]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When there is a server error (e.g. Bad Gateway), the response information sent by CloudFlare (ray ID, CF server location, user IP) is all displayed by default. This presents a privacy concern towards users that are broadcasting themselves playing the game. This was seen widespread during the Hard Drop Super Lobby event.

### Reproducing
1. Reload the page when a server connection error is received while the server is down (e.g. during a restart)
2. Observe the error page.

### Expected behavior
Technical details are recommended to by hidden by default. This can be done with a show/hide toggle with the front-end code.

### Screenshots
https://imgur.com/qksuHPn

### Your setup
 - Windows 10 Version 20H2 (OS Build 19042.804)
 - Microsoft Edge (Chromium Based) > Version 88.0.705.74

### Additional context
No additional context.

**Comment by o5k** [comment]
Fixed in 6.0.1.
