### ISSUE TITLE
Rotation buttons switched when controller connected after program running

### ISSUE THREAD

**Issue by cspence97** [tetrio/issues#636]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
I am using my macbook pro running the desktop client.  I use my nintendo switch joycons over bluetooth.  I do not use joy2key or any similar software for connectivity, they natively work on my mac.  Every time I have them connected and start tetrio it works perfectly.  Every time I start tetrio and then connect my joycons the rotate buttons are switched.  I have tried going to the config and seeing if the input was switched however it does not register as switched.  A simple restart resolves the issue.

### Reproducing
1. Start tetrio
2. Connect controller
3. Start any game mode
4. Press rotate buttons

### Expected behavior
tetris pieces move as intended with each button press doing its intended function

### Your setup
- Mac OS Big Sur 11.0.1
- Desktop client

### Additional context
I have not tried this on the browser version

**Comment by o5k** [comment]
Merging this into #396
