### ISSUE TITLE
Show days remaining before name change is available

### ISSUE THREAD

**Issue by ZudoB** [tetrio/issues#637]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
I changed my username to something silly, and I want to change it back. I can't remember exactly when I changed it, and the account menu doesn't tell me, so I have to keep trying until it eventually works.

I enter my password and 2FA code (which I can't autofill easily in Desktop) just for it to tell me that "usernames can only be changed every 30 days", which is slightly irritating from a UX standpoint.

### Describe the solution you'd like
Display how long I have to wait (or the absolute date and time) before I can change my name, next to the username change form on Config>Account.

### Describe alternatives you've considered
Can't really think of any other ways to approach this, since it's only a quality of life improvement.

**Comment by o5k** [comment]
Added in next patch.
