### ISSUE TITLE
8bitdo Controller inputs not working after a few seconds in game

### ISSUE THREAD

**Issue by StixmanKai** [tetrio/issues#641]
### Checklist (issue will be disregarded & closed if incomplete!)

- [ X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X ] I am using the **newest version** of TETR.IO.
- [ X] I know **how to reproduce the issue**.
- [X ] I am using a **supported browser** or the Desktop Client.
- [X ] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [ X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
The controller is recognised by tetrio and the buttons can be binded in the controls section. However, when I get in a game the controller input works until I drop the first piece and then no other inputs are received.
### Reproducing
1. Disconnect controller
2. Reconnect controller
3. Start a game and place a block
4. No further inputs are recognised

### Expected behavior
The blocks to continue to work when I press buttons on controller

### Screenshots
<img width="894" alt="Screenshot 2021-03-03 at 15 46 34" src="https://user-images.githubusercontent.com/79990775/109831874-bf550e00-7c37-11eb-930c-4623978911f2.png">
Keys are bound to the controller

### Your setup
 - **OS and version**: [macOS Mojave]
 - **Browser and version**: [e.g. Chrome Version 88.0.4324.192]

### Additional context
Controller is 8bitdo SN30pro+
After one piece is dropped the controller stops working until it is disconnected and reconnected

**Comment by o5k** [comment]
Merging this into #396
