### ISSUE TITLE
View incoming garbage in Minimal

### ISSUE THREAD

**Issue by Lexitik** [tetrio/issues#642]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.

When using Minimal graphics, you have no indicator of receiving garbage until it is already in your queue.
In a 1v1 setting, you can easily enable side by side and screen-watch to anticipate garbage.
But in a FFA, ***garbage can be literally impossible to react to***, especially with strong players. (See below)
This is extremely frustrating, especially to low-end PC players who want to optimize frame-rate for game consistency. 

### Describe the solution you'd like

A simple option to enable a minimal garbage-receiving animation can help immensely.

### Describe alternatives you've considered

At the very least, enable the option to hear incoming garbage, as the different sounds allow you to gauge how much you received.

### Additional context

The second and killing blow show garbage coming into the board before the game can even show the garbage in the queue

https://user-images.githubusercontent.com/62867685/110035143-22a27700-7cf0-11eb-985b-43f789edf3ab.mp4

**Comment by SebatheDragonbear** [comment]
2 alternatives I could offer is 

1. Make the incoming garbage animation behind all the boards

2. Reduce the particle size (with a possible slider) and flash the borders yellow when It impacts your board instead of going trough the middle

**Comment by ZaptorZap** [comment]
Has this improved any since passthrough was disabled? The garbage bar now does interactively display pending garbage before it's ready to enter the field:
![image](https://user-images.githubusercontent.com/64891705/189462890-8f970292-87ff-4e11-bacb-0923dd251165.png)

**Comment by ZaptorZap** [comment]
I'm gonna close this as a resolved stale request now.
