### ISSUE TITLE
Upgrading desktop client cleans appdata/.../tetrio-desktop folder

### ISSUE THREAD

**Issue by jydiw** [tetrio/issues#647]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Upgraded desktop client. All of my saved replays were deleted. They were saved in the default location--`~\AppData\Local\Programs\tetrio-desktop\replays`. While I am not 100% certain it happened because of the update, I went in to save a new replay after updating and my replay folder was empty.

### Reproducing
1. Have replays.
2. Update tetr.io.

### Expected behavior
Not deleting replays.

### Your setup
 - Windows 10
 - tetr.io client v8

**Comment by p1nkl0bst3r** [comment]
As far as I know there is no default save location, you have to choose this yourself and it remembers the last location saved to. (at least on linux).
I advise you to not save any files in any folder in AppData yourself, just save your replays to your Documents folder or some other folder not in use by in this case TETR.IO.

**Comment by o5k** [comment]
Please do not save random files (be it replays, or anything else) in the AppData folder, as this folder is cleaned on upgrade. This is intended behaviour.
