### ISSUE TITLE
Controls/Keys input stopped working during gameplay

### ISSUE THREAD

**Issue by plafilat** [tetrio/issues#649]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Happens randomly, suddenly the whole controls (on pc platforms) just stopped working and stayed freezing till you lost the game. Sometimes when you hold a certain key down, for example, I'm using my own custom keys configuration, I use A and D to moves left and right. If I were to hold A while the bug happens, the pieces will start to move to the left by themselves, from where it happens, till the end (game over). After it stopped working, you cannot use any other keys during that game after the bug happens. forfeit the game, restarting the game, nothing works.  

### Reproducing
I am unsure if this only happens for low-end computers, but:

1. Open up Tetr,IO (Chrome, Firefox, Ect... , Desktop application)
2. Click on "Config"
3. Scroll down to "Handling"
4. Set everything to a higher value than default settings (in this case ARR: 1.5, DAS: 9, DCD: 0, SDF: 30)
5. leaves the other two settings alone
6. Choose and play random gamemodes for a while, should happens

### Expected behavior
the entire keyboard input should stop working while playing

### Screenshots
when the bug is executed *in this case, I let go of the "moving right" key before the bug happen
![image](https://user-images.githubusercontent.com/80546941/110996074-aa852280-837b-11eb-8b63-e651c77d94b3.png)
 
few moments later
![image](https://user-images.githubusercontent.com/80546941/110996164-d3a5b300-837b-11eb-9825-d5eea91fca30.png)
![image](https://user-images.githubusercontent.com/80546941/110996220-ed46fa80-837b-11eb-88fe-f9041bedf758.png)

### Your setup
 - **OS and version**: 
 Windows, 7
 - **Browser and version**: [e.g. Chrome 76]
Chrome Version 89.0.4389.82
TETR.IO 6.0.2
Firefox 86.0
### Additional context
I think it has to do with low-end devices and the latest version patches of the game itself (6.0.2). I also experiencing where moving Tetris pieces left to right suddenly just startled up and leave the game with a ton of input delays (if you tweak your handling). Though freezing is more common on websites for me

**Comment by rs-fog** [comment]
Same problem, all keys (except 1-4 for target selection in versus, these still work) stops working randomly until end of the game.

OS: Windows 7, tested on: Chromium 90 & Chromium 91.0.4445.0, low-end device (4GB RAM)

**Comment by rs-fog** [comment]
Seems like it was fixed in 6.0.3 (no longer reproduces for me)
