### ISSUE TITLE
Profanity filter strips line breaks from chat messages

### ISSUE THREAD

**Issue by ZudoB** [tetrio/issues#651]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
If a user message contains line breaks (possible when sent via a bot over Ribbon), they are stripped from the message when the profanity filter processes it. 

### Reproducing
1. Enable the profanity filter.
2. Using a bot account, send a `chat` command to Ribbon with a line break (\n) in the message body.
3. Observe that the line break is removed.
4. Disable the profanity filter.
5. Send the chat command again.
6. Observe that the line break is visible.

### Expected behavior
The line break should remain in the message with or without the profanity filter enabled - or perhaps it should always be removed. Either way, this is inconsistent between the two settings.

### Screenshots
Left: filter enabled, Right: filter disabled
![](https://cdn.discordapp.com/attachments/673305614318960671/821716817844240444/unknown.png)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: TETR.IO Desktop 8.0.0, Firefox 86

### Additional context
This is an issue specific to bot accounts, since regular users cannot send line breaks in chat when using the client.

**Comment by ZudoB** [comment]
bonk

**Comment by deedeeen** [comment]
yes, still relevant (this comment doesn't have recovering values; waiting to be fixed)

**Comment by o5k** [comment]
Fixed in next version.
