### ISSUE TITLE
Add an official custom texture sheet option for the tetriminos

### ISSUE THREAD

**Issue by GabJustGab** [tetrio/issues#652]
### Checklist ###

- [ × ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [ × ] I am using the **newest version** of TETR.IO.
- [ × ] I am certain this is a **feature request**, not a bug.
- [ × ] I've **thought this feature through** properly.

-----

Okay, so, since from what I've seen nobody has suggested this yet, may I ask to add the option to customize the texture of the tetriminos just like with the custom backgrounds?
We could easily customize the looks of the blocks to make them fit better with the theme of the background. Granted, we'd need to have the base sprite sheet to actually make it work, but it would be pretty neat!

**Comment by o5k** [comment]
Semi-duplicate, closing in favor of #359 

By the way, there's [a Firefox plugin and tetrio-desktop mod](https://gitlab.com/UniQMG/tetrio-plus/-/wikis/home) called TETR.IO Plus that does this, as well.
