### ISSUE TITLE
 Board Bounciness and Damage Shakiness does not work properly in Super Lobby

### ISSUE THREAD

**Issue by S7RODE** [tetrio/issues#654]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a supported browser or the **Desktop Client**.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
I use the Board Bounciness and Damage Shakiness settings, but this does not work properly in Super Lobby. The board moves more and more strangely as the game progresses.

### Reproducing
1. In CONFIG > GAMEPLAY, set both the 'Board Bounciness' and 'Damage Shakiness' settings to 100%, and turn off the 'Do Not Animate Background in Super Lobbies'.
2. Enter the super lobby room with more than 100 people.
3. You can see the other player's board move weirdly as the game progresses.

### Expected behavior
Probably the phenomenon appears after I was eliminated. But sometimes my board moves strangely with that settings even while I'm alive... so I'm not sure.

### Screenshots
I recorded the video instead screenshots:
https://streamable.com/823nnj
from 1:47.

### Your setup
 - **OS and version**: Windows 10 and TETR.IO Desktop (without TETR.IO PLUS)

### Additional context
I like the Board Bounciness and Damage Shakiness settings so I turn it on and playing the game, so I hope this bug is fixed before the Hard Drop Super Lobby opens in about 3 days.

**Comment by S7RODE** [comment]
When I play Quick Play Super Lobby right now, it seems that this phenomenon occurs after I'm eliminated. Could this bug be fixed before the Hard Drop Super Lobby tomorrow?

**Comment by o5k** [comment]
Fixed in next patch.
