### ISSUE TITLE
could there be a way for people with bad internet like me to not lose a lot of tr from disconnecting (I've lost 1 third of my rank because of disconnects)

### ISSUE THREAD

**Issue by lastskygamer** [tetrio/issues#659]
### Checklist (issue will be disregarded & closed if incomplete!)

- [ ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [ ] I am using the **newest version** of TETR.IO.
- [ ] I am certain this is a **feature request**, not a bug.
- [ ] I've **thought this feature through** properly.

-----

**Comment by o5k** [comment]
No, as the server cannot differentiate between you forfeiting and pulling the Ethernet cord. Giving a lower TR loss to disconnects would open the door to people constantly unplugging ethernet when they're about to lose. TETR.IO is already very, VERY lenient in its connections. The game specifically warns you that you should have stable internet to play!

**Comment by lastskygamer** [comment]
thank you for responding
