### ISSUE TITLE
zenProgression data in local storage, when read from server, refuses to apply lower set values than the ones stored on the server

### ISSUE THREAD

**Issue by karl-police** [tetrio/issues#662]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
zenProgression data in local storage, when read from server, it refuses to apply lower set values than the ones stored on the server.

Say, you set Level 20 to Level 200. You can not

### Reproducing
1. Inspect Element
2. Application Local Storage
3. Find "zenProgression" and modify "level" to something higher. Do not do this while in Zen mode
4. Refresh page and play Zen mode, you'll notice your level is higher.
5. Now go out of Zen and modify "level" to something lower. Then refresh the page again.
6. You will notice the level did not change when going in Zen mode again.

### Expected behavior
That it reads and applies the value, as that is not really, that well.... handled?

### Screenshots
None

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Chrome 89

**Comment by o5k** [comment]
This is intended. Zen data is backed up to the server, and when starting Zen, the higher of the two is applied. This allows you to play Zen on one device and pick the game up on another.
