### ISSUE TITLE
Tetra League Multiple Queues

### ISSUE THREAD

**Issue by realTronsi** [tetrio/issues#668]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [ X] I am using the **newest version** of TETR.IO.
- [ X] I know **how to reproduce the issue**.
- [ X] I am using a **supported browser** or the Desktop Client.
- [X ] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [ X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
You are able to queue up multiple times and be matched against multiple opponents in tetra league.

### Reproducing
1. Have 2 Tabs
2. Queue up on the first tab then close
3. Queue up on the second tab

### Expected behavior
Server queueing checks if player is already in queue/in a game before queueing up and automatically closing queue up when websocket connection is lost

### Your setup
 - MacOS
 - Chrome 89

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by realTronsi** [comment]
> On the bright side, you can practice to play 2 tetris games at once and gain/lose TR 2x as fast.

The first game that you join is automatically forfeited so you lose the TR, and the second game is disconnected.

**Comment by o5k** [comment]
Fixed in a previous patch.
