### ISSUE TITLE
TETR.IO requires WEBGL it seems WEBGL is disabled in your browser. WEBGL is required for the game to render properly.  please check your browser settings to ensure WEBGL is enabled in your browser, then try again.  this often happens if HARDWARE ACCELERATION is turned off in your browser. try enabling it in browser settings. So annoying, it occurs sometimes after 2-3 games even though i use the desktop tetr.io

### ISSUE THREAD

**Issue by dakmat-05** [tetrio/issues#673]
### Checklist (issue will be disregarded & closed if incomplete!)

- [ ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [ ] I am using the **newest version** of TETR.IO.
- [ ] I know **how to reproduce the issue**.
- [ ] I am using a **supported browser** or the Desktop Client.
- [ ] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [ ] I am certain this is a **bug**, not a feature request.

-----

### Reproducing
2. Click on '...'
3. Scroll down to '...'

### Your setup
 - **OS and version**: [e.g. Windows 7]
 - **Browser and version**: [e.g. Chrome 76]

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
> it occurs sometimes after 2-3 games even though i use the desktop tetr.io

this usually means your GPU is erroring, making the system decide it's not possible to keep using the GPU

nothing i can do about a faulty gpu :/

**Comment by dakmat-05** [comment]
Hmm. Okay. Thank you for the response.

**Comment by brandon-lockaby** [comment]
I'm also getting this issue after updating yesterday.  WebGL is working everywhere else.
