### ISSUE TITLE
The points and ranking in tetra league

### ISSUE THREAD

**Issue by starlux300** [tetrio/issues#681]
My problem is the points and the ranking in tetra league, how sometimes you are paired with new people in the game in tetra league of level 5 or 6 with no rank but they slaughter you in the game, it is nothing equal and it seems to me absolute nonsense.

The first solution I have in mind is to see the game stats you have, how you move the pieces quickly, the placement and precision of how they do it, because pairing up with someone without rank who kills me in 2 seconds is not very nice , but it's just a suggestion.

The other solution I have in mind is the matchmaking after the rank games that give it a rank of 5000 or 4000 for the stats it has, not a 2000 and so much that it massacres everyone it touches, because it is not fair at all.

And a last complaint with a solution would be the connection failure, that if it takes you out of the game that it does not lower the points but that the other person who did not take it out of the points, but it takes me out of some games for Some quick failure and it lowers my points like this, it is horrible and the solution would be to literally code it so that it does not lower the points for those failures and to the other I know why he is not to blame and morally won

Thank you for spending your time reading me if you did and I hope it can be solved since it is something incoherent that they give you 4 t spins in 30 seconds and you cannot move with your range.

**Comment by deedeeen** [comment]
1. Well, it's not that pros fail to join the game. Or they might just be smurfing.
2. You already had that. Play a few games and you'll see.
3. This is too obscure. Please elaborate on this.
4. Now _this_ is a valid argument. Although osk will always push the games in favor of the players that were not disconnected.

**Comment by o5k** [comment]
im having trouble understanding what you're saying, but for the last element: the game **cannot** know whether someone disconnected due to an internet issue, or if they yoinked the ethernet plug on purpose

giving internet issues less of a penalty would be abused instantly, think you're gonna lose? just pull the plug to avoid fate!

it's something that honestly cannot be avoided

**Comment by deedeeen** [comment]
as now osk has officially addressed the last point, you better rephrase everything
