### ISSUE TITLE
Can't log in the desktop game

### ISSUE THREAD

**Issue by JoaoVitorBaggio** [tetrio/issues#682]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When i open the game, i simply can't log in, it just keeps loading on the screen of the screenshot. I tried to reinstall the program but it doesn't change anything. In the browser the game is ok.

### Reproducing
1. Open the game on my computer

### Expected behavior
The login window apears and i click in "join".

### Screenshots
![image](https://user-images.githubusercontent.com/72949356/117023663-b03e1b00-accf-11eb-826a-19d9beda6410.png)

### Your setup
 - Windows 8.1
 - Desktop Tetr.io (the error is not ocurring on browser)

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by ZaptorZap** [comment]
I've seen this issue around plenty of times on the TETR.IO Discord server. It usually occurs when there's an update to the game, and your cache conflicts with the new files served by the server. There are a couple of workarounds to solving this issue:
1. Just try reloading without a cache. The shortcut to do this is `CTRL+F5`
2. Manually clear your Desktop Client cache through the File Explorer. You can access the folder this cache is stored in through the built in Windows Run dialog box:
2.1 Press `Windows+R`
2.2 Enter in the file path `%appdata%\tetrio-desktop\Cache`
2.3 Press the `Enter` button
2.4 Delete **all** files in the File Explorer window that should appear.

**Comment by JoaoVitorBaggio** [comment]
din not work, still the same :/
