### ISSUE TITLE
Add a Team Battle game-mode for ranked or custom games.

### ISSUE THREAD

**Issue by Aurora11-stack** [tetrio/issues#691]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
No, this is not related to a problem, but just a feature request. 

### Describe the solution you'd like
I'd like to see some sort of team battle game-mode for ranked or custom lobbies. Maybe even duos/quads, or **four teams of 25**. Maybe if partying was implemented, you can join team games with your party.

### Describe alternatives you've considered
This is quite a simple idea I guess, not much alternatives to describe.

### Additional context
Maybe something similar to tetris99 on the switch?
Edit: Also, I only just figured out how to use the search tool properly. Sorry about this, I didn't realise similar concepts have already been submitted.

**Comment by EHwaterball** [comment]
I don't think that ranked games would work out well. In other games, your team can interact with you in various ways and help out. In a Tetris team battle, there's literally zero interaction and doesn't encourage a playstyle different from a ranked 1v1.

**Comment by ZaptorZap** [comment]
I'd like to reference [the Q&A Hard Drop hosted a while back](https://www.youtube.com/watch?v=JBYfsXPw2i0), specifically this quote:
>Blink: So if you guys questions from the audience, I actually didn't prepare many questions, so if you guys have questions feel free to ask. Aside from that I don't really have too many questions. ... "Any thoughts on team games?" says BeastinShen. I'm gonna set it over to the audience for questions. We have multiple questions on team mode, and team games.
>
>osk: I've been thinking about a team mode for quite a while, becuase I do think the concept of a team mode would be really really really cool. There is one thing I don't want to do and that is make, basically the same as normal modes except.. Well the way that most people implement team games basically goes; "Well everyone in Team A is dead. Now Team B wins!" and that's kind of rigged to me. I want to kind of see what I can come up with, that would be a more interesting way of making a team game. I've had some ideas, you know of maybe respawn timers or maybe an entire capture the flag type system. I'm kind of throwing ideas around, and when I actua-
>
>Blink: Wait, capture the flag? What do you have in mind there? Capture the flag? In tetris? Can you elaborate a little bit on what your thought is on that? What were you thinking, when it comes to capture the flag in tetris?
>
>osk: This isn't any final idea yet right?
>
>Blink: Give us a sneak peek of what's going on in that head of yours.
>
>osk: One of the ideas I had is well you have two teams with four players. One of each player is carrying the flag, of that team. If that person then gets eliminated, it will then transfer the flag to the person who eliminated them. Now the enemy team has the other teams flag, and can progress that flag by just clearing lines. I don't know the exact grading method I'd use for that yet. Maybe it's just based on APM, or maybe it's based on score, or maybe it's based on the ammount of lines cleared. Basically you'd progress the flag, but that'd also cause other people to target you. So you'd have to make sure that you can keep up. Once you manage to get the flag to 100% progression, then your team scores a point. If you get eliminated while trying to capture your team's flag, and it goes back to the person who eliminated you. Then they can progress to returning the flag, to that team. 
>
>Blink: That sounds so cool. I wish that was implemented just to try it, because it just sounds so interesting and unique compared to any other team mode that's been out. I think you've got some cool ideas. Let me look for some more questions from the audience. Someone asked, "Would that include manual targetting or would all attacks go to the flag bearer?"
>
>osk: It's not manual targetting possible, but I'd also have different targetting strategies. Target the position of the enemy's flag, or target the position of your flag; an idea that I had as well for it. If your flag is being attacked as a team, then of course everyone is going to target the person trying to capture the flag right? It'd be basically impossible to capture a flag, so what I will try to do is make it so you can target your teammates, and offset their garbage. 
>
>Blink: You can counter for your teammate by targetting your teammate?
>
>osk: Yeah, stuff like that.
>
>Blink: Oh that's pretty cool too. Two very unique things, targetting your teammate to offset their damage.
>
>osk: Yeah, you'd have different targetting methods like; target your own team, target your enemy team. Also maybe targetting other people, like everyone except the flag bearer of the other team. Then you can kind of try to flank, and take out the other team's support people in a sense.
>
>Blink: That sounds exciting. Hyped to see what you come out with in the future, when it comes to team mode.

**Comment by Aurora11-stack** [comment]
I can't wait to see what osk implements with teams, it's awesome to see that he's already planned for such a gamemode. Tetr.io is so easily accessible, I play with my friends everyday so I'd be sick if I could team up with them! I guess imma close this for now.
