### ISSUE TITLE
Red bar appears and locks onto the piece the player is controlling for about a quarter of a second in 40 Lines mode

### ISSUE THREAD

**Issue by JasonPlayzGD** [tetrio/issues#694]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Every once in a while in 40 Lines in the web version of tetr.io, a red bar (which I assume is from multiplayer mode) appears for about a quarter of a second, locking onto the piece that I was controlling. This doesn't happen that often, but is frequent enough to notice it.

### Reproducing
1. Go to 'Solo'
2. Click on '40 Lines'
3. Click on 'Start'

### Expected behavior
A regular 40 Lines game with no random flashes of a red bar locking onto the piece the player is controlling.
### Screenshots
The bar appears and disappears so quick that it is very hard to take a screenshot without recording footage of it (Which I don't know how to record on Chrome OS) I have made a mockup image of it in an image editor though.
![image](https://user-images.githubusercontent.com/78827555/118280076-da46c880-b499-11eb-98a8-0aa993ac0401.png)

### Your setup
 - **OS and version**: [Chrome OS Version 83.0.4103.119 (Official Build) (64-bit)]
 - **Browser and version**: [Google Chrome Version 83.0.4103.119 (Official Build) (64-bit)]

### Additional context
The problem may be that I am on Chrome OS, but I don't see why that would be an issue in the first place. 
The problem also could be that the chromebook that I am using is managed by my school (since it's a school chromebook) but I still don't see why that would be an issue too since I am logged in with my gmail account instead of my school account which basically removes all of the limitations, making it just a regular chromebook.
When I am on Windows 10 at my home (browser and desktop client), it works fine. 
I do not know if this happens in other modes as I have not checked them yet, but it is still possible.

**Comment by o5k** [comment]
This looks to me like a faulty GPU. Can you show me the console logs? You can get those by hitting F12, then navigating to the Console tab in the pane that shows up. Do that when you see this issue appear again.

**Comment by JasonPlayzGD** [comment]
This is what the console says when it happens 
![image](https://user-images.githubusercontent.com/78827555/118907993-86e7d680-b8ee-11eb-8a4c-65f0aaee7e8b.png)

**Comment by o5k** [comment]
Hmm, can you scroll up? I'm looking for something like a "WebGL Error".

**Comment by JasonPlayzGD** [comment]
I didn't see that anywhere when I scrolled up
