### ISSUE TITLE
Custom game lines sent option

### ISSUE THREAD

**Issue by Theginjahninjah** [tetrio/issues#697]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.

When you play a multiplayer match, on the end screen, you can see how many lines you sent to other players. I think it would be neat to see that number in a custom game as well.

### Describe the solution you'd like

I would like a stat at the end of custom games for how many lines you would have sent over, if you were in a multiplayer game. 

### Describe alternatives you've considered

It could be a permanent stat at the end, a toggle to switch to the multiplayer stats screen, or the numbers that pop up in a multiplayer game for lines could be added to the custom game options. Thank you!

**Comment by ZaptorZap** [comment]
This issue is a duplicate issue of #283. Right now, you can use ZEN mode's custom "Versus" display to see them in SOLO play in some capacity, but it's clear to me there's a demand for such stats in custom games, too.
