### ISSUE TITLE
32 Bit Support for non 64 bit pcs

### ISSUE THREAD

**Issue by xacvwe** [tetrio/issues#698]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
they don't support an 32 bit pc

### Describe the solution you'd like
add 32 bit support

### Describe alternatives you've considered
None

### Additional context
None

**Comment by deedeeen** [comment]
related to #378
if you are strictly referring to desktop, it will be a dupe
