### ISSUE TITLE
Conflict between game focus and messages

### ISSUE THREAD

**Issue by deedeeen** [tetrio/issues#700]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When you spectate a multiplayer game with TETR.IO Social Network open, any keyboard inputs which are both for text cursor relocate (id est arrow keys, Home, End, Page Up/Down) and focus changes of players' stacks in background are both committed at the same time.

### Reproducing
1. Spectate an ongoing game
2. Try to access someone's messages, either via notifications (if possible) or by accessing a player's profile card and messaging them
3. Click in the message inputting box of the user 
4. Do anything that may conflict between focus change and cursor relocate

### Expected behavior
Only the cursor in message input should be relocated instead of the focus.

### Screenshots
No screenshots available

### Your setup
 - **OS and version**: Windows 10 20H2
 - **Browser and version**: Microsoft Edge version 90.0.818.62

### Additional context
This issue was only tested with Guideline controls.

**Comment by deedeeen** [comment]
Retested; this also affect letters.

**Comment by deedeeen** [comment]
yup, still existing

**Comment by o5k** [comment]
Fixed in next version.
