### ISSUE TITLE
Automatically dismiss game starting notification

### ISSUE THREAD

**Issue by dtinth** [tetrio/issues#702]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
![image](https://user-images.githubusercontent.com/193136/119277684-43250200-bc4b-11eb-8a30-5ba49c90654a.png)

### Describe the solution you'd like
The previous notification should automatically be dismissed when focusing on a the tab.

### Describe alternatives you've considered
Another solution is to dismiss the previous notification when creating a new one.

### Additional context
Previously-created notifications can be closed using [`Notification.close()`](https://developer.mozilla.org/en-US/docs/Web/API/Notification/close) API

**Comment by dtinth** [comment]
# Workaround

I wrote this userscript to improve notification handling.

- New notification replaces older one
- Notifications are cleared when focusing on tab
- Clicking on a notification focuses on tetr.io

```js
// ==UserScript==
// @name         Tetrio notification improvement
// @namespace    http://dt.in.th/
// @version      0.1
// @description  Auto clear noti
// @author       You
// @match        https://tetr.io/
// @icon         https://www.google.com/s2/favicons?domain=tetr.io
// @grant        none
// ==/UserScript==
{
  const state = window.dtinth_tetrio_state ??= {}
  const OriginalNotification = state.Notification ??= window.Notification
  const list = state.list ??= []

  const clear = () => {
    try {
      for (const n of list) {
        n.close()
      }
      list.length = 0
    } catch (e) {
      console.error('Cannot clear notifications')
    }
  }
  window.addEventListener('focus', () => {
    clear()
  })
  window.Notification = function(...a) {
    clear()
    const notification = new OriginalNotification(...a)
    if (!notification.onclick) {
      notification.onclick = () => {
        window.focus()
        notification.close()
      }
    }
    list.push(notification)
    return notification
  }
  window.Notification.requestPermission = OriginalNotification.requestPermission
}
```

**Comment by o5k** [comment]
Added in next patch.
