### ISSUE TITLE
Account deleted, yet forced to login into certain account

### ISSUE THREAD

**Issue by mit2000** [tetrio/issues#703]
Hi, I'm having an issue to log out from my deleted account. The site was just forcing me to logging in with the deleted account.

![Screenshot 2021-05-27 070152](https://user-images.githubusercontent.com/84882689/119746052-b92ea080-beb9-11eb-8607-6c6eabae12ab.png)
![Screenshot 2021-05-27 070337](https://user-images.githubusercontent.com/84882689/119746055-baf86400-beb9-11eb-92fa-09ba0d9a3ac5.png)

**Comment by ZudoB** [comment]
clear your cookies, although bear in mind that creating a new account is against the rules unless you have permission to do so

**Comment by deedeeen** [comment]
they probably will only leave

**Comment by mit2000** [comment]
> clear your cookies, although bear in mind that creating a new account is against the rules unless you have permission to do so

already cleared it, yet it still goes back to the second pic though
