### ISSUE TITLE
Possibility of sending empty messages in chat

### ISSUE THREAD

**Issue by GlitchyPSIX** [tetrio/issues#709]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
It is possible to end an empty message to a TETR.IO chat.

### Reproducing
1. Focus on any chat to send a message.
2. Type in a single or multiple of either of the following characters: " " (SPACE), " " (ALT+2 5 5)
3. Send message

### Expected behavior
Nothing should be sent (Not literally a NOTHING message, more so the chatbox should be cleared and nothing sent.)

### Screenshots
![Screenshot](https://i.imgur.com/jxNetGc.png)

### Your setup
 - **OS and version**: Windows 10 Home
 - **Browser and version**: TETR.IO Desktop v6.0.8

**Comment by deedeeen** [comment]
Hmm, i'm thinking of retaining this as a rather fun feature.

**Comment by GlitchyPSIX** [comment]
> Hmm, I'm thinking of retaining this as a rather fun feature.

Bad. Bad. Bad Bad Bad bad Baaaaaaaaaa🐑d

**Comment by deedeeen** [comment]
> Bad. Bad. Bad Bad Bad bad Baaaaaaaaaa🐑d
nolol

**Comment by r00ster91** [comment]
> Hmm, I'm thinking of retaining this as a rather fun feature.

I agree. I don't see how this can cause any harm.

**Comment by deedeeen** [comment]
And I don't think anything could conflict against empty messages, given that osk has allowed this to happen.

**Comment by r00ster91** [comment]
Implementing this will also need handling lots of weird edge cases like zero-width spaces, so I suggest to just keep it logical and let me send spaces if I want to.

**Comment by deedeeen** [comment]
It also allows for that kind of _artwork_, hence the additional fun. :)
