### ISSUE TITLE
Have Audio Channel solely for Next Game Piece SFX

### ISSUE THREAD

**Issue by littlewormboy** [tetrio/issues#713]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [ X] I am using the **newest version** of TETR.IO.
- [X ] I am certain this is a **feature request**, not a bug.
- [X ] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
It is practically impossible to listen to only the next game piece given the number of sound effects for line clears and pieces being locked.

### Describe the solution you'd like
I would like a separate audio channel volume slider for Next Game Piece SFX and separate channels for all other game sound effects.

**Comment by deedeeen** [comment]
#676
