### ISSUE TITLE
Add translation to the website

### ISSUE THREAD

**Issue by PikAsriel** [tetrio/issues#717]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
This function can help solve the language barrier.

### Describe the solution you'd like
Make a translation function to the site.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by ZudoB** [comment]
this duplicates #102

**Comment by deedeeen** [comment]
definitely a dupe
