### ISSUE TITLE
event ratio too high osk fix it osk fix it osk fix it osk fix i

### ISSUE THREAD

**Issue by 25Pi25** [tetrio/issues#719]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
I mashed move left, move right, rotate left, rotate right, and hold all at the same time for about 5 seconds and I was kicked from the room

### Reproducing
1. play a lobby
2. spam the fuck out of the buttons (i'm on a 60hz monitor if it matters)
3. cry about it

### Expected behavior
i expected myself to continue to play the game!!!!!!!

### Screenshots
![image](https://user-images.githubusercontent.com/67805443/121830081-16c43a80-cc79-11eb-890e-9668044754d1.png)

### Your setup
 - window s10
 - tetrio desktop

### Additional context
i was playing a loby and i got owned,,,,,, and i lost to an s+ osk fix it

**Comment by RedStone576** [comment]
very useful reproducing steps

**Comment by ZaptorZap** [comment]
>  I am not using anything that modifies game code (e.g. TETR.IO+).
Clearly you are, as [TETR.IO+](https://gitlab.com/UniQMG/tetrio-plus/-/wikis/home)'s "key OSD" setting is visible onscreen in your screenshot.

**Comment by 25Pi25** [comment]
ok mr zaptorzap i did it without t+ anmd its still afficting it
![image](https://user-images.githubusercontent.com/67805443/121830811-c0f09200-cc7a-11eb-9c91-7e3027a1b7a8.png)

**Comment by ZaptorZap** [comment]
Yeah I thought it would work regardless, since this is TETR.IO's built in macro prevention **working as intended.** If you would like a higher EPF limit, please consider applying for a bot account, as those accounts have a special heightened EPF limit.
