### ISSUE TITLE
"Exit tetr.io?" prompt does not reopen when you dismiss it from clicking on the overlay

### ISSUE THREAD

**Issue by ryanbraganza** [tetrio/issues#722]
### Checklist
- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue

The "Exit tetr.io?" prompt does not reopen when you dismiss it from clicking on the overlay instead of clicking on the "cancel" button.

### Reproducing
1. Open tetrio desktop
2. alt+f4 (or click the x)
3. Click the overlay (not the "cancel" button in the prompt)
4. alt+f4 again (or click the x)
5. The exit tetrio prompt does not appear again.

### Expected behavior
After the second alt+f4 the exit tetrio prompt should appear again.

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: 6.0.8-production

**Comment by ryanbraganza** [comment]
This still happens on 6.0.9-production

**Comment by o5k** [comment]
Fixed in next version.
