### ISSUE TITLE
I can't even run tetr.io Desktop on my window 7

### ISSUE THREAD

**Issue by Mogly000** [tetrio/issues#724]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
After I install tetr.io desktop it give me black screen and no report
Its like restating itself really

### Reproducing
1. Install Tetr.io Desktop
2. Open Tetr.io Desktop
3. Can't run the bloody thing

### Expected behavior
Blank screen and and loading cursor

### Screenshots
![Capture](https://user-images.githubusercontent.com/85986471/122176990-c4249180-ceb7-11eb-9f1d-ff1b2a556aa4.PNG)

### Your setup
 - Window 7 laptop

### Additional context
- There is none

**Comment by ZaptorZap** [comment]
Could you perhaps include the results from the DirectX Diagnosis test in a separate message? You may run one of these through the Windows Run dialog:
1. Press `Windows+R`
2. Type in `dxdiag`
3. Press `Enter`

**Comment by Mogly000** [comment]
![Capture 1](https://user-images.githubusercontent.com/85986471/122178942-a1937800-ceb9-11eb-8df0-b21f4f569913.PNG)
![Capture 2](https://user-images.githubusercontent.com/85986471/122178957-a48e6880-ceb9-11eb-8372-8fe61f3ed79f.PNG)
![Capture 3](https://user-images.githubusercontent.com/85986471/122178964-a6f0c280-ceb9-11eb-9114-53f9f5b5eb5c.PNG)
![Capture](https://user-images.githubusercontent.com/85986471/122178973-a8ba8600-ceb9-11eb-9f32-c4a6f36fe29a.PNG)

**Comment by Mogly000** [comment]
Never mind i have a potato laptop i guess i will just use the website like usual
