### ISSUE TITLE
From Tetra League Ending to Joining Friend in Public Lobby Error

### ISSUE THREAD

**Issue by DontTouchAnything** [tetrio/issues#725]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
After finishing a game of TL, if you attempt to join someone in a public lobby from your friends list **in the ending screen,** the game will black screen.

### Its Reproduceable
I cringe every time I do it. 

### Expected behavior
You should just join the lobby your friend is in.

### My Wild Guess
The game is having trouble leaving the match.

### Your setup
 - **OS and version**: Windy 10
 - **Browser and version**: Desky Top 6.0.8 with tetrio plus (like it matters)

**Comment by zacharylohrman** [comment]
Huh? "with TETR.IO plus (like it matters)"???? Doesn't using a mod invalidate all bug reports?? Also, you're a bit disrespectful with this, and you're kind of 'taking the piss' a bit. Please consider correctly following the bug report format osk has set out for his users.

**Comment by ZaptorZap** [comment]
Like it or not, they do have a point. Considering the relative safety in which you can test this issue, please test it with TETR.IO PLUS *disabled*. I'll re-open this the moment someone reading this gets it to happen without any modifications installed. 

As it stands, this blatant lie is pretty silly:
![image](https://user-images.githubusercontent.com/64891705/123049182-239d0880-d3b4-11eb-9518-1d40336a5a1a.png)

**Comment by DontTouchAnything** [comment]
@ZaptorZap Desktop 6.0.8 without tetrio plus because it did not really matter :CATSCREEEEEM: 

I forgot to copy the console. Ill do it next time someone is online and in a lobby and I don't lose to an S+

https://user-images.githubusercontent.com/42194320/123113370-815d3f00-d40c-11eb-919c-c4d8416e40a3.mp4

**Comment by o5k** [comment]
Fixed in next version.
