### ISSUE TITLE
Formatting issues in DMs after being silenced

### ISSUE THREAD

**Issue by ZudoB** [tetrio/issues#733]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
After being silenced, a red warning message appears in the most recently opened direct message. 

Switching to another DM, then going back to the DM with the silence message, causes the message to be misformatted, as the HTML is escaped this time.

### Reproducing
1. Open a DM with someone.
2. Get silenced (I tried this with Ribbon Inspector as well as natively with the autosilence)
3. Switch to another DM
4. Switch back to the original DM, and observe the issue

### Expected behavior
The formatting of the silence message should stay the same.

### Screenshots

(demonstrated with Ribbon Inspector to make it easier for me to take screenshots - this happens without any mods so leave me alone @ZaptorZap)

#### Before Switching

![image](https://user-images.githubusercontent.com/4703499/125434388-e4f07572-bb70-4560-baf2-7b0934e751f8.png)

#### After Switching

![image](https://user-images.githubusercontent.com/4703499/125434482-123425b7-589c-47ce-a4d4-1f06a47ac224.png)

#### Native (without any client mods)

![image](https://user-images.githubusercontent.com/4703499/125435377-dd191eea-3a03-4fd3-b13c-846c53ef5b27.png)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: TETR.IO Desktop 8.0.0 / Firefox 89

### Additional context
Nothing relevant appears in the console logs.

**Comment by Dimentio** [comment]
I believe I fixed that a little while ago so closing!
