### ISSUE TITLE
Shifted stack/tetromino, continuous garbage received while sending none.

### ISSUE THREAD

**Issue by Cherry-Smith-VT** [tetrio/issues#738]
### Checklist (issue will be disregarded & closed if incomplete!)

- [ ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [ ] I am using the **newest version** of TETR.IO.
- [ ] I know **how to reproduce the issue**.
- [ ] I am using a **supported browser** or the Desktop Client.
- [ ] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [ ] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue

Basically, when Vedanta and I (Cherry_Smith_VT) play on a public lobby ('SS and below only' lobby), our tetromino/pieces keep on shifted from the original preview. For example, when I put the pieces to the most left and move it two(2) column to the right (press right twice), the shadow show the position that I want to put it, but when I press hard drop, the tetromino were placed on the most left.  This problem become more apparent when opponent use the soft drop for every pieces. My friend said that this problem is caused by lag that messed up DAS, but I do have a good internet connection at that time. Even Vedanta have good internet connection and I can see their tetromino shifted from the place intended to several times.

Besides that, while being in the same lobby, both of us have received continuous garbage while sending none to the opponent.
I can confirm this while spectating Vedanta play. I can see that they received continuous garbage while the opponent(s) is not even downstacking / clearing lines. Also, I can see that the opponent did not received any garbage when Vedanta did a perfect clear even when opponent(s) is not downstacking / clearing lines around that time.

### Reproducing

1. Go to any public lobby . For example, 'SS and Below Only' lobby.
2. Play around 1,00 - 1.50 PPS at 1200 to 1600 (GMT +0)
3. See error (shifted tetromino / misdrop)

### Expected behavior

Shifted tetromino / misdrop while playing.

### Your setup
 - **OS and version**: Windows 10 Home Single Language 21H1
 - **Browser and version**: Tetrio Client Version 6.08 (Newest version because it is 'Up to date'.)

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
as for issue one: most likely computer lag (as in, bad hardware)

what kinda hardware are you running? tried the [performance tips](https://tetr.io/about/performance/) yet?

as for issue two: that's network lag, itll be improved in next release with smart latency preferencing but don't expect magic
