### ISSUE TITLE
Incorrect work of audio muting

### ISSUE THREAD

**Issue by 4500zenja1** [tetrio/issues#740]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X ] I am using the **newest version** of TETR.IO.
- [ X] I know **how to reproduce the issue**.
- [ X] I am using a **supported browser** or the Desktop Client.
- [ X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [ X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When you try to mute the TETR.IO tab on your browser, it mutes as it was expected. However, after reloading the tab, the music is back, even though the tab is still muted at browser side.

### Reproducing
1. Right mouse-button on TETR.IO tab;
2. Click on "Mute tab"
3. Click on "Reload" button (a counter-clock arrow)

### Expected behavior
The TETR.IO site/tab should be still muted even after muting.

### Your setup
 - Windows 11
 - Opera GX LVL3 (core: 77.0.4054.275)

**Comment by flashwave** [comment]
Yeah, tab muting is out of TETR.IO's control nor can I reproduce this in Firefox 88.0.1, so this is likely a problem with Opera GX.
