### ISSUE TITLE
Save others' replay in a public room

### ISSUE THREAD

**Issue by AdachiGenshou** [tetrio/issues#741]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

**Comment by ZaptorZap** [comment]
This very much *is* possible, there's just a couple reasons you might not end up with a full replay. A couple pointers:

- Are you on minimal graphics? If so, do you have "SHOW DUELS SIDE BY SIDE" enabled? If not, that's one of the reasons this button isn't appearing.
- Were you spectating the match **when it began**? If you started spectating midgame, you didn't receive a full replay, so the game will deny you what data you *did* witness unfortunately.

![image](https://user-images.githubusercontent.com/64891705/133170306-36480edf-236c-4614-b899-177d56974b31.png)
