### ISSUE TITLE
"verification join" and "ban" feature

### ISSUE THREAD

**Issue by AndrewAnims** [tetrio/issues#742]
### Checklist (issue will be disregarded & closed if incomplete!)

- [ ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [ ] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
Yes, if you are manually working on a room, but you can't be on a bot, you wanted people to be on your level, such as about U ranks levels, but all of the sudden ranks x and d come out of thin air you you have you kick them out, you want to ban them permanently or might as well add verfication, such as this pop up saying.. .
[(INSERT USERNAME) tried join the game, allow or or disallow (RANK: X) [Y] [N]

Or a additional popup that would say, 
ANDREWYIN123 [friend] [report] [move to spectator] [transfer host] [kick] [BAN]
### Describe the solution you'd like
just add a additional button for the ban button or the verification

### Describe alternatives you've considered
You can try to have a switch says if you would want verification for each join.

### Additional context
It would be nice to add that feature since if you want your ranks to be in a custom room, instead you get beaten by doremy and firestorm and other rank x's try add that, but it would be better if you place them small since if you are in a match and get a interuption of the game a popup and die, that wouldnt be fair.

**Comment by Dimentio** [comment]
You'll have more control on who can play in your room in the upcoming update, so this seems unnecessary.
