### ISSUE TITLE
Ads shifting main menu buttons

### ISSUE THREAD

**Issue by FishPyramid** [tetrio/issues#746]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue

When the banner ad on the main menu appears it shifts all the buttons and i always click the wrong one this is unbearable and it pains me each time is happens (which is frequently)

### Reproducing
1. Go to the main menu
2. Wait for ad to appear
3. Buttons shift

### Expected behavior

The space for the ads should be bigger and not shift the menu or big ads just don't appear

### Your setup
 - Windows 10
 - Chrome Version 92.0.4515.131

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by deedeeen** [comment]
could give us a few screenshots

**Comment by FishPyramid** [comment]
before ad loads
![image](https://user-images.githubusercontent.com/59983826/129451236-ef8b6a2a-fbfe-4c0c-8d66-2271ab897593.png)
after ad loads
![image](https://user-images.githubusercontent.com/59983826/129451257-95604bc8-0c1d-44e4-98ec-5733dca363f2.png)

**Comment by thesilican** [comment]
Agreed, the menu UI is kinda annoying when the ads load [just as you're clicking the button](https://www.reddit.com/r/ProgrammerHumor/comments/9ozauu/a_more_accurate_representation_of_what_happened/), causing the wrong button to be pressed. The amount of time the ad takes to load is inconsistent too, and it also sometimes doesn't load, which makes it hard to predict when you can safely press menu buttons.

Potential ideas for a solution:
- Making the height of the ad container taller, before the ad is loaded
- Moving the ad to the left side

**Comment by o5k** [comment]
ads are planned to be repositioned to more stable sizes in the planned UI redesign
