### ISSUE TITLE
About nationality display in tetr.io

### ISSUE THREAD

**Issue by doashoi** [tetrio/issues#748]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X ] I am using the **newest version** of TETR.IO.
- [ X] I am certain this is a **feature request**, not a bug.
- [X ] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.

【I am a Chinese player. In order to play tetr.io stably, I use VPN connection. However, because I selected the Japanese node when I log in for the first time, my nationality is displayed as Japan. I want to modify it, but I can't find it. And Japan is still displayed after I log in again with nodes from other countries.】

### Describe the solution you'd like

【The button to select or change nationality, or any way to solve this problem.】

### Additional context

【look forward to your reply.】

**Comment by deedeeen** [comment]
The ability to change your country currently depends on the paid TETR.IO Supporter. This'll be a hard one to resolve.

**Comment by ZaptorZap** [comment]
Unfortunately, as mentioned, you can already change your nationality. This infographic takes you to the appropriate place, but it points at a free option as the one that changes your flag is paid. You can hide your flag like so:
![image](https://user-images.githubusercontent.com/64891705/129449728-02b39a31-75e5-4b6c-a611-783671637e7c.png)

**Comment by iDm1** [comment]
This is done wrong in tetr.io currently. You should be able to choose your country manually during the registration process. Today alot of people are using VPNs, as you can see from amount of VPN sponsorships on YouTube, but tetr.io registration process is still in a stone age.
