### ISSUE TITLE
Tetr.io completely muted

### ISSUE THREAD

**Issue by Eparcs** [tetrio/issues#749]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [ X] I am using the **newest version** of TETR.IO.
- [ ] I know **how to reproduce the issue**.
- [ X] I am using a **supported browser** or the Desktop Client.
- [ X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [ X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
- tetr.io is completely muted, sound works elsewhere (as well as tetr.io on browser though I use the desktop application). It remains muted across my headset, laptop built in microphone and earphones. There is a similar unresolved bug report from long ago which I found but seeing as it was inconclusive I've decided to post one myself.
### Reproducing
2. Click on '...'
3. Scroll down to '...'
- If I recall correctly this problem occurred from the moment I opened tetr.io. I have re-downloaded tetr.io and the issue remains, 

### Screenshots
![image](https://user-images.githubusercontent.com/88945646/129457652-056c1a1c-c790-4197-a9f4-c3a2ee9f47f2.png)

### Your setup
 - **OS and version**: [e.g. Windows 7] Windows 8.1 (Build 9600.20094)
 - **Browser and version**: [e.g. Chrome 76] Version 92.0.4515.131 (Official Build) (64-bit)

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)
![image](https://user-images.githubusercontent.com/88945646/129457760-21337622-2798-4556-b98e-cadb37f38b1c.png)

![image](https://user-images.githubusercontent.com/88945646/129457791-b8f9b7fc-7a5d-4e50-8d31-cfcc17fdd544.png)

![image](https://user-images.githubusercontent.com/88945646/129457809-30274e57-3bb1-4889-91bc-2a493a22cb79.png)

the 'failed to load' seem to be different now and then.

**Comment by flashwave** [comment]
do you have the tab muted maybe? this screenshot is firefox but i'm pretty sure it's in the same location in chrome

![image](https://user-images.githubusercontent.com/5001057/129485415-da106199-2201-4b1d-a2f5-aff71ab5615b.png)

**Comment by Eparcs** [comment]
Sorry been away and unable to check anything for now, I use desktop app so I don't think this is the issue, if this is possible with app then I have not done this consciously so my laptop mightve done something if this turns out to be the case

**Comment by Eparcs** [comment]
> do you have the tab muted maybe? this screenshot is firefox but i'm pretty sure it's in the same location in chrome
> 
> ![image](https://user-images.githubusercontent.com/5001057/129485415-da106199-2201-4b1d-a2f5-aff71ab5615b.png)

I don't see how I can do this with the app as it does not allow me to however it seems the issue has resolved itself for the time being, would be nice to know what else could cause this for the future, you don't have to respond as I'm not sure if you're like staff or just tryna help me out but thanks regardless

**Comment by ZaptorZap** [comment]
I can't say I'm sure what caused this either, but it's definitely not a common report which, as you've said, has resolved itself.
