### ISSUE TITLE
Doesn't play smooth. Input is sluggish, delayed, etc. 

### ISSUE THREAD

**Issue by HitGubber69** [tetrio/issues#750]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue

The game just doesn't play/feel smooth. When I play on browser version, inputs have very noticeable delay, like 0.1 seconds at least. On desktop mode it's much less, but still noticeably higher than on jstris.

I am not talking about the DAS or the ARR. I know about the ARR charge difference between tetr.io and jstris, but it's not "slippery", it's the opposite. There is a noticeable delay between pressing a key and seeing the piece move on the screen. The framerate is fine, the input is just delayed.

It also seems to fluctuate/improve and then reset. For example, right at the start of joining a tetra league game the input is higher than at the end of the game. Then after the match ends, I jump in a 40L, and it's high again.

### Reproducing

Just jump in a game and compare to jstris. Especially noticeable in browser, but still there in desktop.

### Expected behavior

No input delay like when I play jstris, cultris, worldwide-combos, etc.

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Chrome 92

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
use tetrio desktop, if that too doesnt help try [performance tips](https://tetr.io/about/performance/)

if it's still bad send specs here
