### ISSUE TITLE
Cannot open replay made in custom lobby

### ISSUE THREAD

**Issue by Zhuinden** [tetrio/issues#753]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue

If you press "Download" on the Save Replay button after a custom lobby match, and even if you name it to `*.ttr`, the desktop client says "File load failed"

### Reproducing

1.) save replay in custom game (and name it `some_filename.ttr`)
2.) drag & drop onto desktop client

### Expected behavior
The replay should load.

### Screenshots
![image](https://user-images.githubusercontent.com/11718392/130309524-43616da6-d790-4974-82fb-53705d078341.png)

### Your setup
 - **OS and version**: [e.g. Windows 10]
 - Desktop client
 - 
### Additional context

```
TypeError: Cannot read property 'username' of undefined
    at FileReader.s.onload (eval at <anonymous> (bootstrap.js?hv=3bc142c.yd02QKRTv.khC3t3zhz:2), <anonymous>:7432:153193)
```

**Comment by ZaptorZap** [comment]
Could you upload the file you were trying to GitHub so we may test it ourselves?

**Comment by ZaptorZap** [comment]
Oh, wait, that shouldn't be necessary. This is human error displayed on the file extension, as you're looking for **`.ttrm`** and **not** `.ttr`. The "m" means **m**ultiplayer. Just rename the file to include that **m**.

**Comment by Zhuinden** [comment]
You're right, `ttrm` works, thanks
