### ISSUE TITLE
GPU Temps rise 20 deg C - Desktop Version

### ISSUE THREAD

**Issue by Tyuda** [tetrio/issues#754]
GPU Temperature is rising 20 deg C

When running Tetrio on Desktop Temperature of GPU is 20 deg higher than when running Tetr.io on Browser.

Fan was blowing hot.
On Desktop version GPU can by default run at around 75 deg C.
On Browser - Edge it was running 40-55 deg C

I did turn settings down from Ultra to High on the Desktop to match my settings in the browser.
Desktop version was then running around 65-70 deg.

Asus Rog Strix Laptop with GTX 1660 Ti, 16GB Ram + i7-10th gen
HDMI to Widescreen Monitor with display 3440 x 1440
Windows 10 build 19042

This is reproducible with every 1 game on the Desktop version. The GPU warms immediately and when first noticed I only had Spotify running alongside Tetrio. But have recreated this multiple times and also happens when Desktop Tetrio is running alone on the above system.

**Comment by o5k** [comment]
this is a video game, it will use your resources to ensure the game runs as smooth as possible
if you dont want this, your main option here is to go to CONFIG->DESKTOP and turn on HARD VSYNC

**Comment by deedeeen** [comment]
improvement label is better for this issue
also this issue is essentially showing off /j
