### ISSUE TITLE
About once every 3 games I get this bug where the  game clicks on chat I think or something... and automatically moves the tetris piece to 1 corner, either left or right. Usually that bug persists for 10-20 seconds, usually means loss of round but sometimes I can survive it. If the bug is on when round is lost, new round starts without the bug

### ISSUE THREAD

**Issue by Hqe1** [tetrio/issues#757]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Reproducing
2. Click on '...'
3. Scroll down to '...'

### Your setup
 - **OS and version**: [e.g. Windows 7]
 - **Browser and version**: [e.g. Chrome 76]

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
your keybinds
