### ISSUE TITLE
Please disable the volume change on scroll 

### ISSUE THREAD

**Issue by luke-robertson** [tetrio/issues#758]
- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
Please remove the volume change on scroll, i have a magic mouse and happens all the time drives me mad,

### Describe the solution you'd like
volume change in settings

### Describe alternatives you've considered
this is my only mouse im not buying a new one for 1 website

**Comment by ZaptorZap** [comment]
![image](https://user-images.githubusercontent.com/64891705/131843586-bc719597-62f0-4f27-87b4-bb16185ec161.png)

This is an option, found in the ingame config.

**Comment by ZudoB** [comment]
If you're triggering the volume control in game (which is the only situation in which scrolling actually changes the volume) you should just take your hand off the mouse...

**Comment by luke-robertson** [comment]
@ZaptorZap thanks, i had no idea the config was on the main menu, i kept looking in profile

**Comment by luke-robertson** [comment]
@ZudoB 

while in lobby waiting for match to start, i still want to use my mouse with out the random audio spikes.

I have disabled the setting, thanks

**Comment by ZaptorZap** [comment]
You're all good. Just realized my "just screenshot setting and close the issue" might've come across as a bit rude, heh.
