### ISSUE TITLE
Game render froze during spectator focus switch

### ISSUE THREAD

**Issue by JeDaYoshi** [tetrio/issues#759]
- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [ ] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
I was spectating a game (which I was playing into but was KO'd), where at one point the game just suddenly froze when someone was KO'd and the game was switching focus to another player. The internals were working; there were KO pop-ups, chat was fully functional. But the game was not showing any frame updates, the LIVE top bar was stuck, switching focus to someone else clicking in the game didn't work, and using chat commands/hotkeys didn't work.

As a side note, when the lobby's game started again, everything just disappeared and went back to normal, so it's not as serious... it just gets stuck until the next game.

### Reproducing
Unsure of exact requirements. All I did was join this month's Hard Drop Super Lobby, stay there for a couple of hours, then it suddenly happened. No alt-tabs or anything whatsoever. At worst I think I was focused on the chat textbox.

### Expected behavior
The game should have removed the KO'd player and switched focus to someone else. But instead, it completely froze there.

### Screenshots
![2021-09-11 23-16-02](https://user-images.githubusercontent.com/7420695/132967673-b3fc1a44-8741-4b3f-9a76-1a5d057b5492.png)
![2021-09-11 23-16-30](https://user-images.githubusercontent.com/7420695/132967678-ff687cc8-fe04-4569-a4fa-cd3a185dee49.png)
![2021-09-11 23-17-14](https://user-images.githubusercontent.com/7420695/132967679-fc3d8f08-5b27-41fd-a58b-f7cbe2bc3c09.png)
![2021-09-11 23-17-23](https://user-images.githubusercontent.com/7420695/132967681-287b5cef-e531-4d94-8eb6-c38823cd0049.png)

### Your setup
 - **OS and version**: Linux 5.13.0 - Ubuntu 20.04 LTS
 - **Browser and version**: Chromium 93
 - **Game build**: Yv98I3Fpi
 
### Additional context
Unsure based on the messages if it has anything to do, but errors popped up visible in the browser's console.
![2021-09-11 23-19-09](https://user-images.githubusercontent.com/7420695/132967695-5edd4551-e4c7-4d9e-9880-29e428d9b64a.png)

**Comment by o5k** [comment]
Can't exactly tell what the issue is, the rendering (which this seems to be) has been rewritten though, so I'll close for now assuming it's fixed, if not let me know with new console logs
