### ISSUE TITLE
Grid lines are messed up when on minimal

### ISSUE THREAD

**Issue by ezhao1** [tetrio/issues#760]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X ] I am using the **newest version** of TETR.IO.
- [X ] I know **how to reproduce the issue**.
- [X ] I am using a **supported browser** or the Desktop Client.
- [ X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [ X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When the game is set to minimal settings in config, the grid lines are messed up and barely show up (only a few lines at the top are showing). When the window is resized the grid lines change and fluctuate but always stay messed up.

### Reproducing
1. Go to config.
2. Click on 'Video & Interface'
3. Set to minimal
4. Click on 'Gameplay'
5. Set Grid visibility to 100%.
6. Refresh.
7. Go to solo -> 40 lines -> start
8. See that the grid lines are messed up (probably differing depending on screen size / resolution).

### Expected behavior
I expect all the grid lines to be visible at all times.

### Screenshots
![tetriogridlines](https://user-images.githubusercontent.com/46204677/133002648-5671793f-5998-46a9-9be2-012bb50f6dfc.png)

### Your setup
 - Windows 10
 - Chrome 92.0.4515.159

### Additional context
Happens with chrome on my macbook as well but with a different line format so it seems to be a somewhat universal issue.
<img width="1437" alt="Screen Shot 2021-09-12 at 5 16 22 PM" src="https://user-images.githubusercontent.com/46204677/133003121-3ce51124-afde-4431-a838-ba8336f92f80.png">

**Comment by ZaptorZap** [comment]
This is, almost definitely, the auto-inclusion of the "RENDER AT A LOW RESOLUTION" option in minimal graphics. Please turn this off and tell us if it's still happening:

![image](https://user-images.githubusercontent.com/64891705/133003206-687a6246-1a72-4673-b120-a913f9d3cb47.png)

**Comment by ezhao1** [comment]
> This is, almost definitely, the auto-inclusion of the "RENDER AT A LOW RESOLUTION" option in minimal graphics. Please turn this off and tell us if it's still happening:
> 
> ![image](https://user-images.githubusercontent.com/64891705/133003206-687a6246-1a72-4673-b120-a913f9d3cb47.png)

ohhhhhhhh that fixed it! Thanks!
