### ISSUE TITLE
Chrome: If the game is not visible, the game logic is completely frozen in time

### ISSUE THREAD

**Issue by mat1jaczyyy** [tetrio/issues#764]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When using Google Chrome, TETR.IO logic will stop executing if the game is not visible/rendering. This can be done by switching tabs, minimizing, or simply covering your Chrome window with another window. This is incredibly annoying, as keeping this for just 15 seconds will cause the server to kick you out. It would also be personally very useful for hosting bots locally on Chrome without having to adjust window size to display a small portion in order for the game to work, although this repros on a completely regular and unmodded game.

### Reproducing
1. Enter any multiplayer game (private room, QP, TL, etc)
2. Make sure the game is not visible on screen (changed tab, chrome minimized, or just covered with another window)
3. Game logic will now freeze completely. If lasts for 15 seconds, server will kick.

If you're viewing the "minimized" player from another player's perspective, their time stat will freeze, indicating they're not executing any game logic.

### Expected behavior
The game logic continues to execute even if the game is not visible.

### Screenshots
Not applicable

### Your setup
 - **OS and version**: Windows 10 21H1
 - **Browser and version**: Google Chrome 93.0.4577.82 (Official Build) (64-bit)

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by mat1jaczyyy** [comment]
An alternative that resolves my specific use case, but still doesn't fix the root problem: is there any way to simultaneously launch multiple instances of TETR.IO Desktop, where the issue does not reproduce (you can minimize and the game still works)?

**Comment by o5k** [comment]
Know about this sadly, there is nothing I can do about it. This is yet another one of Google's steps of telling all game developers and webapp developers that don't exactly follow Google's principles to go fuck themselves. It happens on newest Chrome versions, and as usual will probably be pushed into other browsers too, later on...

I'm looking into workaround right now. One of said workarounds is perhaps playing audio? I know Chrome will completely freeze your tab to 1 update a MINUTE if you don't play any audio, so if you could turn off "mute bgm when tabbed out", perhaps that helps. However, game logic will still be paused, and there is nothing I can do about it other than tell you to use Desktop..

> is there any way to simultaneously launch multiple instances of TETR.IO Desktop

If you install it in multiple places, perhaps? You might need to fiddle with command line flags to make it not use the same profile folder though

**Comment by mat1jaczyyy** [comment]
> One of said workarounds is perhaps playing audio?
I do have BGM disabled (only SFX enabled), but after enabling music and disabling the mute if hidden setting, there is no tangible difference in repro.

> If you install it in multiple places, perhaps? You might need to fiddle with command line flags to make it not use the same profile folder though

The installer is silent, so it doesn't have an obvious way to do this. Even if you could do it (or you copypaste `Local/Programs/tetrio-desktop` files elsewhere, wouldn't both games be using the same `Roaming/tetrio-desktop` folder? Could that cause them to clash?

**Comment by mat1jaczyyy** [comment]
For what it's worth, this also reproes on Edge in the exact same manner, while Firefox instead does one update every few seconds inconsistently (although for my use case, Firefox does not have any concept of local overrides, which I need for bot)

**Comment by ZudoB** [comment]
> wouldn't both games be using the same Roaming/tetrio-desktop folder? Could that cause them to clash?

Could you try launching the game executable with the `APPDATA` environment variable set to something else? Not in a position to try right now, but [from what I can gather](https://www.electronjs.org/docs/api/app#appgetpathname) this should cause Electron to use a different path to store its data.

**Comment by o5k** [comment]
> I do have BGM disabled (only SFX enabled), but after enabling music and disabling the mute if hidden setting, there is no tangible difference in repro.

guess that makes sense, the issue you're describing is that setInterval and requestAnimationFrame immediately halt (or at least, become unreliable) no matter what

> For what it's worth, this also reproes on Edge in the exact same manner

cuz edge is just chromium now :(

**Comment by mat1jaczyyy** [comment]
@ZudoB the game still doesn't launch 2nd instance even with Programs folder copied and pasted elsewhere, and AppData changed with `SET APPDATA=D:\temp`.

**Comment by o5k** [comment]
more like cantfix, sadly

**Comment by deedeeen** [comment]
should there be a dedicated label for the impossibility to fix hmm

**Comment by mat1jaczyyy** [comment]
Sadge
