### ISSUE TITLE
playfield  not loading

### ISSUE THREAD

**Issue by SzymenL0K0** [tetrio/issues#766]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x ] I am using the **newest version** of TETR.IO.
- [ ] I know **how to reproduce the issue**.
- [x ] I am using a **supported browser** or the Desktop Client.
- [x ] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [ x] I am certain this is a **bug**, not a feature request.

-----
Sometimes when game starts in Tetra League playfield don't show up. I see chat and can talk to my opponent, but after some time i get disconnected from server. 
id of this or something is: fc1dbdf5d06f5c11
I have stable and strong connection to internet. 
I'm using firefox browser 92.0 (64bits)

### Reproducing
2. Click on '...'
3. Scroll down to '...'

### Your setup
 - **OS and version**: [e.g. Windows 7]
 - **Browser and version**: [e.g. Chrome 76]

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
anything in console?
