### ISSUE TITLE
Alt-F4 bug on TETR.IO Desktop client on Windows

### ISSUE THREAD

**Issue by ThatCookie** [tetrio/issues#767]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
The alt+f4 menu doesn't show up when it's the second time opening it

### Reproducing
1. Go to 'TETR.IO Desktop client'
2. Press 'ALT+F4'. A menu meant to confirm that you want to exit the game will show up
3. Click anywhere but on the menu
4. Press 'ALT+F4'. No menu shows up. See the issue

### Expected behavior
The menu should show up again, as if you had pressed "cancel"

### Your setup
 - **Windows 10**
 - **Desktop V8**

**Comment by ZaptorZap** [comment]
This report seems to be a duplicate issue of #722, sorry.
