### ISSUE TITLE
Muting Issue

### ISSUE THREAD

**Issue by strangeovertone** [tetrio/issues#768]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Refreshing the site after muting it unmutes the site, even though the browser marks it as still muted.
### Reproducing
1. Right Click Tab > Mute Site
2. Refresh page
3. Unmuted game audio

### Expected behavior
The site is supposed to stay muted. All other websites do this.

### Your setup
 - Windows 10, Ubuntu 21.04
 - Google Chrome, Google Canary. 

### Additional context
I've seen this problem addressed before, but the other user was using Opera. I think that if this problem is persistent between browsers, it might not be a browser issue. I've also heard of people being unable to replicate this problem with Firefox.

**Comment by ZudoB** [comment]
Not able to reproduce this (Chrome 94, macOS Monterey) - however, if TETR.IO is doing something that inadvertantly bypasses a site mute, it's a browser issue and not a TETR.IO problem.

As a workaround, mute TETR.IO via the in game settings.
