### ISSUE TITLE
Add Multiplayer Gamemode "Score Attack"

### ISSUE THREAD

**Issue by rozivector** [tetrio/issues#769]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
No. It is not, it just improvement in multiplayer game mode.

### Describe the solution you'd like
It is be good to additional free multiplayer than versus mode. It is "**Score Attack**" mode, which first player have the highest score will be victory. Player who have topped out earlier will over but the score still counted and if all players have topped out, the game is over and return a result. The gamerule is used Classic Score attack which allowed to levelled up the game.

### Describe alternatives you've considered
It is alternative if the versus mode has already exist and used alternative mode as Score Attack mode.

### Additional context
Nothing.

**Comment by deedeeen** [comment]
This is sadly a duplicate for #456.

**Comment by rozivector** [comment]
Well it is. But it is just pointing at classic rules. Not at all, so they can approved the implementation. Which means, it can handle the moderation because it is very very basic. Some settings must be set locked at default.
