### ISSUE TITLE
Conflict between targeting and messages

### ISSUE THREAD

**Issue by deedeeen** [tetrio/issues#772]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When using a keyboard to type a character in direct messages clashing with targeting modes, it will still reflect in the main game.

### Reproducing
1. Try to enter a direct message via profile cards or before a game starts
2. Press a key that clashes as the game starts
3. See error: both actions are carried out at once

### Expected behavior
One of the two should be negated.

### Your setup
 - **OS and version**: Windows 10 21H1 (19043.1237)
 - **Browser and version**: Microsoft Edge, version 94.0.992.31

### Additional context
Issue #700 is about focusing and it also has the same error regarding the Social overlay.

**Comment by deedeeen** [comment]
still there

**Comment by o5k** [comment]
Fixed in next patch.
