### ISSUE TITLE
Revert the change of FT5+ for the unranked

### ISSUE THREAD

**Issue by deedeeen** [tetrio/issues#773]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
There are currently no apparent problems as of the time of the issue. This issue is merely a suggestion about unranked matches being first-to-5 or first-to-7 due to their Tetra Ratings. It is not compatible with the matches ranked by official percentiles.

### Describe the solution you'd like
Scrap the change altogether, and that all unranked players will have their games set at a minimum of FT3.

### Describe alternatives you've considered
Use the rank estimations to decide on the number of sets.

**Comment by ZudoB** [comment]
Do you actually have a reason for requesting this?

**Comment by deedeeen** [comment]
#755.

**Comment by ZudoB** [comment]
That... doesn't really explain why you want the change reverted. Is there a particular reason why you think FT3 is better than FT5/FT7 for unranked players higher than 20K/24K?

**Comment by deedeeen** [comment]
Less hassle to reduce your rating deviation, ensuring enough fairness if you even deserved a higher set count, 20k still belongs to A+ or less/24k still belongs to SS or less (if it does happen) and the like.

**Comment by MegaminX836** [comment]
better safe than sorry, imo 20k/24k are almost certainly the skill of S-/U, and should have FT5/7 matches, in fact, it could even be possible to reduce the FT5 threshold to 18k/19k and FT7 to 23.5k because S- is around 17k and U 23.2k

**Comment by deedeeen** [comment]
then you can consider my alternative solution - do it based on the estimated ranks

**Comment by deedeeen** [comment]
also may anyone add the "controversial" label for me?

**Comment by Sup3rFire** [comment]
I don't agree with this for the reason that I almost lost to an A rank due to rng.

**Comment by Sup3rFire** [comment]
> then you can consider my alternative solution - do it based on the estimated ranks

Using estimated ranks would probably only change the threshold by 1k TR. (wouldn't make much of a difference)

**Comment by deedeeen** [comment]
> I don't agree with this for the reason that I almost lost to an A rank due to rng.

I don't agree with this for the reason that it is way outside the scope of FT5+. Unless you're S- or better.

**Comment by deedeeen** [comment]
> Using estimated ranks would probably only change the threshold by 1k TR. (wouldn't make much of a difference)

It will still reflect the newest leaderboard instead of referring to a set TR.

**Comment by Sup3rFire** [comment]
> I don't agree with this for the reason that it is way outside the scope of FT5+. Unless you're S- or better.

I'm a U rank.

**Comment by deedeeen** [comment]
> I'm a U rank.

Was your TR right before the match, estimated or established, qualifying for U or better?

**Comment by Sup3rFire** [comment]
> Was your TR right before the match, estimated or established, qualifying for U or better?

I was like 23.5k TR at the time so it was definitely qualifying for U

**Comment by deedeeen** [comment]
> I was like 23.5k TR at the time so it was definitely qualifying for U
that's better - just to clarify, you want FT5 for that battle right?

**Comment by Sup3rFire** [comment]
> that's better - just to clarify, you want FT5 for that battle right?

Yeah definitely, FT5 helps balance the RNG out and keeps people from losing games randomly.

**Comment by deedeeen** [comment]
> Yeah definitely, FT5 helps balance the RNG out and keeps people from losing games randomly.

I don't like FT7 being thrown into the battle, but FT5 works for me.

**Comment by Sup3rFire** [comment]
> I don't like FT7 being thrown into the battle, but FT5 works for me.

FT7 only happens in 24k and above. It won't affect average people, but would be extremely helpful for reducing the amount of RNG that occurs in higher skill levels.

**Comment by Sup3rFire** [comment]
Unless you are high skilled enough, you will almost never encounter FT7.

**Comment by deedeeen** [comment]
I still do not prefer FT7 to appear as part of a mutually unranked match. There is a chance that you don't deserve a FT7 game at all, or if someone of unranked FT7 battles against a ranked FT5.

**Comment by Sup3rFire** [comment]
> I still do not prefer FT7 to appear as part of a mutually unranked match. There is a chance that you don't deserve a FT7 game at all

this is more of an issue in how TR is calculated when a player has high RD. There is still a very low chance you don't deserve the higher FT game because the rating required for the higher FT is much higher than where you would normally get the higher FT. ~1k TR for FT7 (might not seem like much but you don't get basically any TR starting from like 23k) and ~3k TR for FT5.

> or if someone of unranked FT7 battles against a ranked FT5.

osk said that:
> Games between **two unranked players** are now still FT5 and FT7 if the higher of their TRs is over 20K and 24K respectively

**Comment by deedeeen** [comment]
> this is more of an issue in how TR is calculated when a player has high RD. There is still a very low chance you don't deserve the higher FT game because the rating required for the higher FT is much higher than where you would normally get the higher FT. ~1k TR for FT7 (might not seem like much but you don't get basically any TR starting from like 23k) and ~3k TR for FT5.

it boils down to how confident the system is. as the system will only generate a consistent TR at a RD at most 100 and that rank pinpoints your sets to win, I still want FT7 to not be played until at least one player establishes a rank strictly qualifying for FT7. note that I now agree with the FT5, just that I don't want it to tie with the TR but something else.

> Quoting osk: Games between two unranked players are now still FT5 and FT7 if the higher of their TRs is over 20K and 24K respectively

yeah, it's pretty much my fault for this :P

**Comment by MegaminX836** [comment]
if we are using the estimated ranks, would we consider the unranked's estimated level to be glicko - 2RD, glicko -RD, just the glicko, glicko + RD or glicko + 2RD or something else? We would want to skew this in this scenario because of the uncertainty.

**Comment by MegaminX836** [comment]
Also, would this apply to players that have not finished their rating games? i believe these players still have an estimated glicko and RD, just that it is not visible to the player.

**Comment by deedeeen** [comment]
the formula for TR can be applied to a RD beyond 100; it was only discouraged for the usage because you will not have had a stable rating. 
and they do have hidden estimated figures.

**Comment by MegaminX836** [comment]
yeah so instead of using the TR formula you skew the glicko with the RD first to be safe (would probably need a different formula), _then_ compare to the estimated ranks to decide between FT3/5/7.

**Comment by deedeeen** [comment]
the only problem is to find a formula that does this that won't tie itself to a set number.

**Comment by ZaptorZap** [comment]
Due to relative inactiveness regarding unique individuals, as well as a generally negative/inconclusive reaction to the proposal (such as the 4 👎 reactions in the topmost description post), it's very unlikely osk will be considering the superficial changes proposed. Thus, to help clear the issue queue, we have decided to close and lock the discussion after internal debate between the staff. If osk does decide to go through with the changes, then the chat logs created here will be preserved for their viewing.
