### ISSUE TITLE
client side saved textures

### ISSUE THREAD

**Issue by StampyIIYT** [tetrio/issues#774]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Describe the solution you'd like
Making custom textures may already be possible, but its not obvious, but having the textures be saved and loaded in the Tetr.io desktop folder would allow anyone to easily create, edit, and import custom texture packs that can load on their end of the game.

### Describe alternatives you've considered
A program that can import images to the client.

**Comment by o5k** [comment]
Won't be implemented this way, prefering #359
