### ISSUE TITLE
Memory shortage when big height/width of field is inputted

### ISSUE THREAD

**Issue by 4500zenja1** [tetrio/issues#776]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When I'm trying to create a custom game with large board dimensions, like 10000x10000, firstly nothing happens, and then an error of memory shortage is appearing in my browser. Maybe there are some other cases in app or smth else, but still

### Reproducing
1.  Go to "Solo"
2. Go to "Custom"
3. Put on "Board width/height" fiels some big numbers that > 10e4.
4. Press "Start".

### Expected behavior
A field with prescribed amount of width/height blocks should be available to play with.

### Your setup
 - **OS and version**: Windows 10 Pro, 20H2
 - **Browser and version**: Opera GX LVL3 (core: 78.0.4093.186)

### Additional context
A limit for maximal amount of width/height blocks ought to appear in the future updates and/or checking if the area of the field is NOT bigger than maximal one.

**Comment by o5k** [comment]
...not entirely sure what you expected

**Comment by o5k** [comment]
fixed
