### ISSUE TITLE
Fire VFX look too small when spectating with more than 9 players

### ISSUE THREAD

**Issue by Strode0496** [tetrio/issues#777]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When spectating a game in a room with more than 9 players, the fire graphic looks too small if the player's board is on fire. When the number of players is reduced to 8 or less, it will look normal again.

### Reproducing
1. Choose the graphic settings above the setting where the fire graphic is visible(probably HIGH or ULTRA).
2. Enter a room with a large number of players(mainly QUICK PLAY) and spectate the game. Wait for the player to catch fire.
3. If the player fires when there are more than 9 players, i.e. when the player thumbnail is simplified, you can see the fire appear very small.
4. When the number of players is reduced to 8 or less, the fire graphics are displayed normally again.

### Expected behavior
The size of the fire effect also changed depending on the player's board size so spectating was not a problem until the 6.1.0 graphics update.

### Screenshots
![2021-09-30 03;17;06.PNG](https://cdn.discordapp.com/attachments/707944758458318881/893074467302031400/2021-09-30_031706.PNG)
![2021-09-30 03;13;38.PNG](https://cdn.discordapp.com/attachments/707944758458318881/893074869665824778/2021-09-30_031338.PNG)
Video: https://streamable.com/bzp4o6 (from 45s)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Desktop client

### Additional context
I'm using a FHD monitor and RTX 2060.

**Comment by deedeeen** [comment]
Random question: may I have the exact W10 build/version?

**Comment by Strode0496** [comment]
> Random question: may I have the exact W10 build/version?

Are you asking about my Windows OS version?

**Comment by deedeeen** [comment]
> Are you asking about my Windows OS version?

Yes.

**Comment by Strode0496** [comment]
Idk if you're talking about this, but it's 1909.

**Comment by deedeeen** [comment]
Yup, that's the thing. Thanks.
