### ISSUE TITLE
Broken TL replay when the player disconnected from match before start of the game

### ISSUE THREAD

**Issue by 4500zenja1** [tetrio/issues#778]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
If you're trying to replay the match where the opponent left the match before the start of the 1st round, their tab in VS row is completely empty, while the mine doesn't have PPS, APM and VS fields. While trying to click the empty tab, "Unknown user ID" error is appearing.
Also, the round table is completely empty, too.

### Reproducing
1. Play a TL game where your opponent (or you) is leaving the match before the start of the 1st round;
2. Go to the replay of this match.

### Expected behavior
The full statistics of the opponent is expected to be seen (points, APM, etc.) + PPS, APM and VS on my side. Also a single row of the 1st round where you can see the opponent has left the match should be there, too.

### Screenshots
![Снимок экрана 2021-09-30 221752](https://user-images.githubusercontent.com/83463196/135517088-692bb1be-652a-4278-95a9-778b774c2ea9.png)

### Your setup
 - **OS and version**: WIndows 10 Pro 20H2
 - **Browser and version**: Opera GX LVL3 (core: 79.0.4143.73)

### Additional context
![Снимок экрана 2021-09-30 222052](https://user-images.githubusercontent.com/83463196/135517355-92c4f160-3724-44b3-9cb0-81cb1788708b.png)

**Comment by 4500zenja1** [comment]
Additional information:

1. https://tetr.io/#R:qdBH5RnuG — the url of replay in question;
2. If you have watched the other replay where everything is OK, and then go to the broken replay, the data will be rewritten as if the data from the NORMAL replay was inputted. 
https://tetr.io/#R:_jWJEsMDy is the url of the replay which data has been flew into the replay in the question.
Also note that every single characteristics is taken from that replay, except for my score — it is still 0.
![Снимок экрана 2021-09-30 222228](https://user-images.githubusercontent.com/83463196/135517671-1a147245-40e6-4e1f-bf22-d1ef06463069.png)

**Comment by Sup3rFire** [comment]
I've also happens on other normal multiplayer games.

**Comment by Dimentio** [comment]
I believe I accidentally fixed this in the next update, I cannot replicate anymore
