### ISSUE TITLE
"Disable sound entirely" does not disable sound entirely

### ISSUE THREAD

**Issue by wooster0** [tetrio/issues#786]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
If you check "Disable sound entirely" in the config, the sound is not immediately disabled entirely. Only sound effects are disabled. All sound is disabled only after a restart of the game. All sound should immediately be disabled on click.

### Reproducing
1. Go to 'Config'
2. Click on 'Volume & Audio'
3. Scroll down to 'Disable sound entirely'
4. Click it 

### Expected behavior
The sound is immediately disabled entirely and you hear nothing after clicking the option.

### Your setup
 - **OS and version**: Pop!_OS 21.04
 - **Browser and version**: I use the client.

### Additional context
See also: #455

**Comment by r00ster91** [comment]
This is still an issue.

**Comment by patrickzhou1234** [comment]
yes. this is an issue

**Comment by Dimentio** [comment]
Looks good on the latest patch, I assume this got fixed so closing!
