### ISSUE TITLE
Ability to play from a replay board state, like in Four-tris (a third party tool)

### ISSUE THREAD

**Issue by itchylol742** [tetrio/issues#787]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

When reviewing replays, I want to see what mistakes I made, and what I could have done instead. The only way to see what I could have done instead is visualize the pieces (hard) or use Four-tris (third party software) which requires a bit of finangling to do.

### Describe the solution you'd like

A built in tool that allows you to play from the board state of a replay.

### Describe alternatives you've considered

Continuing to use Four-tris, or integrating Four-tris into Tetr.io since Four-tris is open source.

### Additional context

Four-tris is a third party training tool for all tetris games (not just Tetrio) that allows users to set a custom board state, and set a custom piece queue then play using that board state. The first picture shows Four-tris when playing normally, the second shows the use of setting a custom board state by drawing with the mouse and changing the queue to be only T pieces.

![fourtris png](https://user-images.githubusercontent.com/42976312/136636907-e27760f4-1bb2-4a09-95c4-b5a070a932c2.PNG)

![fourtris2 png](https://user-images.githubusercontent.com/42976312/136636952-bfde0c9b-0c75-41ac-a073-28ec51e28e02.PNG)

**Comment by ZaptorZap** [comment]
Downright integration of four-tris seems rather unlikely, as four-tris is an fully featured downloadable client created in the AutoIt programing language, one that very much conflicts with TETR.IO's JavaScript oriented web-facing codebase. This integration could be restricted to the downloadable TETR.IO Desktop, but, at that point, I feel it's such a departure from TETR.IO's standard for design practices regarding visual flair and usability.

Regardless, this seems to be a duplicate request of both #763 and #212, unfortunately.
