### ISSUE TITLE
[Visual bug] Moonbeams from attacks remain sparkling if Garbage Travel Speed is very high

### ISSUE THREAD

**Issue by GlitchyPSIX** [tetrio/issues#799]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 Home

### Browser and version

TETR.IO Desktop (6.1.3)

### Describe the bug/issue

[A moonbeam will keep glowing in the background](https://i.imgur.com/NrvDYJJ.gif) and after the round is over when Garbage Travel Speed is set to a high number. (500 in this case)

### Reproducing

1. Create a custom room with a garbage travel speed of 500.
2. Send garbage
3. Wait for the round to end (See #800)

### Expected behavior

The screen is clean.

### Screenshots

https://i.imgur.com/NrvDYJJ.gif

### Additional context

testing t99 like ruleset xd

**Comment by GlitchyPSIX** [comment]
excuse me of course it is still relevant

**Comment by o5k** [comment]
Fixed in next patch.
