### ISSUE TITLE
Separate Solo and Multiplayer settings

### ISSUE THREAD

**Issue by mat1jaczyyy** [tetrio/issues#8]
Separating game parameters for Solo and Multiplayer would be a nice addition. For example, I like to play 40 Line with instant soft drop to try and fix mistakes quickly, but I don't like this in multi where I have to play consistently and tuck pieces precisely. Alternatively, easily switchable presets might be a thing, but sound like more of a hassle to do.

**Comment by GameTilDead** [comment]
I'm glad I came across this, any update in the last 3+ years?
