### ISSUE TITLE
Round end will not display fanfare if Garbage Travel Speed is high

### ISSUE THREAD

**Issue by GlitchyPSIX** [tetrio/issues#800]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 Home

### Browser and version

TETR.IO Desktop (6.1.3)

### Describe the bug/issue

After the round ends, no fanfare is displayed as the visual effect for garbage plays slowly. (Only happens when garbage travel speed is high [tested with 500])

### Reproducing

- Steps from #799

### Expected behavior

The fanfare plays and shows the winner's playername.

### Screenshots

![image](https://user-images.githubusercontent.com/11571952/138628682-909c324a-3515-4edf-bb6d-143a7e2050f0.png)
This is all you see until the results screen. The moonbeams eventually complete their path.

**Comment by GlitchyPSIX** [comment]
:gun: it is still relevant because it still happens

**Comment by o5k** [comment]
Fixed in next patch.
