### ISSUE TITLE
Support for vertical monitors

### ISSUE THREAD

**Issue by sean1006** [tetrio/issues#810]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

By default, it seems like the game will be scaled a decent size smaller when playing on a split screen or using a vertical monitor.

### Describe the solution you'd like

It would be nice if there was some sort of automatic scaling to better use screen estate for windows which are more vertical than horizontal. Even a manual toggle to allow this would be great. It would be a good general usability improvement if it's not too hard to implement.

Mostly talking about solo play since implementation in versus seems like it would be a pretty big redesign.

### Describe alternatives you've considered

On the user side, we can manually scale up via browser, but it's a hassle and often leads to other functionality feeling more clunky (buttons, interface, etc.).

**Comment by ZaptorZap** [comment]
Unfortunately, this seems to be a duplicate issue report of #458. While you mention scaling with the browser, it's also _possible_ to breach the general limits of the ingame "board zoom" slider as well, to make things plenty more readable.
