### ISSUE TITLE
Clicking NEXT in the lobby results can freeze game

### ISSUE THREAD

**Issue by BunnyBoing** [tetrio/issues#811]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 21H1

### Browser and version

Google Chrome 95.0.4638.69

### Describe the bug/issue

When a game is finished in a lobby, and you are brought to the screen that shows each player's statistics and results, when clicking on the Next button, you can click on (what I think) is an ad on the next screen, and it will visually freeze the game in one of the transition frames, until the next game has started.

### Reproducing

1. Play a game in a lobby
2. When ending the game, press the Next button (make sure there are ads on your screen)
3. If there is an ad, the game should completely freeze, until the game starts.

### Expected behavior

When you click on the Next button, the game should freeze. If it freezes on one of the later transition frames, where you can see the chat, and some of the buttons, you will probably be able to see one of the ads behind it.

### Additional context

I am 90% sure it only works with ads on the next screen.

**Comment by Blyxyas** [comment]
Wanted to say that this happens 90~% of the matches I play, both in Tetra League as in a Custom Game with another person.
