### ISSUE TITLE
Frequent crashes in Firefox under Linux using Wayland

### ISSUE THREAD

**Issue by K4rakara** [tetrio/issues#817]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Linux Kernel 5.14.16-arch1-1, Arch Linux, Sway Window Manager

### Browser and version

Mozilla Firefox 95.0b3, with MOZ_ENABLE_WAYLAND=1, may apply to Chromium as well

### Describe the bug/issue

Seemingly at random, the game will hard crash the entirety of Firefox, requiring the browser to be closed and reopened. In my testing, this issue consistently occurred within 30 minutes of starting to play.

### Reproducing

Set up a virtual machine with any Linux distro. I'm not sure if this bug is present under X11 (the other graphics backend for Linux), but for the sake of reproducibility, Fedora should be the easiest to reproduce this bug under, since it uses Wayland by default. 

Once you've set up a Fedora VM, install firefox on it, as well as a terminal. I'm not sure if Fedora has one installed out of the box, but one should be available in the store.

Open up the terminal and type the following:

```sh
export MOZ_ENABLE_WAYLAND=1;
firefox;
```

This will start Firefox with Wayland support. Once its opened, navigate to [tetr.io](https://tetr.io) and play for about 30 minutes in zen mode. The bug should manifest at some point during that time period. For me, it occurred at least once every 5 minutes.

Once the tab has crashed, attempting to reload it or open a new tab of tetr.io, it instantly crashes.

### Expected behavior

Well, no crashes, especially not at random.

### Screenshots

![unknown](https://user-images.githubusercontent.com/40474474/140619007-2d8d3059-0449-4a89-a1c8-7489e257858b.png)

### Console logs

The tab hard crashes, so there's no way I know of to get logs other than maybe setting up a debug websocket to send messages to?

If theres some way I can get firefox to emit console.log messages to stdout, I could upload that.

### Additional context

I experienced a similar issue with the desktop version, installed using the [AUR package](https://aur.archlinux.org/packages/tetrio-desktop/), which resulted in my _entire desktop_ to become frozen and unusable.

**Comment by ZudoB** [comment]
In a similar manner to #768, this isn't a TETR.IO problem since the issue is extending out of the browser sandbox. Wayland is notoriously unstable right now, so please consider using Xorg as a workaround.

**Comment by K4rakara** [comment]
> In a similar manner to #768, this isn't a TETR.IO problem since the issue is extending out of the browser sandbox. Wayland is notoriously unstable right now, so please consider using Xorg as a workaround.

Ah, my bad. I'll try running the game in a container with Xwayland, that might do the trick. If not, I'll try filing a bug on Firefox.

**Comment by notkirito** [comment]
Can't reproduce on Firefox 93.0 on Arch Linux, sway, MOZ_ENABLE_WAYLAND=1, kernel 5.14.14-arch1-1. IMO not a Wayland issue, maybe it's a Firefox beta issue?

**Comment by K4rakara** [comment]
> Can't reproduce on Firefox 93.0 on Arch Linux, sway, MOZ_ENABLE_WAYLAND=1, kernel 5.14.14-arch1-1. IMO not a Wayland issue, maybe it's a Firefox beta issue?

That could be it as well-- I'm running Firefox Developer Edition, which is just a bit behind nightly iirc? It works on my laptop that is on Firefox 93 as well, but that has an intel HD card.

**Comment by notkirito** [comment]
I have an Intel HD card too.
