### ISSUE TITLE
Matrix size adjustment for multiplayer

### ISSUE THREAD

**Issue by GhtGhoster** [tetrio/issues#819]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I like to make art. The new feature in solo custom games gives me new freedom but also makes me lonely :( and nobody can come into the room to have a look either :(

### Describe the solution you'd like

I would like to be able to use the new matrix size adjustment feature in custom solo games in multiplayer custom rooms as well.

### Describe alternatives you've considered

Streaming, but my internet is too weak and either way it doesn't have the same vibe.

### Additional context

![how it could look like](https://user-images.githubusercontent.com/32255934/140871235-42a59e39-7b0b-43bb-84d7-33a58df16f76.png)

**Comment by ZaptorZap** [comment]
This seems to be a duplicate issue of #475, unfortunately. I'll have to reopen that, though, so hold on a second.
