### ISSUE TITLE
Passthrough on Tetra League

### ISSUE THREAD

**Issue by UrushiY** [tetrio/issues#821]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome 95

### Describe the bug/issue

I was playing Tetra League and there was passthrough during the match, a couple of times, and I lost cause of that

### Reproducing

I don't know what exaclty need to be done for that to happen, but I just
1. Play Tetra League
2. Specially during openings it happens

### Expected behavior

Not have passthrough and the garbage cancels

**Comment by ZudoB** [comment]
You may still experience passthrough in certain situations, for example if one or more players has high latency.

Unfortunately, it's impossible to remove passthrough completely without compromising other aspects of gameplay.
