### ISSUE TITLE
Soft drop bug in Chrome

### ISSUE THREAD

**Issue by animalotta0206** [tetrio/issues#826]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

chrome os Version: 94.0.4606.124 (Official Build) (64-bit)

### Browser and version

Version: 94.0.4606.124 

### Describe the bug/issue

<p>The soft drop used when doing T-spin etc. has a bug that the soft drop operation is input continuously very rarely.<br>
If such a bug occurs, you can temporarily fix it by typing the soft drop operation on the keyboard again.</p>

### Expected behavior

<p>If such a bug occurs in an online match, the operability will be very poor, which may have an adverse effect on the match.</p>

**Comment by ZaptorZap** [comment]
Easily reproducible, duplicate bug report of #680 (admittedly an old, closed issue so I can't blame you for not seeing it. I'll reopen it now)
Not unique to the Chrome browser either, as it's possible in both Firefox and the Desktop client.
