### ISSUE TITLE
WEBGL crashing

### ISSUE THREAD

**Issue by Seiryu-uwu** [tetrio/issues#827]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

mac OS Catalina 10.15.7

### Browser and version

chrome

### Describe the bug/issue

![Screenshot 2021-11-22 at 09 07 24](https://user-images.githubusercontent.com/94827899/142825273-23216552-fa06-4b65-a263-90443cfb39e7.png)
webgl keeps crashing

### Expected behavior

cant play any game

**Comment by ZaptorZap** [comment]
Are there any logs you could send us? Just hit `Command+Option+J` to open it, and send over any text highlighted **red**. Furthermore, does this happen as soon as you login? When you start a match, be it 40 LINES or QUICK PLAY? Midgame at some point?

**Comment by Seiryu-uwu** [comment]
no it happens when i start a match
![Screenshot 2021-11-22 at 09 26 53](https://user-images.githubusercontent.com/94827899/142827762-fefdcaed-2e88-43bf-a878-cbd51fc0a2b0.png)
.

**Comment by ZaptorZap** [comment]
Well, those specific errors really shouldn't forbid WebGL from running correctly, they seem to point to missing or blocked ads, actually, and TETR.IO certainly runs fine under ad-blockers. Are you sure this is all your console's showing? Have you modified your Mac's graphics hardware in any capacity, or, are you running Catalina under unsupported hardware? I understand these GPUs should be fairly standardized.

**Comment by Seiryu-uwu** [comment]
![Screenshot 2021-11-22 at 09 35 15](https://user-images.githubusercontent.com/94827899/142828895-3af9d810-07ce-4854-ae73-ba64749ff1a7.png)
![Screenshot 2021-11-22 at 09 35 26](https://user-images.githubusercontent.com/94827899/142828899-600bf851-def1-4500-ab3d-e1e957f850ef.png)
this is everything thats red. I never modified anything on this mac and everything should be running on supported hardware. I only changed the ssd in my mac.
