### ISSUE TITLE
Switching from spectator to playing mid-game

### ISSUE THREAD

**Issue by theknightD2** [tetrio/issues#828]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

So I have realized that there is no way to switch from spectator to playing and vice versa in any room if there is a game in progress.
Now, you might be thinking, why can't you switch when the game is finished?
Well, like a lot of you, I play zen while waiting. 
I don't always notice when a game has finished and thus miss my chance. 
If I consciously keep checking, well that kind of defeats the point of having zen, since I can't focus on both.

### Describe the solution you'd like

What I would like to see is the ability to switch from spectator to playing while a game is in progress. So if you were spectating, you would be able to switch to playing, and it might say something like "Your change will apply next round" or something.

### Describe alternatives you've considered

I don't know, skip playing zen one round to make the change?
(Which is boring).

**Comment by o5k** [comment]
Fixed in next patch.
