### ISSUE TITLE
Download Tetrio Desktop Error

### ISSUE THREAD

**Issue by Xenonites** [tetrio/issues#829]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

OS: 17763.1577 . Version: 1809

### Browser and version

Chrome, Version 96.0.4664.45 (64-bit)

### Describe the bug/issue

I downloaded the tetrio desktop setup and i've run it for 3 hours now and the installing is stuck

### Expected behavior

I hope that this can be fixed because i play tetrio using desktop version and if this didn't getting solved, probably i'll quit this game.

### Screenshots

![image](https://user-images.githubusercontent.com/94899574/143004227-af2b5847-f131-4bd6-881b-3def0c88bf6b.png)

**Comment by Kecxyz** [comment]
From ZaptorZap in TETR.IO discord:
>You can use a *good* archiving program, such as 7zip(<https://www.7-zip.org/download.html>), to manually extract the game's contents for a much more manual installation for now. Here's a quick video guide(really, just open the `.exe` as a compressed folder and drag stuff out!):[Video](https://cdn.discordapp.com/attachments/673305614318960671/904141134752784434/use_7zip.mp4)

**Comment by Xenonites** [comment]
Thank you so much 🙏🏻🙏🏻

Pada tanggal Sel, 23 Nov 2021 18.18, Kecxyz ***@***.***>
menulis:
