### ISSUE TITLE
Show graph for e.g. Blitz improvements & recent games

### ISSUE THREAD

**Issue by RiedleroD** [tetrio/issues#830]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I want to see my progress over time & boast about my god-like tetris skills (which don't exist, fyi)

### Describe the solution you'd like

A/Multiple graph(s) in the user statistics section, with various data (I personally would like to see Blitz highscore over time)

Could also be added for worldwide records and average daily scores, stuff like that.

### Describe alternatives you've considered

none, this is a add or don't add feature.

**Comment by Anonymous-Brazilian** [comment]
That would honestly be a really cool feature

**Comment by KGX-Rusky** [comment]
You can check out https://tetrio.team2xh.net/ for now, it's got graphs of your TR, APM, PPS and VS and a bunch of other things, although it might take a billion years to load.

**Comment by AzuraHorizons** [comment]
I assume this should be closed as completed, likely alongside several other Tetra Channel updates with the recent beta 

(I'll stop commenting on them all, I assume the staff team can find the relevant issues themselves.)

**Comment by ZaptorZap** [comment]
ya
