### ISSUE TITLE
Serious Network issues from server

### ISSUE THREAD

**Issue by joysti** [tetrio/issues#831]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Chrome

### Describe the bug/issue

Serious Network issues from server

### Expected behavior

I'm user from Korea, and Network error has been seriously effecting gameplay for last 5 to 6 days.
My wifi doesn't have a problem but network error happens almost 3~4 times in 5 games.
(I got lost almost 3 in a row in tetra league because of network issue..)
It happens case by case, but everytime the network unstables, my friends playing tetrio also undergoes network issues.
So I think it's a server problem from tetrio... and it really effects my gameplay and get sad.. :(
Please help me..

### Screenshots

![image](https://user-images.githubusercontent.com/94926970/143081091-cbdb18a0-b721-4ef7-be65-88b85e99289a.png)

**Comment by o5k** [comment]
your internet sucks

**Comment by joysti** [comment]
> your internet sucks

no it's not ;

**Comment by zvuc** [comment]
Another user from korea here. I have been playing tetrio at least every 2 days every evening (KST 9PM ~ 12PM) so I know for sure at least there's something going on with the network/servers. From my several months of playing I've never experienced myself disconnecting during match, but the frequency greatly increased recently. And starting today I've been getting constant lags (=sudden spikes) during tetra league which ended in the same "Network changed" error.
<img width="521" alt="Screen Shot 2021-11-24 at 11 30 13 PM" src="https://user-images.githubusercontent.com/2870726/143258057-5b0cb47c-13de-4f37-9ba9-297533f08fff.png">

And no, my internet does not suck, 50MB/s up and down, no ping issues, everything else works fine. If nothing on tetrio side has been changed regarding connection/servers I'm only assuming there's some problem with routing specific to the Korea region.

Please do investigate on this, looking at today's state of the matches it doesn't seem like I want to challenge myself playing Tetra League again until it's returned to normal.

**Comment by flashwave** [comment]
Try doing a speedtest using [this](https://proof.ovh.net/) to one of the French servers, I don't recall specifically which data centre tetrio uses. If it is something on the server side, it's probably a temporary issue in the hands of the provider.
