### ISSUE TITLE
Practice Mode with CPUs + Achievements

### ISSUE THREAD

**Issue by GagePatoine** [tetrio/issues#833]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

You see, I almost ALWAYS LOSE to actual players, mostly because of how bad I am.

### Describe the solution you'd like

Okay. *clap* Here's the idea.

Vanilla/Practice Mode. It's basically just Zen mode, but it works like normal Tetris. BUT, here's the catch.

You can add customizable CPUs to the run. You can change how good they are, and how many. And most importantly, unlike Custom (which I'm not sure can do that), it _ACTUALLY GIVES YOU EXP._

And if you get a 100 player Practice match, you also get a special badge that's basically just a pixelated medal with a robot on it.

I also have another idea as well! Achievements. You know the drill for that one.

So there's my ideas. Hopefully it can be made sometime.

### Describe alternatives you've considered

I'm also considering if you could add it to the Custom mode as well? I dunno...

**Comment by Jabster28** [comment]
Looking at the open issues, the first one sounds likes duplicate of (now stale) #78, unless i'm missing something? And your idea for achievements is a duplicate of #23. You can add your two cents as comments on those issues, though.

**Comment by GagePatoine** [comment]
> Looking at the open issues, the first one sounds likes duplicate of (now stale) #78, **unless i'm missing something**?

Now, I'm not talking about bots that JOIN the game, I'm talking about bots that are in the game from the start, as soon as you click Start.

> And your idea for achievements is a duplicate of #23.

...Wait, ***really?***

**Comment by Jabster28** [comment]
Yeah, it's a small world out there. Great minds think alike and all that.

> as soon as you click Start.

Start as in the "START" button at the bottom? If so, that's the same thing that issue is talking about. If you mean like before you make the room, I'm not sure how that'd be any different gameplay-wise.

**Comment by ZaptorZap** [comment]
Yeah, I've gotta agree with @Jabster28 here, this appears to be a duplicate request of the aforementioned #78 feature request so I'll reopen that up. I can tell a large part of this feature request was its addition as a SOLO mode, though. This report has already gotten a small shoutout on #78 but you're more than welcome to leave a longer reply there detailing your desire for a SOLO mode too, if you'd like.
