### ISSUE TITLE
Incorrect country when creating a new account

### ISSUE THREAD

**Issue by AWildShinx** [tetrio/issues#834]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 7 

### Browser and version

Chrome Version 96.0.4664.45 (Official Build) (64-bit)

### Describe the bug/issue

When creating a new account, I noticed that my nationality is listed as Australian. However, my nationality is Indonesian. I was about to change my nationality flag, only to see that I have to pay for it. Are there ways to request flag change?

### Reproducing

1. I created a username and password to make a Tetr.io account
2. It suddenly listed as Australian

There is not much I can tell about reproducing it

### Expected behavior

It shows Australian nationality instead of Indonesian nationality

### Screenshots

![image](https://user-images.githubusercontent.com/67431060/143793627-abc8f998-aaf4-4bdf-a517-de6982c46027.png)

**Comment by ZudoB** [comment]
Email support@tetr.io

**Comment by ZaptorZap** [comment]
Furthermore, this points towards yourself registering under a VPN or otherwise proxied connection and isn't exactly unintended behavior.

**Comment by AWildShinx** [comment]
Well, I don't remember turning on VPN while registering, oh well
