### ISSUE TITLE
chat glitch 

### ISSUE THREAD

**Issue by madkiwilol** [tetrio/issues#835]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

chrome os

### Browser and version

google chrome

### Describe the bug/issue

you have to press space before enter to talk instead of 

### Reproducing

go on multiplayer 
and then just talk 

### Expected behavior

just enter to talk instead of having to press space and then press enter 

### Additional context

idk if it is just my Chromebook or my grammar setting

**Comment by ZudoB** [comment]
There is a keybind for opening chat while in game. If yours is set to space, then you'll naturally have to press space to open the chat box.

Either this is intended behaviour, or you're not providing enough information to identify the issue.

**Comment by madkiwilol** [comment]
no, its after you type what you want in chat so i click on the boz and type
what i want so "gg" and then i have to press space before enter and my
keybind is `  not  space

**Comment by flashwave** [comment]
Pretty much sounds like some kind of autocomplete thing getting in the way, try disabling the grammar setting and see if it persists.

**Comment by madkiwilol** [comment]
Will do, thanks!

**Comment by craftxbox** [comment]
Can reproduce. This is a function of language autocorrection, and not TETR.IO. Disable autocorrection in the settings through  Advanced > Languages and inputs > Inputs > <your input method>
And changing 'Auto-Correction' from Modest, or Aggressive, to off.

**Comment by madkiwilol** [comment]
Awesome, thanks!
