### ISSUE TITLE
Forcing TETR.IO to close using Command Prompt makes the program go black and does not ever load the menu.

### ISSUE THREAD

**Issue by Lailou12** [tetrio/issues#836]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 Version: 20H2

### Browser and version

MS Edge Version 96.0.1054.34

### Describe the bug/issue

When you type in TASKKILL /F /IM TETR.IO.exe in the Command Prompt, then run the command, it forcefully closes the game, with no popup whatsoever to confirm this. After booting the game up, TETR.IO as always, checks for updates, it fails and tries to load the menu. It can't so it is stuck in a black screen.

### Reproducing

1. Open Command Prompt
2. Type in TASKKILL /F /IM TETR.IO.exe
3. Reboot the game.

### Expected behavior

I expected TETR.IO to just close, not do this bug, as it had no child processes that were shown in Task Manager, after that, I expected it to boot up normally.

### Additional context

I have played TETR.IO on the desktop version for quite some time now, it seems to only work when you play it for a long time, as I couldn't reproduce the glitch when I tried to do it again.

Glitch result:

SUCCESS: The process "TETR.IO.exe" with PID 19776 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 3520 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 7692 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 26412 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 27024 has been terminated.

Reproduction result:

SUCCESS: The process "TETR.IO.exe" with PID 15164 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 25272 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 20816 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 19576 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 26180 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 12696 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 18296 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 25688 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 2600 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 9680 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 4420 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 24356 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 22728 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 29372 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 26056 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 24852 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 17188 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 25368 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 20440 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 19776 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 20552 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 524 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 10308 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 13092 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 25360 has been terminated.
SUCCESS: The process "TETR.IO.exe" with PID 4908 has been terminated.

Additional processes were somehow involved. I don't know a lot about coding and stuff like that.

**Comment by o5k** [comment]
...so what's wrong with the X button?

**Comment by Lailou12** [comment]
I tried closing it, the same thing happened, stuck on the black screen.

**Comment by ZaptorZap** [comment]
Have you tried restarting the computer yet?

**Comment by Lailou12** [comment]
The TETR.IO program screen went black, not the computer itself, sorry if you misunderstood.

**Comment by ZaptorZap** [comment]
Well, the question still stands. A fresh reboot will likely clean up some messed up files from your less-than-ideal unplanned, forced shutdown of the TETR.IO application.

**Comment by Lailou12** [comment]
I could've done that, but I instead reinstalled the game and everything seems to be working fine now.
Also, I missed some information. I was in a zen game when I did the prompt, it must be why I couldn't reproduce it.
