### ISSUE TITLE
Invalid default bag type "7bag" in custom rooms

### ISSUE THREAD

**Issue by ZudoB** [tetrio/issues#841]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

macOS 12.0.1

### Browser and version

Firefox 94.0.2

### Describe the bug/issue

When creating a custom room, the default bag type is set to "7bag". While this technically works, the correct value should be "7-bag", as `/set` will reject "7bag" as a value for this option.

### Reproducing

1. Create a custom room
2. Navigate to the "GAME" tab
3. Observe that "Random Bag Type" is set to "7bag"
4. Try `/set game.options.bagtype=7bag` and note that this is rejected by the server

### Expected behavior

Random Bag Type (game.options.bagtype) should be set to "7-bag" by default, rather than "7bag".

### Screenshots

When creating a custom lobby:

<img width="615" alt="image" src="https://user-images.githubusercontent.com/4703499/145070177-16bdaba5-b5c8-482b-ab2a-4921e1690d3c.png">

The correct value:

<img width="626" alt="image" src="https://user-images.githubusercontent.com/4703499/145070256-1f574757-6094-4538-8531-d2c36ebeecbf.png">

### Console logs

Nothing applicable here. Appears to be a server issue, as the erroneous value is sent *by the server* to the client.

### Additional context

While this typically doesn't affect regular users, this caused me a bit of a headache as a bot developer - while saving the default custom room settings, I noticed that the bag type wasn't being reset properly due to the erroneous value.

**Comment by o5k** [comment]
Fixed in next patch.
