### ISSUE TITLE
Bug with levels

### ISSUE THREAD

**Issue by GavroluX** [tetrio/issues#842]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome 96.0.4664.45

### Describe the bug/issue

Leveling up is detected differently based on the tab you have opened, you can be level 20 on one tab and 10 on the other if you leveled up from 10 to 20 on the other tab

### Reproducing

1. have 2 tabs opened
2. one should level up at least once
3. on one tab you'll be a level ahead and on the other one behind.

### Expected behavior

the servers should update levels in lobby not just in profile, it seems that profile update is client side too(?) unsure of that, but that doesn't matter. the point is, levels should update automatically regardless of what tabs you have opened or browser, e.g every minute or so.

### Screenshots

---

### Console logs

---

### Additional context

---

**Comment by flashwave** [comment]
for what reason do you have two tabs open? as far as the server is concerned you're level 20 regardless in this situation, just seems like needless work to "fix" this

**Comment by GavroluX** [comment]
The reason is I was in a room waiting for the in game game to end, then a
friend invited to a room so I opened another tab for that, but yeah, I
guess it wouldn't need a fix, sorry for the trouble.
