### ISSUE TITLE
hey I have a macbook and this won't work

### ISSUE THREAD

**Issue by Christian9823** [tetrio/issues#849]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Macbook Air

### Browser and version

Chrome

### Describe the bug/issue

ok for some reason if I try to open the tetrio PLUS, but it keeps saying "this creator is not verified" and it is making me mad, so can you fix that please

### Expected behavior

ok so when I tried to open the Tetrio PLUS app, I thought it would work normally

**Comment by ZaptorZap** [comment]
Sorry, but we do not provide support for the third party modification TETR.IO PLUS. Please report this issue with [their issue tracker](https://gitlab.com/UniQMG/tetrio-plus/-/issues) instead. Thanks!
