### ISSUE TITLE
Google Chrome auto-fills username and password in chat and room ID boxs.

### ISSUE THREAD

**Issue by ghost** [tetrio/issues#853]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 Version 20H2

### Browser and version

Google Chrome: 96.0.4664.93 (Official Build) (64-bit) (cohort: Stable)

### Describe the bug/issue

Google Chrome thinks that chatbox is a username and Room ID is password.

### Reproducing

1. Turn on "Hide Room IDs"
2. Go out of settings and click on multiplayer.

3. i. If you have Google's auto-fill on your password will fill in the "enter room id or url and hit enter" box.
3. ii. If you do not have Google's auto-fill on and start typing in the "enter room id or url and hit enter" box it will give you a save password prompt.

### Expected behavior

(With auto-fill on.) Google will auto-fill password in "enter room id or url and hit enter" box and will auto-fill email in the chatbox.

### Console logs

![image](https://user-images.githubusercontent.com/96155050/146105280-e0a7f5ab-9245-4fbf-87a0-cbb2f7e29aa1.png)

**Comment by monzawu** [comment]
![Image](https://github.com/user-attachments/assets/88c3df82-97d4-4009-9a9b-86b4ccf52cf3)
This issue happens to me for a long time. Looks like it's caused by the input box "type=password"

OS: Chrome OS
Chrome: 133.0.6943.184
