### ISSUE TITLE
Stuck on trying to load tetr.io

### ISSUE THREAD

**Issue by DC-19** [tetrio/issues#854]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Brave (a varient of Chrome) Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)

### Describe the bug/issue

The website gets stuck loading once it connects, then endlessly shows the loading animation in the bottom corner

### Reproducing

1) Search for tetr.io
2) Hangs on the loading animation

### Expected behavior

I expected it to load the login screen.

### Console logs

bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2 Bootstrapping for hardver 44356d4.0LlqdBANm.368NFiVjm
(index):3 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://tetr.io/:3:16
(anonymous) @ (index):3
tetr.io/:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://tetr.io/res/font/pfw.ttf
tetr.io/:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://tetr.io/res/font/hun2.ttf?v=9
(index):16 GET https://api.adinplay.com/libs/aiptag/pub/TTI/tetr.io/tag.min.js net::ERR_BLOCKED_BY_CLIENT
VM54:4063 webgl backend was already registered. Reusing existing backend factory.
t.registerBackend @ VM54:4063
64.../../device_util @ VM54:4067
o @ VM54:4067
eval @ VM54:4067
148../backends/backend @ VM54:4067
o @ VM54:4067
eval @ VM54:4067
330../version @ VM54:4067
o @ VM54:4067
eval @ VM54:4067
1../nsfw_classes @ VM54:4067
o @ VM54:4067
eval @ VM54:4067
3../index @ VM54:4067
o @ VM54:4067
r @ VM54:4067
eval @ VM54:4067
eval @ VM54:4067
eval @ VM54:4067
(anonymous) @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
Promise.then (async)
p.onload @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
load (async)
i @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
d @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
(anonymous) @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
(anonymous) @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
VM54:4063 cpu backend was already registered. Reusing existing backend factory.
t.registerBackend @ VM54:4063
53.../../engine @ VM54:4067
o @ VM54:4067
eval @ VM54:4067
148../backends/backend @ VM54:4067
o @ VM54:4067
eval @ VM54:4067
330../version @ VM54:4067
o @ VM54:4067
eval @ VM54:4067
1../nsfw_classes @ VM54:4067
o @ VM54:4067
eval @ VM54:4067
3../index @ VM54:4067
o @ VM54:4067
r @ VM54:4067
eval @ VM54:4067
eval @ VM54:4067
eval @ VM54:4067
(anonymous) @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
Promise.then (async)
p.onload @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
load (async)
i @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
d @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
(anonymous) @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
(anonymous) @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
VM54:4063 Platform browser has already been set. Overwriting the platform with [object Object].
t.setPlatform @ VM54:4063
229.../environment @ VM54:4067
o @ VM54:4067
eval @ VM54:4067
148../backends/backend @ VM54:4067
o @ VM54:4067
eval @ VM54:4067
330../version @ VM54:4067
o @ VM54:4067
eval @ VM54:4067
1../nsfw_classes @ VM54:4067
o @ VM54:4067
eval @ VM54:4067
3../index @ VM54:4067
o @ VM54:4067
r @ VM54:4067
eval @ VM54:4067
eval @ VM54:4067
eval @ VM54:4067
(anonymous) @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
Promise.then (async)
p.onload @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
load (async)
i @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
d @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
(anonymous) @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
(anonymous) @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
VM54:4069 TETR.IO
VM54:4069 Please be careful when pasting anything in the console. Attackers may be out to steal your login information.
bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2 Uncaught exception inside main!
(anonymous) @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
Promise.then (async)
p.onload @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
load (async)
i @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
d @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
(anonymous) @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
(anonymous) @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at eval (eval at <anonymous> (https://tetr.io/bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2:12843), <anonymous>:4069:15338)
    at eval (eval at <anonymous> (https://tetr.io/bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2:12843), <anonymous>:4069:15537)
    at eval (eval at <anonymous> (https://tetr.io/bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2:12843), <anonymous>:4069:17687)
    at eval (eval at <anonymous> (https://tetr.io/bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2:12843), <anonymous>:4069:670744)
    at eval (<anonymous>)
    at https://tetr.io/bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2:12843
(anonymous) @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
Promise.then (async)
p.onload @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
load (async)
i @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
d @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
(anonymous) @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
(anonymous) @ bootstrap.js?hv=44356d4.0LlqdBANm.368NFiVjm:2
tetr.io/:1 The resource https://cdn.xsolla.net/img/favicon.ico was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
tetr.io/:1 The resource https://secure.xsolla.com/favicon.ico was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
DevTools failed to load source map: Could not load content for https://tetr.io/tf.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by ZaptorZap** [comment]
The loading animations should have some more verbose output right above it, telling you what's taking so long to load: 
![image](https://user-images.githubusercontent.com/64891705/146298014-345f8c36-c634-4498-8d0b-e4604ebb4d31.png)
Regardless, it seems to me that console output displays two things
* You have a rather slow internet connection, leading to game assets timing out while loading.
* Brave itself is intentionally blocking some assets, thanks to some over-sensitive content blockers. 
I'd look into that second part, personally. I know Firefox's "Enhanced Tracking Blocking" should have the same problem, but for myself? Game loads fine.

If it still isn't working after these investigations, I'd just suggest [the official Desktop client](https://tetr.io/about/desktop/) as an alternative to Brave's native functions.
