### ISSUE TITLE
TETR.IO Desktop App Native Arm build for Apple Silicon / M1 Macs

### ISSUE THREAD

**Issue by mudd258** [tetrio/issues#855]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

The TETR.IO app is noticeably less responsive than using it in a web browser for Apple Silicon Mac users since there's no native arm build. Native Arm Mac for electron has been out since electron 11 so this should be quite simple to implement.

### Describe the solution you'd like

Native Arm build of TETR.IO app for Apple Silicon Macs.

### Describe alternatives you've considered

Using Firefox on my M1 Mac isn't as smooth as using the native app on my other Windows x86_64 device.

**Comment by ZaptorZap** [comment]
Oh, come to think of it, this is a duplicate issue of #789. Sorry.
