### ISSUE TITLE
ZEN MODE animation bug when opening another window (Mixes with next stage + music goes off)

### ISSUE THREAD

**Issue by ultra-244** [tetrio/issues#864]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 PRO 64bits

### Browser and version

Chrome 96.0.4664.110 64 bits

### Describe the bug/issue

I have found a bug on zen mode, if you pass a level and the animation begins and you press the windows key (to open another app) or open a window, the game shows the next level stage before the animation finishes, but the animation keeps going until it finishes and goes away, it also removes the background and music completly of the menu and zen mode until you join another mode. TESTED ON FULL SCREEN/HAPPENS ON FULL SCREEN
(Before opening a window and coming back)
Nothing happens
(After opening a window and coming back)
![Captura de pantalla 2021-11-02 173650](https://user-images.githubusercontent.com/96917715/147829719-774fff38-622e-4183-ad27-5fcdd21ac3cc.png)
. 
I got this bug a while a go, but i tested it today again

### Reproducing

1. Finish a stage
2. Minimize the tetr.io app and open another (Example: Google chrome)
3. Open back tetr.io
4. See the bug (Stage glitched inside animation)

### Expected behavior

The stage should not mix with the animation

### Screenshots

![Captura de pantalla 2021-11-02 173650](https://user-images.githubusercontent.com/96917715/147829921-4b77f5af-5cce-4782-abfe-115cc85e742f.png)
(Also on description)

### Console logs

![image](https://user-images.githubusercontent.com/96917715/147830225-15578d81-e2cf-4176-9e72-62c52dc9a273.png)
![image](https://user-images.githubusercontent.com/96917715/147830249-6bd21e43-6956-4f97-8464-efeac8cb45c8.png)

### Additional context

Its just a small bug

**Comment by ultra-244** [comment]
I can record it if needed

**Comment by SweetSea-ButImNotSweet** [comment]
@ZaptorZap just a note: my issue have some differents when comparing to this one
First thing that I had a quick test on Microsoft Edge and seem can't replicate the bug
Second: the background is not be blacken and the music still playing smoothly, only animation sucks
Third, different version, but seem haven't been fixed yet
![image](https://github.com/tetrio/issues/assets/106439598/151a6f61-1ebe-4c78-9a0a-6af92f384f9e)

**Comment by Dimentio** [comment]
As far as I understand, the animation just continue playing when you're focused on the tab again. It's just how it works, most modern browsers suspend execution of scripts when unfocused
