### ISSUE TITLE
Passthrough in Tetra league

### ISSUE THREAD

**Issue by UrushiY** [tetrio/issues#866]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome 95

### Describe the bug/issue

Passthrough on Tetra league and other game modes

### Expected behavior

Not have Passthrough

**Comment by deedeeen** [comment]
?
