### ISSUE TITLE
Save zen settings

### ISSUE THREAD

**Issue by blokkendos** [tetrio/issues#868]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

The settings in zen are not saved when I resume zen. This is especially annoying to new players who wish to play without leveling, as the leveling animations are long and interruptive.

### Describe the solution you'd like

Zen settings automatically saved with progress.

### Describe alternatives you've considered

Players experienced with the interface get in the habit of tweaking their settings every session.

**Comment by Dimentio** [comment]
I've added this at last and boy it feels great!
