### ISSUE TITLE
Amogus/Sus badge

### ISSUE THREAD

**Issue by FourCheesesticks** [tetrio/issues#870]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

There aren't that many badges to earn for the average player.

### Describe the solution you'd like

Adding an Amogus/Sus badge for creating the following pattern:
![image](https://user-images.githubusercontent.com/87853438/148662547-8985f1db-556d-4cdb-ad6a-90406b618c7d.png)

Suggestions for the badge:
![image](https://user-images.githubusercontent.com/87853438/148662614-28ad6cb3-b6b4-4007-b4ba-0530fd1ba31b.png)
 or 
![image](https://user-images.githubusercontent.com/87853438/148662727-47af6b80-5c19-4184-9b91-28fc5d527f5f.png)

### Describe alternatives you've considered

Add alternate badges which are earned in similar ways.

**Comment by ZudoB** [comment]
no
