### ISSUE TITLE
Showing APM/PPS in quickplay after death

### ISSUE THREAD

**Issue by blokkendos** [tetrio/issues#871]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Problem: Sometimes when I am having a good game I get spiked and top out before I can see how well I was doing. This is because the view switches to spectator immediately after topping out, so you are unable to see your apm/pps/# kos.

The lines sent/received stat only approximates apm because it doesn't take into account lines blocked.

### Describe the solution you'd like

A more complete post-game screen that shows your apm/pps

### Describe alternatives you've considered

When a player tops out, pause 2-3 seconds before switching to spectator so the player can consider their stats and their board

**Comment by rajun274** [comment]
+1 to this. I love being able to see my game stats (PPS and APM) after a 1:1 private room game and just looking at the replay. And I really wish I could see them after a QUICK PLAY game, after a ROOM LISTING game, or after a private CUSTOM game. 

Although I'm OK with OP's solution (display your stats on-screen post-game, as well as after you top out). more ideally for me is if I could just download the replay file of my own playing. Reason: I regularly watch my own replays to see where I messed up, or where I could've done better.

**Comment by rajun274** [comment]
+1. Many times after I top out (either in Quick Play, Custom Room, or after one Tetra League game in the entire match), I want to see how I performed (PPS and APM), but the information disappears so quickly that I cannot see it. Just having it displayed for 2 to 3 seconds after topping out would be a major improvement.
