### ISSUE TITLE
tetr.io isnt working without a vpn

### ISSUE THREAD

**Issue by nothinghere23** [tetrio/issues#874]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 Home

### Browser and version

chrome 97.0.4692.71

### Describe the bug/issue

when i open tetr.io the browser or the desktop version a screen of a spinning t-piece appears with text under it saying 
"checking you browser before accessing tetr.io this process is automatic. your browser will redirect to your requested content shortly"
but it never does and i get stuck on that screen forever 
except when i turn on a vpn it works and i can play but its very slow and laggy i dont know how to fix this help

### Reproducing

1. i type "tetr.io" in chrome 
2. i get that screen

### Expected behavior

getting to play tetr.io again?

### Screenshots

![Screenshot (938)](https://user-images.githubusercontent.com/97863675/149702937-212a723a-34be-4780-a876-cc7c71ef32f6.png)

### Console logs

![Screenshot (946)](https://user-images.githubusercontent.com/97863675/149703062-958f3064-c095-4a69-bee5-8ee7b8ce0260.png)

**Comment by NathanAdhitya** [comment]
that is CF's challenge to check whether you are a bot or not.
ERR_ABORTED seems to be from your side, you may be using chrome plugins that block you from passing cloudflare's challenges.

try the desktop version.

**Comment by ZaptorZap** [comment]
Yeah sorry, this isn't widespread enough of an issue. Cloudflare's "I'm Under Attack" mode should be a temporary measure, so even if that troubleshooting step doesn't work the game itself will absolutely work later once this system can be turned off from osk's side.
