### ISSUE TITLE
add 'Enable old(~ 6.0.7) graphic rendering system' settings 

### ISSUE THREAD

**Issue by Hamstep** [tetrio/issues#875]
### Checklist

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

![화면 캡처 2022-01-18 164405](https://user-images.githubusercontent.com/76607639/149977520-a10bfbcb-0c29-437c-b457-b7a73073b4e0.png)

TETR.IO has undergone a lot of changes in the graphics system since the 6.1.0 update. (TETR.IO는 6.1.0 업데이트 이후 그래픽 시스템이 크게 바뀌었습니다,)

However, I think the particle and letter halo effects that were changed at that time are more regressive. (하지만 저는 파티클과 글자 후광 효과가 퇴보했다고 생각합니다.)

### Describe the solution you'd like

I wish the "Enable old(~ 6.0.7) graphics rendering system" settings.
(저는 '이전 그래픽 렌더링 시스템 활성화' 설정이 추가되길 원합니다.)

### Describe alternatives you've considered

![Honeycam 2022-01-19 01-47-27](https://user-images.githubusercontent.com/76607639/149981365-276c7d46-ee0c-42ff-8039-c706f47d8ace.gif)

![비교샷1](https://user-images.githubusercontent.com/76607639/149987141-6132a55f-af46-43a0-a03d-828f58739e4d.png)

![비교샷2](https://user-images.githubusercontent.com/76607639/149987188-2a21b8b4-422f-4932-b3d9-de083d830a35.png)

![비교샷3](https://user-images.githubusercontent.com/76607639/149989491-90563b99-e338-4074-a0bb-7720a351738c.png)

![비교샷4](https://user-images.githubusercontent.com/76607639/149990093-5eb4eb9f-3b8e-40c1-97bc-b6cababf212b.png)

### Additional context

I think it would be great to have this feature. PLEASE MAN :)
(꼭 이 기능이 생기면 좋겠다고 생각합니다. 부탁드려요)

**Comment by deedeeen** [comment]
As far as I know, the old graphics will not return.

**Comment by ZaptorZap** [comment]
> As far as I know, the old graphics will not return.

Oh wow, it's almost like this report is a _feature request_, not a roadmap! Neat.

Anyway, I can think of many more reasons why this wouldn't be added. I'll copy in a few quotes, keep in mind these all come from osk himself:
> **Please stop asking for things to be made into toggles when you dislike them, give a reason why you dislike them, give alternatives**
Making things a toggle both misses the point of the original issue, is a copout for having to explain alternatives or why the original is flawed, and most importantly, makes it _harder_ to implement and even harder to maintain

> in a perfect world settings would be nearly empty, put it like that

...
> if you particularly care you can ask uniqmg to add boardskin skinning so you can change the boardskin png to not have it

Talking about **screenshot 1** here, UniQMG has indeed added boardskin skinning to his [TETR.IO PLUS](https://gitlab.com/UniQMG/tetrio-plus/-/wikis/home) project. Here's [the custom queue.png that reverts that specific change](https://cdn.discordapp.com/attachments/691024746065952820/893294992389455964/queue.png). It should be possible to semi-revert to **screenshot 2**'s stylization by replacing the moonbeam textures as well, but I hate to break it to you, the majority of the community thought the previous attack particle was far too disruptive and flashy. Nobody misses it, nor has recreated the texture.

As for the "dust" particles, I'll admit I quite liked those myself. Alas, the game designer doesn't quite agree:
> and some people[sic] miss the weird particles on the text like QUAD etc
> it had particles on ultra before but i threw them out because they looked dogshit
> yes theyre ugly as shit lol

I think there's another problem stopping this from becoming a reality though. It's not as simple as just forward-porting the game's rendering code from previous versions. As that [patchnote you showed](https://tetr.io/about/patchnotes/#chlog_6_1_0) said, the **entire** graphics system was reworked. As a result, the style we see nowadays only shares visual similarities to the "old(~ 6.0.7) graphic rendering system". The tradeoff? **Drastically improved performance across all graphics presets,** _especially_ on MINIMAL or LOW graphics (although then again, **screenshot 3 and 4** would be ULTRA-only anyhow)

**Comment by Hamstep** [comment]
Thanks for the reply. (답변 감사드립니다)
a bummer, but I'm happy to be able to customize it with all skins. (아쉽지만 스킨으로 어느정도 바꿀 수 있어 다행이라 생각합니다)
I will close this issue. (이제 이 이슈는 닫을게요)
