### ISSUE TITLE
Tetrio message notification sound is extremely loud and does not depend on the sfx slider nor the tab you're currently in

### ISSUE THREAD

**Issue by emeraldtip** [tetrio/issues#877]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Firefox 96.0.2

### Describe the bug/issue

The notification sound when someone sends you a message is extremely loud and does not depend on the sfx level. It also plays when you don't have the tetrio tab open

### Reproducing

1. go to tetrio
2. Turn off sound effects and select another tab
3. Get someone to send you a message
4. Get earraped

### Expected behavior

I already discolosed everything in the describe the bug/issue section

**Comment by ZudoB** [comment]
Turn off “play notification sounds at full volume”.

**Comment by emeraldtip** [comment]
oh bruh

**Comment by emeraldtip** [comment]
whyyyy tho

**Comment by emeraldtip** [comment]
game design ig
