### ISSUE TITLE
New Objective In Solo Custom Mode: Attack

### ISSUE THREAD

**Issue by MkTr** [tetrio/issues#878]
### Checklist

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Describe the feature you'd like

In solo custom games, alongside Timed, Lines, and None, add an objective to create a number of garbage lines to win. Alongside this, adding a counter which keeps track of your attack would be useful, as well as an option under the Key setting. 
I know it's not that different from the lines objective, but I'm assuming it's easy to code. If it isn't as easy as copying and pasting something then ignore this lol

### Is your feature request related to a problem? 

I know Zen mode allows you to see your attack as you play (via the versus display), but I'd like a place to practice my attack with a time limit and incrementing speed, instead of playing infinitely.

**Comment by ZaptorZap** [comment]
I like the concept of this being an **objective,** but this does seem far too similar to both #697 and indeed #283 to exist as its own issue. Sorry.
