### ISSUE TITLE
Desktop client performing poorly

### ISSUE THREAD

**Issue by TheWalkingTaco** [tetrio/issues#880]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop

### Describe the bug/issue

The game refuses to exceed 20fps on the desktop client. My GPU is competent enough to run it at any setting and I've made sure the game is running off the GPU. It's almost like it's capped at 20fps for no apparent reason, unlike some issues I've had in the past, it does not correct itself when it is unfocused. I have tried every setting possible and a lot of combinations, but it just doesn't seem to go past 20fps. In browser it breaks 160fps on the same settings.

### Reproducing

Not sure. Just installed TETR.IO desktop and it just runs poorly.

### Expected behavior

As advertised, the desktop client should be miles ahead of the browser. Instead I get unplayable framerates that are a fraction of my browser's frames.

### Screenshots

https://i.imgur.com/l7gLrGE.png
https://i.imgur.com/KbHJRQB.png

### Console logs

https://i.imgur.com/WphZx2x.png

**Comment by powerpointgamer** [comment]
Interestingly enough, I have a laptop with a gtx 1650 and I get performance problems similar to yours on it, but my school laptop somehow runs better.
