### ISSUE TITLE
Mortal kombat screams in ice eyes too quiet

### ISSUE THREAD

**Issue by subzero-chan** [tetrio/issues#884]
### Checklist

* [x]  I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.

* [x]  I am using the **newest version** of TETR.IO.

* [x]  I am using a **supported browser** or the Desktop Client.

* [x]  I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).

![I am certain this is a **bug**, not a feature request.](https://user-images.githubusercontent.com/97819201/151466862-2f5b5a1f-03c6-4261-86bc-aa36b0788efc.svg)

### OS and Version

Windows XP
### Browser and version

Desktop Client 8.0.0
### Describe the bug/issue

in tetra league, the song was ice eyes but i had trouble hearing the mortal kombat screams
### Reproducing

1. go to config -> volume & audio -> tweak music -> kamoking - ice eyes
2. play
3. listen for mortal kombat scream
4. be confused
### Expected behavior

sounds clearer after boosting the mids

https://user-images.githubusercontent.com/97819201/151470073-fbcbee1e-e5c8-46c9-b3ba-eb48498bca0b.mp4

**Comment by ZudoB** [comment]
this is going to live in my head rent free for the next few weeks

**Comment by flashwave** [comment]
i love this
