### ISSUE TITLE
Option to disable leveling animation in Zen

### ISSUE THREAD

**Issue by TheCatMan2000** [tetrio/issues#890]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

A way to disable the leveling animation in Zen. The animation can be straining on the eyes for some and the two flashes of white can be a barrier for those with photo-sensitivity problems wanting to play Zen mode.

### Describe alternatives you've considered

Thanks to suggestions in the TETR.IO Discord, I've been able to achieve something close to this by disabling leveling outright, but I feel this is not a complete solution. Just because the animation can cause problems for some, doesn't mean their leveling shouldn't be tracked in Zen.

**Comment by ZaptorZap** [comment]
This seems a bit *too* similar to #584 (especially the first reply outlining the level up animations), so I'll be marking this issue as a duplicate one. (lots of people agree with you over on this other issue, *removing* the animations as opposed to just making them faster)
