### ISSUE TITLE
Option for coloured ghost pieces

### ISSUE THREAD

**Issue by Quarg** [tetrio/issues#891]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I struggle to read my piece from the ghost / shadow, as I am used to distinguishing between L and J, and S and Z by colour. Which I cannot do when reading my current piece from the shadow / 

### Describe the solution you'd like

I would like an option for the the ghost / shadow to be coloured to match the tetriomino.

### Describe alternatives you've considered

Perhaps a ghost saturation slider could make sense?

### Additional context

![image](https://user-images.githubusercontent.com/6743892/154575905-388a7223-c414-4a57-b047-b229b6a60778.png)

**Comment by ZudoB** [comment]
You've missed the option, it's under CONFIG > GAMEPLAY:
![image](https://user-images.githubusercontent.com/4703499/154576408-a339eddf-7ada-4393-8775-4b2b0ab8b351.png)

**Comment by Quarg** [comment]
Ah, yep, so I have. Gotta say I love the amount of customisation options, even if it can make it easy to miss one!
