### ISSUE TITLE
Newest MacOS Chrome version can not play game.

### ISSUE THREAD

**Issue by huangshan-ios** [tetrio/issues#895]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Mac OS Big Sur v 11.6.2

### Browser and version

Chrome Version 98.0.4758.102 (Official Build) (x86_64)

### Describe the bug/issue

I can not go to the gameplay but other features seem fine. Whenever I go to the game, it will show a blank screen.

### Expected behavior

Can go to the gameplay screen.

### Screenshots

![Screen Shot 2022-02-24 at 16 58 19 (2)](https://user-images.githubusercontent.com/35356334/155502326-24390afa-4978-4642-ab6b-618cb801c631.png)

**Comment by huangshan-ios** [comment]
<img width="290" alt="Screen Shot 2022-03-12 at 21 45 39" src="https://user-images.githubusercontent.com/35356334/158022609-eb9005a8-178c-4cb8-a26f-8ec2a84a58f6.png">
This is the error, how about this issue?

**Comment by o5k** [comment]
can you give me the full logs? from start to finish

**Comment by huangshan-ios** [comment]
<img width="2048" alt="Screen Shot 2022-03-12 at 21 49 25" src="https://user-images.githubusercontent.com/35356334/158022711-176398d5-5752-409f-9e27-2b6061fca62c.png">
@o5k You mean this?

**Comment by o5k** [comment]
weird... can anyone else repro?

**Comment by iloverenge** [comment]
I have Version 98.0.4758.107 (Official Build) (64-bit), so a slightly different version and TETR.IO works fine for me. I am on Chrome OS though.

**Comment by huangshan-ios** [comment]
<img width="653" alt="Screen Shot 2022-03-13 at 06 43 56" src="https://user-images.githubusercontent.com/35356334/158038884-93471ede-cea7-4d7f-a711-680169ce420b.png">
@o5k I think this is the issue, do you want anything more?

**Comment by rajun274** [comment]
FYI, one coworker said that after they updated Chrome to the latest version, tetrio games started working again.

**Comment by Kernald** [comment]
For what it's worth, I just update Chrome on my machine (from 99 to 100.0.4896.75), it didn't help - I still have the same issue.

**Comment by craftxbox** [comment]
CNR on Chrome/101.0.4951.67 & Windows 10

**Comment by rajun274** [comment]
FYI, issue still occurs. Friend tried to play for the first time on Mac + Chrome, latest version of Chrome, blank screen. Then tried Firefox & it worked.

**Comment by cdvillard** [comment]
[tetr.io-1654790161008.log](https://github.com/tetrio/issues/files/8871956/tetr.io-1654790161008.log)

Here are logs from my latest attempt to play using Chrome v. 102.0.5005.61 (Official Build) (x86_64) on macOS Monterey v.12.3.1 (21E258).

**Comment by Que-tin** [comment]
This is a MacOS Problem. Related to all Chromium based Browsers, e.g. Edge, Brave & Chrome.

Having the same issue since a while, tried debugging it but there is no difference at the first sight. Needs to be debugged on MacOS.

**Comment by cdvillard** [comment]
Still having this issue with Chrome.

**Comment by xantho09** [comment]
Still having this issue with Chrome. 

OS: macOS Ventura 13.2.1
Chrome: Version 112.0.5615.49 (Official Build) (x86_64)

**Comment by tonytonyjan** [comment]
Still having the same issue with Chrome
OS: MacOS Ventura 13.3.1 (a) (22E772610a)
Chrome: Version 117.0.5938.88 (Official Build) (x86_64)
