### ISSUE TITLE
Enemy's board shake like crazy?

### ISSUE THREAD

**Issue by timelessnesses** [tetrio/issues#896]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

TETR.IO application

### Describe the bug/issue

https://www.youtube.com/watch?v=x9ui_PCprjM  
The right board shake like crazy. The opponent told me that they didn't edit any settings at all.

### Reproducing

I don't really know how to reproduce this.

### Expected behavior

Board shake normally

### Screenshots

https://www.youtube.com/watch?v=x9ui_PCprjM

### Console logs

I closed the game.  
Oof!

**Comment by ZaptorZap** [comment]
![image](https://user-images.githubusercontent.com/64891705/156131057-985ba87a-e9a6-4a4e-9088-f4200e6e27be.png)
Have you ensured these values are at a respectable level? Seems to me you may have bumped them up a notch without noticing it. Also, I'm seeing some really bad lag here. This might impact the board bounciness as well, so please [tend to that issue](https://tetr.io/about/performance/) as well.

**Comment by timelessnesses** [comment]
![image](https://user-images.githubusercontent.com/59832159/156131308-7232ffa3-8e57-4bf3-bc93-cf8b20cb7a5e.png)

**Comment by ZaptorZap** [comment]
Yeah....this isn't how clientside configuration works. Your settings are **your settings**, and changing them will reflect the changes in any subsequent replay of replays, as your friend seems to understand and is informing you in this screenshot. As previously stated, please check on the sensitivity of the "BOARD BOUNCINESS" setting.

**Comment by timelessnesses** [comment]
> Yeah....this isn't how clientside configuration works. Your settings are **your settings**, and changing them will reflect the changes in any subsequent replay of replays, as your friend seems to understand and is informing you in this screenshot. As previously stated, please check on the sensitivity of the "BOARD BOUNCINESS" setting.

![image](https://user-images.githubusercontent.com/59832159/156133676-8fd3dff6-11d8-4f67-90d7-0c832f639fb4.png)
  
here's settings

**Comment by ZaptorZap** [comment]
Very well then, it's almost certainly related to the immense lag I was witnessing in [your original YouTube POV](https://www.youtube.com/watch?v=x9ui_PCprjM). Have you gotten a chance to look through [the TETR.IO performance tips](https://tetr.io/about/performance/) yet? If these performance patches don't cut it, just **lower BOARD BOUNCINESS** to counteract the framerate issue.

**Comment by timelessnesses** [comment]
> Very well then, it's almost certainly related to the immense lag I was witnessing in [your original YouTube POV](https://www.youtube.com/watch?v=x9ui_PCprjM). Have you gotten a chance to look through [the TETR.IO performance tips](https://tetr.io/about/performance/) yet? If these performance patches don't cut it, just **lower BOARD BOUNCINESS** to counteract the framerate issue.

i do have gpu but it spit code 43 and it died 😢  
i will try low it down
