### ISSUE TITLE
Unable to open .ttrm replay file

### ISSUE THREAD

**Issue by USSRRED** [tetrio/issues#897]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Win 10

### Browser and version

Chrome 98.0.4758.102	

### Describe the bug/issue

All replay files are .ttrm and no file/media player can decode it. (Private multiplayer match) 

### Reproducing

- After a private match ends click "Save replay"
- A .ttrm file will be downloaded
- File will not open

### Expected behavior

An mp4 file would be downloaded and the replay would be easily accessible.

**Comment by ZaptorZap** [comment]
Here's a [quick how-to guide](https://github.com/ZaptorZap/tetriofaq/wiki/Troubleshooting#replays) on how to open .ttrm files:
![drag em in](https://user-images.githubusercontent.com/64891705/154011440-96a40b8c-e9e6-41ee-958d-87ee4af01a4c.gif)
![click the button](https://user-images.githubusercontent.com/64891705/154011502-f5d7fd12-13c0-4107-be51-0fa6f760f499.gif)

If you want rendered replays, just record them with external programs like OBS or the Windows Game Bar. Doing them in-game would be a **feature request** as opposed to a bug report.

**Comment by USSRRED** [comment]
As expected, I now look like an absolute dumbass.
