### ISSUE TITLE
 View Discord Connection On Tetra Channel

### ISSUE THREAD

**Issue by sourTaste000** [tetrio/issues#898]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I'm trying to make a discord bot that automatically assigns TETR.IO ranks to users in discord. The only problem is, you cannot access the user's discord from the Tetra Channel API, but only from the main game API, so the only solution is asking the user to screenshot and manually verify it. Is it possible to make the discord link public?

### Describe the solution you'd like

Make the user's connection public and visible(or private if the user wants to) on Tetra Channel.

### Describe alternatives you've considered

- Manually verifying
- Asking the user to confirm this is their account(assuming they are being honest)
- Accessing the main game API

### Additional context

I thought this is already suggested, but after searching the issues I cannot find it(maybe I didn't look closer), so I'll open this issue.

**Comment by ZaptorZap** [comment]
I don't blame you for missing it, but I just did the most vaguest [search for "discord"](https://github.com/tetrio/issues/issues?q=discord) and happened upon #554 and #24. I think it's somewhat implied that these would be available through the [TETRA CHANNEL API](https://tetr.io/about/api/) should they become available on userpages. Furthermore, the main game API wouldn't give you this information anyhow (Unless you were thinking about having users pass over _their TETR.IO credentials_ to your project in some automated process? That wouldn't be a very good practice.), and usage of it is **strictly forbidden** without a bot account.
