### ISSUE TITLE
Incorrect tooltip in Solo > Custom settings

### ISSUE THREAD

**Issue by ActuallySophia** [tetrio/issues#899]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop client

### Describe the bug/issue

The description for the board height setting in the Solo > Custom settings menu says "The width of the playing field."

A previous issue about this bug was closed without either a fix or a comment explaining why it was closed without being fixed.

### Reproducing

1. Go to Solo.
2. Go to Custom.
3. Hover over "Board Height."

### Expected behavior

The tooltip should say "The height of the playing field."

### Screenshots

![20220302_tetrio](https://user-images.githubusercontent.com/100809390/156464970-1fff8b56-068d-4cf4-a115-a9d515c76327.png)

**Comment by ZaptorZap** [comment]
Oh, this is actually a duplicate issue of (currently closed but soon to not be closed) issue #808.
