### ISSUE TITLE
Got negative score in the special event

### ISSUE THREAD

**Issue by Roy101061** [tetrio/issues#900]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

win 10

### Browser and version

chrome 98.0.4758.102

### Describe the bug/issue

I got a negative score on the special event, here's the screenshot.

![TETR IO 2022_3_4 下午 11_43_16](https://user-images.githubusercontent.com/86598941/156794342-8751f76e-d7af-43d6-9c30-f5264a74c2ca.png)
![TETR IO 2022_3_4 下午 11_43_24](https://user-images.githubusercontent.com/86598941/156794378-b478fece-2dc8-4426-b965-7f16c5875066.png)

It was 235k when line 65, but the score decreased when I get a quad (222k when line 69).

![TETR IO 2022_3_4 下午 11_46_02](https://user-images.githubusercontent.com/86598941/156794776-c6564f8d-424c-4c1d-85e0-32dc4db225f1.png)
![TETR IO 2022_3_4 下午 11_46_08](https://user-images.githubusercontent.com/86598941/156794835-1fe4f577-cb91-4fc9-8194-d06bcc70da7b.png)

And the score even became to negative when I got another quad (22k line105, -17k line 109).

### Expected behavior

It should add scores like normally not decrease or got a negative one.

### Console logs

I didn't get the logs because I restart it before I remembered to do that.

### Additional context

Replay here: (I can't send it so I changed the file type to .txt)
[replay.txt](https://github.com/tetrio/issues/files/8187078/replay.txt)

**Comment by ZudoB** [comment]
yep this is intentional behaviour, you can get a negative score if you rack up a lot of REGRETs

**Comment by Roy101061** [comment]
Ok, I just found out that it's not a bug, sorry for posting a issues ヘ（。□°）ヘ
