### ISSUE TITLE
harddrop handled before right rotation

### ISSUE THREAD

**Issue by chokomancarr** [tetrio/issues#905]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Firefox 98.0

### Describe the bug/issue

When playing on controller with slow handling (1.5F arr, 6.9F das, 5F are), pressing right rotation and harddrop close to each other sometimes drops the piece without rotating, and the rotation is applied to the next piece.
This does not happen to left rotation, where the rotation / harddrop always obeys the key press order.

### Reproducing

1. Enter a custom game with above settings
2. press rotate and then hard drop very quickly for multiple pieces
3. some pieces will not rotate before dropping

### Expected behavior

rotation / harddrop always obey the key press order

### Screenshots

![image](https://user-images.githubusercontent.com/6769909/158499331-d77c20cc-c0ac-427d-bc68-0d0ba23fe103.png)
![image](https://user-images.githubusercontent.com/6769909/158499337-5cdc3d66-26d0-44d3-bd14-4e370ed5b2c5.png)

**Comment by ZaptorZap** [comment]
A replay file would be nice to have, but this seems like an impossible "bug" to fix. Unless you're programmatically sending keypresses with a macro of some sort, as I have in the attached video, the margin for simple user error here is enormous, and that's even assuming you're on a USB keyboard without input delay. Evidently you're using a controller, which isn't very reassuring.

https://user-images.githubusercontent.com/64891705/158503762-a97c3529-c198-4207-ab4b-b2072d1bb5bd.mp4

![image](https://user-images.githubusercontent.com/64891705/158503952-0aceeac5-5b1c-48e8-83c9-ccacb366862a.png)
(an image of Firefox's rendered JSON view of the replay.ttr this custom game generated, showing consistent handling of frame perfect inputs)

As far as "rotation is applied to the next piece" goes, I'm decently sure you're simply *holding* the rotation key after the piece drops? If this is the case, you're activating what's known to the community at large as the ["initial rotation system"](https://tetris.wiki/IRS), or "IRS" for short. IRS is an intended mechanic, and you can cancel an IRS while in [ARE delays](https://tetris.wiki/ARE) by simply letting go of the rotation button. The five frame window you've given yourself doesn't make this very easy, but you can overdramatize the ARE limits to see what I'm talking about. Furthermore, from what I read and remembered, Puyo Puyo Tetris does **not** have these systems.

**Comment by chokomancarr** [comment]
Disclaimer: i am not a webdev major & am completely blind to tetrio internal workings, so i might be completely misguided here, but:

here are some of my observations from tinkering with the debug console
![image](https://user-images.githubusercontent.com/6769909/158520869-561ac89a-bfcf-4494-932b-67f4ab94b850.png)

afaik, gamepad input in javascript is processed using a polling system (as opposed to event listener system for keyboards), and therefore is subject to frame refresh / polling rates. This also means that the same problem likely does not happen to keyboard inputs.

i wrote some code to dump out the input logs when the game is running:
```
oldt = 0;
buf = new Array(19).fill(false);
function check1() {
	var p = navigator.getGamepads()[0];
	if (p.timestamp > oldt) {
		oldt = p.timestamp;
		var chg = false;
		for (var a = 0; a < 19; a++) {
			if (p.buttons[a].pressed) {
				if (!buf[a]) {
					buf[a] = true;
					switch (a) {
						case 11: console.log("harddrop"); break;
						case 12: console.log("rotate R"); break;
						case 15: console.log("rotate L"); break;
						default: console.log(a); break;
					}
					chg = true;
				}
			}
			else {
				buf[a] = false;
			}
		}
		if (chg) {
			console.log("--- end frame");
		}
	}
}
setInterval(check1, 50);
```
I observed the following when pressing left/right rotate followed by harddrop:

![Screenshot (270)](https://user-images.githubusercontent.com/6769909/158519373-65dd9c86-43c0-4519-a733-10a991186096.png)
![Screenshot (269)](https://user-images.githubusercontent.com/6769909/158519378-41544c10-a500-4307-94d7-ea83d65ac518.png)

(while both rotations happen at the same frame as the harddrop, the order of commands executed is different)

based on this, can we say that tetrio handles same-frame inputs in the order of `left rotate -> harddrop -> right rotate` in that order, and is an intended behavior?


on another note, holding the rotation key after a harddrop should not be affecting IRS iirc? because rotation inputs do not (unlike DAS) therefore only the *order* is of concern here.

**Comment by HDFlood** [comment]
> on another note, holding the rotation key after a harddrop should not be affecting IRS iirc? because rotation inputs do not (unlike DAS) therefore only the order is of concern here.

Actually, that's inaccurate. If you up the ARE/LCD to a more absurd number, like 30F, you'll notice that *tapping* an input during entry delay will trigger IHS/IRS. I tested that just now with 30F, but the same principle will work with 5F. The same will happen with holding an input *if it's after HD*.

**Comment by chokomancarr** [comment]
ah i should clarify, i meant *pressing down rotate before hardrop, but holding the rotate key during entry delay*
basically if the order of initially pressing down is correct, it shouldnt matter
