### ISSUE TITLE
IHS/IRS Toggle

### ISSUE THREAD

**Issue by HDFlood** [tetrio/issues#906]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Note: TL = Tuning Limit, NL = No Limit

I play with a few friends using TL settings now and then. Never once have they not been thrown off by the existence of IHS/IRS because the other stackers we play on don't use it; notably, the PPT series (and T99 when sniping people). Coming from WWC and its usage of both TL and NL settings, and how TE:C has settings for reacting to IHS/IRS inputs, I'm surprised that *none of the listed games, TETR.IO included, have a way to disable IHS/IRS outright* (though you're really doing yourself a disservice by turning it off in TE:C). The only use for it in TETR.IO's NL environment is to buffer the *very first input* as well, so while it's nice to have IHS/IRS in TETR.IO, it also feels rather counterproductive to have it on all the time for people that aren't used to having it.

This would be a rather unnoticeable change as the original IHS/IRS has rather little application outside of TL environments, which I doubt a good majority of the userbase would bat an eye to in that case.

### Describe the solution you'd like

- IHS/IRS Switch in the Handlings menu
- "Force IHS/IRS" Switch in custom lobbies
   - This is to stay consistent with the ability to force tunings

### Describe alternatives you've considered

Like TE:C, there could be a way for TETR.IO to handle IHS/IRS inputs, either by tapping or holding a key/input. I prefer having IHS/IRS so I don't want to remove it outright.

**Comment by ZaptorZap** [comment]
Oh, this is a real similar duplicate to #204 (could've found it by searching up "IRS toggle"). I can tell a bit more effort went into this post, but I'm still closing it in favor of the older one for a consistent procedure concerning duplicate issues. Sorry.
