### ISSUE TITLE
I got access denied?

### ISSUE THREAD

**Issue by timelessnesses** [tetrio/issues#907]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

TETR.IO application

### Describe the bug/issue

I am trying to play tetr.io BUT suddenly when I opening the game I get access denied in both tetr.io and browser?  
![](https://cdn.rukchadisa.live/r/TETR.IO_E6yFmAkmUy.png)  
The status page say it still online and in twitter it doesn't say anything.  
I can't really see anything in discord due to I get banned.  
Can you help me what happened?

### Reproducing

1. Run the game up

### Expected behavior

I can play game normally

### Screenshots

![](https://cdn.rukchadisa.live/r/TETR.IO_E6yFmAkmUy.png)  
![](https://cdn.rukchadisa.live/r/msedge_o7FYnRrLiE.png)

### Console logs

![image](https://user-images.githubusercontent.com/59832159/158706128-7e7f24b1-38ad-4312-bb34-d97d25af3786.png)

### Additional context

I swear I didn't do anything wrong

**Comment by ZudoB** [comment]
server maintenance, be patient
