### ISSUE TITLE
Custom background image issue

### ISSUE THREAD

**Issue by itzshadowvn** [tetrio/issues#909]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Google Chrome

### Describe the bug/issue

My Custom background image wont load when i enable it. When i enable it, its just turns to a black background and not my custom background.

### Expected behavior

I expected my background image would load when i enable and reset the page but after i enable and reset the page. The background dosent load, it just show a black background

### Screenshots

![image](https://user-images.githubusercontent.com/101913915/159104895-cb0d3ef3-52cf-4590-a3a1-ec008fa7b6c0.png)

**Comment by ZaptorZap** [comment]
Have you seen [this troubleshooting documentation](https://github.com/ZaptorZap/tetriofaq/wiki/Personalization#built-in-backgrounds) yet? It might fix the issue.
![image](https://user-images.githubusercontent.com/64891705/159105006-1e4a7614-b19c-4468-a967-fea1486e1cb4.png)
