### ISSUE TITLE
Multiple people silenced for unsent messages  

### ISSUE THREAD

**Issue by B0N3CRUSH3R** [tetrio/issues#914]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Google Chrome

### Describe the bug/issue

Me and several other players i know all got silenced for 5 days for sending rude comments, all these messages are the same, and sent at the same time which of none of us sent, typed or even logged into our accounts at this time, this would be one thing for one player like information getting out but others have this same issue

### Reproducing

1.login to tetr.io
2.slienced for 5 days

### Expected behavior

I expect to be unsilenced and to have the bug/ glitch/ hack fixed as soon as you could  

### Screenshots

![Tetris bug](https://user-images.githubusercontent.com/102632432/160722818-30bb2a3d-9042-4cc3-b7fd-63d378878929.png)
![Tetris bug2](https://user-images.githubusercontent.com/102632432/160723255-b3baa5ce-9a46-4eee-8046-d7c4e7d7d8d4.png)

### Console logs

![Tetris bug3](https://user-images.githubusercontent.com/102632432/160725250-857367f5-db8a-4c2b-ba9a-1529e8ac9e30.png)

**Comment by ZaptorZap** [comment]
I'm redacting every screenshot you posted, but contained within, might I point out something:
![image](https://user-images.githubusercontent.com/64891705/160725436-da3917fa-b1fe-42f3-9927-831805969a88.png)
Now I'll agree, this is a good showcase of a limitation with our quoted text, but this isn't the place to appeal. This issue solves itself with proper usage of the moderation tools, so we'll ensure this does not occur again. Ban appeals are **not** allowed in this forum, so please visit [this link instead](http://tetr.io/about/support).
