### ISSUE TITLE
why are my tetrio matrix so small

### ISSUE THREAD

**Issue by mynamedonder** [tetrio/issues#915]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 8.1 x64

### Browser and version

FIrefox Nightly 100.0a1 (2022-03-29) (32-bit

### Describe the bug/issue

when i start a game (sprint 40l) , the matrix zoom out to small
i can't play can't see anything
i think that's a bug of firefox nightly then i use chrome and have same problem
i checked zoom in - zoom out option but they're 100% normal

### Reproducing

1.Sign in
2. play 40lines
3. the bug happen

### Screenshots

![ảnh](https://user-images.githubusercontent.com/70124069/160747879-ee0d55b0-127d-4d2e-8a90-4fdccbe9b479.png)

**Comment by ZaptorZap** [comment]
Do you have footage of the board shrinking mid-game? Or is the board always shrunk? Have you tried **increasing** the aforementioned board zoom? If you have, and the setting didn't take effect immediately, please **reload** the game or **resize** the window to make those settings take effect.

**Comment by mynamedonder** [comment]
thx, the bug is fixed
