### ISSUE TITLE
iframe support

### ISSUE THREAD

**Issue by 112cxyz** [tetrio/issues#916]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

iframes are not able to be used

### Describe the solution you'd like

im making a browser project using iframes and many people will be able to tetr.io i know is not the best way to do it but it would benefit from it.

### Describe alternatives you've considered

a clonable github "desktop" for chromebooks. that uses html and is a local client

**Comment by ZudoB** [comment]
Not happening. Allowing your web application to be framed is [generally a terrible idea from a security perspective](https://owasp.org/www-community/attacks/Clickjacking), and it’d inevitably lead to dodgy ad-infested sites embedding TETR.IO for their own gain.
