### ISSUE TITLE
Playerhead stays controllable if you never release LMB

### ISSUE THREAD

**Issue by Kecxyz** [tetrio/issues#917]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop Client v8

### Describe the bug/issue

When `Jump to next round after end` is enabled in replay viewer, you can drag the playerhead around even when the replay is counting down.

### Reproducing

1. Open a multiplayer replay that have more than 1 round.
2. Enter a round.
3. Turn on `Jump to next round after end`.
4. Drag the playerhead to the end of timeline.
5. Continue holding the playerhead, now you can drag it around even in the countdown.

### Expected behavior

You will not be able to scroll through the timeline during countdown

### Screenshots

https://user-images.githubusercontent.com/41269576/161392340-919f17cc-53b5-4da7-93ab-c8829d84fb5b.mp4

### Console logs

![image](https://user-images.githubusercontent.com/41269576/161392258-6c5ca183-7255-49ce-bdfc-c45a87b016ae.png)

**Comment by o5k** [comment]
Fixed in next patch.
