### ISSUE TITLE
After a "netsplit" occurring, system room #X-QP fails to regenerate

### ISSUE THREAD

**Issue by ZaptorZap** [tetrio/issues#919]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Linux zaptor 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux

### Browser and version

Firefox 98.0.2 (64-bit)

### Describe the bug/issue

Following an unlucky netsplit of digital worker `rewrite-kotarou`, one that occurred about **seventy** minutes ago, this netsplit expectedly and unavoidably disconnected all players connected to the worker **and took the system room `#X-QP` alongside it as collateral**, leaving QUICK PLAY inoperable. [This Twitch clip shows the issue occur live, at approximately Mon 04 Apr 2022 08:40 PM PDT](https://clips.twitch.tv/BigHungryPeafowlPJSugar-y_ZsRI6Twtu3KOZK). During this clip, largely uneffected streamer [jermy145](https://www.twitch.tv/jermy145) passes by the disabled QUICK PLAY button, showing 0 users inside as no such room exists. As of right now, attempting to join QUICK PLAY from the main menu will incur a "NO SUCH ROOM" error(pictured in section "Screenshots"), as QUICK PLAY has failed to regenerate, as per, **what I would assume to be**, standard procedure.

### Expected behavior

As per a procedure following all netsplits, particularly ones effecting workers hosting QUICK PLAY, QUICK PLAY should be checked for existence, and I or other players should be allowed into such a room.

### Screenshots

![image](https://user-images.githubusercontent.com/64891705/161679985-aa462d97-76c8-417c-b741-6137404526ef.png)

### Additional context

I may have slightly "cheated" with insider information for the exact details, but I believe the worker hosting QUICK PLAY and the time the netsplit occurred should have been public information none-the-less, as the client reports to you which worker you are connecting to upon connecting to a room, and the server reports to _all connected clients_ when a netsplit occurs.

**Comment by ZaptorZap** [comment]
Oh, I forgot to mention: custom rooms and the TETRA LEAGUE are operating normally, and we're seeing some comendable efforts for a QUICK PLAY alternative in public listings through automation with [ingame bots](https://ch.tetr.io/u/autohost) such as [AUTOHOST](https://gitlab.com/Zudo/autohost/-/wikis/home). Of course, this is undesirable, as QUICK PLAY is meant to be neutral ground, whereas custom lobbies give considerable power to lobby hosts.
![image](https://user-images.githubusercontent.com/64891705/161682005-08585e8c-7dd3-4715-99ca-e9f5ae4caac6.png)

**Comment by ZaptorZap** [comment]
It's happened again, just now, from a split on `rewrite-akane`. I don't hold high hopes for automatic regeneration, so we're counting on @o5k to see this.

**Comment by ZaptorZap** [comment]
Pretty much identically to [my previous update](https://github.com/tetrio/issues/issues/919#issuecomment-1088932963), after waking up and checking, QUICK PLAY definitely exists again for now.

**Comment by o5k** [comment]
Fixed in next patch.
