### ISSUE TITLE
Minos losing control and the game just killed you even when you got the chance to downstack / counter-attack

### ISSUE THREAD

**Issue by Cherry-Smith-VT** [tetrio/issues#922]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Tetrio desktop.

### Describe the bug/issue

1. When playing against player with more than 2pps, (no matter what is the apm), I lost control of the tetrominos. Cannot play properly and always misdrop even when I play at 1.5 pps.

2. The tetrominos just simply placed themselves although I have chance to do clutch recovery / downstack.

### Reproducing

1. Play tetrio multiplayer as usual, Quick Play, Tetra League, Open / Closed room.
2. (Part 1) The DAS become messed up, movement from left to right is not following my handling settings.
2. (Part 2) When I upstack to do counter-attack, the minos just placed down (hard drop) even without I press any key and simply losing me the game.

### Expected behavior

The pieces should move based on my handling settings. Not some kind of messed up movement.

**Comment by ZaptorZap** [comment]
Are you **unequivocally, absolutely sure your hardware isn't causing the issue**? There's no easy way to say this, but the game isn't sentient, nor is it actively sabotaging gameplay above 2pps. The evidence is in the [various](https://ch.tetr.io/s/blitz_global) [TETRA LEAGUE](https://ch.tetr.io/players/) [leaderboards](https://ch.tetr.io/s/40l_global) which has many runs [verifiably](https://twitter.com/mgcasi/status/1446502968308629505) [ran](https://www.youtube.com/watch?v=-JJ1HMev7wg) [by](https://www.youtube.com/watch?v=lbyzUt7U_EA) [humans](https://www.youtube.com/watch?v=MJDz4-pr9J4) at far higher speeds. Might also be worth looking into issue #680 as the phrase "movement from left to right is not following my handling settings." reminds me of this issue quite a bit.

If you're still superstitious after seeing this assorted collage of footage, please **send an example** of the issue in action, extremely preferably in a `.ttr(m)` format such that both you and I can look at the direct inputs and frame timings as the game perceives them. These files are rather clear "**J**ava**S**cript **O**bject **N**otation" files to read if you have any method for formatting(for example, I use Firefox standalone), even without prior development experience.

**Comment by Cherry-Smith-VT** [comment]
Yes. Because my friends with better hardware and better internet got the
same issues.

**Comment by ZaptorZap** [comment]
And as for live examples? They can even be partial sprints, I'm not picky. Personally, I've had the same ~$60 Cooler Master keyboard/mouse combo since **Christmas 2020** and I can't say I've experienced this catastrophic failure of handling. Not long ago, not recently, nor really ever. (I'm currently clocking in at about 3 **P**ieces **P**er **S**econd on [my 40 LINES personal best](https://tetr.io/#r:616dd2a3d58d451ba51e882f))

**Comment by Cherry-Smith-VT** [comment]
As far as I concern the problem only happened when we were playing in open
lobby/tetra league with opponent with higher than 2 pss.

**Comment by ZaptorZap** [comment]
[Well](https://tetr.io/#R:NiJGXfDRTX), [I](https://tetr.io/#R:ZmQhruCFw) [certainly](https://tetr.io/#R:PwRr2fNEE) [have](https://tetr.io/#R:PhqowCHf7) [some](https://tetr.io/#R:OLGU0Fk-Q) [live](https://tetr.io/#R:WULuHOBqTK) [examples](https://tetr.io/#R:vHqrvSz3nX) [of](https://tetr.io/#R:wPVAIbH_5) [>2PPS](https://tetr.io/#R:PpOvatr9T) [gameplay](https://tetr.io/#R:A2siKMrvh) [in](https://tetr.io/#R:dVmqjS_jW) [TETRA](https://tetr.io/#R:yac0Mvtan) [LEAGUE](https://tetr.io/#R:-EUNf6852) [environments](https://tetr.io/#R:gDCtfBQ9U) [without](https://tetr.io/#R:9qda5XAFP) [much](https://tetr.io/#R:AyDc10BoD) [hassle](https://tetr.io/#R:8EVBBd1Rg) [for](https://tetr.io/#R:74AzH8fha) [the](https://tetr.io/#R:t8c-l97Oh) [professionals](https://tetr.io/#R:Mwz7Ak9U5) [involved](https://tetr.io/#R:XG-a00vMU). [No](https://tetr.io/#R:uzVXEAYNd), [I](https://tetr.io/#R:EtlinYdGS) [don't](https://tetr.io/#R:_PwXvQPbR) [believe](https://tetr.io/#R:OxOXy8kzH) [they're](https://tetr.io/#R:f1m6qHe5l) "used to this happening" |separator for following YouTube footage of the MOBA-like "Super Lobby" events consisting of over 500 players in some cases| [or](https://www.youtube.com/watch?v=ud8kcePIMDg) [correct](https://www.youtube.com/watch?v=aE1iKlQPXUM) [for](https://www.youtube.com/watch?v=xyxF-KLTROs) [it](https://www.youtube.com/watch?v=nshFIyMWsWQ).
