### ISSUE TITLE
Controller recognized twice but no input

### ISSUE THREAD

**Issue by shaggnanigans** [tetrio/issues#923]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 10 build 19044.1586

### Browser and version

Chrome Version  100.0.4896.75

### Describe the bug/issue

Tetrio browser recognizes my controller but does not respond to any inputs intermittently. Some times refreshing the browser fixes it and some times it does not. I also found that restarting razer synapses some times fixes it. I found out this only happens when my Razer Tartarus V2 is plugged in also have a razer black widow and death adder but neither of them seem to cause the issue. It shows "a controller was connected" twice  as soon as my xbox controller connects.

I have tried different controllers with the same results and it seems directly related to the Tartarus V2. If I unplug the Tartarus V2 and refresh the browser it works fine, if I plug the Tartarus V2 back in it causes the controller inputs to stop.

I understand it I am too small of a fringe problem to bother with, I would like to leave my Tartarus V2 plugged in. Seems if Tetrio didn't think it was a controller that would probably fix the issue, but maybe it is more complicated then I know. At the very least I hope I can help you help others that might have a the same or similar problem.

Thanks
Shaggnanigans

P.S. Love the game, it is simply amazing, even if I do blame it when I make mistakes ;)

### Reproducing

1. Sign into Tetrio
2. turn on controller and press a button (usually elite series 2)
3. "A controller was connected"  "A controller was connected"
4. no response from controller
5. unplug key pad (Razer Tartarus V2)
6. "A controller was disconnected"
7. Controller still not recognized
8.  refresh browser, sign in and hit a button on controller and it works normally
9. plug Tartarus V2 back in and "A Controller was connected" and no longer recognizes xbox controller input 

### Expected behavior

I would like Tetrio to treat my Razer key pad another keyboard input rather than treating it as a controller

### Screenshots

![Connected twice](https://user-images.githubusercontent.com/65840038/162371081-8f5c3860-ad72-4571-90b3-a6a1a1f14a20.png)

### Console logs

![connected twice console logs](https://user-images.githubusercontent.com/65840038/162371347-33d423a4-ee70-4c57-b69c-ca287a71921c.png)

**Comment by godotgamedeveloper** [comment]
I am responding to the addition of the stale label.  I confirm I am having the same issue as OP described.

**Comment by xXbaodeptraiXx** [comment]
You have to go into the config page and change the input method to the correct device to use the gamepad.

**Comment by shaggnanigans** [comment]
I had no issues for a long time but now it has started again except I no longer have the Tartarus V2. No matter what controller I plug in Tetr.io does not recognize the inputs. I have verified that the controller works with anything else no problems.
