### ISSUE TITLE
2FA autofill

### ISSUE THREAD

**Issue by szymon221** [tetrio/issues#926]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome 100

### Describe the bug/issue

2FA brings up autofill prompt

### Reproducing

1. Go to login page
2. Get To 2FA prompt
3. See previously entered code

### Expected behavior

No 2FA should appear

### Screenshots

![image](https://user-images.githubusercontent.com/39997113/163067146-55dd09ae-ad10-473f-8165-a7cbabb4b78b.png)

**Comment by o5k** [comment]
Fixed in next patch.
