### ISSUE TITLE
pfp background bug

### ISSUE THREAD

**Issue by Sapph8008** [tetrio/issues#927]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 10

### Browser and version

chrome 94

### Describe the bug/issue

changing the profile picture to a specific colour like #ff0066 will cause the background of the game mode select  screen to be the same colour as the profile picture.

### Expected behavior

when i change the pfp to a specific solid colour it will cause the bug.

### Additional context

wish i could f12 but im on a Chromebook. :(

**Comment by deedeeen** [comment]
whoops, you self-closed that issue.
