### ISSUE TITLE
Sudden and Repeated Disconnection from the Game

### ISSUE THREAD

**Issue by minou-meows** [tetrio/issues#931]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Firefox 99.0.1

### Describe the bug/issue

In the space of about ten minutes, I disconnected from the same lobby (called "Something Happened! A+ and Below) twice, with no clear reason given, and each time the page had to reload back to the log-in part.

### Reproducing

1. Go to the lobby I just mentioned via "Multiplayer -> Room Listing"
2. Scroll down a bit and you will find it
3. Play in the lobby for a few minutes and you will suddenly disconnect

### Expected behavior

I didn't expect to disconnect like this at all, especially because there appears to be nothing wrong with my internet.

### Screenshots

I don't have screenshots but I copy-and-pasted this "Socket ID" : SOCKET ID: 412a66f717148f47

### Console logs

![paste this into github](https://user-images.githubusercontent.com/104144234/164458057-6ea7522d-e09b-406e-a9d4-e412d94a63d9.png)

### Additional context

I have never had this issue before in my several months of playing this game, so it is really quite strange

**Comment by o5k** [comment]
Network issues are outside the scope of this repo
