### ISSUE TITLE
Tetra Channel: Unable to access the leaderboard of countries within the UK from player profile.

### ISSUE THREAD

**Issue by Kecxyz** [tetrio/issues#932]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 v21H1

### Browser and version

Chrome v100.0.4896.127

### Describe the bug/issue

The leaderboard of all countries within the UK (England, Scotland, Wales and Northern Ireland) are all inaccessible from the player country ranking button. And instead redirect you to the global leaderboard.

Direct link to these leaderboard also didn't work and just redirect you to the global leaderboard. Test for it yourself using the link below
Wales: [https://ch.tetr.io/players/#GB-WLS](https://ch.tetr.io/players/#GB-WLS)
England: [https://ch.tetr.io/players/#GB-ENG](https://ch.tetr.io/players/#GB-ENG)
Scotland: [https://ch.tetr.io/players/#GB-SCT](https://ch.tetr.io/players/#GB-SCT)
Northern Ireland: [https://ch.tetr.io/players/#GB-NIR](https://ch.tetr.io/players/#GB-NIR)

### Reproducing

1. Open the Tetra Channel and find a ranked player from one of the country above (The country dropdown selector works so use those)
2. After you found a player in that country click on their profile.
3. Scroll to Tetra League part and click on their country ranking.
4. You will return to the global leaderboard.

### Expected behavior

After you click on country ranking or use the direct link, you should see the country leaderboard and not the global leaderboard.

### Additional context

The Tetra Channel API did return the correct leaderboard.
![image](https://user-images.githubusercontent.com/41269576/164625789-735705cb-15ef-47b2-abd7-de59fc369b38.png)

**Comment by o5k** [comment]
Fixed in next patch.
