### ISSUE TITLE
server problem

### ISSUE THREAD

**Issue by namnamjeopjeop** [tetrio/issues#933]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 10

### Browser and version

tetrio exclusive browser (chorme 100.0.4896.127 64bit Latest version)

### Describe the bug/issue

The server keeps having problems, so I quit the game regardless of my will.

I've already suffered a lot from this.

### Reproducing

1. Turn on the game

2. play a game

3. Play a game.

4. The game suddenly turns off.

### Expected behavior

I don't know why this is happening. This doesn't happen when I do something else on the Internet.

### Screenshots

![1234123412342423535235235](https://user-images.githubusercontent.com/104265908/164912004-b931c9a9-f62d-426f-bdfb-5285d01befb8.PNG)

### Console logs

![111111111](https://user-images.githubusercontent.com/104265908/164911973-1d3ba6a9-7146-4fa7-8469-77d161fcf9e6.PNG)
![123412341234](https://user-images.githubusercontent.com/104265908/164911974-ac6f53fd-46ed-46c4-9197-07d34abc342f.PNG)

### Additional context

This issue has been ongoing for more than 6 months

**Comment by o5k** [comment]
Network issues are outside the scope of this repo
