### ISSUE TITLE
Links to YouTube videos or MP4 files to play in the background, along with custom songs

### ISSUE THREAD

**Issue by cod3breaker12** [tetrio/issues#934]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Not at all. I thought this would be pretty useful, but it **doesn't interact with gameplay whatsoever**.

### Describe the solution you'd like

Instead of using just links to PNGs or JPEGs or other image formats, what if we could **use links to YouTube videos or MP4s or other video formats to play in the background**? What about an option to disable audio for those videos? What about custom songs, where we could import or use links for MP3s or audio files, and if a video with audio starts playing, the music pauses?

### Describe alternatives you've considered

We _COULD_ just play YouTube videos or audios or Spotify or whatever in the background, but the videos for backgrounds sounded pretty cool. **I have a feeling using a link to an MP4 or GIF might work**, but _custom songs still sound like a pretty valid option_.

### Additional context

I could try the MP4 or GIF link option later today, so if you already have that down, listen to the other suggestion that I have.

**Comment by o5k** [comment]
very far out of scope of tetrio
