### ISSUE TITLE
Binding hard drop to alt causing issues

### ISSUE THREAD

**Issue by quanpunchhhhh** [tetrio/issues#935]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Tetr.io desktop client

### Describe the bug/issue

I have my hard drop bound to alt since my spacebar is unreliable. I found that using alt + tab during the countdown will automatically hard drop the piece and cancel the next hard drop input.

https://user-images.githubusercontent.com/49852204/165428702-0afe65bd-36d3-4e7e-a1e1-d187029913cc.mp4

### Reproducing

1- Bind hard drop to left alt
2- Enter game
3- alt + tab out then back into the game during the countdown

### Expected behavior

Alt tabbing while during the countdown shouldn't affect the game even though it happens before the countdown ends.

**Comment by ZaptorZap** [comment]
I'm very sure this is extremely related to, if not a **duplicate** of, #680, in which if the game loses focus for any reason, any buttons held will not receive a "keyup" event, causing the held key to get "stuck". In this case, the issue generates in the form of an _initial hard drop_, normally possible by holding your hard drop key during the countdown. In fact, I bound "SOFT DROP" to my own ALT key and experienced the very same scenario recorded in #680 while following your instructions. This is just a new, innovative way to lose focus while holding one of your bound buttons.
