### ISSUE TITLE
Enlarged opponent board

### ISSUE THREAD

**Issue by DuePatronousREAL** [tetrio/issues#936]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Chrome

### Browser and version

Chrome

### Describe the bug/issue

I was going into a game of tetra league, and when I got in, my opponent's board was large. I have it to where it isn't side by side on 1v1s, but the board was large, and was on the top right corner

### Reproducing

1 - Start a game of league (With side by side duels turned off)
2 - look at that player's stats (I don't know if this affects the game, but it's what I did)
3 - go to another tab until the game starts
4 - the opponent's board it too large

### Expected behavior

Nothing of what I saw, I was hoping for a normal first round (since it fixed itself after the first round), but what I got was a weird looking game

### Screenshots

I recorded the game after a bit of playing and ![Screenshot 2022-04-29 9 10 00 AM](https://user-images.githubusercontent.com/95217924/165961620-a566b69c-0b35-4836-a0d7-b04e6cacaa88.png) that

**Comment by DuePatronous** [comment]
I'm back on my main after a while of not remembering the password and not being able to reset it, this is still me though
