### ISSUE TITLE
MAKE IT OPENSOURCE!!!

### ISSUE THREAD

**Issue by WesleyBryie** [tetrio/issues#937]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [ ] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

It is not a problem, but I think that if the code for tetrio was opensource then it would be better.

### Describe the solution you'd like

You already have a github organisation so why not go ahead and upload the code?

### Describe alternatives you've considered

No alternatives except not uploading code.

**Comment by o5k** [comment]
maintaining an open source piece of software is just another boatload of work, and it'd be super fun for cheaters to look through

just not worth it, in literally every way, sorry

**Comment by Wilker-a** [comment]
i'm willing to localize it to Portuguese if it's available on Weblate, but using the service free of charge requires it to have a free/libre software license

###### ..i don't think having the game be proprietary will do anything against cheating imo.
