### ISSUE TITLE
Make Zen settings more discoverable

### ISSUE THREAD

**Issue by Ads20000** [tetrio/issues#938]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Currently, players have to discover, by accident or by hearing from other players, the Zen settings, they are not intuitive to discover. This means that many people don't see the ways they can play around in Zen for a very long time.

### Describe the solution you'd like

There should be a cog constantly displaying in the top-right or bottom-left of the Zen screen, which one can click on or hover over (or move the cursor to the right edge as usual) to reveal the settings panel, a cog icon is widely associated with 'settings' and should make the settings panel a lot more discoverable. Perhaps there could then be a setting at the bottom of the settings panel which lets the user disable the icon so that it doesn't intrude on the screen, as at current, and only opens at the right edge. The discoverability setting should make it clear that, if the cog icon is disabled, one has to move the cursor to the right edge to bring up the settings panel, so that people don't remove the cog and then can't find the settings panel.

### Describe alternatives you've considered

Another option would be to have a 'how to open the settings menu' animation happen when a user first loads Zen mode, so that settings can be discoverable that way.

**Comment by o5k** [comment]
Added in next version.
