### ISSUE TITLE
Silence message should fade out and not stay on screen while playing

### ISSUE THREAD

**Issue by Founntain** [tetrio/issues#939]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Desktop Client

### Describe the bug/issue

When you get silenced the notification that pops up to tell you that you got silenced, shouldn't stay (and block your screen) and should fade out or re-appear after the TL game ended.

The notification shouldn't even pop-up because in Tetra Leagues your status is Busy. (Because you also get a chat message you should notice it anyway)

### Reproducing

1. Get into a TL match (or any other game)
2. While in game, get silenced

### Expected behavior

Silence notification shouldn't be displayed during TL matches, because you are busy status automaticly when playing a League match.

**Comment by ZudoB** [comment]
Click the silence message to dismiss it. Also consider not getting silenced.

**Comment by Founntain** [comment]
Yes not getting silenced is a tip. But I simply can't click it when I'm in the middle of the game, blocking my screen a bit.
Thanks anyways. Was just a suggestion

**Comment by ZudoB** [comment]
Moderation actions are by far the most important notification you could possibly receive, as they may well apply to a user's current problematic behaviour. As such, they take precedence over Busy mode, and need to be explicitly acknowledged before disappearing.

**Comment by o5k** [comment]
This. In fact, I may make them require _more_ action to acknowledge in the future. Simple as "don't get silenced".

(...also, remember back when getting silenced would kick you?)

**Comment by Founntain** [comment]
> This. In fact, I may make them require _more_ action to acknowledge in the future. Simple as "don't get silenced".

I can absolutly understand that it should take even more actions to acknowledge. I really like how you guys handle bad behaviour, it's important and needed, because I guess there are a lot of people that won't learn it.

> (...also, remember back when getting silenced would kick you?)

No I don't know that because I never got silenced in my 2 years on tetr.io :)

> Simple as "don't get silenced".

Yep, lesson learned the hard way, I'll stick to not use the chat at all in TL like used to. (unless for a gg or hf)
Thank you Zudo & osk for elaborating.
