### ISSUE TITLE
Banned?

### ISSUE THREAD

**Issue by GreenMatcha1122** [tetrio/issues#942]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 

### Browser and version

Chorome

### Describe the bug/issue

on my account I logged in on with my school account and it said my account was perma-banned for A-LINED [AL8367] - continuous alting. I sent an email to tetr.io support. And then I tested logging in on my home account and there was no ban.  i still do not know if i was banned or not. This was on the web version of tetr.io BTW.

(my apologies to tetr.io for sending an email when I fix the issue)

### Reproducing

go to tetr.io
A ban may appear or not

### Expected behavior

go to tetr.io
A ban won't appear(unless you are cheating or not following rules)

### Screenshots

I forgot to take screen shots and I cannot get the same thing to happen again

### Console logs

I am not good at cumputing and don't know what this is 

### Additional context

n/a

I was on school interent

**Comment by ZaptorZap** [comment]
> Joined 38 minutes ago
> https://ch.tetr.io/u/greenmatcha1122 doesn't exist
> ban appeal (even an IP one, after sending an email)

Yeah this isn't a valid issue report. You hit an **IP ban**—one that doesn't exist on your home network. IPs can be selectively restricted separate from accounts. Please feel free to read more about IP addresses **[here](https://en.wikipedia.org/wiki/IP_address)**.
