### ISSUE TITLE
Profile status always Online (In Menus) on TETR.IO when not on the game

### ISSUE THREAD

**Issue by Artixuwu** [tetrio/issues#944]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Desktop Version

### Describe the bug/issue

My friends recently reported that my status would always say that I'm online and in the menu when I'm not even in the game or on my computer. Very small issue but I don't know how to fix it. I've tried logging out of all devices and logging back in, reinstalling etc but nothing worked.

### Expected behavior

My status should go to offline when I'm quitting the game and going offline, not staying online.

**Comment by o5k** [comment]
Fixed in next patch.
