### ISSUE TITLE
tetrio:// protocol room links behave unexpectedly if the user is currently on the login screen

### ISSUE THREAD

**Issue by ZudoB** [tetrio/issues#947]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

TETR.IO Desktop v8

### Describe the bug/issue

Joining a room using a `tetrio://` room link, while TETR.IO Desktop is displaying the "welcome back" login screen, causes unexpected behaviour.

When the link is clicked or otherwise executed, the client will join the linked room, while remaining on the login screen. The user can then continue to join and play the game as if they started the client normally, but a connection will remain open in the background, leading to unexpected behaviour (such as room joins being rejected, since the user is "already in that room"). 

### Reproducing

1. Change "skip login screen" to "never" in the TETR.IO Desktop config menu.
2. Reload TETR.IO Desktop, so you see the "welcome back" login screen.
3. Click on, or otherwise execute, a `tetrio://` protocol room link (e.g. `tetrio://X-QP`)
4. Observe the client joining the linked room while remaining on the login screen.

### Expected behavior

The client should display the standard deeplink "welcome back" screen, and should absolutely not attempt to join a room before the user explicitly requests to do so.

![](https://zudo.pics/3zl4mrn3.png)

### Screenshots

Here's a video of this occurring. 

https://user-images.githubusercontent.com/4703499/169706576-7f6bdd40-5073-45fc-aec7-dda83cecfeff.mp4

### Console logs

![](https://zudo.pics/78lvwpp6.png)

**Comment by o5k** [comment]
Fixed in next patch.
