### ISSUE TITLE
Ribbon Expired

### ISSUE THREAD

**Issue by mema2121** [tetrio/issues#948]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 11

### Browser and version

chrome 101

### Describe the bug/issue

consecutive ribbon errors after update today

### Expected behavior

that the game continues?

### Screenshots

![Screenshot (745)](https://user-images.githubusercontent.com/106047782/169736985-fe2b91f3-ab82-414a-97aa-294eaf622791.png)
![Screenshot (746)](https://user-images.githubusercontent.com/106047782/169737011-5aa585b6-b03e-46ca-ae89-b3bcbc6bc458.png)

**Comment by ZaptorZap** [comment]
Network issues are outside the scope of this repo
