### ISSUE TITLE
Since tetr.io can be run on apple devices why not make it mobile friendly

### ISSUE THREAD

**Issue by scratchusernamemrtbts** [tetrio/issues#950]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

since tetr.io can be run on apple stuff so i use it to spectate random people in quick play
but the buttons and stuff arent really mobile friendly especially when using split screen
![Uploading 373725DB-07DB-4181-A581-A705CA890323.jpeg…]()

### Describe the solution you'd like

maybe make the gui smaller when it detect the screen is small
or even better make mobile controls

### Describe alternatives you've considered

just make it automatically put you into spectator mode when you join on mobile cus u can't play on mobile anyways and the spectate button sometimes cant be clicked

**Comment by scratchusernamemrtbts** [comment]
somehow the image didn’t upload so lemme reupload it
![](https://media.discordapp.net/attachments/673305614318960671/978498567243169843/IMG_0568.png)

**Comment by o5k** [comment]
It's a lot of effort, for a userbase who I am not particularly interested in reaching (.io game players are already very detached from the game, mobile gaming is even more so). I might do it in the future, but for now I do not have particular interest in the mobile gaming sphere

**Comment by scratchusernamemrtbts** [comment]
ok
i understand

**Comment by Antoni0111** [comment]
![Screenshot_20220528-195132_Edge](https://user-images.githubusercontent.com/103315112/170824376-5654607b-14ae-4f05-b3b7-12c4c7a2ad35.jpg)
still a little bit small...... but thanks for the reply from ZaptorZap. Hope the mobile display issue could be solved someday!

**Comment by scratchusernamemrtbts** [comment]
> ![Screenshot_20220528-195132_Edge](https://user-images.githubusercontent.com/103315112/170824376-5654607b-14ae-4f05-b3b7-12c4c7a2ad35.jpg)
> still a little bit small...... but thanks for the reply from ZaptorZap. Hope the mobile display issue could be solved someday!

I recommend u try setting ur display size for android maybe it helps

**Comment by MilanPlayZ** [comment]
It would be amazing to have this fixed. I would like to play Tetrio on the go, and in my collage because we don't have computers there. I connected my keyboard to my phone and it worked like on pc. It's working, but it's really hard to see. That's the only problem with it. I hope they fix it someday.

**Comment by scratchusernamemrtbts** [comment]
> It would be amazing to have this fixed. I would like to play Tetrio on the go, and in my collage because we don't have computers there. I connected my keyboard to my phone and it worked like on pc. It's working, but it's really hard to see. That's the only problem with it. I hope they fix it someday. 

sorry for super late reply
as i stated a workaround for this (you have a keyboard) is setting ur device text and display size setting to very small)
