### ISSUE TITLE
40 lines restarts after hard dropping

### ISSUE THREAD

**Issue by realitytrain** [tetrio/issues#951]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Brave V1.39.111

### Describe the bug/issue

I can hard drop a few times if I'm lucky, then the board flips and my run restarts. I've checked the online version, blitz, zen, and all multiplayer modes which work, I've updated it, uninstalled and reinstalled, updated my graphics drivers etc. PC has a  Gigabyte B450 Aorus Elite motherboard, 32gb of ddr4 t-force delta RAM, ryzen 5 3600x and a 1660 super if that helps. The game also works fine if i dont use the hard drop and just soft drop the whole time. Only started after the new 6.2.1 update about 2 days ago

https://user-images.githubusercontent.com/98303958/170246425-51251b9c-9073-4b46-af8f-56f7a0123b78.mp4

### Reproducing

1. start a game of 40 lines
2. move the pieces around a few times
3. hard drop
4. run will reset

### Expected behavior

wanted the game to not restart after a few moves

### Console logs

![Screenshot 2022-05-25 205725](https://user-images.githubusercontent.com/98303958/170246979-373fa9c0-8752-49a8-9824-b76f810e516a.png)

**Comment by Jabster28** [comment]
does this happen with the web version too? what about in incognito?

**Comment by ZudoB** [comment]
Turn off “retry on finesse fault” before starting the 40L game.
