### ISSUE TITLE
Stick deadzones

### ISSUE THREAD

**Issue by BoxBoy7999** [tetrio/issues#952]
### Checklist

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I can't use my controller properly on the desktop version because it has _slight_ stick drift, so my inputs always get set to a stick direction.

### Describe the solution you'd like

Add customisable controller stick deadzones

### Describe alternatives you've considered

A toggle to turn off input axes and only accept buttons.

**Comment by o5k** [comment]
This is what "controller sensitivity" does, lower it down to increase deadzone size

**Comment by BoxBoy7999** [comment]
im dumb

**Comment by BoxBoy7999** [comment]
Sorry for wasting your tume
