### ISSUE TITLE
tetr.io keeps logs out user

### ISSUE THREAD

**Issue by RadityoXYZ** [tetrio/issues#955]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 21H2

### Browser and version

Edge 101.0.1210.53

### Describe the bug/issue

yesterday i can play the game just fine, but now that i can't log into my account for no reason..
it keeps logging out by itself. and no, my password isn't wrong.

### Expected behavior

automatically logs into the game

### Screenshots

![TETR IO_WYnd5qcUVh](https://user-images.githubusercontent.com/51162871/171188839-ce1a6d24-69df-47f0-8782-737957ad6951.png)

### Console logs

undefined
VM103:4128 GET https://tetr.io/api/users/me net::ERR_CONTENT_DECODING_FAILED 304

**Comment by o5k** [comment]
Is this still happening? Looks like an internet issue seeing the logs
