### ISSUE TITLE
Tetrio fps capped at either 60 or 120

### ISSUE THREAD

**Issue by Danksquidboy** [tetrio/issues#956]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 19044.1706

### Browser and version

Chrome Version 102.0.5005.63

### Describe the bug/issue

When I play the game normally, if I dont use the minimal option the game will automatically cap my fps to 60. (sometimes 120? idk) It's hard to play without good controls.

### Reproducing

1. launch tetrio
2. play something
3. watch the fps drop in pain

### Expected behavior

I expected to play properly? I didn't expect my fps to be capped to 60 without a reason. Might be something with vsync to do or something.

### Console logs

![image](https://user-images.githubusercontent.com/76915282/171192519-50804954-4058-4ac8-9032-d5db06dab3d0.png)

### Additional context

It happens at random times, sometimes it happens, sometimes it doesnt.

**Comment by ZaptorZap** [comment]
The issue here is Google Chrome. If you wanna play without **VSync**, consider downloading [the TETR.IO Desktop application](https://tetr.io/about/desktop). VSync is automatically disabled, here. If you'd rather stick with Chrome, here's some information on how to disable VSync there:
> find your chrome shortcut (say, the one on your taskbar) and rightclick it, then choose Properties
> then, in the Target: field, just add `--disable-gpu-vsync` to the end of it
> ye, just right click w/e you use to start chrome, and edit the target field to have that tag
> <img width="626" height="581" src="https://cdn.discordapp.com/attachments/673303546564968566/689866242563113057/2020-03-18_17-01-44.png">

**Comment by ZaptorZap** [comment]
It's just occurred to me—how exactly are you getting your FPS baselines? There's an ingame FPS counter with `F8`, and some external program might be skewing the results to be in-line with your monitor's refresh rate(or god forbid your compositor's refresh rate). If that's the case, it makes the inconsistent results at least a tiny bit more explainable.

**Comment by Danksquidboy** [comment]
![image](https://user-images.githubusercontent.com/76915282/171935170-9c34b047-9736-4f49-982b-090fee6d9fb3.png)
this seems normal though?

**Comment by ZaptorZap** [comment]
> - [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
> TETR.IO PLUS v0.23.7 on Tetrio Desktop.

I'm sorry, but this is the 2nd fault you made in your initial report. Once you're running TETR.IO PLUS, _you're no longer connecting TETR.IO with a genuine client_. I know what you're probably thinking: "But it doesn't change anything! TETR.IO PLUS _barely_ even modifies the game!"

Point is: it really **does** modify the game, particularly when playing on the desktop client. For instance, TETR.IO PLUS entirely removes the "are you sure?" dialog you get when closing the game. That's not something you can toggle.

Furthermore, I went ahead and looked up that model of yours, and the results aren't too relieving:
![image](https://user-images.githubusercontent.com/64891705/171960221-9531eccc-8d03-4133-9eba-f6aaf96d2800.png)
I'm not sure if this _should_ have bearing on your maximum framerate in TETR.IO, but it seems undeniable that this graphics card physically supports anything above 60 Hertz per second at a maximum, according to [this official spec sheet](https://psref.lenovo.com/syspool/Sys/PDF/IdeaCentre/IdeaCentre_G5_14IMB05/IdeaCentre_G5_14IMB05_Spec.pdf).
