### ISSUE TITLE
autohost lobby ranking systems aren't keeping too-high ranked players out

### ISSUE THREAD

**Issue by toraeontetris** [tetrio/issues#961]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I've been playing in the B+ and below lobbies for a bit, and lately I've been seeing a lot of players who probably shouldn't be in there in the first place. I'm a B player, and usually I'm able to hold my own, sometimes even get 1st or 2nd place, but lately I've been KO'd almost immediately by high APM players and then had to watch them battle it out at the speed of A or S players for minutes at a time. Just last night I was playing, and watched a "new" player beat the entire lobby multiple times, with a placing speed that was just ridiculous. I checked and they had 7/10 ranking games, 5 of which they had won. And they weren't the only one. There were at least two more "new" unranked players that were playing at their speed, and there were also a few unranked players with TR's of at least 8500. For reference, I'm B rank and my TR wavers between 6500 and 7000. During this time, Autohost caught one smurf (after they had won at least 10 games) and kicked them for exceeding the max APM, but ignored the rest.

### Describe the solution you'd like

I have two solutions. The first one is to bar unranked new players from ranked rooms altogether. It doesn't take long to finish rating games and gain a TR, and I think this would keep a lot of smurfs and players with too-high ranks out.

The second solution is to base the Autohost room requirements on TR instead of letter ratings. This would keep unranked vets from being able to play just because they didn't have a letter rating.

### Describe alternatives you've considered

You could also base the Autohost room requirements on APM, which, again, would keep high-up players out.

I don't really know about coding, so I don't know what this would entail, but tweaking Autohost and making it better at monitoring the games could also help. (sorry this one is kind of lame- it might actually be the best solution, but I don't know how Autohost works so I cant give any specific ideas. it seems like the problem is with autohost, but if you changed the room requirements then you wouldn't have to do anything else.)

### Additional context

<img width="1572" alt="Screen Shot 2022-06-05 at 11 50 26 PM" src="https://user-images.githubusercontent.com/106947050/172105613-bb123b34-6d14-4459-8a4e-ad996cb1c74b.png">
not sure if this one actually helps at all since I cant tell how active APM works, but they were both playing at the speed of A players at least

<img width="831" alt="Screen Shot 2022-06-06 at 12 14 28 AM" src="https://user-images.githubusercontent.com/106947050/172105688-e613bd20-c351-4cc5-a285-07b8b0a8e0b3.png">
a "new" player who would definitely be higher ranked than a B+ if they were ranked

<img width="198" alt="Screen Shot 2022-06-06 at 12 15 02 AM" src="https://user-images.githubusercontent.com/106947050/172105759-fdc96961-12dc-4b0b-8617-3c8d7c0089e7.png">
the number of wins this person got before autohost recognized them as exceeding the room's max APM

please let me know if there are any things that need to be clarified or if you want more screenshots or "evidence" or whatever lol.

**Comment by ZaptorZap** [comment]
Looks like you missed your feature request—**Autohost's repository is here: https://gitlab.com/Zudo/autohost/-/issues**

That said, please **report** these individuals as well. You can do so by pressing this button:
![image](https://user-images.githubusercontent.com/64891705/172107236-2451fac2-1614-4200-ad32-276dbe7e82ae.png)
Account issues are outside the scope of this repository, so I'll be closing the request immediately.
