### ISSUE TITLE
Picture checking system is somewhat broken

### ISSUE THREAD

**Issue by timelessnesses** [tetrio/issues#966]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Tetr.io Desktop Client 

### Describe the bug/issue

The picture checking system for avatar is somewhat broken.  
look at this picture. 
![](https://cdn.rukchadisa.live/r/owo.jpeg)<br>
But when uploaded to tetr.io as avatar (unsure about banner) it was blocked as inappropriate 

### Reproducing

Try change your profile picture in tetr.io to https://cdn.rukchadisa.live/owo.jpeg

### Expected behavior

The picture check process accept it as normal picture

**Comment by ZaptorZap** [comment]
Sorry, but this issue actually comes from one of our [open source dependencies](https://tetr.io/about/acknowledgements/); specifically called "[NSFW JS](https://nsfwjs.com/)"(found on GitHub [here](https://github.com/infinitered/nsfwjs)). There's more information about what you can do in this scenario with [this **frequently asked question's answer**](https://github.com/ZaptorZap/tetriofaq/wiki/Personalization#my-profile-picture-isnt-nsfw), but unfortunately, there's nothing we can do for you on this issue report repository. Account issues such as these aren't really in scope of the issues we track here.
