### ISSUE TITLE
Tetrio stuck on "Starting Tetr.io"

### ISSUE THREAD

**Issue by ImPalyYT** [tetrio/issues#968]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Tetrio Desktop V8

### Describe the bug/issue

It's Always stuck on "Starting Tetr.io", tried to hold F4 for 5 seconds. Still did not work and I tried waiting for 10 minutes nothing and My Firewall was off.

(And if you want to know my laptop specs here. Intel Celeron, 3Gb RAM, 64-bit Operating System)

### Expected behavior

Stuck on "Starting Tetr.io", F4 Does not work, Don't know why it is using high ram usage, Failed to check for updates,

That is all I know.

### Screenshots

![Screenshot (123)](https://user-images.githubusercontent.com/97025017/175754105-aecff3a2-6348-4691-ad03-78bf3967d022.png)
![Screenshot (126)](https://user-images.githubusercontent.com/97025017/175754112-0c2be894-63d1-4fed-abfa-5d22dff3dfba.png)

**Comment by o5k** [comment]
Is TETR.IO allowed through your firewall?

> Celeron, 3Gb RAM

ouch

**Comment by JadiPlayz** [comment]
hold F4 for five seconds
