### ISSUE TITLE
Scunthorpe Naming System Issue

### ISSUE THREAD

**Issue by Conrad306** [tetrio/issues#970]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Ubuntu 22.04

### Browser and version

Firefox 101.0.1

### Describe the bug/issue
I attempted to register with my name "Conrad306", however, it flagged my name as inappropriate.
Whatever current name check system has issues with flagging names, as it flags my name Conrad306 as inappropriate. Whatever is going on is likely the [Scunthorpe Problem](https://en.wikipedia.org/wiki/Scunthorpe_problem). 

### Expected behavior

Allowing a name such as "Conrad306" or the typical "Scunthorpe"

**Comment by ZudoB** [comment]
Unfortunately, this isn't a problem that's easily solved. It's borderline impossible to fix the Scunthorpe problem without also allowing a whole host of creative filter bypasses.

I've whitelisted the name "Conrad306" so you should be able to register with it now, and we encourage anyone encountering a similar false positive to contact staff directly.

**Comment by Conrad306** [comment]
thank you, I understand that and i've had to deal with stuff like this myself. I appreciate it!

**Comment by ZudoB** [comment]
...sure, but again, requests such as this should be directed to https://tetr.io/about/support please
