### ISSUE TITLE
Getting disconnected on FT match

### ISSUE THREAD

**Issue by Mogly000** [tetrio/issues#974]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop Client and chrome 

### Describe the bug/issue

Playing online match keep kicking me out

### Reproducing

Open any tetr.io
Play Online match
Fight
Get kick out because it said it is my internet

### Expected behavior

This will kick you out only on FT match

### Screenshots

![Capture 3](https://user-images.githubusercontent.com/85986471/177461549-00c3a466-0ffa-4a7b-be6b-cf11cac06845.PNG)
![Capture 4](https://user-images.githubusercontent.com/85986471/177461557-97e704b7-dfdc-4690-9468-d939972ade14.PNG)
![Capture](https://user-images.githubusercontent.com/85986471/177461559-c6384950-e699-45c2-9ba6-4d4ba7b89c7a.PNG)

### Additional context

I already try other games online and tetr io is the only one i have problem

**Comment by ZaptorZap** [comment]
Network issues are outside the scope of this repo
