### ISSUE TITLE
Tetra channel Live streamers are not Live

### ISSUE THREAD

**Issue by Korriii** [tetrio/issues#975]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Edition	Windows 11 Home Single Language Version	21H2 Installed on	‎22/‎04/‎2022 OS build	22000.739 Experience	Windows Feature Experience Pack 1000.22000.739.0

### Browser and version

idk?

### Describe the bug/issue

The tetra channel for streamers are not usually Live, When I check the tetra channel for streamers to watch , Most of them are not live, And if you click on one of them it directs it to there channel, I have to manually go to twitch and search for tetr.io to see which ones are live and which ones are not, Also it could be an inconvenience for streamers who play tetr.io on stream but cannot be seen in tetra channel. 

### Reproducing

1.go to tetr.io
2.click tetra channel
3.scroll down to see streamers who are live
4.hover over the names and you can see a picture of a grey camera and if you click on the streamer they are not live

### Expected behavior

I want the tetra channel to be fix of this bug or  either its not a bug, And it could be nuisance for streamers when they stream on tetr.io but they're names do not appear on tetra channel.

### Screenshots

![Screenshot (8)](https://user-images.githubusercontent.com/107013254/177923897-e0eff649-b386-4cf9-83a4-40211a0307c5.png)

### Additional context

Although I am not sure if this is a bug that only applies to Me I want to at least help the game on any problems I can find

**Comment by ZaptorZap** [comment]
This's probably the lowest priority "[priority](https://github.com/tetrio/issues/issues?q=is%3Aissue+label%3Apriority)" labeled issue, but you're totally right: the entire Twitch integration has broken, and **nobody** on the list is live right now. I can't imagine what caused this to stop updating all of a sudden, but the above screenshot still holds true nearly a day later, this time on the standalone TETRA CHANNEL site. _(every user on this list has the aforementioned gray camera thumbnail)_
![image](https://user-images.githubusercontent.com/64891705/178085471-fe5d3a44-3bc3-4a91-a5d9-626c1e1af566.png)

**Comment by o5k** [comment]
Not.... entirely sure what causes this, but Twitch API seems to sometimes invalidate my token even though it hasn't expired? Very strange. Will look into this

**Comment by Korriii** [comment]
Thanks
