### ISSUE TITLE
Cookie "Preferences" button won't respond

### ISSUE THREAD

**Issue by Wilker-a** [tetrio/issues#980]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Fedora 36 / Linux

### Browser and version

Chromium 103.0.5060.114 (Official Build, ungoogled-chromium) 64 bits

### Describe the bug/issue

![a screenshot featuring the banner highlighted](https://user-images.githubusercontent.com/10854855/179374800-ac38118e-ec68-4f20-a4ce-036df254f2ae.png)

Clicking "Preferences" in the Cookie Policy banner does not respond with any interfaces to allow me to change cookie preferences. Instead, it just reloads the page.

### Reproducing

1. Enter the main page for the first time (assuming no cookies from tetr.io were set before);
2. Click "Preferences" in the Cookie Policy banner;

### Expected behavior

A dialog window is supposed to show up allowing for any user to choose which cookies to enable, or keep everything disabled except for essential ones such as login credentials and game settings.

### Screenshots

![a gif recording of the screen showing the behavior](https://user-images.githubusercontent.com/10854855/179375289-c059e014-9877-40c1-a62f-ec337e08ceb3.gif)

### Additional context

There are no other means to have access to this button, since the banner is gone forever if you either click Ok or if you have an automatic login set up. Because of this i was unable to test it on the download version.

**Comment by ZaptorZap** [comment]
For transparency, that PREFERENCES link goes towards https://tetr.io/?cmpscreen, and it doesn't actually show up on my Firefox browser either. Thing is, I'm aware that's down to how _Firefox_ blocks things, especially considering I've explicitly requested **strict** tracking protection, so this isn't really an issue osk could fix. Your scenario with Chromium blocking it is a bit strange, but, pardon the suspicion(I haven't used Chrome in years), what implications does this "crossed out eyeball" icon in the address bar bring to the table?
![image](https://user-images.githubusercontent.com/64891705/179382058-5296b664-024c-4fd6-a414-d83ba6022bbf.png)

It seems to only show up *after* you've requested the ?cmpscreen extension, so the correlation here is apparent to me.
<hr>
You can disable automatic sign in through the ingame CONFIG, as shown below:

![image](https://user-images.githubusercontent.com/64891705/179382152-17641e00-600f-4982-9912-0502e98967c1.png)

But, disabling the login shows a different kind of bottleneck—the preferences are hidden as soon as you're greeted with the JOIN button. You can kinda snipe the button as the game loads, and it **will** refresh the page, but no cmpscreen will appear. I have a feeling this was disabled on purpose, especially considering you can disable third party adverts entirely on the desktop client. (it's right below where you turned off automatic sign-in)

**Comment by Wilker-a** [comment]
i didn't notice that icon either, but looking into it, that's just my setting to block all the 3rd party cookies from the single advert that loads up on my screen

**Comment by Wilker-a** [comment]
i didn't notice that icon before, but looking into it, that's just my setting to block all the 3rd party cookies from the single advert that loads up on my screen. 

![image](https://user-images.githubusercontent.com/10854855/179390656-f57de482-0cc7-43ce-b0e9-ad5a83296856.png)
![image](https://user-images.githubusercontent.com/10854855/179390924-75368c9b-bc50-4cd8-9af4-7fc6c1fb3a5f.png)

i don't see how it would make sense to disable cmpscreen, since you're not required to enable tracking cookies to still have the adverts on screen. that would be dumb.

**Comment by o5k** [comment]
strange, indeed the CMP isn't willing to show for me either, looks like a change on AdinPlay's side, will have to consult or change the way I use it...trying to avoid their fugly popup lol

**Comment by o5k** [comment]
Fixed in next version.
