### ISSUE TITLE
Malwarebytes detects a trojan connection after the networking update (7/20)

### ISSUE THREAD

**Issue by instilledbee** [tetrio/issues#983]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chromium 103

### Describe the bug/issue

When I start TETR.IO, either from the browser or the desktop client, Malwarebytes detects a trojan connection. This alert never appeared prior to the networking update last 7/20.

While this is most likely a false positive, I would like to let the development team know.

### Reproducing

1. Install Malwarebytes (either the free trial or Premium version)
2. Open TETR.IO (new browser tab, desktop client)
3. Log in to the game

### Expected behavior

No anti-virus alerts are thrown when playing TETR.IO

### Screenshots

![image](https://user-images.githubusercontent.com/5665389/180186341-8a935faa-88a5-40c7-899f-580e0a04f0d1.png)

### Console logs

![image](https://user-images.githubusercontent.com/5665389/180186501-03a62669-adbe-4d55-bb8d-98fb81957b93.png)

**Comment by o5k** [comment]
Weird, definitely a false positive,  seems to only happen for that spool. Maybe the IP is blacklisted due to abuse by a previous owner? Might try to give it a new IP.

**Comment by o5k** [comment]
Will be getting new IPs for them.
