### ISSUE TITLE
quick play into a no person room

### ISSUE THREAD

**Issue by galioverhere** [tetrio/issues#984]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop Client newest version

### Describe the bug/issue

I play quick play, it stuck and I wanted to quit the game, but it started after I quit, there is no one there, only me in game, my Attack at the time is 10057, no normal game would be like that, right? I played to 10057 and screenshot.

### Expected behavior

It should be a normal quick-play game, not into a bug room.

### Screenshots

![unknown(40)](https://user-images.githubusercontent.com/106040858/180200190-0366d053-f870-40a9-b9f9-cbf390408506.png)
as you can see my ATTACK is 10057, I played for a long time, reached 10000 I end it, that is weird. after I kill myself, other "people" are still alive, but there are no other people.

**Comment by o5k** [comment]
Do you have any console logs?

**Comment by galioverhere** [comment]
this?
Bootstrapping for hardver 11e4962b.QLRNJ_TVq.-8J0IDWwR0
VM102:4259 webgl backend was already registered. Reusing existing backend
factory.
t.registerBackend @ VM102:4259
VM102:4259 cpu backend was already registered. Reusing existing backend
factory.
t.registerBackend @ VM102:4259
VM102:4259 Platform browser has already been set. Overwriting the platform
with [object Object].
t.setPlatform @ VM102:4259
VM102:4265 TETR.IO
VM102:4265 Please be careful when pasting anything in the console.
Attackers may be out to steal your login information.
VM102:4265 Using the Desktop Client
VM102:4265 Up to date. Local version 6.3.0-production | Commit 11e4962b
(7/21/2022, 4:00:12 AM) | Server cycle QLRNJ_TVq | Build -8J0IDWwR0
(7/21/2022, 4:11:18 AM)
5A cookie associated with a cross-site resource at <URL> was set without
the `SameSite` attribute. A future release of Chrome will only deliver
cookies with cross-site requests if they are set with `SameSite=None` and
`Secure`. You can review cookies in developer tools under
Application>Storage>Cookies and see more details at <URL> and <URL>.
tag.min.js:1154
     ✰ TTI - tetr.io ✰ aiplib v11.0 - prebid v6.24.1 - MCM 22431394745 ✰
   ads by https://www.adinplay.com/
VM102:4265 Ceriad provider has been loaded successfully.
VM102:4265 tetr-io_728x90_1 mounted, now 1 mounts
VM102:4265 PixiJS 6.1.3 - WebGL 2
VM102:4265 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) tetrio-desktop/8.0.0 Chrome/83.0.4103.122
Electron/9.4.0 Safari/537.36 -CPU: 8-coreMemory: ~8 GBConnection: 9.9 Mbps,
0ms RTT [4g]
VM102:4265 Renderer: ANGLE (Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0
ps_5_0)
VM102:4265 Obtaining Ribbon endpoint...
VM102:4265 Obtained Ribbon endpoint /ribbon/shizuru and 20 spools.
VM102:4265 Getting a spool...
VM102:4265 Spool > Spooling started
VM102:4265 Spool >    70ms ap-north-konata [JP] v1 // 0.078125, 0.125,
0.09375
VM102:4265 Spool >    98ms ap-north-mishima [KR] v1 // 0.109375, 0.09375,
0.015625
VM102:4265 Spool >   100ms ap-north-hina [KR] v1 // 0.140625, 0.078125,
0.078125
VM102:4265 ap-north-konata 50
VM102:4265 ap-north-mishima 18
VM102:4265 ap-north-hina 17
VM102:4265 Spool > Spooled ap-north-mishima!
VM102:4265 Obtained spool ap-north-mishima (ap-north-mishima.spool.tetr.io)
[KR].
The resource https://cdn.xsolla.net/img/favicon.ico was preloaded using
link preload but not used within a few seconds from the window's load
event. Please make sure it has an appropriate `as` value and it is
preloaded intentionally.
The resource https://secure.xsolla.com/favicon.ico was preloaded using link
preload but not used within a few seconds from the window's load event.
Please make sure it has an appropriate `as` value and it is preloaded
intentionally.
VM102:368 Ribbon 03138375601ce0d3 opened
DevTools failed to load SourceMap: Could not parse content for
https://tetr.io/tf.min.js.map: Unexpected token < in JSON at position 0

osk ***@***.***> 於 2022年7月21日 週四 晚上7:53寫道：

**Comment by o5k** [comment]
Hmmmm... did the game start exactly when you tried to quit?

**Comment by o5k** [comment]
Should be fixed? Let me know if it's still happening.
