### ISSUE TITLE
The positions of PPS and APM get swapped in the "Victory/Defeat" and "Replay" screens

### ISSUE THREAD

**Issue by ArchWand** [tetrio/issues#986]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Ubuntu 22.04

### Browser and version

Firefox 102.0.1 Snap

### Describe the bug/issue

After the end of a Tetra League match, the order the stats are displayed in goes `APM`, `PPS`, and `VS`. However, when you go to view the replay, the summary gives the stats in the order of `PPS`, `APM`, and `VS`. I'm not sure if this is intentional, or due to my configs, but I think the order should remain consistent.

### Reproducing

1. Finish a tetra league match.
2. Note the order the stats are displayed in.
3. Click the Replay button
4. Compare the order the stats are displayed in.

### Expected behavior

The order the stats are displayed in should be consistent across the UI.

### Screenshots

![image](https://user-images.githubusercontent.com/57409597/181352998-08bc4f04-7941-4693-86de-ff90d8bd75dc.png)

![image](https://user-images.githubusercontent.com/57409597/181353043-984cf0ed-96e6-440a-88f9-ff7ecb233301.png)

**Comment by ArcWandx86** [comment]
am I allowed to bump this

**Comment by Dimentio** [comment]
Fixed in next patchnote!
