### ISSUE TITLE
Sometimes I encounter unbalanced opponents

### ISSUE THREAD

**Issue by BubbleBlackTea** [tetrio/issues#988]
Hello I'm the TETR.IO player BUBBLEBLACKTEA with the User ID 6170316e0e6ac854a4008645.

The TETR.IO Tetra League intend to be "matched up with a player of similar skill in a game of 1v1 versus."

But sometimes I encounter opponent with a TR a lot higher than me, higher rank, or the one that have a lot higher VS point.

For example, my TR is 15357 and i'm in the A+ rank, but I encountered a player of S- rank and 17462 TR, this is very very unfair for the ones that recently get to the A+ rank, and I'm really not ready to play in the S rank at all, the TR difference between the two players is TOO BIG. And another example is my VS point is 43.63, and my opponent has a 59.86 VS point, which means that the opponent's gameplay is a lot better than me, and the opponent could play a lot faster than me, could place pieces a lot faster than me, which is NOT fair at all, how can I enjoy playing in Tetra League if the matching system is always like this?

Because of that, I got consecutive losing streaks, and even worse, the more I lose THE HARDER the opponent I match.

I'm looking forward for the response, and I hope the TETR.IO Tetra League matching system could be even better.

Thank you for the attention.

**Comment by ZaptorZap** [comment]
Have you read [Tenchi's FAQ](https://tetrio.team2xh.net/?t=faq#rank-match) about the issue at hand yet? Furthermore, are you aware matchup calculation is driven only by "Glicko" and **not** TR (which, while constructed from Glicko, can be misleading—from the ranges you mentioned, TR is "worth" a lot less Glicko around the middle: that's at 12,500 TR) and can **exaggerate** perceived differences in skill. Furthermore, [this Tweet](https://twitter.com/tetriogame/status/1300156265344241664) from the official TETR.IO Twitter account explains the dynamic you can expect during these matchups: 
* If you lose, you lose little. The matchmaking system _expects this to occur_ and lowers your RD for it—further minimizing losses from an "unfair" matchup.
* If you win, you'll win a **lot**. The matchmaking system didn't expect this, and awards you _more RD_ for this—further capitalizing on potential gain.

There's more of an explanation on what Rating Deviation is in TETR.IO's context [here](https://github.com/ZaptorZap/tetriofaq/wiki/Mechanics#rating-deviation) and [here](https://tetris.wiki/TETR.IO#TETRA_LEAGUE). Glicko is not unique to TETR.IO, and it has a Wikipedia page [here](https://en.wikipedia.org/wiki/Glicko_rating_system) if you would like to learn more about the matchmaking systems. If you want very simple advice to try and minimize matchups such as these, just **leave and re-enter matchmaking** about every 40 seconds—be warned: it might take slightly or significantly longer to find a match like this! (and, also, please understand that *other* individuals may match against you if *they* were waiting for very long too)
