### ISSUE TITLE
Oversight with "Hide chat while ingame" feature

### ISSUE THREAD

**Issue by Sup3rFire** [tetrio/issues#993]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Brave Version 1.42.86  Chromium: 104.0.5112.81 (Official Build)  (64-bit)

### Describe the bug/issue

When the `Hide chat when ingame` feature is enabled, it is difficult to click on any player names in chat. 

This happens because the chat starts to close when you click on the player name and the `mouseclick` event only fires when your mouse is over the element after the `mouseup` event has fired. The closing of the chat makes it difficult to keep your mouse over the player name when releasing the mouse button, especially when the names are shorter.

This issue can be solved in 2 different ways:
1. The chat can be programmed to close only if the current element being focused is not inside the chat element, as opposed to closing the chat when the chat input element is unfocused, or
2. The player profile modal can be made to trigger after `mousedown` instead of `mouse click`

### Reproducing

1. Turn on the `Hide chat when ingame` feature in the `Video & Interface` section of config.
2. Go to any room and start a match / spectate a match
3. Open chat and attempt to click on a player's name

### Expected behavior

The player name in chat should be easily clickable.

**Comment by 4500zenja1** [comment]
I have exactly the same problem: with "Hide chat when ingame" set by default (I play on Minimal graphics), sometimes I can click on username only once in 5–10 times lol. Sometimes I would like to see what's the guy writing in chat, reassure about their TL stats, etc.

Props to @Sup3rFire for bringing out that problem :)

**Comment by Sup3rFire** [comment]
Issue is still present

**Comment by Dimentio** [comment]
Fixed in next patchnote!
