### ISSUE TITLE
"out of focus" caused by advertisements

### ISSUE THREAD

**Issue by yourlocaljedi** [tetrio/issues#994]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows

### Browser and version

chrome

### Describe the bug/issue

Hello,

This issue for me has started becoming too frequent now. While I'm actively playing tetra league, the game randomly pops up the "out of focus, click to return to tetrio"  When I do click back on the browser, the pieces move by itself all the way to the left or to the right. If i try putting the pieced in the opposite direction, it pulls it back to the dominant side. If you guys can please fix this bug, it's made me lose multiple games. Thank you. 

### Expected behavior

If you can please fix it so that doesn't happen while actively playing.

**Comment by ZaptorZap** [comment]
An intermediary fix to the sticking issue is described in #680: just press the "stuck" key again and it **will** begin working again.

That said, this is *almost always* an issue on your computer and no one else's. Are you **sure** no other application, such as an antivirus notification, is fighting for application focus here? Could you perhaps record a video of this phenomena?

**Comment by yourlocaljedi** [comment]
Hi,

I’ve used two different computers and a laptop and I get the same issue on all this device. I thought it was just the case for that 1 computer so then that’s when I tested it on other devices. When I get the chance, I will try to get a video of it.

Thank you

**Comment by aheadsounds** [comment]
i have been having the same issue

**Comment by ZaptorZap** [comment]
> Are you **sure** no other application, such as an antivirus notification, is fighting for application focus here? Could you perhaps record a video of this phenomena?

I'm going to expect you to do the same, or there's nothing we can help you with here

**Comment by yourlocaljedi** [comment]
Hello,

I realized what was causing it. This only started happening after the big update that happen btw, I forgot to mention initially. But it tends to occur when the ad changes to a different ad.

**Comment by d3nwah** [comment]
I too experience this issue

**Comment by d3nwah** [comment]
Turns out it wasn't chat related, I disabled it in the options and it's still happening. Very frustrating in ranked matches.

**Comment by gustavoem** [comment]
I have the same behaviour on

Mac OS Monterey 12.1
Chrome 107.0.5304.110 

However, the bug does not occur on the same PC, on Firefox version 84.0.2

**Comment by zoomi4649** [comment]
same thing happens to me.

**Comment by gtbot2007** [comment]
I think it has to do with when a ad pops up on the bottom

**Comment by kaianinja** [comment]
Yep, same for me. And I confirm it is because of the ads at the bottom. I got this problem on google chrome and edge

**Comment by kaianinja** [comment]
Are we planning to fix this?

**Comment by anajullia** [comment]
Same bug

**Comment by anajullia** [comment]
same bug happening to me, on windows 11 chrome

**Comment by BowiePro** [comment]
i have this bug too when a new ad pops up, chromeos

**Comment by kaianinja** [comment]
Hello is there any update?

**Comment by flame91** [comment]
I have the same issue. This game sucks

**Comment by THite06** [comment]
Just experienced this issue today, and it caused a loss during a Tetra league match. I hope this bug gets fixed.

**Comment by Jomukku** [comment]
You just have to turn off your touchpad, you are accidentally clicking it while playing and fucking everything up. 
If it ever happens to you again tho, to quickly fix the key moving to ''x'' direction just press ''x'' key.

**Comment by Dimentio** [comment]
An attempt to fix this was implemented lately, is it still occurring?

**Comment by flame91** [comment]
@Dimentio 
YES.
It happens more often than it used to.

**Comment by copgraveyard** [comment]
this is happening to me almost every game, both on windows 11 and macOS monterey, 12.7.5. it's really starting to get annoying, i can't count how many times i've lost a game due to this. i thought it was just my computer but i tried both computers and it's still happening. no idea what the issue is. please fix this soon!

**Comment by ghost** [comment]
i had this problem too but i found the solution for myself it was because i had caret browsing on

**Comment by ktg5** [comment]
This is happening to me as well -- can confirm.

**Comment by atonix** [comment]
This issue is still happening, I'm on Windows 11 Desktop and any time the ad changes it goes out of focus

**Comment by Findaquil** [comment]
I'm now also experiencing this issue. My Supporter just expired, never had an issue before, now the ads are there and quick play is constantly breaking. Dodgy way of pushing for people to pay for Supporter.

**Comment by ZaptorZap** [comment]
We constantly encourage everyone to completely turn off all ads with the ingame toggle or by just installing [uBlock Origin](https://ublockorigin.com/):

https://github.com/user-attachments/assets/e36b1078-71da-41e3-9e8d-fde5a90c4800

I assure you this isn't an intentional strategy to coerce people into spending money.

**Comment by Findaquil** [comment]
Thank you, I will try that. I've been supporter on and off for so long I had completely forgotten there were ads, and I didn't expect there to be an option to turn them off. As an update, when it happens to me I can't regain focus at all - clicking, changing tab out and back in, the message remains.

**Comment by AlphaJules** [comment]
Windows 11 client on two different PCs. 

I frequently get the 'Out of Focus' notification during gameplay. At first, I too thought it was a keyboard input issue, so I switched out keyboards and continued receiving the out of focus notification. So then I tried on a different PC and continued getting the notification. This all started with an update within the last 2-3 months as I've never had this happen before then.

It appears to occur during Quick Play most frequently, although I have witnessed it during other modes as well.

I have ZERO issues with 'Out of Focus' in the browser.

**Comment by Keydex** [comment]
Reporting that I see this issue on Edge, Windows 11.

Checking my event input, my keyboard is not sending erroneous key presses. 

I do have uBlock origin and this is happening in solo 40 lines mode. Since I can easily reproduce, I'll check what can alleviate it.

**Comment by Keydex** [comment]
Confirmed that this is due to removing ads from ublock origin. Perhaps holding arrows makes us out of focus from the game window/highlight an ad. 

It does appear that it triggers a breakpoint in the debugger when the game thinks it's out of focus. Perhaps maintainers can attempt to reproduce.

**Comment by ZaptorZap** [comment]
Well the debugger trap is intentional, and it happens anytime the devtools are open, so as to discourage any kind of undue bot development that may violate the rules. I haven't heard about uBlock _causing_ this issue before though. TETR.​IO's usually pretty kind to ad blocking efforts.

**Comment by Keydex** [comment]
Hey @ZaptorZap, i just retested some things. 

I can confirm that this is still happening when uBlock is off. So my initial statement was false, sorry about that. 

What I narrowed it down to is Microsoft Edge on Windows 11. 

**Problem Occurs**
- Edge Private window 4k Ublock On and off
- Edge Private window 1080p Ublock On and off

Problem does not occur on the same system with 
Google Chrome 4k with Ublock On. 

Edge Version 132.0.2957.115 (Official build) (64-bit)
Chrome Version Version 132.0.6834.83 (Official Build) (64-bit)

The video below shows me starting a new solo game on microsoft edge, no ublock origin enabled. At the start I hold right, and it becomes out of focus. I then click on the screen, and when trying to play it tries to go to the right on its own.

https://github.com/user-attachments/assets/1bcd5390-6da8-4031-b5c1-e55867469e77
