### ISSUE TITLE
Controller detected but not working

### ISSUE THREAD

**Issue by SaamariYT** [tetrio/issues#997]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop Client 

### Describe the bug/issue

When I plug a controller, the game sends me the "controller connected" notification but I can't bind anything on it; either using an official ps4 controller or a nacon compact one (I tried both and they don't work)

### Reproducing

Plug a controller
Get the controller connected notification
Try to bind something

### Expected behavior

I expected to be able to bind actions to controller buttons

**Comment by ZaptorZap** [comment]
Have you seen [this troubleshooting guide regarding controllers yet](https://github.com/ZaptorZap/tetriofaq/wiki/Troubleshooting#controllers)?
